# Generate the analyst-facing standalone scripts from package-native modules.
# Files under inst/scripts named in `econimap_standalone_spec()` are build
# artifacts. Edit their R/ modules, then run this script.

econimap_generator_root <- function() {
  file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
  if (length(file_arg)) {
    script <- normalizePath(sub("^--file=", "", file_arg[1]), mustWork = TRUE)
    return(dirname(dirname(script)))
  }
  candidates <- c(getwd(), file.path(getwd(), "econimap"), file.path(getwd(), ".."))
  hit <- candidates[file.exists(file.path(candidates, "DESCRIPTION")) & dir.exists(file.path(candidates, "R"))]
  if (!length(hit)) stop("Could not locate the econimap package root.", call. = FALSE)
  normalizePath(hit[1], mustWork = TRUE)
}

econimap_standalone_spec <- function() {
  hier <- sprintf("%03d", 10:18)
  list(
    "hier_mmm.R" = c("000-econimap-utils.R", paste0(hier, c(
      "-hier_mmm-setup.R", "-hier_mmm-time-holidays.R", "-hier_mmm-metadata-context.R",
      "-hier_mmm-priors-data.R", "-hier_mmm-init.R", "-hier_mmm-posteriors-diagnostics.R",
      "-hier_mmm-fit-engine.R", "-hier_mmm-decisioning.R", "-hier_mmm-public-wrappers.R"
    ))),
    "quasi_geo_test.R" = c("000-econimap-utils.R", sprintf("%03d-quasi_geo-%s.R", 20:25, c(
      "utils", "events", "evidence", "estimation", "priors", "runner"
    ))),
    "optimizer_scenario_planner.R" = c("000-econimap-utils.R", sprintf("%03d-optimizer-%s.R", 30:35, c(
      "utils-constraints", "curve-engine", "scenarios", "uncertainty", "methods", "runner-output"
    ))),
    "mmm_deck_output_builder.R" = c("000-econimap-utils.R", sprintf("%03d-deck-%s.R", 40:45, c(
      "utils-standardize", "optimizer-posterior-tables", "tables", "static-charts",
      "html-excel-shiny", "runner"
    ))),
    "bau_response_curves.R" = c("000-econimap-utils.R", "050-bau_response_curves.R"),
    # This file intentionally includes the fitted-MMM engine so the sequential
    # workflow remains a true standalone analyst surface.
    "sequential_hierarchical_bayes.R" = c(
      "000-econimap-utils.R",
      paste0(hier, c(
        "-hier_mmm-setup.R", "-hier_mmm-time-holidays.R", "-hier_mmm-metadata-context.R",
        "-hier_mmm-priors-data.R", "-hier_mmm-init.R", "-hier_mmm-posteriors-diagnostics.R",
        "-hier_mmm-fit-engine.R", "-hier_mmm-decisioning.R", "-hier_mmm-public-wrappers.R"
      )),
      "060-sequential-hierarchical-bayes.R"
    )
  )
}

econimap_generated_script_lines <- function(package_root, output_file, modules) {
  module_paths <- file.path(package_root, "R", modules)
  missing <- modules[!file.exists(module_paths)]
  if (length(missing)) stop("Missing module(s): ", paste(missing, collapse = ", "), call. = FALSE)
  hashes <- unname(tools::md5sum(module_paths))
  header <- c(
    paste0("# ", output_file),
    "# AUTO-GENERATED FROM PACKAGE MODULES. DO NOT EDIT THIS FILE DIRECTLY.",
    paste0("# Source modules: ", paste(modules, collapse = " | ")),
    paste0("# Source md5: ", paste(paste0(modules, "=", hashes), collapse = " | ")),
    ""
  )
  body <- unlist(lapply(seq_along(module_paths), function(i) {
    separator <- if (i < length(module_paths)) "" else character()
    c(readLines(module_paths[i], warn = FALSE), separator)
  }), use.names = FALSE)
  c(header, body)
}

generate_econimap_standalone_scripts <- function(package_root = econimap_generator_root(), check = FALSE) {
  package_root <- normalizePath(package_root, mustWork = TRUE)
  output_dir <- file.path(package_root, "inst", "scripts")
  if (!dir.exists(output_dir)) dir.create(output_dir, recursive = TRUE)
  results <- lapply(names(econimap_standalone_spec()), function(output_file) {
    expected <- econimap_generated_script_lines(
      package_root, output_file, econimap_standalone_spec()[[output_file]]
    )
    output_path <- file.path(output_dir, output_file)
    current <- if (file.exists(output_path)) readLines(output_path, warn = FALSE) else character()
    matches <- identical(current, expected)
    if (isTRUE(check) && !matches) {
      stop("Generated standalone script is stale: ", output_path, call. = FALSE)
    }
    if (!isTRUE(check)) writeLines(expected, output_path, useBytes = TRUE)
    data.frame(file = output_file, status = if (matches) "current" else if (check) "stale" else "generated")
  })
  stan_source <- file.path(package_root, "inst", "stan", "hier_mmm.stan")
  stan_output <- file.path(output_dir, "hier_mmm.stan")
  if (!file.exists(stan_source)) stop("Canonical Stan file is missing: ", stan_source, call. = FALSE)
  stan_matches <- file.exists(stan_output) && identical(
    readLines(stan_source, warn = FALSE), readLines(stan_output, warn = FALSE)
  )
  if (isTRUE(check) && !stan_matches) stop("Generated standalone Stan file is stale: ", stan_output, call. = FALSE)
  if (!isTRUE(check)) file.copy(stan_source, stan_output, overwrite = TRUE)
  out <- do.call(rbind, c(results, list(data.frame(
    file = "hier_mmm.stan", status = if (stan_matches) "current" else if (check) "stale" else "generated"
  ))))
  rownames(out) <- NULL
  out
}

if (!interactive() && sys.nframe() == 0L) {
  args <- commandArgs(trailingOnly = TRUE)
  print(generate_econimap_standalone_scripts(check = "--check" %in% args))
}
