# 010-hier_mmm-setup.R
# Generated by behavior-preserving split of hier_mmm.R.

# =============================================================================
# hier_mmm.R
# FINAL BUNDLE VERSION: v19_consultant_workflow_patch_2026_05_19
#
#
# KEY CHANGES FROM v15
#   1. Holdout rows are marked before mean-indexing, so training-scale denominators
#      do not use validation/holdout values.
#   2. Stan log_lik is now length N_train only; use extract_loo_hier_mmm().
#   3. Added lightweight prior-scale warnings before Stan compile.
#   4. Tightened prior-vs-posterior near_prior flag from 0.25 to 0.10 prior SD.
#   5. Fixed duplicated corr_ucm_actual field in UCM/media stealing diagnostics.
#   6. Made posterior mean extraction use a named lookup instead of repeated table scans.
#   7. Public API cleanup: dep_var_col / dep_scale_col names, automatic Stan file lookup,
#      deployment-ready output defaults, student_t default likelihood, and fixed dvalue default.
#   8. Metadata can include coef_hierarchy_scale to shrink group coefficient variation
#      for national-only or weakly geo-resolved media.
# PURPOSE
#   Parsimonious hierarchical Bayesian MMM wrapper for weekly panel data.
#   This is the FINAL MODEL wrapper. It is not a prior factory.
#
# MODEL DESIGN
#   - No manual family column in the metadata input.
#   - Each variable is its own transform-sharing unit internally.
#   - Curves are estimated at the VARIABLE level only, never at the group level.
#   - Curve parameters are only instantiated for variables with has_curve = 1.
#   - Optional holdout rows can be excluded from the likelihood but retained for prediction diagnostics.
#   - Curve normalization is based on TRAINING rows only to avoid validation leakage.
#   - Coefficient prior floors are small and configurable so near-zero guardrail priors are not accidentally loosened.
#   - Major run checkpoints can be printed and optionally written to a log file.
#   - v16 keeps the explicit index mapping and avoids fragile data.table x.* join lookups.
#   - Coefficients vary by group through a hierarchical prior.
#   - Non-UCM variables not listed in the metadata file are excluded from the modeled
#     variable matrix by default.
#   - Data is automatically sorted by group_col, then time_col.
#   - group_col + time_col must be unique within the input data.
#
# RECOMMENDED DEFAULT INTERCEPT SETUP
#   Default baseline is Fourier seasonality without a stochastic UCM level:
#   intercept_type = "fourier"
#   ucm_spec = list(
#     season = TRUE,
#     cycle = FALSE,
#     season_period = 52L,
#     season_harmonics = 2L,
#     cycle_period = 104L,
#     cycle_harmonics = 1L
#   )
#
#   Final UCM joint-estimation run is still supported through:
#   intercept_type = "ucm"
#   init_strategy = "ucm_pathfinder"
#   or the convenience wrapper fit_hier_mmm_ucm_final().
#
# MODEL-LEVEL INTERCEPT / UCM INPUTS
#   UCM can be controlled either by wrapper inputs or by metadata rows with role = "ucm".
#   UCM rows are internal model variables/components generated by the model;
#   they are not required to exist as raw data columns.
#   Supported UCM config rows include ucm_level, ucm_season, and ucm_cycle with:
#     - enabled   : TRUE/FALSE
#     - period    : used for season/cycle rows
#     - harmonics : used for season/cycle rows
#     - prior     : prior center or scale for UCM rows
#     - precision : optional prior precision; converted to prior sd as 1 / sqrt(precision)
#
# REQUIRED WEEKLY DATA INPUT
#   Weekly group-level panel data with at least:
#     - dep_var_col     : dependent variable column
#     - group_col       : panel id (for example mod_id)
#     - time_col        : sortable weekly column
#     - entity_col    : target entity being modeled in each row / panel
#     - one column for every non-UCM variable listed in the metadata file
#   - any data columns NOT listed as non-UCM metadata variables are excluded from X
#     and are not modeled as variables unless explicitly passed in
#     extra_control_cols
#
# REQUIRED METADATA INPUT (single file / data.table / data.frame)
#   Required model-variable columns:
#     - variable            : raw data column for normal X variables; internal UCM name for role=ucm
#     - role                : media, distribution, price, promo, trade, comp, macro, dummy, control, other, ucm
#     - coef                : coefficient prior center at VARIABLE level
#     - coef_precision      : coefficient prior precision at VARIABLE level
#
#   Optional but commonly used model-variable columns:
#     - source_entity       : source entity for that variable. Blank / NA / 0 /
#                             GLOBAL / globale all mean "GLOBAL"; otherwise this
#                             is compared to entity_col as a halo diagnostic.
#                             It is not the hierarchy key by itself.
#     - rrate               : prior center for retention / adstock. In
#                             sampled-curve mode this is a prior center, not a
#                             fixed value.
#     - rrate_precision     : prior precision for rrate
#     - cvalue              : internal saturation inverse-scale/rate prior center
#                             retained for backward compatibility. Prefer
#                             curve_rate or anchor_saturation in new metadata.
#                             For Hill, this is not EC50; EC50 on the normalized
#                             curve-input scale is 1 / curve_rate when dvalue = 1.
#                             In sampled-curve mode this is a prior center, not a
#                             fixed value.
#     - cvalue_precision    : prior precision for the internal curve rate
#     - dvalue              : prior center for saturation shape. It is fixed near
#                             its center unless estimate_dvalue = TRUE.
#     - dvalue_precision    : prior precision for dvalue
#     - coef_bound          : coefficient constraint cell: pos, neg, (lower,upper), (lower,), (,upper), blank/free
#     - coef_hierarchy_scale: multiplier on group-level coefficient variation.
#                             Use lower values for national-only or weakly
#                             geo-resolved media when group-specific effects are
#                             weakly identified.
#     - anchor_saturation   : saturation level at median active support. If no
#                             curve_rate/cvalue is supplied, media defaults to
#                             0.50 at median active support.
#     - curve_bound         : optional shorthand curve bound; parameter-specific bounds below override it
#     - rrate_bound         : optional rrate bound cell using the same parenthetical syntax
#     - cvalue_bound        : optional internal curve-rate bound cell using the
#                             same parenthetical syntax; curve_rate_bound is also accepted
#     - dvalue_bound        : optional dvalue bound cell using the same parenthetical syntax
#
# IMPORTANT RULES
#   - If rrate, internal curve rate, and dvalue are all 0, that variable is treated as NO-CURVE.
#   - Curve precisions are optional and default to intentionally weak values.
#     Coefficient precision is currently required unless supplied through a
#     business-prior conversion helper.
#   - sample_curve_parameters = "always" estimates rrate and curve_rate in Stan.
#     sample_curve_parameters = "never" uses the fixed R-precomputed transform
#     path for speed and sampler geometry.
#   - coef_by_mod_id stays on model scale; decomposition outputs are rescaled to
#     original units when possible.
#   - source_entity is generic. It does not need to be product-specific.
#   - source_entity is normalized so blank / NA / 0 / GLOBAL / globale all become "GLOBAL".
#   - halo is diagnosed as source_entity != entity_col for non-GLOBAL variables.
#
# NOTES
#   - This wrapper converts precision to prior sd internally with optional relaxation.
#   - coef_bound applies to coefficients. rrate_bound/curve_rate_bound/dvalue_bound apply to curve parameters.
#   - Curves are bounded internally to parsimonious defaults:
#       rrate  in [0.00, 0.90]
#       internal curve rate in [0.05, 8.00]
#       dvalue in [0.50, 2.00]
#   - If estimate_dvalue = FALSE, dvalue is effectively fixed near its metadata center.
#   - Default likelihood is student_t because weekly MMM data often has outliers/heavy tails.
#   - Stan file is auto-detected from the folder containing hier_mmm.R.
#   - Outputs default to ./hier_mmm_outputs unless output_dir is changed.
#
# OUTPUTS
#   - fit              : CmdStanMCMC object
#   - stan_data        : data passed to Stan
#   - metadata         : cleaned metadata input
#   - curve_priors     : per-variable curve priors used by Stan
#   - variable_lookup  : variable order / coef_bound / halo diagnostics
#   - group_lookup     : mapping of group index back to group value
#   - data             : cleaned / ordered working data
#   - coef_by_mod_id   : wide coefficient table by group/mod_id
#   - wide_decomp      : row-level wide decomposition table
#   - long_decomp      : row-level long decomposition table
#   - separated diagnostics:
#       diagnostics_bayes_* for the joint Bayesian model / sampler / fit quality
#       diagnostics_ucm_* for UCM parameters and intercept components
#   - optional coef_override_input can provide mod_id/group-specific backup coefficient priors
#
# DEPENDENCIES
#   install.packages(c("data.table", "cmdstanr", "posterior"))
# =============================================================================

`%||%` <- function(x, y) if (is.null(x)) y else x

require_hier_mmm_pkg <- function(pkg, context) {
  if (!requireNamespace(pkg, quietly = TRUE)) {
    stop("Package '", pkg, "' is required for ", context, ". Install it before running this Stan/modeling function.", call. = FALSE)
  }
  invisible(TRUE)
}

# Infer the deployment directory when this file is sourced.
# This lets fit_hier_mmm() find hier_mmm.stan without requiring the user to pass stan_file.
get_hier_mmm_script_dir <- function() {
  frames <- sys.frames()
  ofiles <- vapply(frames, function(f) {
    if (!is.null(f$ofile)) as.character(f$ofile)[1] else NA_character_
  }, character(1))
  ofiles <- ofiles[!is.na(ofiles) & nzchar(ofiles)]
  if (length(ofiles)) return(dirname(normalizePath(ofiles[length(ofiles)], mustWork = FALSE)))
  getwd()
}

.hier_mmm_deploy_dir <- get_hier_mmm_script_dir()

resolve_hier_mmm_stan_file <- function(stan_file = NULL) {
  if (!is.null(stan_file) && nzchar(stan_file)) {
    stan_file <- path.expand(stan_file)
    if (!file.exists(stan_file)) stop("Stan file does not exist: ", stan_file)
    return(normalizePath(stan_file, mustWork = TRUE))
  }

  package_stan <- tryCatch({
    if (exists("econimap_stan_path", mode = "function")) {
      econimap_stan_path("hier_mmm.stan", must_work = FALSE)
    } else {
      character(0)
    }
  }, error = function(e) character(0))

  candidates <- unique(c(
    package_stan,
    file.path(.hier_mmm_deploy_dir, "hier_mmm.stan"),
    file.path(.hier_mmm_deploy_dir, "hier_mmm_v17_fourier_default.stan"),
    file.path(getwd(), "hier_mmm.stan"),
    file.path(getwd(), "hier_mmm_v17_fourier_default.stan")
  ))
  hit <- candidates[file.exists(candidates)]
  if (length(hit)) return(normalizePath(hit[1], mustWork = TRUE))

  stop(
    "Could not find a matching Stan file. Put hier_mmm.R and hier_mmm.stan in the same folder, ",
    "or pass stan_file explicitly. Checked: ", paste(candidates, collapse = "; ")
  )
}


read_input_table <- function(x) {
  if (is.null(x)) stop("Input table is NULL.")
  if (inherits(x, "data.table")) return(copy(x))
  if (is.data.frame(x)) return(as.data.table(copy(x)))

  if (is.character(x) && length(x) == 1L) {
    path <- path.expand(x)
    if (!file.exists(path)) stop("Input file does not exist: ", path)
    ext <- tolower(tools::file_ext(path))
    if (ext %in% c("csv", "txt", "tsv")) return(fread(path))
    if (ext == "rds") return(as.data.table(readRDS(path)))
    if (ext %in% c("xlsx", "xls")) {
      if (!requireNamespace("readxl", quietly = TRUE)) {
        stop("Reading Excel inputs requires the readxl package. Use CSV or install readxl.")
      }
      return(as.data.table(readxl::read_excel(path)))
    }
    stop("Unsupported input file type: .", ext)
  }

  stop("Input must be a file path, data.table, or data.frame.")
}

finite_or_stop <- function(x, label) {
  bad <- is.na(x) | !is.finite(x)
  if (any(bad)) stop(label, " contains NA/NaN/Inf values. Bad rows: ", paste(which(bad)[seq_len(min(sum(bad), 10L))], collapse = ", "))
  invisible(TRUE)
}

log_hier_mmm_checkpoint <- function(stage,
                                    status = "OK",
                                    detail = "",
                                    checkpoint_file = NULL,
                                    verbose = TRUE) {
  status <- toupper(trimws(as.character(status %||% "OK")))
  stage <- trimws(as.character(stage %||% ""))
  detail <- trimws(as.character(detail %||% ""))
  ts <- format(Sys.time(), "%Y-%m-%d %H:%M:%S")
  msg <- if (nzchar(detail)) {
    sprintf("[%s] %-7s | %s | %s", ts, status, stage, detail)
  } else {
    sprintf("[%s] %-7s | %s", ts, status, stage)
  }
  if (isTRUE(verbose)) message(msg)
  if (!is.null(checkpoint_file) && nzchar(checkpoint_file)) {
    dir.create(dirname(checkpoint_file), recursive = TRUE, showWarnings = FALSE)
    cat(paste0(msg, "\n"), file = checkpoint_file, append = TRUE)
  }
  invisible(msg)
}

validate_numeric_input_cols <- function(dt,
                                        cols,
                                        label = "model input",
                                        stop_on_zero_variance = TRUE) {
  cols <- unique(cols[cols %in% names(dt)])
  if (!length(cols)) return(invisible(TRUE))

  for (cc in cols) {
    suppressWarnings(dt[, (cc) := as.numeric(get(cc))])
    finite_or_stop(dt[[cc]], paste0(label, " column '", cc, "'"))
    s <- safe_sd(dt[[cc]])
    if (isTRUE(stop_on_zero_variance) && s <= 1e-8) {
      stop(label, " column '", cc, "' has zero/nearly-zero variance across all rows.")
    }
  }
  invisible(TRUE)
}

smooth_vector <- function(x, window = 7L) {
  x <- as.numeric(x)
  n <- length(x)
  window <- as.integer(window %||% 7L)
  if (n <= 2L || window <= 1L) return(x)
  window <- min(window, n)
  if (window %% 2L == 0L) window <- max(1L, window - 1L)
  if (window <= 1L) return(x)

  y <- as.numeric(stats::filter(x, rep(1 / window, window), sides = 2))
  good <- which(is.finite(y))
  if (!length(good)) return(rep(mean(x, na.rm = TRUE), n))
  if (length(good) < n) {
    y <- stats::approx(x = good, y = y[good], xout = seq_len(n), rule = 2)$y
  }
  y
}

clip_numeric <- function(x, lower, upper) pmin(pmax(x, lower), upper)


safe_sd <- function(x, floor = 1e-8) {
  s <- stats::sd(x, na.rm = TRUE)
  if (!is.finite(s) || is.na(s) || s < floor) floor else s
}

finite_min_or_na <- function(x) {
  x <- as.numeric(x)
  x <- x[is.finite(x)]
  if (length(x)) min(x) else NA_real_
}

finite_max_or_na <- function(x) {
  x <- as.numeric(x)
  x <- x[is.finite(x)]
  if (length(x)) max(x) else NA_real_
}

normalize_curve_type_hier_mmm <- function(x) {
  out <- tolower(trimws(as.character(x %||% "weibull")))
  out[is.na(out) | !nzchar(out)] <- "weibull"
  out[out %in% c("weibull_cdf", "exponential", "exp")] <- "weibull"
  out[out %in% c("hill_function", "hill_curve", "logistic_saturation")] <- "hill"
  bad <- setdiff(unique(out), c("weibull", "hill"))
  if (length(bad)) stop("Unsupported curve_type values: ", paste(bad, collapse = ", "), ". Use 'weibull' or 'hill'.")
  out
}

saturate_media_hier_mmm <- function(x, cvalue, dvalue = 1, curve_type = "weibull") {
  z <- pmax(suppressWarnings(as.numeric(x)), 1e-12) * suppressWarnings(as.numeric(cvalue)[1])
  dvalue <- suppressWarnings(as.numeric(dvalue)[1])
  if (!is.finite(dvalue) || dvalue <= 0) dvalue <- 1
  curve_type <- normalize_curve_type_hier_mmm(curve_type)[1]
  pow_z <- z ^ dvalue
  if (identical(curve_type, "hill")) {
    pow_z / (1 + pow_z)
  } else {
    1 - exp(-pow_z)
  }
}

normalize_curve_normalization_scope_hier_mmm <- function(x) {
  out <- tolower(trimws(as.character(x %||% "active_train")[1]))
  if (is.na(out) || !nzchar(out)) out <- "active_train"
  out <- gsub("-", "_", out)
  out <- switch(out,
    active = "active_train",
    active_only = "active_train",
    nonzero = "active_train",
    non_zero = "active_train",
    nonzero_train = "active_train",
    active_train = "active_train",
    all = "all_train",
    train = "all_train",
    all_train = "all_train",
    stop("curve_normalization_scope must be 'active_train' or 'all_train'.", call. = FALSE)
  )
  out
}

curve_normalization_mask_hier_mmm <- function(x_ref, train_mask, scope = "active_train") {
  scope <- normalize_curve_normalization_scope_hier_mmm(scope)
  train_mask <- as.logical(train_mask)
  train_mask[is.na(train_mask)] <- FALSE
  if (!any(train_mask)) train_mask <- rep(TRUE, length(x_ref))
  if (identical(scope, "all_train")) return(train_mask)
  active <- train_mask & is.finite(x_ref) & x_ref > 0
  if (any(active)) active else train_mask
}

curve_rate_from_anchor_hier_mmm <- function(x,
                                            rrate,
                                            dvalue = 1,
                                            anchor_saturation = 0.50,
                                            curve_type = "weibull",
                                            train_mask = NULL,
                                            normalize_curve_x = TRUE,
                                            curve_normalization_scope = "active_train") {
  x_ref <- pmax(suppressWarnings(as.numeric(x)), 0)
  x_ref[!is.finite(x_ref)] <- 0
  n <- length(x_ref)
  if (is.null(train_mask)) train_mask <- rep(TRUE, n)
  train_mask <- rep(as.logical(train_mask), length.out = n)
  train_mask[is.na(train_mask)] <- FALSE
  if (!any(train_mask)) train_mask <- rep(TRUE, n)
  rrate <- min(max(suppressWarnings(as.numeric(rrate)[1]), 0), 0.999)
  dvalue <- suppressWarnings(as.numeric(dvalue)[1])
  if (!is.finite(dvalue) || dvalue <= 0) dvalue <- 1
  anchor_saturation <- clip_numeric(suppressWarnings(as.numeric(anchor_saturation)[1]), 0.01, 0.99)
  if (!is.finite(anchor_saturation)) return(NA_real_)

  carry <- numeric(n)
  carry_state <- 0
  for (ii in seq_along(x_ref)) {
    carry_state <- x_ref[ii] + rrate * carry_state
    carry[ii] <- carry_state
  }
  carry_scale <- 1
  if (isTRUE(normalize_curve_x)) {
    norm_mask <- curve_normalization_mask_hier_mmm(x_ref, train_mask, curve_normalization_scope)
    carry_scale <- mean(carry[norm_mask], na.rm = TRUE)
    if (!is.finite(carry_scale) || is.na(carry_scale) || abs(carry_scale) <= 1e-8) carry_scale <- 1
  }
  z <- carry / carry_scale
  active <- train_mask & is.finite(z) & z > 0 & is.finite(x_ref) & x_ref > 0
  anchor_x <- stats::median(z[active], na.rm = TRUE)
  if (!is.finite(anchor_x) || anchor_x <= 0) return(NA_real_)

  curve_type <- normalize_curve_type_hier_mmm(curve_type)[1]
  if (identical(curve_type, "hill")) {
    (anchor_saturation / (1 - anchor_saturation)) ^ (1 / dvalue) / anchor_x
  } else {
    (-log(1 - anchor_saturation)) ^ (1 / dvalue) / anchor_x
  }
}

# Backward-compatible aliases. The returned value is the Stan internal
# saturation inverse-scale/rate, not a Hill EC/EC50 location parameter.
cvalue_from_anchor_hier_mmm <- curve_rate_from_anchor_hier_mmm
curve_location_from_anchor_hier_mmm <- curve_rate_from_anchor_hier_mmm
