# 011-hier_mmm-time-holidays.R
# Generated by behavior-preserving split of hier_mmm.R.

mean_index_by_group <- function(dt, cols, by, eps = 1e-8, train_col = NULL) {
  dt <- copy(as.data.table(dt))
  cols <- unique(cols[cols %in% names(dt)])
  if (!length(cols)) return(dt)

  if (!is.null(train_col) && train_col %in% names(dt)) {
    den <- dt[get(train_col) == TRUE | get(train_col) == 1L, lapply(.SD, function(x) {
      m <- mean(x[is.finite(x)], na.rm = TRUE)
      if (!is.finite(m) || is.na(m) || abs(m) <= eps) 1 else m
    }), by = by, .SDcols = cols]
  } else {
    den <- dt[, lapply(.SD, function(x) {
      m <- mean(x[is.finite(x)], na.rm = TRUE)
      if (!is.finite(m) || is.na(m) || abs(m) <= eps) 1 else m
    }), by = by, .SDcols = cols]
  }

  den_cols <- paste0(cols, "__mi_denom")
  setnames(den, cols, den_cols)
  dt <- den[dt, on = by]

  for (i in seq_along(cols)) {
    cc <- cols[i]
    dd <- den_cols[i]
    dt[, (cc) := fifelse(abs(get(dd)) <= eps, get(cc), get(cc) / get(dd))]
    dt[, (dd) := NULL]
  }
  dt[]
}

mean_index_global_cols <- function(dt, cols, eps = 1e-8, train_col = NULL) {
  dt <- copy(as.data.table(dt))
  cols <- unique(cols[cols %in% names(dt)])
  if (!length(cols)) return(dt)
  train_mask <- rep(TRUE, nrow(dt))
  if (!is.null(train_col) && train_col %in% names(dt)) {
    train_mask <- dt[[train_col]] == TRUE | dt[[train_col]] == 1L
    train_mask[is.na(train_mask)] <- FALSE
  }
  for (cc in cols) {
    x <- dt[[cc]]
    m <- mean(x[train_mask & is.finite(x)], na.rm = TRUE)
    if (!is.finite(m) || is.na(m) || abs(m) <= eps) m <- 1
    dt[, (cc) := get(cc) / m]
  }
  dt[]
}

build_fourier_matrix <- function(time_vec, period = 52L, harmonics = 2L) {
  n <- length(time_vec)
  period <- as.integer(period %||% 52L)
  harmonics <- as.integer(harmonics %||% 0L)
  if (n <= 0L || harmonics <= 0L || period <= 1L) return(matrix(0, n, 0))

  ord_levels <- sort(unique(time_vec))
  tt <- match(time_vec, ord_levels)
  mats <- vector("list", harmonics)
  coln <- character(2L * harmonics)

  for (k in seq_len(harmonics)) {
    ang <- 2 * pi * k * tt / period
    mats[[k]] <- cbind(sin(ang), cos(ang))
    coln[(2L * k - 1L):(2L * k)] <- c(sprintf("season_sin_%02d", k), sprintf("season_cos_%02d", k))
  }

  out <- do.call(cbind, mats)
  colnames(out) <- coln
  storage.mode(out) <- "double"
  out
}

parse_hier_mmm_dates <- function(x, label = "date") {
  if (inherits(x, "Date")) return(as.Date(x))
  if (inherits(x, "IDate")) return(as.Date(x))
  if (inherits(x, "POSIXt")) return(as.Date(x))
  if (is.numeric(x)) {
    if (all(is.na(x))) return(as.Date(rep(NA, length(x))))
    med <- stats::median(x, na.rm = TRUE)
    if (is.finite(med) && med > 30000) return(as.Date(x, origin = "1899-12-30"))
    if (is.finite(med) && med > 10000) return(as.Date(x, origin = "1970-01-01"))
  }
  out <- suppressWarnings(as.Date(x))
  if (all(is.na(out)) && length(x)) {
    stop("Could not parse ", label, " as dates for holiday control generation.", call. = FALSE)
  }
  out
}

hier_mmm_nth_weekday <- function(year, month, weekday, n) {
  d0 <- as.Date(sprintf("%04d-%02d-01", as.integer(year), as.integer(month)))
  w0 <- as.POSIXlt(d0)$wday
  d <- d0 + ((weekday - w0) %% 7L) + 7L * (as.integer(n) - 1L)
  as.Date(d)
}

hier_mmm_last_weekday <- function(year, month, weekday) {
  first_next <- if (as.integer(month) == 12L) {
    as.Date(sprintf("%04d-01-01", as.integer(year) + 1L))
  } else {
    as.Date(sprintf("%04d-%02d-01", as.integer(year), as.integer(month) + 1L))
  }
  d0 <- first_next - 1L
  w0 <- as.POSIXlt(d0)$wday
  as.Date(d0 - ((w0 - weekday) %% 7L))
}

hier_mmm_easter_date <- function(year) {
  y <- as.integer(year)
  a <- y %% 19L
  b <- y %/% 100L
  c <- y %% 100L
  d <- b %/% 4L
  e <- b %% 4L
  f <- (b + 8L) %/% 25L
  g <- (b - f + 1L) %/% 3L
  h <- (19L * a + b - d - g + 15L) %% 30L
  i <- c %/% 4L
  k <- c %% 4L
  l <- (32L + 2L * e + 2L * i - h - k) %% 7L
  m <- (a + 11L * h + 22L * l) %/% 451L
  month <- (h + l - 7L * m + 114L) %/% 31L
  day <- ((h + l - 7L * m + 114L) %% 31L) + 1L
  as.Date(sprintf("%04d-%02d-%02d", y, month, day))
}

hier_mmm_holiday_catalog <- function(calendars, years) {
  calendars <- tolower(trimws(as.character(calendars %||% "us_major")))
  calendars[is.na(calendars) | !nzchar(calendars)] <- "us_major"
  calendars[calendars %in% c("us", "usa", "united_states", "us-major")] <- "us_major"
  calendars[calendars %in% c("eu", "europe", "eu-major")] <- "eu_major"
  calendars[calendars %in% c("global", "global-major", "major")] <- "global_major"
  years <- sort(unique(as.integer(years[is.finite(years)])))
  rows <- list()
  for (cal in unique(calendars)) {
    for (yy in years) {
      if (identical(cal, "us_major")) {
        rows[[length(rows) + 1L]] <- data.table(
          calendar = cal,
          holiday_name = c(
            "new_years_day", "martin_luther_king_day", "memorial_day",
            "independence_day", "labor_day", "thanksgiving_day", "christmas_day"
          ),
          holiday_date = as.Date(c(
            sprintf("%04d-01-01", yy),
            as.character(hier_mmm_nth_weekday(yy, 1L, 1L, 3L)),
            as.character(hier_mmm_last_weekday(yy, 5L, 1L)),
            sprintf("%04d-07-04", yy),
            as.character(hier_mmm_nth_weekday(yy, 9L, 1L, 1L)),
            as.character(hier_mmm_nth_weekday(yy, 11L, 4L, 4L)),
            sprintf("%04d-12-25", yy)
          ))
        )
      } else if (identical(cal, "eu_major")) {
        easter <- hier_mmm_easter_date(yy)
        rows[[length(rows) + 1L]] <- data.table(
          calendar = cal,
          holiday_name = c("new_years_day", "easter_monday", "may_day", "christmas_day", "boxing_day"),
          holiday_date = as.Date(c(
            sprintf("%04d-01-01", yy),
            as.character(easter + 1L),
            sprintf("%04d-05-01", yy),
            sprintf("%04d-12-25", yy),
            sprintf("%04d-12-26", yy)
          ))
        )
      } else if (identical(cal, "global_major")) {
        rows[[length(rows) + 1L]] <- data.table(
          calendar = cal,
          holiday_name = c("new_years_day", "christmas_day"),
          holiday_date = as.Date(c(sprintf("%04d-01-01", yy), sprintf("%04d-12-25", yy)))
        )
      } else {
        stop("Unsupported built-in holiday calendar: ", cal,
             ". Use 'US_major', 'EU_major', 'global_major', or pass custom_holidays.", call. = FALSE)
      }
    }
  }
  if (!length(rows)) return(data.table(calendar = character(), holiday_name = character(), holiday_date = as.Date(character())))
  unique(rbindlist(rows, fill = TRUE))
}

hier_mmm_custom_holidays <- function(custom_holidays = NULL) {
  if (is.null(custom_holidays)) {
    return(data.table(calendar = character(), holiday_name = character(), holiday_date = as.Date(character())))
  }
  if (inherits(custom_holidays, "Date") || is.character(custom_holidays) || is.numeric(custom_holidays)) {
    dates <- parse_hier_mmm_dates(custom_holidays, label = "custom_holidays")
    names_in <- names(custom_holidays)
    return(data.table(
      calendar = "custom",
      holiday_name = if (!is.null(names_in) && length(names_in) == length(dates)) make.names(names_in) else paste0("custom_", seq_along(dates)),
      holiday_date = dates
    ))
  }
  ch <- as.data.table(copy(custom_holidays))
  dcol <- intersect(c("holiday_date", "date", "period", "week", "ds"), names(ch))[1]
  if (is.na(dcol)) stop("custom_holidays must include holiday_date/date/period/week/ds.", call. = FALSE)
  ncol <- intersect(c("holiday_name", "holiday", "name", "event"), names(ch))[1]
  ccol <- intersect(c("calendar", "region", "country"), names(ch))[1]
  out <- data.table(
    calendar = if (!is.na(ccol)) as.character(ch[[ccol]]) else "custom",
    holiday_name = if (!is.na(ncol)) as.character(ch[[ncol]]) else paste0("custom_", seq_len(nrow(ch))),
    holiday_date = parse_hier_mmm_dates(ch[[dcol]], label = "custom_holidays")
  )
  out[is.na(calendar) | !nzchar(calendar), calendar := "custom"]
  out[is.na(holiday_name) | !nzchar(holiday_name), holiday_name := paste0("custom_", .I)]
  unique(out[!is.na(holiday_date)])
}

normalize_holiday_config_hier_mmm <- function(holiday_config = NULL) {
  if (is.null(holiday_config) || identical(holiday_config, FALSE)) {
    return(list(enabled = FALSE))
  }
  if (identical(holiday_config, TRUE)) holiday_config <- list()
  if (!is.list(holiday_config)) stop("holiday_config must be TRUE/FALSE or a list.", call. = FALSE)
  calendars <- holiday_config$calendars %||% holiday_config$calendar %||% "US_major"
  windows <- tolower(trimws(as.character(holiday_config$windows %||% holiday_config$window %||% "week_of")))
  windows[windows %in% c("holiday", "current", "during", "week", "weekof", "same_week")] <- "week_of"
  windows[windows %in% c("before", "pre", "lead", "previous", "prior", "week-before")] <- "week_before"
  windows[windows %in% c("after", "post", "lag", "following", "next", "week-after")] <- "week_after"
  bad <- setdiff(unique(windows), c("week_before", "week_of", "week_after"))
  if (length(bad)) stop("Unsupported holiday windows: ", paste(bad, collapse = ", "),
                        ". Use week_before, week_of, and/or week_after.", call. = FALSE)
  mode <- tolower(trimws(as.character(holiday_config$mode %||% "aggregate")))[1]
  if (!mode %in% c("aggregate", "separate")) stop("holiday_config$mode must be 'aggregate' or 'separate'.", call. = FALSE)
  period_days <- suppressWarnings(as.integer(holiday_config$period_days %||% NA_integer_))[1]
  if (!is.na(period_days) && (!is.finite(period_days) || period_days <= 0L)) stop("holiday_config$period_days must be a positive integer.", call. = FALSE)
  list(
    enabled = TRUE,
    calendars = calendars,
    custom_holidays = holiday_config$custom_holidays,
    windows = unique(windows),
    mode = mode,
    prefix = as.character(holiday_config$prefix %||% "holiday")[1],
    period_days = period_days,
    include_built_in = isTRUE(holiday_config$include_built_in %||% TRUE)
  )
}

add_holiday_controls_hier_mmm <- function(data, time_col, holiday_config = NULL, existing_extra_cols = NULL) {
  cfg <- normalize_holiday_config_hier_mmm(holiday_config)
  dt <- as.data.table(copy(data))
  if (!isTRUE(cfg$enabled)) {
    return(list(data = dt, extra_control_cols = existing_extra_cols %||% character(), audit = data.table()))
  }
  if (!(time_col %in% names(dt))) stop("time_col not found for holiday controls: ", time_col, call. = FALSE)
  period_start <- parse_hier_mmm_dates(dt[[time_col]], label = time_col)
  if (anyNA(period_start)) stop("time_col contains unparseable dates for holiday controls.", call. = FALSE)
  unique_dates <- sort(unique(period_start))
  inferred_days <- if (length(unique_dates) >= 2L) {
    diffs <- as.integer(diff(unique_dates))
    diffs <- diffs[is.finite(diffs) & diffs > 0L]
    if (length(diffs)) as.integer(stats::median(diffs)) else 7L
  } else {
    7L
  }
  period_days <- cfg$period_days
  if (!is.finite(period_days) || is.na(period_days) || period_days <= 0L) period_days <- inferred_days
  period_end <- period_start + period_days - 1L
  years <- seq(
    as.integer(format(min(period_start, na.rm = TRUE) - period_days * 2L, "%Y")),
    as.integer(format(max(period_end, na.rm = TRUE) + period_days * 2L, "%Y"))
  )
  holidays <- data.table()
  if (isTRUE(cfg$include_built_in)) holidays <- hier_mmm_holiday_catalog(cfg$calendars, years)
  holidays <- rbindlist(list(holidays, hier_mmm_custom_holidays(cfg$custom_holidays)), fill = TRUE)
  holidays <- unique(holidays[!is.na(holiday_date)])
  if (!nrow(holidays)) {
    return(list(data = dt, extra_control_cols = existing_extra_cols %||% character(), audit = data.table()))
  }
  window_offsets <- c(week_before = -1L, week_of = 0L, week_after = 1L)
  make_col <- function(parts) {
    nm <- paste(parts[nzchar(parts)], collapse = "_")
    nm <- gsub("[^A-Za-z0-9_]+", "_", nm)
    nm <- gsub("_+", "_", nm)
    nm <- gsub("^_|_$", "", nm)
    if (!nzchar(nm)) nm <- "holiday_control"
    nm
  }
  add_col_safe <- function(base) {
    col <- base
    ii <- 1L
    while (col %in% names(dt)) {
      ii <- ii + 1L
      col <- paste0(base, "_", ii)
    }
    col
  }
  audit_rows <- list()
  generated_cols <- character()
  for (ww in cfg$windows) {
    offset <- window_offsets[[ww]]
    if (identical(cfg$mode, "aggregate")) {
      col <- add_col_safe(make_col(c(cfg$prefix, ww)))
      dt[, (col) := 0]
      target_dates <- holidays$holiday_date + offset * period_days
      flag <- vapply(seq_along(period_start), function(i) any(target_dates >= period_start[i] & target_dates <= period_end[i]), logical(1))
      dt[, (col) := as.numeric(flag)]
      generated_cols <- c(generated_cols, col)
      audit_rows[[length(audit_rows) + 1L]] <- data.table(
        generated_col = col,
        mode = cfg$mode,
        window = ww,
        calendar = paste(sort(unique(holidays$calendar)), collapse = "|"),
        holiday_name = "all",
        holiday_count = length(unique(holidays$holiday_date)),
        active_rows = sum(flag, na.rm = TRUE),
        period_days = period_days
      )
    } else {
      for (hh in seq_len(nrow(holidays))) {
        hname <- tolower(make.names(holidays$holiday_name[hh]))
        col <- add_col_safe(make_col(c(cfg$prefix, hname, ww)))
        target_date <- holidays$holiday_date[hh] + offset * period_days
        flag <- target_date >= period_start & target_date <= period_end
        dt[, (col) := as.numeric(flag)]
        generated_cols <- c(generated_cols, col)
        audit_rows[[length(audit_rows) + 1L]] <- data.table(
          generated_col = col,
          mode = cfg$mode,
          window = ww,
          calendar = holidays$calendar[hh],
          holiday_name = holidays$holiday_name[hh],
          holiday_count = 1L,
          active_rows = sum(flag, na.rm = TRUE),
          period_days = period_days
        )
      }
    }
  }
  audit <- rbindlist(audit_rows, fill = TRUE)
  list(
    data = dt,
    extra_control_cols = unique(c(existing_extra_cols %||% character(), generated_cols)),
    audit = audit
  )
}


parse_model_intercept <- function(intercept_type = "fourier", ucm_spec = NULL) {
  itype <- tolower(trimws(as.character(intercept_type %||% "fourier")))
  if (itype %in% c("", "na", "n/a")) itype <- "fourier"
  if (itype %in% c("seasonal", "seasonality", "fourier_season", "fourier-season", "fourier_only", "fourier-only")) itype <- "fourier"

  if (itype == "none") {
    return(list(
      label = "none",
      intercept_mode = 0L,
      use_level = 0L,
      use_season = 0L,
      use_cycle = 0L,
      season_period = NA_integer_,
      season_harmonics = 0L,
      cycle_period = NA_integer_,
      cycle_harmonics = 0L
    ))
  }

  if (itype == "flat") {
    return(list(
      label = "flat",
      intercept_mode = 1L,
      use_level = 0L,
      use_season = 0L,
      use_cycle = 0L,
      season_period = NA_integer_,
      season_harmonics = 0L,
      cycle_period = NA_integer_,
      cycle_harmonics = 0L
    ))
  }

  if (!itype %in% c("fourier", "ucm")) {
    stop("intercept_type must be one of: 'none', 'flat', 'fourier', 'ucm'.")
  }

  default_spec <- if (itype == "fourier") {
    list(
      level = FALSE,
      season = TRUE,
      cycle = FALSE,
      season_period = 52L,
      season_harmonics = 2L,
      cycle_period = 104L,
      cycle_harmonics = 1L
    )
  } else {
    list(
      level = TRUE,
      season = TRUE,
      cycle = FALSE,
      season_period = 52L,
      season_harmonics = 2L,
      cycle_period = 104L,
      cycle_harmonics = 1L
    )
  }
  spec <- modifyList(default_spec, ucm_spec %||% list())

  use_level <- isTRUE(spec$level)
  use_season <- isTRUE(spec$season)
  use_cycle <- isTRUE(spec$cycle)

  if (itype == "ucm" && !use_level) {
    stop("When intercept_type = 'ucm', ucm_spec$level must be TRUE. Use intercept_type = 'fourier' for a no-level Fourier baseline.")
  }
  if (itype == "fourier" && use_level) {
    stop("When intercept_type = 'fourier', ucm_spec$level must be FALSE. Use intercept_type = 'ucm' for a stochastic level baseline.")
  }
  if (itype == "fourier" && !use_season && !use_cycle) {
    stop("intercept_type = 'fourier' requires season = TRUE and/or cycle = TRUE.")
  }

  season_period <- as.integer(spec$season_period %||% 52L)
  season_harmonics <- as.integer(spec$season_harmonics %||% 2L)
  cycle_period <- as.integer(spec$cycle_period %||% 104L)
  cycle_harmonics <- as.integer(spec$cycle_harmonics %||% 1L)

  if (use_season) {
    if (!is.finite(season_period) || is.na(season_period) || season_period <= 1L) {
      stop("ucm_spec$season_period must be > 1 when season = TRUE.")
    }
    if (!is.finite(season_harmonics) || is.na(season_harmonics) || season_harmonics < 1L) {
      stop("ucm_spec$season_harmonics must be >= 1 when season = TRUE.")
    }
  } else {
    season_period <- NA_integer_
    season_harmonics <- 0L
  }

  if (use_cycle) {
    if (!is.finite(cycle_period) || is.na(cycle_period) || cycle_period <= 1L) {
      stop("ucm_spec$cycle_period must be > 1 when cycle = TRUE.")
    }
    if (!is.finite(cycle_harmonics) || is.na(cycle_harmonics) || cycle_harmonics < 1L) {
      stop("ucm_spec$cycle_harmonics must be >= 1 when cycle = TRUE.")
    }
  } else {
    cycle_period <- NA_integer_
    cycle_harmonics <- 0L
  }

  if (use_level) {
    label <- "level"
    if (use_season && use_cycle) {
      label <- "level+season+cycle"
    } else if (use_season) {
      label <- "level+season"
    } else if (use_cycle) {
      label <- "level+cycle"
    }
  } else {
    label <- if (use_season && use_cycle) {
      "fourier+cycle"
    } else if (use_season) {
      "fourier"
    } else {
      "cycle"
    }
  }

  list(
    label = label,
    intercept_mode = 2L,
    use_level = as.integer(use_level),
    use_season = as.integer(use_season),
    use_cycle = as.integer(use_cycle),
    season_period = season_period,
    season_harmonics = season_harmonics,
    cycle_period = cycle_period,
    cycle_harmonics = cycle_harmonics
  )
}


