# 015-hier_mmm-posteriors-diagnostics.R
# Generated by behavior-preserving split of hier_mmm.R.

extract_posterior_means_hier_mmm <- function(fit, prep) {
  require_hier_mmm_pkg("posterior", "extracting Stan posterior means")

  sm <- summarize_fit_vars(
    fit,
    variables = c(
      "beta", "rrate", "cvalue", "dvalue", "context_coef", "alpha_flat", "gamma",
      "level_component", "cycle_component", "season_component", "level_state", "sigma_y"
    )
  )
  if (!all(c("variable", "mean") %in% names(sm))) {
    stop("CmdStan summary did not return expected columns 'variable' and 'mean'.")
  }

  sm_lookup <- setNames(sm$mean, sm$variable)
  get_mean <- function(name, default = 0) {
    v <- sm_lookup[[name]]
    if (!is.null(v) && is.finite(v)) as.numeric(v) else default
  }

  J <- prep$stan_data$J
  G <- prep$stan_data$G
  K_extra <- prep$stan_data$K_extra
  K_context <- as.integer(prep$stan_data$K_context %||% 0L)

  beta <- matrix(0, nrow = G, ncol = J)
  for (g in seq_len(G)) {
    for (j in seq_len(J)) {
      beta[g, j] <- get_mean(sprintf("beta[%d,%d]", g, j), 0)
    }
  }

  rrate <- rep(0, J)
  cvalue <- rep(0, J)
  dvalue <- rep(1, J)
  if (prep$stan_data$J_curve > 0L) {
    for (k in seq_len(prep$stan_data$J_curve)) {
      j <- prep$stan_data$curve_idx[k]
      rrate[j] <- get_mean(sprintf("rrate[%d]", k), 0)
      cvalue[j] <- get_mean(sprintf("cvalue[%d]", k), 0)
      dvalue[j] <- get_mean(sprintf("dvalue[%d]", k), 1)
    }
  }

  alpha_flat <- vapply(seq_len(G), function(g) get_mean(sprintf("alpha_flat[%d]", g), 0), numeric(1))
  gamma <- if (K_extra > 0) vapply(seq_len(K_extra), function(k) get_mean(sprintf("gamma[%d]", k), 0), numeric(1)) else numeric()
  context_coef <- if (K_context > 0) {
    vapply(seq_len(K_context), function(k) get_mean(sprintf("context_coef[%d]", k), prep$stan_data$context_coef_mu[k] %||% 0), numeric(1))
  } else numeric()
  level_component <- vapply(seq_len(prep$stan_data$N), function(i) get_mean(sprintf("level_component[%d]", i), 0), numeric(1))
  cycle_component <- vapply(seq_len(prep$stan_data$N), function(i) get_mean(sprintf("cycle_component[%d]", i), 0), numeric(1))
  season_component <- vapply(seq_len(prep$stan_data$N), function(i) get_mean(sprintf("season_component[%d]", i), 0), numeric(1))
  level_state <- vapply(seq_len(prep$stan_data$N), function(i) get_mean(sprintf("level_state[%d]", i), 0), numeric(1))
  sigma_y <- get_mean("sigma_y", NA_real_)

  list(
    beta = beta,
    rrate = rrate,
    cvalue = cvalue,
    dvalue = dvalue,
    alpha_flat = alpha_flat,
    gamma = gamma,
    context_coef = context_coef,
    level_component = level_component,
    cycle_component = cycle_component,
    season_component = season_component,
    level_state = level_state,
    sigma_y = sigma_y
  )
}


build_experiment_calibration_diagnostics_hier_mmm <- function(fit, prep) {
  audit <- copy(as.data.table(prep$experiment_calibration %||% data.table()))
  if (!nrow(audit)) return(audit)
  draws <- tryCatch(
    fit$draws("calibration_pred", format = "matrix"),
    error = function(e) NULL
  )
  if (is.null(draws) || !ncol(draws)) {
    audit[, `:=`(
      posterior_lift_mean = NA_real_,
      posterior_lift_q05 = NA_real_,
      posterior_lift_q50 = NA_real_,
      posterior_lift_q95 = NA_real_,
      posterior_minus_observed = NA_real_,
      calibration_z = NA_real_,
      calibration_status = "posterior_draws_unavailable"
    )]
    return(audit[])
  }
  summaries <- rbindlist(lapply(seq_len(nrow(audit)), function(i) {
    nm <- paste0("calibration_pred[", i, "]")
    if (!(nm %in% colnames(draws))) return(data.table(calibration_id = audit$calibration_id[i]))
    x <- as.numeric(draws[, nm])
    data.table(
      calibration_id = audit$calibration_id[i],
      posterior_lift_mean = mean(x, na.rm = TRUE),
      posterior_lift_q05 = as.numeric(stats::quantile(x, 0.05, na.rm = TRUE)),
      posterior_lift_q50 = as.numeric(stats::quantile(x, 0.50, na.rm = TRUE)),
      posterior_lift_q95 = as.numeric(stats::quantile(x, 0.95, na.rm = TRUE))
    )
  }), use.names = TRUE, fill = TRUE)
  audit[summaries, on = "calibration_id", `:=`(
    posterior_lift_mean = i.posterior_lift_mean,
    posterior_lift_q05 = i.posterior_lift_q05,
    posterior_lift_q50 = i.posterior_lift_q50,
    posterior_lift_q95 = i.posterior_lift_q95
  )]
  audit[, `:=`(
    posterior_minus_observed = posterior_lift_mean - observed_lift_raw_scale,
    calibration_z = (observed_lift_raw_scale - posterior_lift_mean) / observed_lift_sd_raw_scale,
    calibration_status = fifelse(
      !is.finite(posterior_lift_mean),
      "posterior_draws_unavailable",
      fifelse(
        observed_lift_raw_scale >= posterior_lift_q05 & observed_lift_raw_scale <= posterior_lift_q95,
        "observed_inside_posterior_90pct",
        "review_prior_posterior_tension"
      )
    )
  )]
  audit[]
}

build_outputs_hier_mmm <- function(fit,
                                   prep,
                                   extra_control_cols = NULL,
                                   posterior_means = NULL,
                                   include_prediction_intervals = TRUE) {
  pm <- posterior_means %||% extract_posterior_means_hier_mmm(fit, prep)
  dt <- copy(prep$data)
  vl <- copy(prep$variable_lookup)[order(variable_idx)]
  if (!"curve_type" %in% names(vl)) vl[, curve_type := "hill"]
  gl <- copy(prep$group_lookup)[order(group_idx)]
  var_names <- vl$variable
  curve_vars <- vl[has_curve == 1L, variable]
  linear_vars <- vl[has_curve == 0L, variable]

  dt[, row_id := .I]
  dt[, sample := fifelse(is_holdout__, "holdout", "train")]

  # coefficient outputs are kept on MODEL SCALE (before decomp rescaling)
  coef_long <- as.data.table(expand.grid(group_idx = gl$group_idx, variable_idx = vl$variable_idx, KEEP.OUT.ATTRS = FALSE))
  coef_long[, coef := as.numeric(pm$beta[cbind(group_idx, variable_idx)])]
  coef_long[gl, on = "group_idx", `:=`(
    group_value = i.group_value,
    model_id = i.group_value,
    mod_id = i.group_value,
    target_entity = i.target_entity
  )]
  coef_long[vl, on = "variable_idx", `:=`(variable = i.variable, source_entity = i.source_entity, role = i.role, has_curve = i.has_curve)]
  setcolorder(coef_long, c("group_value", "model_id", "mod_id", "target_entity", "variable", "source_entity", "role", "has_curve", "coef"))
  coef_by_group <- dcast(coef_long, group_value + model_id + target_entity ~ variable, value.var = "coef")
  coef_by_mod_id <- dcast(coef_long, mod_id + target_entity ~ variable, value.var = "coef")

  contrib_cols <- character()
  center_predictors <- isTRUE(prep$center_predictors_for_sampling) &&
    !is.null(prep$stan_data$X_center_mean) &&
    nrow(prep$stan_data$X_center_mean) == prep$stan_data$G
  center_offset_model <- numeric(nrow(dt))

  # intercept contribution on model scale
  if (prep$intercept_spec == "flat") {
    dt[, intercept := pm$alpha_flat[group_idx]]
    contrib_cols <- c(contrib_cols, "intercept")
  } else if (isTRUE(prep$intercept_use_level == 1L) || isTRUE(prep$intercept_use_cycle == 1L) || isTRUE(prep$intercept_use_season == 1L)) {
    dt[, intercept_level := pm$level_component]
    if (isTRUE(prep$intercept_use_level == 1L)) {
      dt[, intercept_flat := 0]
    } else {
      dt[, intercept_flat := pm$alpha_flat[group_idx]]
    }
    dt[, intercept_cycle := pm$cycle_component]
    dt[, intercept_seasonality := pm$season_component]
    dt[, intercept_total := intercept_flat + intercept_level + intercept_cycle + intercept_seasonality]
    if (isTRUE(prep$intercept_use_level == 1L)) contrib_cols <- c(contrib_cols, "intercept_level") else contrib_cols <- c(contrib_cols, "intercept_flat")
    if (isTRUE(prep$intercept_use_cycle == 1L)) contrib_cols <- c(contrib_cols, "intercept_cycle")
    if (isTRUE(prep$intercept_use_season == 1L)) contrib_cols <- c(contrib_cols, "intercept_seasonality")
  } else {
    dt[, intercept := 0]
    contrib_cols <- c(contrib_cols, "intercept")
  }

  # extra controls on model scale
  if (length(extra_control_cols)) {
    used_extra <- extra_control_cols[extra_control_cols %in% names(dt)]
    for (k in seq_along(used_extra)) {
      nm <- used_extra[k]
      dt[, (nm) := get(nm) * pm$gamma[k]]
    }
    contrib_cols <- c(contrib_cols, used_extra)
  }

  # linear variables on model scale
  if (length(linear_vars)) {
    for (v in linear_vars) {
      j <- vl[variable == v, variable_idx]
      beta_vec <- pm$beta[cbind(dt$group_idx, j)]
      context_mult <- context_effect_multiplier_hier_mmm(
        prep$stan_data,
        variable_idx = j,
        row_idx = seq_len(nrow(dt)),
        context_coef = pm$context_coef
      )
      reference_model <- suppressWarnings(as.numeric(vl[variable == v, reference_value_model_scale][1]))
      if (!is.finite(reference_model)) reference_model <- 0
      sampling_center <- if (isTRUE(center_predictors)) prep$stan_data$X_center_mean[dt$group_idx, j] else 0
      center_offset_model <- center_offset_model + beta_vec * context_mult * (sampling_center - reference_model)
      dt[, (v) := (get(v) - reference_model) * beta_vec * context_mult]
    }
    contrib_cols <- c(contrib_cols, linear_vars)
  }

  # curved variables on model scale
  if (length(curve_vars)) {
    for (v in curve_vars) {
      j <- vl[variable == v, variable_idx]
      rr <- pm$rrate[j]
      cv <- pm$cvalue[j]
      dv <- pm$dvalue[j]
      curve_type <- vl[variable == v, curve_type][1] %||% "hill"
      curve_pos <- match(j, prep$stan_data$curve_idx)
      is_rf <- !is.null(prep$stan_data$is_rf_curve) && prep$stan_data$is_rf_curve[curve_pos] == 1L
      tmp <- numeric(nrow(dt))
      for (g in gl$group_idx) {
        idx <- which(dt$group_idx == g)
        tr <- if (isTRUE(is_rf)) {
          reach_frequency_transform_hier_mmm(
            reach_scaled = prep$stan_data$X_rf_reach[idx, curve_pos],
            frequency = prep$stan_data$X_rf_frequency[idx, curve_pos],
            rrate = rr,
            cvalue = cv,
            dvalue = dv,
            train_mask = !dt$is_holdout__[idx],
            normalize_curve_x = prep$normalize_curve_x,
            curve_normalization_scope = prep$curve_normalization_scope %||% "active_train"
          )
        } else {
          media_transform_hier_mmm(
            x = dt[[v]][idx],
            rrate = rr,
            cvalue = cv,
            dvalue = dv,
            curve_type = curve_type,
            train_mask = !dt$is_holdout__[idx],
            normalize_curve_x = prep$normalize_curve_x,
            curve_normalization_scope = prep$curve_normalization_scope %||% "active_train",
            multiplier = 1
          )
        }
        trans_vec <- tr$transformed
        center_value <- tr$center_value
        context_mult <- context_effect_multiplier_hier_mmm(
          prep$stan_data,
          variable_idx = j,
          row_idx = idx,
          context_coef = pm$context_coef
        )
        if (isTRUE(center_predictors)) {
          center_offset_model[idx] <- center_offset_model[idx] + pm$beta[g, j] * context_mult * center_value
        }
        tmp[idx] <- pm$beta[g, j] * context_mult * trans_vec
      }
      dt[, (v) := tmp]
    }
    contrib_cols <- c(contrib_cols, curve_vars)
  }

  contrib_cols <- unique(contrib_cols[contrib_cols %in% names(dt)])
  reporting_cols <- intersect("intercept_total", names(dt))

  if (any(abs(center_offset_model) > 1e-12, na.rm = TRUE)) {
    if ("intercept" %in% contrib_cols) {
      dt[, intercept := intercept - center_offset_model]
    } else if ("intercept_flat" %in% contrib_cols) {
      dt[, intercept_flat := intercept_flat - center_offset_model]
    } else if ("intercept_level" %in% contrib_cols) {
      dt[, intercept_level := intercept_level - center_offset_model]
    }
    if ("intercept_total" %in% names(dt)) {
      dt[, intercept_total := 0]
      if ("intercept_flat" %in% names(dt)) dt[, intercept_total := intercept_total + intercept_flat]
      if ("intercept_level" %in% names(dt)) dt[, intercept_total := intercept_total + intercept_level]
      if ("intercept_cycle" %in% names(dt)) dt[, intercept_total := intercept_total + intercept_cycle]
      if ("intercept_seasonality" %in% names(dt)) dt[, intercept_total := intercept_total + intercept_seasonality]
    }
  }

  dt[, pred_model_scale := rowSums(.SD), .SDcols = contrib_cols]
  dt[, y_model_scale := y_model__]
  dt[, residual_model_scale := y_model_scale - pred_model_scale]

  # rescale decomposition back to original units when possible
  scale_cols <- unique(c(contrib_cols, reporting_cols, "pred_model_scale", "residual_model_scale"))
  for (nm in scale_cols) {
    dt[, (paste0(nm, "__orig")) := get(nm) * rescale_factor__]
  }
  dt[, y_actual := fifelse(is.finite(y_original__), y_original__, y_model_scale * rescale_factor__)]
  dt[, pred := pred_model_scale__orig]
  dt[, residual := residual_model_scale__orig]
  dt[, rescale_factor := rescale_factor__]

  # move original-scale contribution/reporting columns back onto the original names for export
  for (nm in unique(c(contrib_cols, reporting_cols))) {
    dt[, (nm) := get(paste0(nm, "__orig"))]
  }

  # Posterior prediction intervals for fitted mean y_hat, rescaled to original units.
  yhat_sm <- if (isTRUE(include_prediction_intervals) && !is.null(fit)) {
    tryCatch(summarize_fit_vars(fit, variables = "y_hat"), error = function(e) data.table())
  } else {
    data.table()
  }
  if (nrow(yhat_sm) && "variable" %in% names(yhat_sm)) {
    q05_col <- pick_first_existing_col(yhat_sm, c("q5", "q05", "5%", "5.0%", "q_5"))
    q50_col <- pick_first_existing_col(yhat_sm, c("median", "q50", "50%", "50.0%", "q_50"))
    q95_col <- pick_first_existing_col(yhat_sm, c("q95", "95%", "95.0%", "q_95"))
    yhat_idx <- suppressWarnings(as.integer(sub("^y_hat\\[([0-9]+)\\]$", "\\1", yhat_sm$variable)))
    ok <- is.finite(yhat_idx) & yhat_idx >= 1L & yhat_idx <= nrow(dt)
    if (any(ok)) {
      yhat_sm <- yhat_sm[ok]
      yhat_sm[, row_id := yhat_idx[ok]]
      yhat_tmp <- yhat_sm[, .(
        row_id,
        pred_q05_model__ = if (!is.na(q05_col)) get(q05_col) else NA_real_,
        pred_q50_model__ = if (!is.na(q50_col)) get(q50_col) else NA_real_,
        pred_q95_model__ = if (!is.na(q95_col)) get(q95_col) else NA_real_
      )]
      dt[yhat_tmp, `:=`(
        pred_q05 = i.pred_q05_model__ * rescale_factor__,
        pred_q50 = i.pred_q50_model__ * rescale_factor__,
        pred_q95 = i.pred_q95_model__ * rescale_factor__
      ), on = "row_id"]
    }
  }

  id_cols <- c(
    "row_id",
    prep$group_col,
    prep$time_col,
    prep$entity_col,
    "sample",
    "y_actual",
    "pred",
    "pred_q05",
    "pred_q50",
    "pred_q95",
    "residual",
    "rescale_factor",
    "y_model_scale",
    "pred_model_scale",
    "residual_model_scale"
  )
  id_cols <- unique(id_cols[id_cols %in% names(dt)])

  wide_keep <- unique(c(id_cols, reporting_cols, contrib_cols))
  wide_decomp <- dt[, ..wide_keep]

  long_decomp <- melt(
    wide_decomp,
    id.vars = setdiff(wide_keep, contrib_cols),
    measure.vars = contrib_cols,
    variable.name = "variable",
    value.name = "contribution"
  )

  idc <- setdiff(names(wide_decomp), contrib_cols)
  residual_long <- copy(wide_decomp[, idc, with = FALSE])
  residual_long[, variable := "residual"]
  residual_long[, contribution := residual]

  long_decomp <- rbindlist(list(long_decomp, residual_long), use.names = TRUE, fill = TRUE)[order(row_id, variable)]
  decomp_meta <- vl[, .(
    variable,
    role,
    reference_value_spec,
    reference_value_raw,
    reference_value_model_scale,
    reference_value_source,
    x_scaling
  )]
  long_decomp[decomp_meta, on = "variable", `:=`(
    role = i.role,
    reference_value_spec = i.reference_value_spec,
    reference_value_raw = i.reference_value_raw,
    reference_value_model_scale = i.reference_value_model_scale,
    reference_value_source = i.reference_value_source,
    x_scaling = i.x_scaling
  )]
  long_decomp[, attribution_interpretation := data.table::fcase(
    role == "non_media_treatment", "causal_non_media_treatment_contrast_subject_to_assumptions",
    role == "control", "noncausal_control_reference_contrast",
    role %in% c("media", "reach_frequency", "organic_media", "organic_reach_frequency"), "causal_media_contrast_subject_to_assumptions",
    variable == "residual", "residual",
    default = "model_component_not_automatically_causal"
  )]

  list(
    coef_long = coef_long,
    coef_by_group = coef_by_group,
    coef_by_mod_id = coef_by_mod_id,
    wide_decomp = wide_decomp,
    long_decomp = long_decomp
  )
}


build_fit_quality_diagnostics <- function(wide_decomp, group_col, time_col) {
  dt <- copy(as.data.table(wide_decomp))
  req <- c("y_actual", "pred", "residual")
  if (!all(req %in% names(dt))) return(list(overall = data.table(), by_group = data.table()))

  calc <- function(x) {
    y <- x$y_actual
    p <- x$pred
    r <- x$residual
    denom <- sum((y - mean(y, na.rm = TRUE))^2, na.rm = TRUE)
    data.table(
      n = sum(is.finite(y) & is.finite(p)),
      actual_mean = mean(y, na.rm = TRUE),
      pred_mean = mean(p, na.rm = TRUE),
      residual_mean = mean(r, na.rm = TRUE),
      rmse = sqrt(mean(r^2, na.rm = TRUE)),
      mae = mean(abs(r), na.rm = TRUE),
      mape = mean(abs(r / fifelse(abs(y) <= 1e-8, NA_real_, y)), na.rm = TRUE),
      smape = mean(2 * abs(r) / fifelse(abs(y) + abs(p) <= 1e-8, NA_real_, abs(y) + abs(p)), na.rm = TRUE),
      r2 = if (is.finite(denom) && denom > 0) 1 - sum(r^2, na.rm = TRUE) / denom else NA_real_,
      residual_acf1 = {
        rr <- r[is.finite(r)]
        if (length(rr) > 2L) suppressWarnings(stats::acf(rr, plot = FALSE, lag.max = 1)$acf[2]) else NA_real_
      }
    )
  }

  overall <- calc(dt)
  if ("sample" %in% names(dt)) overall[, sample := "all"]

  by_sample <- data.table()
  if ("sample" %in% names(dt)) {
    by_sample <- dt[order(get(time_col)), calc(.SD), by = sample]
  }

  by_group <- data.table()
  if (group_col %in% names(dt)) {
    by_group <- dt[order(get(time_col)), calc(.SD), by = group_col]
    if ("sample" %in% names(dt)) {
      by_group_sample <- dt[order(get(time_col)), calc(.SD), by = c(group_col, "sample")]
      by_group <- rbindlist(list(by_group[, sample := "all"], by_group_sample), use.names = TRUE, fill = TRUE)
    }
  }
  list(overall = rbindlist(list(overall, by_sample), use.names = TRUE, fill = TRUE), by_group = by_group)
}


build_diagnostics_hier_mmm <- function(fit, max_treedepth = NA_integer_) {
  parameter_summary <- summarize_fit_vars(fit)

  sampler_chain <- data.table()
  sampler_overall <- data.table()

  sdiag <- tryCatch(fit$sampler_diagnostics(), error = function(e) NULL)
  if (!is.null(sdiag)) {
    sdiag_arr <- as.array(sdiag)
    dn <- dimnames(sdiag_arr)
    diag_names <- dn[[3]]
    n_iter <- dim(sdiag_arr)[1]
    n_chain <- dim(sdiag_arr)[2]

    get_diag <- function(name) {
      if (!(name %in% diag_names)) return(NULL)
      out <- sdiag_arr[, , match(name, diag_names), drop = TRUE]
      if (is.null(dim(out))) out <- matrix(out, ncol = 1L)
      if (length(dim(out)) == 1L) out <- matrix(out, ncol = 1L)
      out
    }

    div <- get_diag("divergent__")
    td <- get_diag("treedepth__")
    energy <- get_diag("energy__")
    accept <- get_diag("accept_stat__")
    leapfrog <- get_diag("n_leapfrog__")

    chain_list <- vector("list", n_chain)
    for (ch in seq_len(n_chain)) {
      div_n <- if (!is.null(div)) sum(div[, ch], na.rm = TRUE) else NA_real_
      td_n <- if (!is.null(td) && is.finite(max_treedepth)) sum(td[, ch] >= max_treedepth, na.rm = TRUE) else NA_real_
      bfmi <- NA_real_
      if (!is.null(energy)) {
        e <- as.numeric(energy[, ch])
        if (length(e) > 2 && stats::var(e) > 0) {
          bfmi <- mean(diff(e)^2) / stats::var(e)
        }
      }
      chain_list[[ch]] <- data.table(
        chain = ch,
        iterations = n_iter,
        divergences = div_n,
        treedepth_hits = td_n,
        mean_accept_stat = if (!is.null(accept)) mean(accept[, ch], na.rm = TRUE) else NA_real_,
        mean_n_leapfrog = if (!is.null(leapfrog)) mean(leapfrog[, ch], na.rm = TRUE) else NA_real_,
        min_energy_bfmi = bfmi
      )
    }
    sampler_chain <- rbindlist(chain_list, fill = TRUE)
    sampler_overall <- sampler_chain[, .(
      chains = .N,
      iterations_total = sum(iterations, na.rm = TRUE),
      divergences_total = sum(divergences, na.rm = TRUE),
      treedepth_hits_total = sum(treedepth_hits, na.rm = TRUE),
      mean_accept_stat = mean(mean_accept_stat, na.rm = TRUE),
      mean_n_leapfrog = mean(mean_n_leapfrog, na.rm = TRUE),
      min_bfmi = finite_min_or_na(min_energy_bfmi),
      max_rhat = if (n_chain >= 2L && "rhat" %in% names(parameter_summary)) finite_max_or_na(parameter_summary$rhat) else NA_real_,
      min_ess_bulk = if ("ess_bulk" %in% names(parameter_summary)) finite_min_or_na(parameter_summary$ess_bulk) else NA_real_,
      min_ess_tail = if ("ess_tail" %in% names(parameter_summary)) finite_min_or_na(parameter_summary$ess_tail) else NA_real_
    )]
  }

  diagnostics_flags <- data.table()
  if (nrow(sampler_overall)) {
    so <- sampler_overall[1]
    diagnostics_flags <- data.table(
      any_divergences = isTRUE(so$divergences_total > 0),
      any_treedepth_hits = isTRUE(so$treedepth_hits_total > 0),
      max_rhat_over_1_01 = isTRUE(is.finite(so$max_rhat) && so$max_rhat > 1.01),
      min_ess_bulk_under_400 = isTRUE(is.finite(so$min_ess_bulk) && so$min_ess_bulk < 400),
      min_ess_tail_under_400 = isTRUE(is.finite(so$min_ess_tail) && so$min_ess_tail < 400),
      min_bfmi_under_0_3 = isTRUE(is.finite(so$min_bfmi) && so$min_bfmi < 0.3)
    )
  }

  ucm_pattern <- "^(alpha|alpha_flat|level|level0|sigma_level|season|cycle|intercept_)|^(level_component|season_component|cycle_component|level_state)\\["
  if ("variable" %in% names(parameter_summary)) {
    parameter_summary[, diagnostic_block := fifelse(grepl(ucm_pattern, variable), "ucm", "bayesian_model")]
    parameter_summary_ucm <- parameter_summary[diagnostic_block == "ucm"]
    parameter_summary_bayes <- parameter_summary[diagnostic_block == "bayesian_model"]
  } else {
    parameter_summary_ucm <- data.table()
    parameter_summary_bayes <- parameter_summary
  }

  list(
    parameter_summary = parameter_summary,
    parameter_summary_bayes = parameter_summary_bayes,
    parameter_summary_ucm = parameter_summary_ucm,
    sampler_chain = sampler_chain,
    sampler_overall = sampler_overall,
    diagnostics_flags = diagnostics_flags
  )
}

recommend_hier_mmm_sampler_settings <- function(fit_or_diagnostics,
                                                current_max_treedepth = NA_integer_,
                                                iter_warmup = NA_integer_,
                                                iter_sampling = NA_integer_) {
  diagnostics <- if (is.list(fit_or_diagnostics) && !is.null(fit_or_diagnostics[["diagnostics"]])) {
    fit_or_diagnostics[["diagnostics"]]
  } else {
    fit_or_diagnostics
  }
  so <- diagnostics$sampler_overall %||% data.table()
  flags <- diagnostics$diagnostics_flags %||% data.table()
  recs <- list()
  add_rec <- function(priority, issue, recommendation, detail = "") {
    recs[[length(recs) + 1L]] <<- data.table(
      priority = priority,
      issue = issue,
      recommendation = recommendation,
      detail = detail
    )
  }
  if (nrow(flags) && isTRUE(flags$any_divergences[1])) {
    add_rec(
      "high",
      "divergences",
      "Increase adapt_delta, inspect tight coefficient/curve priors, and review collinear media before trusting posterior intervals.",
      if (nrow(so)) paste0("divergences_total=", so$divergences_total[1]) else ""
    )
  }
  if (nrow(flags) && isTRUE(flags$any_treedepth_hits[1])) {
    short_run <- is.finite(iter_warmup) && !is.na(iter_warmup) && iter_warmup < 300L
    add_rec(
      "medium",
      "max_treedepth_hits",
      if (short_run) {
        "This looks like a smoke-test geometry warning first: rerun with at least 300 warmup draws before changing the model. If hits persist under production warmup, compare normal likelihood, centered predictors, tighter external priors, and aggregation or simplification of weakly identified media/baseline terms."
      } else {
        "Max-treedepth pressure is posterior geometry, not a data-plumbing failure. For production runs, use longer warmup/sampling and max_treedepth 12-14; if hits persist, compare normal likelihood, centered predictors, tighter external priors, and aggregation or simplification of weakly identified media/baseline terms."
      },
      if (nrow(so)) paste0("treedepth_hits_total=", so$treedepth_hits_total[1],
                           "; current_max_treedepth=", current_max_treedepth,
                           "; iter_warmup=", iter_warmup,
                           "; iter_sampling=", iter_sampling) else ""
    )
  }
  if (nrow(flags) && (isTRUE(flags$max_rhat_over_1_01[1]) || isTRUE(flags$min_ess_bulk_under_400[1]) || isTRUE(flags$min_ess_tail_under_400[1]))) {
    add_rec(
      "medium",
      "low_effective_sample_or_rhat",
      "Use at least 4 chains, longer warmup/sampling, and review prior/posterior movement for curve and coefficient parameters.",
      if (nrow(so)) paste0("max_rhat=", signif(so$max_rhat[1], 4), "; min_ess_bulk=", signif(so$min_ess_bulk[1], 4), "; min_ess_tail=", signif(so$min_ess_tail[1], 4)) else ""
    )
  }
  if (nrow(flags) && isTRUE(flags$min_bfmi_under_0_3[1])) {
    add_rec(
      "medium",
      "low_bfmi",
      "Try stronger scale priors, better initialization, or simpler baseline structure before interpreting tail behavior.",
      if (nrow(so)) paste0("min_bfmi=", signif(so$min_bfmi[1], 4)) else ""
    )
  }
  if (!length(recs)) {
    add_rec("ok", "no_sampler_red_flags", "No immediate sampler setting change suggested from available diagnostics.", "")
  }
  rbindlist(recs, use.names = TRUE, fill = TRUE)
}

build_hier_mmm_model_readiness <- function(diagnostics,
                                           iter_warmup = NA_integer_,
                                           iter_sampling = NA_integer_,
                                           max_treedepth = NA_integer_,
                                           production_warmup_floor = 300L) {
  issues <- list()
  add_issue <- function(severity, area, issue, detail = "", recommendation = "") {
    issues[[length(issues) + 1L]] <<- data.table(
      severity = severity,
      area = area,
      issue = issue,
      detail = as.character(detail %||% ""),
      recommendation = as.character(recommendation %||% "")
    )
  }

  iter_warmup <- as.integer(iter_warmup %||% NA_integer_)
  iter_sampling <- as.integer(iter_sampling %||% NA_integer_)
  max_treedepth <- as.integer(max_treedepth %||% NA_integer_)
  production_warmup_floor <- as.integer(production_warmup_floor %||% 300L)
  short_run <- is.finite(iter_warmup) && !is.na(iter_warmup) && iter_warmup < production_warmup_floor

  so <- diagnostics$sampler_overall %||% data.table()
  fq <- diagnostics$fit_quality_overall %||% data.table()
  col <- diagnostics$collinearity_overall %||% data.table()
  coef_pp <- diagnostics$prior_posterior_coef %||% data.table()
  curve_pp <- diagnostics$prior_posterior_curve %||% data.table()
  ucm_steal <- diagnostics$ucm_media_stealing_overall %||% data.table()
  ucm_steal_group <- diagnostics$ucm_media_stealing_by_group %||% data.table()

  if (!nrow(so)) {
    add_issue("warning", "sampler", "missing_sampler_diagnostics",
              "Sampler diagnostics were not available in the fit object.",
              "Do not treat the fit as production-reviewed until sampler diagnostics are available.")
  } else {
    so1 <- so[1]
    if (isTRUE(is.finite(so1$chains) && so1$chains < 2)) {
      add_issue("review", "sampler", "single_chain_run",
                paste0("chains=", so1$chains),
                "Use at least 2 chains for convergence screening and 4 chains for production posterior review.")
    } else if (isTRUE(is.finite(so1$chains) && so1$chains < 4)) {
      add_issue("review", "sampler", "fewer_than_four_chains",
                paste0("chains=", so1$chains),
                "Use 4 chains for final production posterior review.")
    }
    if (isTRUE(so1$divergences_total > 0)) {
      add_issue("blocker", "sampler", "divergences",
                paste0("divergences_total=", so1$divergences_total),
                "Do not use posterior intervals or optimizer outputs until divergences are resolved.")
    }
    if (isTRUE(is.finite(so1$min_bfmi) && so1$min_bfmi < 0.3)) {
      add_issue("blocker", "sampler", "low_bfmi",
                paste0("min_bfmi=", signif(so1$min_bfmi, 4)),
                "Review scale priors, initialization, and weakly identified latent structure.")
    }
    if (isTRUE(so1$treedepth_hits_total > 0)) {
      add_issue(
        if (short_run) "review" else "warning",
        "sampler",
        "max_treedepth_hits",
        paste0("treedepth_hits_total=", so1$treedepth_hits_total,
               "; max_treedepth=", max_treedepth,
               "; iter_warmup=", iter_warmup),
        if (short_run) {
          "Rerun with production warmup before treating this as a model failure."
        } else {
          "Compare geometry settings, simplify weakly identified terms, or strengthen credible external priors."
        }
      )
    }
    rhat_valid <- isTRUE(is.finite(so1$chains) && so1$chains >= 2)
    if (rhat_valid && isTRUE(is.finite(so1$max_rhat) && so1$max_rhat > 1.05)) {
      add_issue("blocker", "sampler", "rhat_over_1_05",
                paste0("max_rhat=", signif(so1$max_rhat, 4)),
                "Run longer chains or simplify the model before using fit outputs.")
    } else if (rhat_valid && isTRUE(is.finite(so1$max_rhat) && so1$max_rhat > 1.01)) {
      add_issue("warning", "sampler", "rhat_over_1_01",
                paste0("max_rhat=", signif(so1$max_rhat, 4)),
                "Use longer chains and review affected parameters.")
    }
    if (isTRUE(is.finite(so1$min_ess_bulk) && so1$min_ess_bulk < 400)) {
      add_issue("review", "sampler", "low_bulk_ess",
                paste0("min_ess_bulk=", signif(so1$min_ess_bulk, 4)),
                "Use longer sampling for production intervals.")
    }
    if (isTRUE(is.finite(so1$min_ess_tail) && so1$min_ess_tail < 400)) {
      add_issue("review", "sampler", "low_tail_ess",
                paste0("min_ess_tail=", signif(so1$min_ess_tail, 4)),
                "Use longer sampling before relying on tail intervals.")
    }
  }

  if (short_run) {
    add_issue("info", "run_length", "short_warmup_smoke_run",
              paste0("iter_warmup=", iter_warmup, "; production_floor=", production_warmup_floor),
              "Use this run for plumbing and geometry screening, not final posterior claims.")
  }

  if (nrow(fq) && "sample" %in% names(fq)) {
    train <- fq[sample == "train"]
    holdout <- fq[sample == "holdout"]
    if (nrow(train) && is.finite(train$r2[1]) && train$r2[1] < 0.4) {
      add_issue("warning", "fit", "weak_train_fit",
                paste0("train_r2=", signif(train$r2[1], 4)),
                "Review missing controls, lag structure, transformations, and prior strength.")
    }
    if (nrow(holdout) && is.finite(holdout$r2[1]) && holdout$r2[1] < 0) {
      add_issue("review", "fit", "weak_holdout_fit",
                paste0("holdout_r2=", signif(holdout$r2[1], 4)),
                "Treat decisioning outputs cautiously and inspect holdout periods.")
    }
  }

  if (nrow(col)) {
    top_col <- col[order(-abs_correlation)][1]
    add_issue("review", "identification", "high_collinearity",
              paste0("top_pair=", top_col$variable_1, "|", top_col$variable_2,
                     "; abs_correlation=", signif(top_col$abs_correlation, 4),
                     "; flagged_pairs=", nrow(col)),
              "Expect coefficient/curve tradeoffs; use external, quasi-geo, or business-prior evidence where credible.")
  }

  if (nrow(coef_pp) && all(c("posterior_mean", "near_prior_flag", "far_from_prior_flag") %in% names(coef_pp))) {
    pp_ok <- coef_pp[is.finite(posterior_mean)]
    if (nrow(pp_ok)) {
      near_share <- pp_ok[, mean(near_prior_flag %in% TRUE, na.rm = TRUE)]
      far_share <- pp_ok[, mean(far_from_prior_flag %in% TRUE, na.rm = TRUE)]
      if (is.finite(near_share) && near_share >= 0.75) {
        add_issue("review", "prior_posterior", "coef_posterior_close_to_prior",
                  paste0("near_prior_share=", signif(near_share, 4)),
                  "Check that tight priors are intentionally calibration-grade rather than compensating for weak identification.")
      }
      if (is.finite(far_share) && far_share >= 0.25) {
        add_issue("review", "prior_posterior", "coef_posterior_far_from_prior",
                  paste0("far_from_prior_share=", signif(far_share, 4)),
                  "Review whether prior centers are stale, mismatched to KPI scale, or contradicted by the data.")
      }
    }
  }

  if (nrow(curve_pp) && all(c("posterior_mean", "far_from_prior_flag") %in% names(curve_pp))) {
    curve_ok <- curve_pp[is.finite(posterior_mean)]
    if (nrow(curve_ok)) {
      far_curve_share <- curve_ok[, mean(far_from_prior_flag %in% TRUE, na.rm = TRUE)]
      if (is.finite(far_curve_share) && far_curve_share >= 0.25) {
        add_issue("review", "prior_posterior", "curve_posterior_far_from_prior",
                  paste0("far_from_prior_share=", signif(far_curve_share, 4)),
                  "Review curve prior construction and do not over-interpret saturation without independent support.")
      }
    }
  }

  if (nrow(ucm_steal) && "media_stealing_risk" %in% names(ucm_steal)) {
    risk <- as.character(ucm_steal$media_stealing_risk[1])
    detail <- paste0(
      "risk=", risk,
      "; ucm_share=", signif(ucm_steal$ucm_share_of_actual[1], 4),
      "; corr_level=", signif(ucm_steal$corr_ucm_media[1], 4),
      "; corr_change=", signif(ucm_steal$corr_change_ucm_media[1], 4)
    )
    if (identical(risk, "high")) {
      add_issue(
        "warning", "baseline_identification", "possible_ucm_media_stealing", detail,
        "Review baseline flexibility, omitted controls, media priors, and contribution stability before decisioning. This diagnostic is a warning, not causal proof of stealing."
      )
    } else if (identical(risk, "moderate")) {
      add_issue(
        "review", "baseline_identification", "ucm_media_separation_review", detail,
        "Inspect baseline and media contribution paths together; a large baseline share alone is not evidence of media stealing."
      )
    }
  }
  if (nrow(ucm_steal_group) && "media_stealing_risk" %in% names(ucm_steal_group)) {
    high_group_n <- ucm_steal_group[media_stealing_risk == "high", .N]
    if (high_group_n > 0L && !(nrow(ucm_steal) && identical(as.character(ucm_steal$media_stealing_risk[1]), "high"))) {
      add_issue(
        "review", "baseline_identification", "group_specific_ucm_media_stealing_risk",
        paste0("high_risk_groups=", high_group_n, "/", nrow(ucm_steal_group)),
        "Review affected groups before relying on group-level ROI, mROI, or optimization outputs."
      )
    }
  }

  issue_dt <- if (length(issues)) rbindlist(issues, use.names = TRUE, fill = TRUE) else data.table(
    severity = "ok",
    area = "overall",
    issue = "no_major_readiness_flags",
    detail = "",
    recommendation = "Proceed with standard MMM review: prior predictive checks, posterior diagnostics, fit quality, and business sanity checks."
  )
  rank_lookup <- c(ok = 0L, info = 1L, review = 2L, warning = 3L, blocker = 4L)
  issue_dt[, severity_rank := as.integer(rank_lookup[severity])]
  issue_dt[is.na(severity_rank), severity_rank := 0L]
  setorder(issue_dt, -severity_rank, area, issue)
  top_rank <- issue_dt[1, severity_rank]
  status <- if (top_rank >= 4L) {
    "not_ready"
  } else if (top_rank >= 3L) {
    "review_before_use"
  } else if (top_rank >= 2L) {
    "usable_with_review"
  } else {
    "usable_after_standard_review"
  }

  list(
    summary = data.table(
      model_readiness = status,
      highest_severity = issue_dt[1, severity],
      issue_count = issue_dt[issue != "no_major_readiness_flags", .N],
      blocker_count = issue_dt[severity == "blocker", .N],
      warning_count = issue_dt[severity == "warning", .N],
      review_count = issue_dt[severity == "review", .N],
      info_count = issue_dt[severity == "info", .N],
      short_warmup_smoke_run = short_run,
      iter_warmup = iter_warmup,
      iter_sampling = iter_sampling,
      max_treedepth = max_treedepth,
      top_issue = issue_dt[1, issue],
      top_recommendation = issue_dt[1, recommendation]
    ),
    issues = issue_dt[]
  )
}

build_ucm_component_diagnostics <- function(wide_decomp, group_col, time_col) {
  dt <- copy(as.data.table(wide_decomp))
  component_cols <- intersect(c("intercept_flat", "intercept_level", "intercept_seasonality", "intercept_cycle", "intercept_total"), names(dt))
  if (!length(component_cols)) return(list(overall = data.table(), by_group = data.table()))

  calc <- function(x) {
    rbindlist(lapply(component_cols, function(cc) {
      z <- x[[cc]]
      data.table(
        component = cc,
        n = sum(is.finite(z)),
        mean = mean(z, na.rm = TRUE),
        sd = safe_sd(z),
        min = if (any(is.finite(z))) suppressWarnings(min(z, na.rm = TRUE)) else NA_real_,
        max = if (any(is.finite(z))) suppressWarnings(max(z, na.rm = TRUE)) else NA_real_,
        contribution_share_of_actual = if ("y_actual" %in% names(x) && abs(sum(x$y_actual, na.rm = TRUE)) > 1e-8) sum(z, na.rm = TRUE) / sum(x$y_actual, na.rm = TRUE) else NA_real_,
        acf1 = {
          zz <- z[is.finite(z)]
          if (length(zz) > 2L) suppressWarnings(stats::acf(zz, plot = FALSE, lag.max = 1)$acf[2]) else NA_real_
        },
        corr_with_residual = if ("residual" %in% names(x)) suppressWarnings(stats::cor(z, x$residual, use = "complete.obs")) else NA_real_,
        corr_with_actual = if ("y_actual" %in% names(x)) suppressWarnings(stats::cor(z, x$y_actual, use = "complete.obs")) else NA_real_
      )
    }), fill = TRUE)
  }

  overall <- calc(dt)
  by_group <- data.table()
  if (group_col %in% names(dt)) {
    by_group <- dt[order(get(time_col)), calc(.SD), by = group_col]
  }
  list(overall = overall, by_group = by_group)
}

build_prior_posterior_diagnostics <- function(fit, prep, outputs) {
  sm <- summarize_fit_vars(fit)
  if (!("variable" %in% names(sm))) {
    return(list(coef = data.table(), curve = data.table(), context = data.table()))
  }

  sd_col <- pick_first_existing_col(sm, c("sd", "stddev", "std_dev"))
  q05_col <- pick_first_existing_col(sm, c("q5", "q05", "5%", "5.0%", "q_5"))
  q50_col <- pick_first_existing_col(sm, c("median", "q50", "50%", "50.0%", "q_50"))
  q95_col <- pick_first_existing_col(sm, c("q95", "95%", "95.0%", "q_95"))

  param_stats <- function(param_names) {
    out <- data.table(parameter = param_names)
    stat <- sm[, .(
      parameter = variable,
      posterior_mean = mean,
      posterior_sd = if (!is.na(sd_col)) get(sd_col) else NA_real_,
      posterior_q05 = if (!is.na(q05_col)) get(q05_col) else NA_real_,
      posterior_q50 = if (!is.na(q50_col)) get(q50_col) else NA_real_,
      posterior_q95 = if (!is.na(q95_col)) get(q95_col) else NA_real_
    )]
    out[stat, on = "parameter", `:=`(
      posterior_mean = i.posterior_mean,
      posterior_sd = i.posterior_sd,
      posterior_q05 = i.posterior_q05,
      posterior_q50 = i.posterior_q50,
      posterior_q95 = i.posterior_q95
    )]
    out[]
  }

  coef_diag <- copy(outputs$coef_long)
  if (!all(c("group_idx", "variable_idx") %in% names(coef_diag))) {
    coef_diag[, group_idx := match(mod_id, prep$group_lookup$group_value)]
    coef_diag[, variable_idx := match(variable, prep$variable_lookup$variable)]
  }
  coef_diag[, parameter := sprintf("beta[%d,%d]", group_idx, variable_idx)]
  coef_stats <- param_stats(coef_diag$parameter)
  coef_diag[coef_stats, on = "parameter", `:=`(
    posterior_mean = i.posterior_mean,
    posterior_sd = i.posterior_sd,
    posterior_q05 = i.posterior_q05,
    posterior_q50 = i.posterior_q50,
    posterior_q95 = i.posterior_q95
  )]

  md_coef <- copy(prep$metadata)[, .(
    variable,
    prior_center = coef,
    coef_precision,
    coef_bound,
    bound_type,
    coef_lower,
    coef_upper
  )]
  md_coef[, prior_sd_nominal := 1 / sqrt(pmax(coef_precision, 1e-8))]
  md_coef[, prior_sd_nominal_relaxed := prior_sd_nominal * (prep$coef_prior_relax %||% 1.5)]
  md_coef[, prior_sd_floor := (prep$min_coef_sd_frac %||% 0.05) * abs(prior_center) + (prep$min_coef_sd_abs %||% 0.001)]
  md_coef[, prior_sd_used := fifelse(
    is.finite(coef_precision) & coef_precision >= (prep$hard_prior_precision_threshold %||% 1e6),
    pmax(prior_sd_nominal_relaxed, 1e-8),
    pmax(prior_sd_nominal_relaxed, prior_sd_floor)
  )]

  coef_diag[md_coef, on = "variable", `:=`(
    prior_center = i.prior_center,
    prior_sd_nominal = i.prior_sd_nominal,
    prior_sd_used = i.prior_sd_used,
    coef_precision = i.coef_precision,
    coef_bound = i.coef_bound,
    bound_type = i.bound_type,
    coef_lower = i.coef_lower,
    coef_upper = i.coef_upper
  )]
  coef_diag[, `:=`(
    posterior_minus_prior = posterior_mean - prior_center,
    posterior_z_vs_prior = (posterior_mean - prior_center) / pmax(prior_sd_used, 1e-8),
    posterior_sd_to_prior_sd = posterior_sd / pmax(prior_sd_used, 1e-8),
    near_prior_flag = is.finite(posterior_mean) & abs(posterior_mean - prior_center) <= 0.10 * pmax(prior_sd_used, 1e-8),
    far_from_prior_flag = is.finite(posterior_mean) & abs(posterior_mean - prior_center) >= 2.00 * pmax(prior_sd_used, 1e-8)
  )]

  curve_md <- copy(prep$metadata)[has_curve == 1L]
  curve_diag <- data.table()
  if (nrow(curve_md)) {
    curve_long <- rbindlist(list(
      curve_md[, .(
        variable,
        curve_parameter = "rrate",
        internal_stan_parameter = "rrate",
        prior_center = rrate,
        prior_precision = rrate_precision,
        lower = rrate_lower,
        upper = rrate_upper
      )],
      curve_md[, .(
        variable,
        curve_parameter = "curve_rate",
        internal_stan_parameter = "cvalue",
        prior_center = cvalue,
        prior_precision = cvalue_precision,
        lower = cvalue_lower,
        upper = cvalue_upper
      )],
      curve_md[, .(
        variable,
        curve_parameter = "dvalue",
        internal_stan_parameter = "dvalue",
        prior_center = dvalue,
        prior_precision = dvalue_precision,
        lower = dvalue_lower,
        upper = dvalue_upper
      )]
    ), fill = TRUE)
    curve_long[prep$variable_lookup[, .(variable, variable_idx, curve_param_idx)], on = "variable", `:=`(
      variable_idx = i.variable_idx,
      curve_param_idx = i.curve_param_idx
    )]
    curve_long[, parameter := sprintf("%s[%d]", internal_stan_parameter, curve_param_idx)]
    curve_long[, prior_sd_nominal := 1 / sqrt(pmax(prior_precision, 1e-8))]
    curve_long[, prior_sd_used := pmax(
      prior_sd_nominal * (prep$curve_prior_relax %||% 2),
      0.08 * pmax(upper - lower, 1e-8)
    )]
    curve_long[curve_parameter == "dvalue" & isFALSE(prep$estimate_dvalue), prior_sd_used := pmin(prior_sd_used, 1e-4)]

    curve_stats <- param_stats(curve_long$parameter)
    curve_diag <- copy(curve_long)
    curve_diag[curve_stats, on = "parameter", `:=`(
      posterior_mean = i.posterior_mean,
      posterior_sd = i.posterior_sd,
      posterior_q05 = i.posterior_q05,
      posterior_q50 = i.posterior_q50,
      posterior_q95 = i.posterior_q95
    )]
    curve_diag[, `:=`(
      posterior_minus_prior = posterior_mean - prior_center,
      posterior_z_vs_prior = (posterior_mean - prior_center) / pmax(prior_sd_used, 1e-8),
      posterior_sd_to_prior_sd = posterior_sd / pmax(prior_sd_used, 1e-8),
      near_prior_flag = is.finite(posterior_mean) & abs(posterior_mean - prior_center) <= 0.10 * pmax(prior_sd_used, 1e-8),
      far_from_prior_flag = is.finite(posterior_mean) & abs(posterior_mean - prior_center) >= 2.00 * pmax(prior_sd_used, 1e-8)
    )]
  }

  context_diag <- data.table()
  if (!is.null(prep$context_effects) && nrow(prep$context_effects)) {
    context_diag <- copy(prep$context_effects)
    context_diag[, parameter := sprintf("context_coef[%d]", context_idx)]
    context_stats <- param_stats(context_diag$parameter)
    context_diag[context_stats, on = "parameter", `:=`(
      posterior_mean = i.posterior_mean,
      posterior_sd = i.posterior_sd,
      posterior_q05 = i.posterior_q05,
      posterior_q50 = i.posterior_q50,
      posterior_q95 = i.posterior_q95
    )]
    context_diag[, `:=`(
      prior_center = context_coef_mean,
      prior_sd_used = context_coef_sd,
      posterior_minus_prior = posterior_mean - context_coef_mean,
      posterior_z_vs_prior = (posterior_mean - context_coef_mean) / pmax(context_coef_sd, 1e-8),
      posterior_sd_to_prior_sd = posterior_sd / pmax(context_coef_sd, 1e-8),
      near_prior_flag = is.finite(posterior_mean) & abs(posterior_mean - context_coef_mean) <= 0.10 * pmax(context_coef_sd, 1e-8),
      far_from_prior_flag = is.finite(posterior_mean) & abs(posterior_mean - context_coef_mean) >= 2.00 * pmax(context_coef_sd, 1e-8),
      interpretation = fifelse(
        context_sign == "positive",
        "Higher context increases the target variable contribution multiplier.",
        fifelse(
          context_sign == "negative",
          "Higher context decreases the target variable contribution multiplier.",
          "Higher context may increase or decrease the target variable contribution multiplier."
        )
      )
    )]
    if (all(c("context_train_min_z", "context_train_max_z") %in% names(context_diag))) {
      post_log_a <- context_diag$context_train_min_z * context_diag$posterior_mean
      post_log_b <- context_diag$context_train_max_z * context_diag$posterior_mean
      bound <- as.numeric(prep$context_log_multiplier_bound %||% 2)[1]
      if (!is.finite(bound) || bound <= 0) bound <- 2
      context_diag[, `:=`(
        posterior_multiplier_min_train_range = exp(pmin(clip_numeric(post_log_a, -bound, bound), clip_numeric(post_log_b, -bound, bound), na.rm = TRUE)),
        posterior_multiplier_max_train_range = exp(pmax(clip_numeric(post_log_a, -bound, bound), clip_numeric(post_log_b, -bound, bound), na.rm = TRUE))
      )]
      context_diag[, context_review_flag := (
        context_risk_level != "standard" |
          far_from_prior_flag |
          posterior_multiplier_min_train_range < 0.25 |
          posterior_multiplier_max_train_range > 4
      )]
    }
  }

  list(coef = coef_diag[], curve = curve_diag[], context = context_diag[])
}

build_hier_mmm_prior_audit <- function(prep, prior_post) {
  coef <- copy(as.data.table(prior_post$coef %||% data.table()))
  if (!nrow(coef)) return(data.table())
  md <- copy(as.data.table(prep$metadata))
  keep <- intersect(c(
    "variable", "role", "source_entity", "curve_type", "has_curve",
    "business_prior_metric", "business_prior_input_mean", "business_prior_input_sd",
    "business_prior_input_precision", "business_prior_input_uncertainty_basis",
    "business_prior_input_uncertainty_source", "business_prior_coef_sd",
    "business_prior_coef_precision_uncapped", "business_prior_precision_was_capped",
    "business_prior_distribution", "business_prior_basis", "business_prior_evidence_source",
    "business_prior_evidence_notes", "business_prior_reference_value_raw",
    "business_prior_reference_value_model_scale", "business_prior_elasticity_reference_raw",
    "business_prior_attribution_interpretation", "reference_value_spec", "reference_value_raw",
    "reference_value_model_scale", "reference_value_source", "coef_hierarchy_scope", "coef_hierarchy_key_id",
    "hierarchy_note"
  ), names(md))
  if ("variable" %in% keep) {
    md <- unique(md[, ..keep], by = "variable")
    add_cols <- setdiff(names(md), "variable")
    coef[md, on = "variable", (add_cols) := mget(paste0("i.", add_cols))]
  }

  for (cc in c(
    "business_prior_metric", "business_prior_input_mean", "business_prior_input_sd",
    "business_prior_input_precision", "business_prior_input_uncertainty_basis",
    "business_prior_input_uncertainty_source", "business_prior_basis",
    "business_prior_evidence_source", "business_prior_evidence_notes"
  )) {
    if (!(cc %in% names(coef))) coef[, (cc) := NA]
  }

  coef[, `:=`(
    prior_audit_level = "group_coefficient",
    prior_source = fifelse(!is.na(business_prior_metric) & nzchar(as.character(business_prior_metric)), "business_prior", "metadata_prior"),
    input_prior_metric = as.character(business_prior_metric),
    input_prior_mean = suppressWarnings(as.numeric(business_prior_input_mean)),
    input_prior_sd = suppressWarnings(as.numeric(business_prior_input_sd)),
    input_prior_precision = suppressWarnings(as.numeric(business_prior_input_precision)),
    input_uncertainty_basis = as.character(business_prior_input_uncertainty_basis),
    converted_stan_prior_mean = prior_center,
    converted_stan_prior_sd = prior_sd_used,
    converted_stan_prior_precision = coef_precision,
    posterior_interval_excludes_prior_center = is.finite(posterior_q05) & is.finite(posterior_q95) &
      is.finite(prior_center) & (prior_center < posterior_q05 | prior_center > posterior_q95),
    posterior_stuck_to_prior_flag = is.finite(posterior_sd_to_prior_sd) &
      is.finite(posterior_z_vs_prior) &
      abs(posterior_z_vs_prior) <= 0.10 &
      posterior_sd_to_prior_sd >= 0.80
  )]
  coef[, prior_posterior_status := fifelse(
    far_from_prior_flag,
    "posterior_shifted_from_prior_review",
    fifelse(
      posterior_stuck_to_prior_flag,
      "posterior_still_prior_dominated_review",
      fifelse(near_prior_flag, "posterior_close_to_prior", "posterior_updated_within_prior_width")
    )
  )]
  coef[, recommended_action := fifelse(
    far_from_prior_flag & prior_source == "business_prior",
    "review_business_prior_or_model_identification",
    fifelse(
      posterior_stuck_to_prior_flag,
      "check_whether_data_identify_this_coefficient_or_prior_is_too_tight",
      fifelse(far_from_prior_flag, "review_metadata_prior_or_data_support", "no_immediate_action")
    )
  )]

  cols <- intersect(c(
    "prior_audit_level", "group_value", "model_id", "mod_id", "target_entity",
    "variable", "role", "source_entity", "has_curve", "curve_type",
    "prior_source", "input_prior_metric", "input_prior_mean", "input_prior_sd",
    "input_prior_precision", "input_uncertainty_basis",
    "business_prior_input_uncertainty_source", "business_prior_basis",
    "business_prior_evidence_source", "business_prior_evidence_notes",
    "business_prior_reference_value_raw", "business_prior_reference_value_model_scale",
    "business_prior_elasticity_reference_raw", "business_prior_attribution_interpretation",
    "reference_value_spec", "reference_value_raw", "reference_value_model_scale", "reference_value_source",
    "converted_stan_prior_mean", "converted_stan_prior_sd", "converted_stan_prior_precision",
    "coef_bound", "bound_type", "coef_lower", "coef_upper",
    "posterior_mean", "posterior_sd", "posterior_q05", "posterior_q50", "posterior_q95",
    "posterior_minus_prior", "posterior_z_vs_prior", "posterior_sd_to_prior_sd",
    "near_prior_flag", "far_from_prior_flag", "posterior_interval_excludes_prior_center",
    "posterior_stuck_to_prior_flag", "prior_posterior_status", "recommended_action",
    "coef_hierarchy_scope", "coef_hierarchy_key_id", "hierarchy_note"
  ), names(coef))
  coef[, ..cols][]
}


build_collinearity_diagnostics <- function(prep, threshold = 0.85) {
  dt <- copy(prep$data)
  vars <- prep$variable_lookup$variable
  vars <- vars[vars %in% names(dt)]
  if (length(vars) < 2L) return(list(overall = data.table(), by_group = data.table()))

  pair_cor <- function(x, scope = "overall", group_value = NA_character_) {
    x <- as.data.table(x)
    mat <- as.matrix(x[, ..vars])
    storage.mode(mat) <- "double"
    cm <- suppressWarnings(stats::cor(mat, use = "pairwise.complete.obs"))
    idx <- which(upper.tri(cm), arr.ind = TRUE)
    if (!nrow(idx)) return(data.table())
    out <- data.table(
      scope = scope,
      group_value = group_value,
      variable_1 = colnames(cm)[idx[, 1]],
      variable_2 = colnames(cm)[idx[, 2]],
      correlation = cm[idx],
      abs_correlation = abs(cm[idx])
    )
    out <- out[is.finite(abs_correlation) & abs_correlation >= threshold]
    out[order(-abs_correlation)]
  }

  overall <- pair_cor(dt, scope = "overall", group_value = NA_character_)
  by_group <- data.table()
  if (prep$group_col %in% names(dt)) {
    by_group <- rbindlist(lapply(split(dt, dt[[prep$group_col]]), function(z) {
      pair_cor(z, scope = "group", group_value = as.character(z[[prep$group_col]][1]))
    }), fill = TRUE)
  }

  role_map <- prep$variable_lookup[, .(
    variable,
    role,
    source_entity,
    has_curve
  )]
  add_roles <- function(x) {
    if (!nrow(x)) return(x)
    x[role_map, on = .(variable_1 = variable), `:=`(
      role_1 = i.role,
      source_entity_1 = i.source_entity,
      has_curve_1 = i.has_curve
    )]
    x[role_map, on = .(variable_2 = variable), `:=`(
      role_2 = i.role,
      source_entity_2 = i.source_entity,
      has_curve_2 = i.has_curve
    )]
    x[]
  }

  list(overall = add_roles(overall), by_group = add_roles(by_group))
}


build_ucm_media_stealing_diagnostics <- function(wide_decomp,
                                                 variable_lookup,
                                                 group_col,
                                                 time_col) {
  dt <- copy(as.data.table(wide_decomp))
  media_cols <- variable_lookup[role %in% c("media", "reach_frequency"), variable]
  media_cols <- media_cols[media_cols %in% names(dt)]
  ucm_col <- if ("intercept_total" %in% names(dt)) "intercept_total" else if ("intercept" %in% names(dt)) "intercept" else NA_character_
  if (!length(media_cols) || is.na(ucm_col)) return(list(overall = data.table(), by_group = data.table()))

  dt[, media_total__ := rowSums(.SD, na.rm = TRUE), .SDcols = media_cols]
  dt[, ucm_total__ := get(ucm_col)]
  if (group_col %in% names(dt)) {
    setorderv(dt, c(group_col, time_col))
    dt[, `:=`(
      ucm_change__ = c(NA_real_, diff(ucm_total__)),
      media_change__ = c(NA_real_, diff(media_total__))
    ), by = group_col]
  } else {
    setorderv(dt, time_col)
    dt[, `:=`(
      ucm_change__ = c(NA_real_, diff(ucm_total__)),
      media_change__ = c(NA_real_, diff(media_total__))
    )]
  }

  calc <- function(x) {
    y_sum <- if ("y_actual" %in% names(x)) sum(x$y_actual, na.rm = TRUE) else NA_real_
    media_sum <- sum(x$media_total__, na.rm = TRUE)
    ucm_sum <- sum(x$ucm_total__, na.rm = TRUE)
    corr_level <- safe_cor(x$ucm_total__, x$media_total__)
    corr_change <- safe_cor(x$ucm_change__, x$media_change__)
    ucm_share <- if (is.finite(y_sum) && abs(y_sum) > 1e-8) ucm_sum / y_sum else NA_real_
    high_level <- is.finite(corr_level) && abs(corr_level) >= 0.70
    high_change <- is.finite(corr_change) && abs(corr_change) >= 0.60
    high_share <- is.finite(ucm_share) && abs(ucm_share) >= 0.80
    risk <- if (high_change || (high_share && high_level)) "high" else if (high_level || high_share) "moderate" else "low"
    reasons <- c(
      if (high_share) "large_baseline_share",
      if (high_level) "high_level_comovement",
      if (high_change) "high_change_comovement"
    )
    data.table(
      n = nrow(x),
      ucm_column = ucm_col,
      media_columns = paste(media_cols, collapse = "|"),
      ucm_sum = ucm_sum,
      media_sum = media_sum,
      ucm_share_of_actual = ucm_share,
      media_share_of_actual = if (is.finite(y_sum) && abs(y_sum) > 1e-8) media_sum / y_sum else NA_real_,
      corr_ucm_media = corr_level,
      corr_change_ucm_media = corr_change,
      corr_ucm_actual = if ("y_actual" %in% names(x)) safe_cor(x$ucm_total__, x$y_actual) else NA_real_,
      corr_ucm_residual = if ("residual" %in% names(x)) safe_cor(x$ucm_total__, x$residual) else NA_real_,
      ucm_acf1 = {
        zz <- x$ucm_total__[is.finite(x$ucm_total__)]
        if (length(zz) > 2L) suppressWarnings(stats::acf(zz, plot = FALSE, lag.max = 1)$acf[2]) else NA_real_
      },
      media_acf1 = {
        zz <- x$media_total__[is.finite(x$media_total__)]
        if (length(zz) > 2L) suppressWarnings(stats::acf(zz, plot = FALSE, lag.max = 1)$acf[2]) else NA_real_
      },
      high_ucm_media_corr_flag = high_level,
      high_ucm_media_change_corr_flag = high_change,
      high_ucm_share_flag = high_share,
      media_stealing_risk = risk,
      risk_reasons = if (length(reasons)) paste(reasons, collapse = "|") else "none",
      recommended_action = if (risk == "high") {
        "Review baseline flexibility, omitted controls, media priors, and contribution stability before decisioning."
      } else if (risk == "moderate") {
        "Inspect baseline/media separation; do not infer stealing from baseline share alone."
      } else {
        "No strong baseline/media stealing signal from these diagnostics."
      }
    )
  }

  overall <- calc(dt)
  by_group <- data.table()
  if (group_col %in% names(dt)) {
    by_group <- dt[order(get(time_col)), calc(.SD), by = group_col]
  }
  list(overall = overall, by_group = by_group)
}



write_outputs_hier_mmm <- function(outputs, diagnostics, output_dir, prefix = "") {
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  pfx <- if (nzchar(prefix)) paste0(prefix, "_") else ""
  fwrite(outputs$coef_by_group, file.path(output_dir, paste0(pfx, "coef_by_group.csv")))
  fwrite(outputs$coef_by_mod_id, file.path(output_dir, paste0(pfx, "coef_by_mod_id.csv")))
  fwrite(outputs$wide_decomp, file.path(output_dir, paste0(pfx, "wide_decomp.csv")))
  fwrite(outputs$long_decomp, file.path(output_dir, paste0(pfx, "long_decomp.csv")))

  fwrite(diagnostics$parameter_summary_bayes, file.path(output_dir, paste0(pfx, "diagnostics_bayes_parameter_summary.csv")))
  if (nrow(diagnostics$parameter_summary_ucm)) fwrite(diagnostics$parameter_summary_ucm, file.path(output_dir, paste0(pfx, "diagnostics_ucm_parameter_summary.csv")))

  if (nrow(diagnostics$sampler_chain)) fwrite(diagnostics$sampler_chain, file.path(output_dir, paste0(pfx, "diagnostics_bayes_sampler_chain.csv")))
  if (nrow(diagnostics$sampler_overall)) fwrite(diagnostics$sampler_overall, file.path(output_dir, paste0(pfx, "diagnostics_bayes_sampler_overall.csv")))
  if (nrow(diagnostics$diagnostics_flags)) fwrite(diagnostics$diagnostics_flags, file.path(output_dir, paste0(pfx, "diagnostics_bayes_flags.csv")))
  if (!is.null(diagnostics$sampler_recommendations) && nrow(diagnostics$sampler_recommendations)) fwrite(diagnostics$sampler_recommendations, file.path(output_dir, paste0(pfx, "diagnostics_sampler_recommendations.csv")))
  if (!is.null(diagnostics$model_readiness) && nrow(diagnostics$model_readiness)) fwrite(diagnostics$model_readiness, file.path(output_dir, paste0(pfx, "diagnostics_model_readiness.csv")))
  if (!is.null(diagnostics$model_readiness_issues) && nrow(diagnostics$model_readiness_issues)) fwrite(diagnostics$model_readiness_issues, file.path(output_dir, paste0(pfx, "diagnostics_model_readiness_issues.csv")))

  if (!is.null(diagnostics$fit_quality_overall) && nrow(diagnostics$fit_quality_overall)) fwrite(diagnostics$fit_quality_overall, file.path(output_dir, paste0(pfx, "diagnostics_bayes_fit_quality_overall.csv")))
  if (!is.null(diagnostics$fit_quality_by_group) && nrow(diagnostics$fit_quality_by_group)) fwrite(diagnostics$fit_quality_by_group, file.path(output_dir, paste0(pfx, "diagnostics_bayes_fit_quality_by_group.csv")))

  if (!is.null(diagnostics$ucm_component_overall) && nrow(diagnostics$ucm_component_overall)) fwrite(diagnostics$ucm_component_overall, file.path(output_dir, paste0(pfx, "diagnostics_ucm_component_overall.csv")))
  if (!is.null(diagnostics$ucm_component_by_group) && nrow(diagnostics$ucm_component_by_group)) fwrite(diagnostics$ucm_component_by_group, file.path(output_dir, paste0(pfx, "diagnostics_ucm_component_by_group.csv")))

  if (!is.null(diagnostics$prior_posterior_coef) && nrow(diagnostics$prior_posterior_coef)) fwrite(diagnostics$prior_posterior_coef, file.path(output_dir, paste0(pfx, "diagnostics_prior_vs_posterior_coef.csv")))
  if (!is.null(diagnostics$prior_posterior_curve) && nrow(diagnostics$prior_posterior_curve)) fwrite(diagnostics$prior_posterior_curve, file.path(output_dir, paste0(pfx, "diagnostics_prior_vs_posterior_curve.csv")))
  if (!is.null(diagnostics$prior_posterior_context) && nrow(diagnostics$prior_posterior_context)) fwrite(diagnostics$prior_posterior_context, file.path(output_dir, paste0(pfx, "diagnostics_prior_vs_posterior_context.csv")))
  if (!is.null(diagnostics$prior_audit) && nrow(diagnostics$prior_audit)) fwrite(diagnostics$prior_audit, file.path(output_dir, paste0(pfx, "prior_audit.csv")))

  if (!is.null(diagnostics$collinearity_overall) && nrow(diagnostics$collinearity_overall)) fwrite(diagnostics$collinearity_overall, file.path(output_dir, paste0(pfx, "diagnostics_collinearity_overall.csv")))
  if (!is.null(diagnostics$collinearity_by_group) && nrow(diagnostics$collinearity_by_group)) fwrite(diagnostics$collinearity_by_group, file.path(output_dir, paste0(pfx, "diagnostics_collinearity_by_group.csv")))

  if (!is.null(diagnostics$ucm_media_stealing_overall) && nrow(diagnostics$ucm_media_stealing_overall)) fwrite(diagnostics$ucm_media_stealing_overall, file.path(output_dir, paste0(pfx, "diagnostics_ucm_media_stealing_overall.csv")))
  if (!is.null(diagnostics$ucm_media_stealing_by_group) && nrow(diagnostics$ucm_media_stealing_by_group)) fwrite(diagnostics$ucm_media_stealing_by_group, file.path(output_dir, paste0(pfx, "diagnostics_ucm_media_stealing_by_group.csv")))

  invisible(output_dir)
}
