# 017-hier_mmm-decisioning.R
# Generated by behavior-preserving split of hier_mmm.R.

as_hier_mmm_data_table <- function(x, label = "input") {
  if (is.null(x)) return(NULL)
  out <- read_input_table(x)
  if (!inherits(out, "data.table")) out <- as.data.table(out)
  out
}

normalize_spend_map_hier_mmm <- function(fit_obj,
                                         spend_map = NULL,
                                         raw_data = NULL,
                                         spend_suffix = "_spend",
                                         variables = NULL) {
  vl <- copy(as.data.table(fit_obj$variable_lookup))
  md <- copy(as.data.table(fit_obj$metadata))
  data_cols <- names(fit_obj$data)
  raw_dt <- as_hier_mmm_data_table(raw_data)
  raw_cols <- if (is.null(raw_dt)) character() else names(raw_dt)

  media_roles <- c("media", "reach_frequency")
  candidate_vars <- vl[role %in% media_roles, variable]
  if (!length(candidate_vars)) candidate_vars <- vl$variable
  if (!is.null(variables)) candidate_vars <- intersect(candidate_vars, variables)

  if (!is.null(spend_map)) {
    if (is.character(spend_map) && !is.null(names(spend_map))) {
      sm <- data.table(variable = names(spend_map), spend_col = as.character(spend_map))
    } else {
      sm <- as.data.table(copy(spend_map))
      if (!("variable" %in% names(sm))) stop("spend_map must include a variable column.")
      if (!("spend_col" %in% names(sm))) {
        alt <- intersect(c("cost_col", "spend", "spend_column", "cost_column"), names(sm))
        if (!length(alt)) stop("spend_map must include spend_col or cost_col.")
        setnames(sm, alt[1], "spend_col")
      }
      sm <- sm[, .(variable = as.character(variable), spend_col = as.character(spend_col))]
    }
  } else if ("cost_col" %in% names(md)) {
    sm <- md[variable %in% candidate_vars & !is.na(cost_col) & nzchar(trimws(as.character(cost_col))),
             .(variable, spend_col = as.character(cost_col))]
  } else if ("spend_col" %in% names(md)) {
    sm <- md[variable %in% candidate_vars & !is.na(spend_col) & nzchar(trimws(as.character(spend_col))),
             .(variable, spend_col = as.character(spend_col))]
  } else {
    inferred <- paste0(candidate_vars, spend_suffix)
    exists <- inferred %in% c(data_cols, raw_cols)
    sm <- data.table(variable = candidate_vars[exists], spend_col = inferred[exists])
  }

  if (!nrow(sm)) return(data.table(variable = character(), spend_col = character()))
  sm <- unique(sm[variable %in% candidate_vars], by = "variable")
  missing_cols <- sm[!(spend_col %in% c(data_cols, raw_cols)), spend_col]
  if (length(missing_cols)) {
    stop("Spend columns not found in fit_obj$data or raw_data: ", paste(unique(missing_cols), collapse = ", "))
  }
  sm[]
}
attach_spend_to_hier_mmm_outputs <- function(fit_obj,
                                             spend_map = NULL,
                                             raw_data = NULL,
                                             spend_suffix = "_spend") {
  sm <- normalize_spend_map_hier_mmm(fit_obj, spend_map = spend_map, raw_data = raw_data, spend_suffix = spend_suffix)
  diag <- data.table(
    variable = sm$variable %||% character(),
    spend_col = sm$spend_col %||% character(),
    matched_long_rows = integer(),
    matched_wide_rows = integer()
  )
  fit_obj$spend_attachment_diagnostics <- diag
  if (!nrow(sm)) return(fit_obj)

  raw_dt <- as_hier_mmm_data_table(raw_data)
  if (is.null(raw_dt)) raw_dt <- copy(as.data.table(fit_obj$data))
  long <- copy(as.data.table(fit_obj$long_decomp))
  wide <- copy(as.data.table(fit_obj$wide_decomp))

  key_candidates <- unique(c(fit_obj$time_col, fit_obj$group_col, fit_obj$entity_col))
  join_keys <- key_candidates[key_candidates %in% names(raw_dt) & key_candidates %in% names(long)]
  if (!length(join_keys)) {
    warning("Could not attach spend to Stan outputs: no shared time/group/entity keys between raw_data and long_decomp.")
    fit_obj$spend_attachment_diagnostics[, `:=`(matched_long_rows = 0L, matched_wide_rows = 0L)]
    return(fit_obj)
  }

  support_map <- unique(as.data.table(fit_obj$variable_lookup)[variable %in% sm$variable, .(variable, support_col = variable)], by = "variable")
  support_map <- support_map[support_col %in% names(raw_dt)]

  spend_long <- rbindlist(lapply(seq_len(nrow(sm)), function(i) {
    v <- sm$variable[i]
    sc <- sm$spend_col[i]
    out <- raw_dt[, c(join_keys, sc), with = FALSE]
    setnames(out, sc, "spend")
    out[, variable := v]
    out[, spend := suppressWarnings(as.numeric(spend))]
    out[]
  }), use.names = TRUE, fill = TRUE)
  spend_long <- spend_long[, .(spend = sum(spend, na.rm = TRUE)), by = c(join_keys, "variable")]

  support_long <- data.table()
  if (nrow(support_map)) {
    support_long <- rbindlist(lapply(seq_len(nrow(support_map)), function(i) {
      v <- support_map$variable[i]
      sc <- support_map$support_col[i]
      out <- raw_dt[, c(join_keys, sc), with = FALSE]
      setnames(out, sc, "support")
      out[, variable := v]
      out[, support := suppressWarnings(as.numeric(support))]
      out[]
    }), use.names = TRUE, fill = TRUE)
    support_long <- support_long[, .(support = sum(support, na.rm = TRUE)), by = c(join_keys, "variable")]
  }

  long[spend_long, spend := i.spend, on = c(setNames(join_keys, join_keys), "variable")]
  if (nrow(support_long)) long[support_long, support := i.support, on = c(setNames(join_keys, join_keys), "variable")]
  long[variable %in% sm$variable & !is.finite(spend), spend := NA_real_]
  if ("support" %in% names(long)) long[variable %in% support_map$variable & !is.finite(support), support := NA_real_]

  wide_spend <- dcast(spend_long, paste(paste(join_keys, collapse = " + "), "~ variable"), value.var = "spend", fill = 0)
  spend_vars <- setdiff(names(wide_spend), join_keys)
  if (length(spend_vars)) {
    setnames(wide_spend, spend_vars, paste0("spend_", spend_vars))
    wide_spend[, total_spend := rowSums(.SD, na.rm = TRUE), .SDcols = paste0("spend_", spend_vars)]
  } else {
    wide_spend[, total_spend := 0]
  }
  wide[wide_spend, on = join_keys, `:=`(
    total_spend = i.total_spend
  )]
  for (cc in setdiff(names(wide_spend), c(join_keys, "total_spend"))) {
    wide[wide_spend, on = join_keys, (cc) := get(paste0("i.", cc))]
  }
  if (nrow(support_long)) {
    wide_support <- dcast(support_long, paste(paste(join_keys, collapse = " + "), "~ variable"), value.var = "support", fill = 0)
    support_vars <- setdiff(names(wide_support), join_keys)
    if (length(support_vars)) {
      setnames(wide_support, support_vars, paste0("support_", support_vars))
      wide_support[, total_support := rowSums(.SD, na.rm = TRUE), .SDcols = paste0("support_", support_vars)]
      wide[wide_support, on = join_keys, total_support := i.total_support]
      for (cc in setdiff(names(wide_support), c(join_keys, "total_support"))) {
        wide[wide_support, on = join_keys, (cc) := get(paste0("i.", cc))]
      }
    }
  }

  diag <- sm[, .(
    spend_col,
    support_col = support_map[variable == .BY$variable, support_col][1] %||% NA_character_,
    matched_long_rows = long[variable == .BY$variable & is.finite(spend), .N],
    matched_support_rows = if ("support" %in% names(long)) long[variable == .BY$variable & is.finite(support), .N] else 0L,
    matched_wide_rows = wide[is.finite(total_spend) & total_spend > 0, .N]
  ), by = variable]
  fit_obj$long_decomp <- long[]
  fit_obj$wide_decomp <- wide[]
  fit_obj$spend_attachment_diagnostics <- diag[]
  fit_obj
}

get_aligned_raw_data_hier_mmm <- function(fit_obj, raw_data = NULL) {
  if (is.null(raw_data)) return(copy(as.data.table(fit_obj$data)))
  raw_dt <- as_hier_mmm_data_table(raw_data)
  group_col <- fit_obj$group_col %||% stop("fit_obj is missing group_col.")
  time_col <- fit_obj$time_col %||% stop("fit_obj is missing time_col.")
  if (!all(c(group_col, time_col) %in% names(raw_dt))) {
    stop("raw_data must contain group_col and time_col: ", group_col, ", ", time_col)
  }
  key_dt <- copy(as.data.table(fit_obj$data))[, .(row_id__ = .I, group__ = get(group_col), time__ = get(time_col))]
  raw_key <- copy(raw_dt)
  raw_key[, group__ := get(group_col)]
  raw_key[, time__ := get(time_col)]
  out <- raw_key[key_dt, on = .(group__, time__)]
  setorder(out, row_id__)
  out[]
}

extract_pm_from_fit_obj_hier_mmm <- function(fit_obj) {
  if (!is.null(fit_obj$posterior_means)) return(fit_obj$posterior_means)
  extract_posterior_means_hier_mmm(fit_obj$fit, list(stan_data = fit_obj$stan_data))
}

media_transform_hier_mmm <- function(x,
                                     rrate,
                                     cvalue,
                                     dvalue = 1,
                                     curve_type = "weibull",
                                     train_mask = NULL,
                                     normalize_curve_x = TRUE,
                                     curve_normalization_scope = "active_train",
                                     multiplier = 1) {
  x_ref <- pmax(suppressWarnings(as.numeric(x)), 0)
  x_ref[!is.finite(x_ref)] <- 0
  x_eval <- pmax(x_ref * as.numeric(multiplier)[1], 0)
  n <- length(x_ref)
  if (is.null(train_mask)) train_mask <- rep(TRUE, n)
  train_mask <- rep(as.logical(train_mask), length.out = n)
  train_mask[is.na(train_mask)] <- FALSE
  if (!any(train_mask)) train_mask <- rep(TRUE, n)
  rrate <- min(max(suppressWarnings(as.numeric(rrate)[1]), 0), 0.999)
  cvalue <- suppressWarnings(as.numeric(cvalue)[1])
  dvalue <- suppressWarnings(as.numeric(dvalue)[1])
  if (!is.finite(cvalue)) cvalue <- 0
  if (!is.finite(dvalue) || dvalue <= 0) dvalue <- 1

  adstock_one <- function(z) {
    carry <- 0
    out <- numeric(length(z))
    for (ii in seq_along(z)) {
      carry <- z[ii] + rrate * carry
      out[ii] <- carry
    }
    out
  }

  carry_ref <- adstock_one(x_ref)
  carry_eval <- adstock_one(x_eval)
  carry_scale <- 1
  if (isTRUE(normalize_curve_x)) {
    norm_mask <- curve_normalization_mask_hier_mmm(x_ref, train_mask, curve_normalization_scope)
    carry_scale <- mean(carry_ref[norm_mask], na.rm = TRUE)
    if (!is.finite(carry_scale) || is.na(carry_scale) || abs(carry_scale) <= 1e-8) carry_scale <- 1
  }
  sat_ref <- saturate_media_hier_mmm(carry_ref / carry_scale, cvalue = cvalue, dvalue = dvalue, curve_type = curve_type)
  sat_eval <- saturate_media_hier_mmm(carry_eval / carry_scale, cvalue = cvalue, dvalue = dvalue, curve_type = curve_type)
  norm_mask <- if (isTRUE(normalize_curve_x)) {
    curve_normalization_mask_hier_mmm(x_ref, train_mask, curve_normalization_scope)
  } else {
    train_mask
  }
  trans_mean <- mean(sat_ref[norm_mask], na.rm = TRUE)
  if (!is.finite(trans_mean) || is.na(trans_mean) || abs(trans_mean) <= 1e-8) trans_mean <- if (isTRUE(normalize_curve_x)) 1 else 1e-8
  transformed <- if (isTRUE(normalize_curve_x)) sat_eval / trans_mean else sat_eval
  list(
    transformed = transformed,
    carry_scale = carry_scale,
    transformed_mean = trans_mean,
    center_value = if (isTRUE(normalize_curve_x)) 1 else trans_mean,
    adstock = carry_eval,
    saturation = sat_eval,
    curve_normalization_scope = normalize_curve_normalization_scope_hier_mmm(curve_normalization_scope)
  )
}

variable_contribution_rows_hier_mmm <- function(fit_obj, variable, multiplier = 1, posterior_params = NULL) {
  var_name <- as.character(variable)[1]
  dt <- copy(as.data.table(fit_obj$data))
  vl <- copy(as.data.table(fit_obj$variable_lookup))[order(variable_idx)]
  if (!"curve_type" %in% names(vl)) vl[, curve_type := "weibull"]
  if (!(var_name %in% vl$variable)) stop("Unknown modeled variable: ", var_name)
  pm <- posterior_params %||% extract_pm_from_fit_obj_hier_mmm(fit_obj)
  j <- vl$variable_idx[match(var_name, vl$variable)]
  has_curve <- vl[variable_idx == j, has_curve][1] == 1L
  out <- numeric(nrow(dt))
  scale <- dt$rescale_factor__
  if (is.null(scale)) scale <- rep(1, nrow(dt))

  if (!has_curve) {
    beta_vec <- pm$beta[dt$group_idx, j]
    context_mult <- context_effect_multiplier_hier_mmm(
      fit_obj$stan_data,
      variable_idx = j,
      row_idx = seq_len(nrow(dt)),
      context_coef = pm$context_coef
    )
    out <- beta_vec * context_mult * (dt[[var_name]] * multiplier) * scale
    return(out)
  }

  curve_pos <- match(j, fit_obj$stan_data$curve_idx)
  if (is.na(curve_pos)) stop("Internal error: curve variable not found in curve_idx: ", var_name)
  rr <- pm$rrate[j]
  cv <- pm$cvalue[j]
  dv <- pm$dvalue[j]
  curve_type <- vl[variable_idx == j, curve_type][1] %||% "weibull"

  for (g in sort(unique(dt$group_idx))) {
    idx <- which(dt$group_idx == g)
    tr <- media_transform_hier_mmm(
      x = dt[[var_name]][idx],
      rrate = rr,
      cvalue = cv,
      dvalue = dv,
      curve_type = curve_type,
      train_mask = !dt$is_holdout__[idx],
      normalize_curve_x = fit_obj$normalize_curve_x,
      curve_normalization_scope = fit_obj$curve_normalization_scope %||% "active_train",
      multiplier = multiplier
    )
    trans <- tr$transformed
    context_mult <- context_effect_multiplier_hier_mmm(
      fit_obj$stan_data,
      variable_idx = j,
      row_idx = idx,
      context_coef = pm$context_coef
    )
    out[idx] <- pm$beta[g, j] * context_mult * trans * scale[idx]
  }
  out
}

variable_contribution_sum_hier_mmm <- function(fit_obj, variable, multiplier = 1, posterior_params = NULL) {
  out <- variable_contribution_rows_hier_mmm(fit_obj, variable, multiplier = multiplier, posterior_params = posterior_params)
  sum(out, na.rm = TRUE)
}

build_response_curves_hier_mmm <- function(fit_obj,
                                           spend_map = NULL,
                                           raw_data = NULL,
                                           variables = NULL,
                                           multiplier_grid = seq(0, 3, by = 0.05),
                                           step_pct = 0.01,
                                           response_curve_scope = c("auto", "total", "group", "both"),
                                           spend_suffix = "_spend",
                                           value_per_kpi = NA_real_) {
  response_curve_scope <- match.arg(response_curve_scope)
  dt <- copy(as.data.table(fit_obj$data))
  group_col <- fit_obj$group_col %||% "group"
  if (!(group_col %in% names(dt))) dt[, (group_col) := "ALL"]
  vars <- if (!is.null(variables)) {
    unique(as.character(variables))
  } else if (!is.null(fit_obj$variable_lookup) && "variable" %in% names(as.data.table(fit_obj$variable_lookup))) {
    unique(as.character(as.data.table(fit_obj$variable_lookup)$variable))
  } else {
    character()
  }

  sm <- normalize_spend_map_hier_mmm(
    fit_obj,
    spend_map = spend_map,
    raw_data = raw_data,
    spend_suffix = spend_suffix,
    variables = vars
  )
  if (nrow(sm)) vars <- intersect(vars, sm$variable)
  vars <- vars[vars %in% names(dt)]
  if (!length(vars)) return(data.table())

  multiplier_grid <- sort(unique(pmax(suppressWarnings(as.numeric(multiplier_grid)), 0)))
  multiplier_grid <- multiplier_grid[is.finite(multiplier_grid)]
  if (!length(multiplier_grid)) stop("multiplier_grid must contain finite non-negative values.")
  step_pct <- suppressWarnings(as.numeric(step_pct)[1])
  if (!is.finite(step_pct) || step_pct <= 0) step_pct <- 0.01
  value_per_kpi <- suppressWarnings(as.numeric(value_per_kpi)[1])

  raw_aligned <- get_aligned_raw_data_hier_mmm(fit_obj, raw_data = raw_data)
  if (!(group_col %in% names(raw_aligned))) raw_aligned[, (group_col) := dt[[group_col]]]
  group_values <- sort(unique(as.character(dt[[group_col]])))
  has_meaningful_groups <- length(group_values) > 1L
  include_group <- response_curve_scope %in% c("group", "both") ||
    (identical(response_curve_scope, "auto") && has_meaningful_groups)
  include_total <- response_curve_scope %in% c("total", "both", "auto")

  spend_by_group <- data.table(variable = character(), group = character(), current_spend = numeric())
  if (nrow(sm)) {
    spend_by_group <- rbindlist(lapply(seq_len(nrow(sm)), function(i) {
      v <- sm$variable[i]
      sc <- sm$spend_col[i]
      if (!(sc %in% names(raw_aligned))) {
        return(data.table(variable = v, group = group_values, current_spend = NA_real_))
      }
      tmp <- copy(raw_aligned[, c(group_col, sc), with = FALSE])
      setnames(tmp, c(group_col, sc), c("group", "spend"))
      tmp[, `:=`(group = as.character(group), spend = suppressWarnings(as.numeric(spend)))]
      tmp[, .(current_spend = sum(spend, na.rm = TRUE)), by = group][, variable := v]
    }), fill = TRUE)
  }

  support_by_group <- rbindlist(lapply(vars, function(v) {
    tmp <- dt[, .(current_support = sum(pmax(suppressWarnings(as.numeric(get(v))), 0), na.rm = TRUE)), by = group_col]
    setnames(tmp, group_col, "group")
    tmp[, `:=`(group = as.character(group), variable = v)]
    tmp
  }), fill = TRUE)

  make_rows_one <- function(v, m) {
    contrib <- variable_contribution_rows_hier_mmm(fit_obj, v, multiplier = m)
    base <- variable_contribution_rows_hier_mmm(fit_obj, v, multiplier = 1)
    up <- variable_contribution_rows_hier_mmm(fit_obj, v, multiplier = m + step_pct)
    row_dt <- data.table(
      group = as.character(dt[[group_col]]),
      contribution = contrib,
      current_contribution_row = base,
      up_contribution = up
    )
    by_group <- row_dt[, .(
      contribution = sum(contribution, na.rm = TRUE),
      current_contribution = sum(current_contribution_row, na.rm = TRUE),
      up_contribution = sum(up_contribution, na.rm = TRUE)
    ), by = group]
    by_group[, `:=`(
      scope = "group",
      variable = v,
      spend_multiplier = m
    )]
    by_group_all <- copy(by_group)
    if (!isTRUE(include_group)) by_group <- by_group[0]
    if (isTRUE(include_total)) {
      total <- by_group_all[, .(
        group = "ALL",
        contribution = sum(contribution, na.rm = TRUE),
        current_contribution = sum(current_contribution, na.rm = TRUE),
        up_contribution = sum(up_contribution, na.rm = TRUE),
        scope = "total",
        variable = v,
        spend_multiplier = m
      )]
      by_group <- rbindlist(list(by_group, total), fill = TRUE)
    }
    by_group
  }

  out <- rbindlist(lapply(vars, function(v) {
    rbindlist(lapply(multiplier_grid, function(m) make_rows_one(v, m)), fill = TRUE)
  }), fill = TRUE)

  if (nrow(spend_by_group)) {
    out[spend_by_group, current_spend := i.current_spend, on = .(variable, group)]
    total_spend <- spend_by_group[, .(current_spend = sum(current_spend, na.rm = TRUE)), by = variable][, group := "ALL"]
    out[is.na(current_spend) | !is.finite(current_spend), current_spend := NA_real_]
    out[total_spend, current_spend := i.current_spend, on = .(variable, group)]
  } else {
    out[, current_spend := NA_real_]
  }
  out[support_by_group, current_support := i.current_support, on = .(variable, group)]
  total_support <- support_by_group[, .(current_support = sum(current_support, na.rm = TRUE)), by = variable][, group := "ALL"]
  out[total_support, current_support := i.current_support, on = .(variable, group)]
  out[!is.finite(current_support), current_support := NA_real_]

  out[, `:=`(
    spend = current_spend * spend_multiplier,
    support = current_support * spend_multiplier,
    contribution_vs_current = contribution - current_contribution,
    incremental_contribution_for_mroi = up_contribution - contribution,
    incremental_spend_for_mroi = current_spend * step_pct
  )]
  out[, `:=`(
    roi = fifelse(is.finite(spend) & abs(spend) > 1e-8, contribution / spend, NA_real_),
    mroi = fifelse(is.finite(incremental_spend_for_mroi) & abs(incremental_spend_for_mroi) > 1e-8,
                   incremental_contribution_for_mroi / incremental_spend_for_mroi, NA_real_),
    cost_per_kpi = fifelse(is.finite(contribution) & contribution > 1e-8, spend / contribution, NA_real_),
    value_per_cost = fifelse(is.finite(value_per_kpi) & is.finite(spend) & abs(spend) > 1e-8,
                             contribution * value_per_kpi / spend, NA_real_)
  )]
  out[, `:=`(
    response_curve_basis = "stan_posterior_mean_point_estimate",
    uncertainty_note = "Response curves are generated from posterior means. Posterior draw intervals are not included in this table.",
    flighting_assumption = "Each channel curve scales the historical support path within the selected model data.",
    cost_assumption = "Spend scales with support using the historical spend/support relationship implied by spend_map."
  )]
  setcolorder(out, intersect(c(
    "scope", "group", "variable", "spend_multiplier", "spend", "current_spend",
    "support", "current_support", "contribution", "current_contribution",
    "contribution_vs_current", "roi", "mroi", "cost_per_kpi", "value_per_cost",
    "incremental_spend_for_mroi", "incremental_contribution_for_mroi",
    "response_curve_basis", "uncertainty_note", "flighting_assumption", "cost_assumption"
  ), names(out)))
  out[order(variable, scope, group, spend_multiplier)]
}

extract_posterior_draw_params_hier_mmm <- function(fit_obj,
                                                   max_draws = 200L,
                                                   seed = 123L) {
  if (!is.null(fit_obj$posterior_draw_params)) return(fit_obj$posterior_draw_params)
  if (is.null(fit_obj$fit) || !is.function(fit_obj$fit$draws)) {
    stop("fit_obj does not contain a CmdStan fit with posterior draws.", call. = FALSE)
  }
  require_hier_mmm_pkg("posterior", "extracting posterior draws for response-curve uncertainty")
  pm_mean <- extract_pm_from_fit_obj_hier_mmm(fit_obj)
  draw_vars <- c("beta", "rrate", "cvalue", "dvalue")
  if (as.integer(fit_obj$stan_data$K_context %||% 0L) > 0L) draw_vars <- c(draw_vars, "context_coef")
  draw_mat <- as.matrix(fit_obj$fit$draws(variables = draw_vars, format = "matrix"))
  if (!nrow(draw_mat)) stop("No posterior draws were available for beta/curve parameters.", call. = FALSE)
  max_draws <- suppressWarnings(as.integer(max_draws)[1])
  if (!is.finite(max_draws) || max_draws <= 0L) max_draws <- nrow(draw_mat)
  if (nrow(draw_mat) > max_draws) {
    set.seed(as.integer(seed)[1] %||% 123L)
    keep <- sort(sample(seq_len(nrow(draw_mat)), max_draws))
    draw_mat <- draw_mat[keep, , drop = FALSE]
  }
  cn <- colnames(draw_mat)
  get_draw_value <- function(row_i, nm, default) {
    pos <- match(nm, cn)
    if (is.na(pos)) return(default)
    val <- suppressWarnings(as.numeric(draw_mat[row_i, pos]))
    if (is.finite(val)) val else default
  }
  G <- fit_obj$stan_data$G %||% nrow(pm_mean$beta)
  J <- fit_obj$stan_data$J %||% ncol(pm_mean$beta)
  curve_idx <- fit_obj$stan_data$curve_idx %||% integer()
  params <- vector("list", nrow(draw_mat))
  draw_ids <- rownames(draw_mat)
  if (is.null(draw_ids) || any(!nzchar(draw_ids))) draw_ids <- as.character(seq_len(nrow(draw_mat)))
  for (row_i in seq_len(nrow(draw_mat))) {
    beta <- pm_mean$beta
    for (g in seq_len(G)) {
      for (j in seq_len(J)) {
        beta[g, j] <- get_draw_value(row_i, sprintf("beta[%d,%d]", g, j), beta[g, j])
      }
    }
    rrate <- pm_mean$rrate
    cvalue <- pm_mean$cvalue
    dvalue <- pm_mean$dvalue
    context_coef <- pm_mean$context_coef
    if (length(curve_idx)) {
      for (k in seq_along(curve_idx)) {
        j <- curve_idx[k]
        rrate[j] <- get_draw_value(row_i, sprintf("rrate[%d]", k), rrate[j])
        cvalue[j] <- get_draw_value(row_i, sprintf("cvalue[%d]", k), cvalue[j])
        dvalue[j] <- get_draw_value(row_i, sprintf("dvalue[%d]", k), dvalue[j])
      }
    }
    if (length(context_coef)) {
      for (k in seq_along(context_coef)) {
        context_coef[k] <- get_draw_value(row_i, sprintf("context_coef[%d]", k), context_coef[k])
      }
    }
    params[[row_i]] <- list(
      draw_id = as.character(draw_ids[row_i]),
      beta = beta,
      rrate = rrate,
      cvalue = cvalue,
      dvalue = dvalue,
      context_coef = context_coef,
      alpha_flat = pm_mean$alpha_flat,
      gamma = pm_mean$gamma,
      level_component = pm_mean$level_component,
      cycle_component = pm_mean$cycle_component,
      season_component = pm_mean$season_component,
      level_state = pm_mean$level_state,
      sigma_y = pm_mean$sigma_y
    )
  }
  list(draw_ids = as.character(draw_ids), params = params)
}

build_response_curves_draws_hier_mmm <- function(fit_obj,
                                                 spend_map = NULL,
                                                 raw_data = NULL,
                                                 variables = NULL,
                                                 multiplier_grid = seq(0, 3, by = 0.05),
                                                 step_pct = 0.01,
                                                 response_curve_scope = c("auto", "total", "group", "both"),
                                                 spend_suffix = "_spend",
                                                 value_per_kpi = NA_real_,
                                                 max_draws = 200L,
                                                 seed = 123L) {
  response_curve_scope <- match.arg(response_curve_scope)
  draw_params <- extract_posterior_draw_params_hier_mmm(fit_obj, max_draws = max_draws, seed = seed)
  if (is.null(draw_params$params) || !length(draw_params$params)) return(data.table())
  out <- rbindlist(lapply(draw_params$params, function(pm_draw) {
    draw_id <- as.character(pm_draw$draw_id %||% "")
    pm_draw$draw_id <- NULL
    tmp_fit <- fit_obj
    tmp_fit$posterior_means <- pm_draw
    rc <- build_response_curves_hier_mmm(
      fit_obj = tmp_fit,
      spend_map = spend_map,
      raw_data = raw_data,
      variables = variables,
      multiplier_grid = multiplier_grid,
      step_pct = step_pct,
      response_curve_scope = response_curve_scope,
      spend_suffix = spend_suffix,
      value_per_kpi = value_per_kpi
    )
    if (nrow(rc)) {
      rc[, `:=`(
        .draw = draw_id,
        response_curve_basis = "stan_posterior_draw",
        uncertainty_note = "Response curve generated from one posterior draw of beta and curve parameters."
      )]
      setcolorder(rc, c(".draw", setdiff(names(rc), ".draw")))
    }
    rc
  }), fill = TRUE)
  out[order(variable, .draw, scope, group, spend_multiplier)]
}

make_hier_mmm_business_prior_template <- function(variables) {
  data.table(
    variable = as.character(variables),
    prior_metric = NA_character_,       # coef, ikpc, cpkpi, mcpkpi, roi, mroi
    prior_mean = NA_real_,
    prior_sd = NA_real_,
    prior_precision = NA_real_,
    prior_uncertainty_basis = "sd",      # sd by default; precision is accepted and converted
    prior_distribution = "normal",
    kpi_value_per_outcome = NA_real_,
    evidence_source = NA_character_,
    evidence_notes = NA_character_
  )
}

business_prior_metric_alias_hier_mmm <- function(x) {
  x <- tolower(trimws(as.character(x %||% "")))
  x <- gsub("[^a-z0-9]+", "_", x)
  x <- gsub("^_|_$", "", x)
  out <- x
  out[x %in% c("coefficient", "beta", "model_coef", "coef_prior")] <- "coef"
  out[x %in% c("incremental_kpi_per_cost", "incremental_outcome_per_cost", "incremental_kpi_per_dollar", "ikpc", "kpi_per_cost", "kpi_per_dollar", "outcome_per_cost", "outcome_per_dollar")] <- "ikpc"
  out[x %in% c("cost_per_kpi", "cost_per_outcome", "cost_per_conversion", "cost_per_subscriber", "cost_per_lead", "cpa", "cpkpi")] <- "cpkpi"
  out[x %in% c("mcpkpi", "marginal_cpkpi", "marginal_cost_per_kpi", "marginal_cost_per_outcome", "marginal_cost_per_subscriber", "marginal_cpa")] <- "mcpkpi"
  out[x %in% c("roi", "return_on_investment")] <- "roi"
  out[x %in% c("mroi", "marginal_roi", "marginal_return_on_investment")] <- "mroi"
  out
}

business_prior_metric_candidates_hier_mmm <- function(metric) {
  switch(
    metric,
    coef = c("prior_mean", "coef", "coefficient", "beta", "model_coef", "coef_prior"),
    ikpc = c("prior_mean", "ikpc", "incremental_kpi_per_cost", "incremental_outcome_per_cost", "kpi_per_cost", "kpi_per_dollar", "outcome_per_cost"),
    cpkpi = c("prior_mean", "cpkpi", "cost_per_kpi", "cost_per_outcome", "cost_per_subscriber", "cost_per_lead", "cpa"),
    mcpkpi = c("prior_mean", "mcpkpi", "marginal_cpkpi", "marginal_cost_per_kpi", "marginal_cost_per_outcome", "marginal_cost_per_subscriber", "marginal_cpa"),
    roi = c("prior_mean", "roi"),
    mroi = c("prior_mean", "mroi", "marginal_roi"),
    c("prior_mean", metric)
  )
}

business_prior_row_num_hier_mmm <- function(bp, i, candidates) {
  candidates <- candidates[candidates %in% names(bp)]
  for (cc in candidates) {
    val <- suppressWarnings(as.numeric(bp[[cc]][i]))
    if (is.finite(val)) return(val)
  }
  NA_real_
}

business_prior_detect_metric_hier_mmm <- function(bp, i) {
  if ("prior_metric" %in% names(bp)) {
    pm <- business_prior_metric_alias_hier_mmm(bp$prior_metric[i])
    if (nzchar(pm) && !is.na(pm)) return(pm)
  }
  if ("metric" %in% names(bp)) {
    pm <- business_prior_metric_alias_hier_mmm(bp$metric[i])
    if (nzchar(pm) && !is.na(pm)) return(pm)
  }
  for (metric in c("coef", "ikpc", "cpkpi", "mcpkpi", "roi", "mroi")) {
    if (is.finite(business_prior_row_num_hier_mmm(bp, i, business_prior_metric_candidates_hier_mmm(metric)))) {
      return(metric)
    }
  }
  NA_character_
}

business_prior_uncertainty_basis_alias_hier_mmm <- function(x, default = "sd") {
  x <- tolower(trimws(as.character(x %||% default)))
  x <- gsub("[^a-z0-9]+", "_", x)
  x <- gsub("^_|_$", "", x)
  out <- rep(default, length(x))
  out[x %in% c("sd", "stddev", "std_dev", "standard_deviation", "se", "standard_error")] <- "sd"
  out[x %in% c("precision", "inverse_variance", "inv_variance", "inv_var", "tau")] <- "precision"
  out[x %in% c("auto", "either")] <- "auto"
  out
}

business_prior_row_chr_hier_mmm <- function(bp, i, candidates) {
  candidates <- candidates[candidates %in% names(bp)]
  for (cc in candidates) {
    val <- trimws(as.character(bp[[cc]][i]))
    if (nzchar(val) && !is.na(val)) return(val)
  }
  NA_character_
}

business_prior_sd_precision_hier_mmm <- function(bp,
                                                 i,
                                                 metric,
                                                 default_uncertainty_basis = "sd") {
  base <- business_prior_metric_candidates_hier_mmm(metric)
  sd_cols <- unique(c("prior_sd", paste0(base, "_sd"), paste0(base, "_se")))
  precision_cols <- unique(c("prior_precision", paste0(base, "_precision")))
  sd <- business_prior_row_num_hier_mmm(bp, i, sd_cols)
  precision <- business_prior_row_num_hier_mmm(bp, i, precision_cols)
  row_basis <- business_prior_row_chr_hier_mmm(
    bp,
    i,
    c("prior_uncertainty_basis", "prior_uncertainty_type", "uncertainty_basis", "uncertainty_type", "variance_type", "prior_scale")
  )
  basis <- business_prior_uncertainty_basis_alias_hier_mmm(
    if (is.na(row_basis)) default_uncertainty_basis else row_basis,
    default = default_uncertainty_basis
  )[1]
  sd_valid <- is.finite(sd) && sd > 0
  precision_valid <- is.finite(precision) && precision > 0
  source <- NA_character_
  if (identical(basis, "precision") && precision_valid) {
    sd <- 1 / sqrt(precision)
    source <- "precision"
  } else if (sd_valid) {
    source <- "sd"
  } else if (precision_valid) {
    sd <- 1 / sqrt(precision)
    source <- "precision"
  } else {
    source <- "default_relative_sd"
  }
  list(
    sd = sd,
    precision = precision,
    basis = if (identical(source, "precision")) "precision" else "sd",
    source = source,
    requested_basis = basis
  )
}

kpi_value_for_business_prior_hier_mmm <- function(kpi_value_per_outcome, bp, i, variable) {
  if ("kpi_value_per_outcome" %in% names(bp)) {
    val <- suppressWarnings(as.numeric(bp$kpi_value_per_outcome[i]))
    if (is.finite(val) && val > 0) return(val)
  }
  if (length(kpi_value_per_outcome) > 1L && !is.null(names(kpi_value_per_outcome))) {
    val <- suppressWarnings(as.numeric(kpi_value_per_outcome[[as.character(variable)]]))
    if (is.finite(val) && val > 0) return(val)
  }
  val <- suppressWarnings(as.numeric(kpi_value_per_outcome)[1])
  if (!is.finite(val) || val <= 0) val <- 1
  val
}

normalize_business_spend_map_hier_mmm <- function(metadata_input, spend_map = NULL) {
  if (!is.null(spend_map)) {
    sm <- as.data.table(copy(spend_map))
    if (!"variable" %in% names(sm)) stop("spend_map must include variable.", call. = FALSE)
    if (!"spend_col" %in% names(sm)) {
      alt <- intersect(c("cost_col", "spend", "cost"), names(sm))
      if (!length(alt)) stop("spend_map must include spend_col or cost_col.", call. = FALSE)
      sm[, spend_col := as.character(get(alt[1]))]
    }
    return(sm[, .(variable = as.character(variable), spend_col = as.character(spend_col))])
  }
  md <- read_input_table(metadata_input)
  if (!"variable" %in% names(md)) return(data.table(variable = character(), spend_col = character()))
  scol <- pick_first_existing_col(md, c("spend_col", "cost_col"))
  if (is.na(scol)) return(data.table(variable = character(), spend_col = character()))
  md[, .(variable = as.character(variable), spend_col = as.character(get(scol)))]
}

business_design_sum_hier_mmm <- function(prep, variable) {
  sd <- prep$stan_data
  vl <- prep$variable_lookup
  vv <- as.character(variable)[1]
  row <- vl[variable == vv][1]
  if (!nrow(row)) return(NA_real_)
  j <- row$variable_idx[1]
  if (row$has_curve[1] == 1L) {
    k <- match(j, sd$curve_idx)
    if (is.na(k)) return(NA_real_)
    x <- sd$X_curve_fixed[, k]
  } else {
    x <- sd$X[, j]
  }
  train <- sd$is_train == 1L
  sum(as.numeric(x)[train], na.rm = TRUE)
}

business_marginal_design_sum_hier_mmm <- function(prep, variable, step_pct = 0.01) {
  sd <- prep$stan_data
  vl <- prep$variable_lookup
  vv <- as.character(variable)[1]
  row <- vl[variable == vv][1]
  if (!nrow(row)) return(NA_real_)
  j <- row$variable_idx[1]
  step_pct <- suppressWarnings(as.numeric(step_pct)[1])
  if (!is.finite(step_pct) || step_pct <= 0) step_pct <- 0.01
  train <- sd$is_train == 1L
  if (row$has_curve[1] == 1L) {
    k <- match(j, sd$curve_idx)
    if (is.na(k)) return(NA_real_)
    raw_to_value <- function(raw, lower, upper) {
      lower + (upper - lower) * stats::plogis(raw)
    }
    rr <- raw_to_value(row$rrate_raw_mu[1], row$rrate_lower[1], row$rrate_upper[1])
    cv <- raw_to_value(row$cvalue_raw_mu[1], row$cvalue_lower[1], row$cvalue_upper[1])
    dv <- raw_to_value(row$dvalue_raw_mu[1], row$dvalue_lower[1], row$dvalue_upper[1])
    curve_type <- row$curve_type[1] %||% "weibull"
    up <- numeric(nrow(prep$data))
    for (g in seq_len(nrow(prep$group_lookup))) {
      idx <- which(prep$data$group_idx == g)
      if (!length(idx)) next
      tr <- media_transform_hier_mmm(
        x = sd$X[idx, j],
        rrate = rr,
        cvalue = cv,
        dvalue = dv,
        curve_type = curve_type,
        train_mask = !prep$data$is_holdout__[idx],
        normalize_curve_x = isTRUE(prep$normalize_curve_x),
        curve_normalization_scope = prep$curve_normalization_scope,
        multiplier = 1 + step_pct
      )
      up[idx] <- tr$transformed
    }
    base <- sd$X_curve_fixed[, k]
    return(sum(as.numeric(up[train] - base[train]), na.rm = TRUE))
  }
  x <- sd$X[, j]
  sum(as.numeric(x)[train], na.rm = TRUE) * step_pct
}

apply_business_priors_to_metadata_hier_mmm <- function(data,
                                                       metadata_input,
                                                       business_priors,
                                                       dep_var_col,
                                                       group_col,
                                                       time_col,
                                                       entity_col,
                                                       spend_map = NULL,
                                                       kpi_value_per_outcome = 1,
                                                       default_relative_sd = 0.50,
                                                       min_coef_sd = 1e-6,
                                                       max_precision = Inf,
                                                       uncertainty_basis = "sd",
                                                       marginal_step_pct = 0.01,
                                                       prep_args = list(),
                                                       ...) {
  bp <- as.data.table(copy(business_priors))
  if (!nrow(bp)) return(list(metadata = read_input_table(metadata_input), business_prior_audit = data.table()))
  if (!"variable" %in% names(bp)) stop("business_priors must include variable.", call. = FALSE)
  bp[, variable := as.character(variable)]
  if (anyDuplicated(bp$variable)) {
    stop("business_priors contains duplicate variable rows: ", paste(unique(bp$variable[duplicated(bp$variable)]), collapse = ", "), call. = FALSE)
  }
  default_relative_sd <- suppressWarnings(as.numeric(default_relative_sd)[1])
  if (!is.finite(default_relative_sd) || default_relative_sd <= 0) default_relative_sd <- 0.50
  min_coef_sd <- suppressWarnings(as.numeric(min_coef_sd)[1])
  if (!is.finite(min_coef_sd) || min_coef_sd <= 0) min_coef_sd <- 1e-6
  max_precision <- suppressWarnings(as.numeric(max_precision)[1])
  if (!is.finite(max_precision) || max_precision <= 0) max_precision <- Inf
  uncertainty_basis <- business_prior_uncertainty_basis_alias_hier_mmm(uncertainty_basis, default = "sd")[1]
  marginal_step_pct <- suppressWarnings(as.numeric(marginal_step_pct)[1])
  if (!is.finite(marginal_step_pct) || marginal_step_pct <= 0) marginal_step_pct <- 0.01

  prep_formals <- names(formals(prepare_stan_data_hier_mmm))
  extra_prep_args <- list(...)
  if (length(extra_prep_args)) prep_args <- modifyList(prep_args, extra_prep_args)
  prep_call <- prep_args[names(prep_args) %in% prep_formals]
  prep_call <- modifyList(prep_call, list(
    data = data,
    metadata_input = metadata_input,
    dep_var_col = dep_var_col,
    group_col = group_col,
    time_col = time_col,
    entity_col = entity_col
  ))
  prep <- do.call(prepare_stan_data_hier_mmm, prep_call)
  raw <- read_input_table(data)
  join_keys <- c(group_col, time_col, entity_col)
  train_info <- prep$data[, c(join_keys, "is_holdout__", "rescale_factor__"), with = FALSE]
  raw[train_info, `:=`(
    business_prior_is_holdout__ = i.is_holdout__,
    business_prior_rescale_factor__ = i.rescale_factor__
  ), on = join_keys]
  raw_train <- raw[business_prior_is_holdout__ == FALSE]
  sm <- normalize_business_spend_map_hier_mmm(metadata_input, spend_map = spend_map)
  if (nrow(sm)) sm[, variable := as.character(variable)]

  metadata_out <- read_input_table(metadata_input)
  if (!"variable" %in% names(metadata_out)) stop("metadata_input must include variable.", call. = FALSE)
  metadata_out[, variable := as.character(variable)]

  rows <- lapply(seq_len(nrow(bp)), function(i) {
    v <- bp$variable[i]
    metric <- business_prior_detect_metric_hier_mmm(bp, i)
    input_mean <- business_prior_row_num_hier_mmm(bp, i, business_prior_metric_candidates_hier_mmm(metric))
    sp <- business_prior_sd_precision_hier_mmm(bp, i, metric, default_uncertainty_basis = uncertainty_basis)
    input_sd <- sp$sd
    input_precision <- sp$precision
    dist <- if ("prior_distribution" %in% names(bp)) as.character(bp$prior_distribution[i]) else "normal"
    if (!nzchar(dist %||% "") || is.na(dist)) dist <- "normal"
    evidence_source <- if ("evidence_source" %in% names(bp)) as.character(bp$evidence_source[i]) else NA_character_
    evidence_notes <- if ("evidence_notes" %in% names(bp)) as.character(bp$evidence_notes[i]) else NA_character_
    if (!is.finite(input_mean) || is.na(metric)) {
      return(data.table(variable = v, warning = "invalid_business_prior_metric_or_mean"))
    }
    if (identical(metric, "coef")) {
      coef <- input_mean
      coef_sd <- input_sd
      if (!is.finite(coef_sd) || coef_sd <= 0) coef_sd <- max(abs(coef) * default_relative_sd, min_coef_sd)
      coef_sd <- max(coef_sd, min_coef_sd)
      precision_uncapped <- 1 / coef_sd^2
      precision <- min(precision_uncapped, max_precision)
      return(data.table(
        variable = v, coef = coef, coef_sd = coef_sd, coef_precision = precision,
        coef_precision_uncapped = precision_uncapped,
        coef_precision_was_capped = is.finite(max_precision) && precision_uncapped > max_precision,
        prior_metric = metric, input_prior_mean = input_mean, input_prior_sd = coef_sd,
        input_prior_precision = if (is.finite(input_precision)) input_precision else precision_uncapped,
        input_uncertainty_basis = sp$basis,
        input_uncertainty_source = sp$source,
        input_uncertainty_requested_basis = sp$requested_basis,
        input_precision_preserved = is.finite(input_precision) && input_precision > 0,
        prior_distribution = dist, stan_prior_distribution = "normal_on_coefficient",
        kpi_value_per_outcome = NA_real_, spend_col = NA_character_,
        spend_total_train = NA_real_, model_design_sum_train = NA_real_,
        economic_prior_basis = "direct_coefficient",
        evidence_source = evidence_source, evidence_notes = evidence_notes,
        warning = NA_character_
      ))
    }
    sc <- sm[variable == v, spend_col][1]
    if (is.na(sc) || !nzchar(sc) || !(sc %in% names(raw_train))) {
      return(data.table(variable = v, warning = "missing_spend_col_for_business_prior_conversion"))
    }
    design_sum <- business_design_sum_hier_mmm(prep, v)
    design_basis <- "average_metric_delta_method"
    warning_msg <- NA_character_
    if (metric %in% c("mroi", "mcpkpi")) {
      marginal_design_sum <- business_marginal_design_sum_hier_mmm(prep, v, step_pct = marginal_step_pct)
      if (is.finite(marginal_design_sum) && marginal_design_sum > 0) {
        design_sum <- marginal_design_sum / marginal_step_pct
        design_basis <- "marginal_metric_delta_method"
      } else {
        warning_msg <- paste0(metric, "_converted_with_average_scale_fallback_marginal_design_unusable")
      }
    }
    spend <- pmax(suppressWarnings(as.numeric(raw_train[[sc]])), 0)
    rescale <- suppressWarnings(as.numeric(raw_train$business_prior_rescale_factor__))
    rescale[!is.finite(rescale) | abs(rescale) <= 1e-8] <- 1
    spend_total <- sum(spend, na.rm = TRUE)
    if (!is.finite(spend_total) || spend_total <= 0 || !is.finite(design_sum) || design_sum <= 0) {
      return(data.table(variable = v, warning = "invalid_spend_or_model_design_for_business_prior_conversion"))
    }
    kpi_value <- kpi_value_for_business_prior_hier_mmm(kpi_value_per_outcome, bp, i, v)
    outcome_per_cost <- NA_real_
    outcome_per_cost_sd <- NA_real_
    cost_per_outcome <- NA_real_
    cost_per_outcome_sd <- NA_real_
    if (metric == "ikpc") {
      outcome_per_cost <- input_mean
      outcome_per_cost_sd <- input_sd
    } else if (metric %in% c("cpkpi", "mcpkpi")) {
      cost_per_outcome <- input_mean
      cost_per_outcome_sd <- input_sd
      outcome_per_cost <- 1 / cost_per_outcome
      if (is.finite(cost_per_outcome_sd) && cost_per_outcome_sd > 0) {
        outcome_per_cost_sd <- cost_per_outcome_sd / (cost_per_outcome^2)
      }
    } else if (metric %in% c("roi", "mroi")) {
      outcome_per_cost <- input_mean / kpi_value
      if (is.finite(input_sd) && input_sd > 0) outcome_per_cost_sd <- input_sd / kpi_value
    }
    if (!is.finite(outcome_per_cost) || outcome_per_cost <= 0) {
      return(data.table(variable = v, warning = "invalid_business_prior_economics"))
    }
    if (!is.finite(outcome_per_cost_sd) || outcome_per_cost_sd <= 0) {
      outcome_per_cost_sd <- max(abs(outcome_per_cost) * default_relative_sd, 1e-8)
    }
    exposure_to_model_outcome <- sum(spend / rescale, na.rm = TRUE)
    coef <- (outcome_per_cost * exposure_to_model_outcome) / design_sum
    coef_sd <- max((outcome_per_cost_sd * exposure_to_model_outcome) / design_sum, min_coef_sd)
    precision_uncapped <- 1 / coef_sd^2
    precision <- min(precision_uncapped, max_precision)
    data.table(
      variable = v, coef = coef, coef_sd = coef_sd, coef_precision = precision,
      coef_precision_uncapped = precision_uncapped,
      coef_precision_was_capped = is.finite(max_precision) && precision_uncapped > max_precision,
      prior_metric = metric, input_prior_mean = input_mean, input_prior_sd = input_sd,
      input_prior_precision = input_precision,
      input_uncertainty_basis = sp$basis,
      input_uncertainty_source = sp$source,
      input_uncertainty_requested_basis = sp$requested_basis,
      input_precision_preserved = FALSE,
      prior_distribution = dist, stan_prior_distribution = "normal_delta_method_on_coefficient",
      kpi_value_per_outcome = kpi_value, outcome_per_cost = outcome_per_cost,
      outcome_per_cost_sd = outcome_per_cost_sd,
      cost_per_outcome = if (is.finite(cost_per_outcome)) cost_per_outcome else 1 / outcome_per_cost,
      cost_per_outcome_sd = cost_per_outcome_sd,
      spend_col = sc, spend_total_train = spend_total, model_design_sum_train = design_sum,
      economic_prior_basis = design_basis,
      marginal_step_pct = if (metric %in% c("mroi", "mcpkpi")) marginal_step_pct else NA_real_,
      evidence_source = evidence_source, evidence_notes = evidence_notes,
      warning = warning_msg
    )
  })
  audit <- rbindlist(rows, fill = TRUE)
  usable <- audit[is.na(warning) | !nzchar(warning)]
  if (nrow(usable)) {
    metadata_out[usable, on = "variable", `:=`(
      coef = i.coef,
      coef_precision = i.coef_precision,
      business_prior_metric = i.prior_metric,
      business_prior_input_mean = i.input_prior_mean,
      business_prior_input_sd = i.input_prior_sd,
      business_prior_input_precision = i.input_prior_precision,
      business_prior_input_uncertainty_basis = i.input_uncertainty_basis,
      business_prior_input_uncertainty_source = i.input_uncertainty_source,
      business_prior_coef_sd = i.coef_sd,
      business_prior_coef_precision_uncapped = i.coef_precision_uncapped,
      business_prior_precision_was_capped = i.coef_precision_was_capped,
      business_prior_distribution = i.prior_distribution,
      business_prior_basis = i.economic_prior_basis,
      business_prior_evidence_source = i.evidence_source,
      business_prior_evidence_notes = i.evidence_notes
    )]
  }
  list(metadata = metadata_out[], business_prior_audit = audit[])
}

build_roi_mroi_hier_mmm <- function(fit_obj,
                                    spend_map = NULL,
                                    raw_data = NULL,
                                    variables = NULL,
                                    step_pct = 0.01,
                                    spend_suffix = "_spend",
                                    kpi_value_per_outcome = NA_real_) {
  sm <- normalize_spend_map_hier_mmm(fit_obj, spend_map = spend_map, raw_data = raw_data,
                                     spend_suffix = spend_suffix, variables = variables)
  if (!nrow(sm)) stop("No spend mapping found. Pass spend_map or add cost_col/spend_col to metadata.")
  raw_aligned <- get_aligned_raw_data_hier_mmm(fit_obj, raw_data = raw_data)
  long <- copy(as.data.table(fit_obj$long_decomp))
  if (!is.null(variables)) sm <- sm[variable %in% variables]
  kpi_value_per_outcome <- suppressWarnings(as.numeric(kpi_value_per_outcome)[1])

  rows <- lapply(seq_len(nrow(sm)), function(i) {
    v <- sm$variable[i]
    sc <- sm$spend_col[i]
    spend <- sum(as.numeric(raw_aligned[[sc]]), na.rm = TRUE)
    contribution <- long[variable == v, sum(contribution, na.rm = TRUE)]
    base_contribution <- variable_contribution_sum_hier_mmm(fit_obj, v, multiplier = 1)
    up_contribution <- variable_contribution_sum_hier_mmm(fit_obj, v, multiplier = 1 + step_pct)
    inc_contribution <- up_contribution - base_contribution
    inc_spend <- spend * step_pct
    outcome_per_cost <- if (abs(spend) > 1e-8) contribution / spend else NA_real_
    marginal_outcome_per_cost <- if (abs(inc_spend) > 1e-8) inc_contribution / inc_spend else NA_real_
    data.table(
      variable = v,
      spend_col = sc,
      spend = spend,
      contribution = contribution,
      outcome_per_cost = outcome_per_cost,
      cost_per_kpi = fifelse(is.finite(contribution) & contribution > 1e-8, spend / contribution, NA_real_),
      revenue_roi = fifelse(is.finite(kpi_value_per_outcome) & abs(spend) > 1e-8, contribution * kpi_value_per_outcome / spend, NA_real_),
      roi = outcome_per_cost,
      mroi_step_pct = step_pct,
      incremental_spend = inc_spend,
      incremental_contribution = inc_contribution,
      marginal_outcome_per_cost = marginal_outcome_per_cost,
      marginal_cost_per_kpi = fifelse(is.finite(inc_contribution) & inc_contribution > 1e-8, inc_spend / inc_contribution, NA_real_),
      marginal_revenue_roi = fifelse(is.finite(kpi_value_per_outcome) & abs(inc_spend) > 1e-8, inc_contribution * kpi_value_per_outcome / inc_spend, NA_real_),
      mroi = marginal_outcome_per_cost,
      kpi_value_per_outcome = if (is.finite(kpi_value_per_outcome)) kpi_value_per_outcome else NA_real_,
      decisioning_basis = "posterior_mean_point_estimate",
      economics_note = "roi/mroi are backward-compatible aliases for outcome_per_cost and marginal_outcome_per_cost. Use revenue_roi only when kpi_value_per_outcome is supplied.",
      uncertainty_note = "KPI economics are computed from posterior means only; use as decision support, not posterior uncertainty intervals."
    )
  })
  rbindlist(rows, fill = TRUE)[order(-mroi)]
}

calibrate_lift_tests_hier_mmm <- function(fit_obj,
                                          calibration_input,
                                          id_col = "calibration_id",
                                          variable_col = "variable",
                                          observed_lift_col = "observed_lift",
                                          observed_sd_col = "observed_lift_sd",
                                          observed_precision_col = "observed_lift_precision",
                                          start_col = "start_period",
                                          end_col = "end_period") {
  cal <- as_hier_mmm_data_table(calibration_input, label = "calibration_input")
  if (is.null(cal) || !nrow(cal)) return(data.table())
  if (!(variable_col %in% names(cal))) stop("calibration_input must include ", variable_col)
  if (!(observed_lift_col %in% names(cal))) stop("calibration_input must include ", observed_lift_col)
  if (!(id_col %in% names(cal))) cal[, (id_col) := paste0("calib_", .I)]

  long <- copy(as.data.table(fit_obj$long_decomp))
  group_col <- fit_obj$group_col
  time_col <- fit_obj$time_col

  rows <- lapply(seq_len(nrow(cal)), function(i) {
    row <- cal[i]
    v <- as.character(row[[variable_col]][1])
    obs <- suppressWarnings(as.numeric(row[[observed_lift_col]][1]))
    sd <- NA_real_
    if (observed_sd_col %in% names(row)) sd <- suppressWarnings(as.numeric(row[[observed_sd_col]][1]))
    if ((!is.finite(sd) || is.na(sd) || sd <= 0) && observed_precision_col %in% names(row)) {
      pr <- suppressWarnings(as.numeric(row[[observed_precision_col]][1]))
      if (is.finite(pr) && pr > 0) sd <- 1 / sqrt(pr)
    }
    tmp <- long[variable == v]
    if (group_col %in% names(cal) && group_col %in% names(tmp) && !is.na(row[[group_col]][1]) && nzchar(as.character(row[[group_col]][1]))) {
      tmp <- tmp[get(group_col) == row[[group_col]][1]]
    }
    if (start_col %in% names(cal) && time_col %in% names(tmp) && !is.na(row[[start_col]][1]) && nzchar(as.character(row[[start_col]][1]))) {
      tmp <- tmp[get(time_col) >= row[[start_col]][1]]
    }
    if (end_col %in% names(cal) && time_col %in% names(tmp) && !is.na(row[[end_col]][1]) && nzchar(as.character(row[[end_col]][1]))) {
      tmp <- tmp[get(time_col) <= row[[end_col]][1]]
    }
    model_lift <- tmp[, sum(contribution, na.rm = TRUE)]
    diff <- obs - model_lift
    ratio <- if (is.finite(model_lift) && abs(model_lift) > 1e-8) obs / model_lift else NA_real_
    z <- if (is.finite(sd) && sd > 0) diff / sd else NA_real_
    data.table(
      calibration_id = as.character(row[[id_col]][1]),
      variable = v,
      observed_lift = obs,
      model_lift = model_lift,
      lift_difference = diff,
      observed_to_model_ratio = ratio,
      observed_lift_sd = sd,
      calibration_z = z,
      recommended_coef_multiplier = ifelse(is.finite(ratio), pmin(pmax(ratio, 0.25), 4), NA_real_),
      calibration_flag = fifelse(is.finite(z) & abs(z) > 2, "outside_2sd", fifelse(is.finite(ratio) & (ratio < 0.70 | ratio > 1.30), "ratio_check", "ok"))
    )
  })
  rbindlist(rows, fill = TRUE)
}

apply_calibration_to_metadata <- function(metadata_input,
                                          calibration_diagnostics,
                                          output_path = NULL,
                                          multiplier_col = "recommended_coef_multiplier") {
  md <- read_input_table(metadata_input)
  cd <- as.data.table(copy(calibration_diagnostics))
  if (!nrow(cd)) return(md)
  adj <- cd[is.finite(get(multiplier_col)), .(calibration_multiplier = median(get(multiplier_col), na.rm = TRUE)), by = variable]
  if (!nrow(adj)) return(md)
  md[adj, coef := as.numeric(coef) * i.calibration_multiplier, on = "variable"]
  md[adj, calibration_multiplier := i.calibration_multiplier, on = "variable"]
  if (!is.null(output_path) && nzchar(output_path)) fwrite(md, output_path)
  md[]
}

optimize_budget_hier_mmm <- function(fit_obj,
                                     spend_map = NULL,
                                     raw_data = NULL,
                                     total_budget = NULL,
                                     variables = NULL,
                                     budget_step_frac = 0.01,
                                     min_multiplier = 0,
                                     max_multiplier = 3,
                                     spend_suffix = "_spend",
                                     max_iter = 1000) {
  sm <- normalize_spend_map_hier_mmm(fit_obj, spend_map = spend_map, raw_data = raw_data,
                                     spend_suffix = spend_suffix, variables = variables)
  if (!nrow(sm)) stop("No spend mapping found for optimizer.")
  raw_aligned <- get_aligned_raw_data_hier_mmm(fit_obj, raw_data = raw_data)
  sm[, current_spend := vapply(spend_col, function(cc) sum(as.numeric(raw_aligned[[cc]]), na.rm = TRUE), numeric(1))]
  sm <- sm[current_spend > 0]
  if (!nrow(sm)) stop("All mapped spend columns sum to zero.")
  if (is.null(total_budget)) total_budget <- sum(sm$current_spend)
  if (!is.finite(total_budget) || total_budget <= 0) stop("total_budget must be positive.")
  if (length(min_multiplier) == 1L) min_multiplier <- rep(min_multiplier, nrow(sm))
  if (length(max_multiplier) == 1L) max_multiplier <- rep(max_multiplier, nrow(sm))
  sm[, `:=`(min_multiplier = min_multiplier, max_multiplier = max_multiplier)]

  multipliers <- sm$min_multiplier
  names(multipliers) <- sm$variable
  spend_now <- sm$current_spend * multipliers
  remaining <- total_budget - sum(spend_now)
  chunk <- max(total_budget * budget_step_frac, total_budget / max_iter)
  iter <- 0L

  while (remaining > 1e-8 && iter < max_iter) {
    iter <- iter + 1L
    candidates <- lapply(seq_len(nrow(sm)), function(i) {
      v <- sm$variable[i]
      cur_mult <- multipliers[v]
      if (cur_mult >= sm$max_multiplier[i] - 1e-8) return(NULL)
      alloc <- min(chunk, remaining, sm$current_spend[i] * (sm$max_multiplier[i] - cur_mult))
      if (alloc <= 1e-8) return(NULL)
      delta_mult <- alloc / sm$current_spend[i]
      base <- variable_contribution_sum_hier_mmm(fit_obj, v, multiplier = cur_mult)
      up <- variable_contribution_sum_hier_mmm(fit_obj, v, multiplier = cur_mult + delta_mult)
      data.table(variable = v, add_spend = alloc, delta_mult = delta_mult,
                 incremental_contribution = up - base,
                 marginal_roi = (up - base) / alloc)
    })
    cand <- rbindlist(candidates, fill = TRUE)
    if (!nrow(cand)) break
    cand <- cand[order(-marginal_roi)]
    best <- cand[1]
    multipliers[best$variable] <- multipliers[best$variable] + best$delta_mult
    remaining <- remaining - best$add_spend
  }

  plan <- copy(sm)
  plan[, recommended_multiplier := as.numeric(multipliers[variable])]
  plan[, recommended_spend := current_spend * recommended_multiplier]
  plan[, expected_contribution := vapply(variable, function(v) variable_contribution_sum_hier_mmm(fit_obj, v, multiplier = multipliers[v]), numeric(1))]
  plan[, expected_roi := fifelse(abs(recommended_spend) > 1e-8, expected_contribution / recommended_spend, NA_real_)]
  plan[, `:=`(
    total_budget = total_budget,
    optimizer_iterations = iter,
    unallocated_budget = max(remaining, 0),
    optimizer_basis = "posterior_mean_point_estimate_prototype",
    uncertainty_note = "Budget optimization uses posterior mean response only; it does not yet optimize over posterior uncertainty."
  )]
  plan[order(-recommended_spend)]
}

add_reach_frequency_signal <- function(data,
                                       reach_col,
                                       frequency_col,
                                       output_col,
                                       method = c("effective_reach", "reach_x_frequency"),
                                       frequency_cap = 10) {
  method <- match.arg(method)
  dt <- copy(as.data.table(data))
  if (!all(c(reach_col, frequency_col) %in% names(dt))) stop("reach_col and frequency_col must exist in data.")
  r <- pmax(as.numeric(dt[[reach_col]]), 0)
  f <- pmax(pmin(as.numeric(dt[[frequency_col]]), frequency_cap), 0)
  if (method == "effective_reach") {
    dt[, (output_col) := r * (1 - exp(-f))]
  } else {
    dt[, (output_col) := r * f]
  }
  dt[]
}

write_decision_outputs_hier_mmm <- function(decision_outputs, output_dir, prefix = "") {
  if (is.null(output_dir) || !nzchar(output_dir)) return(invisible(NULL))
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  pfx <- if (nzchar(prefix)) paste0(prefix, "_") else ""
  for (nm in names(decision_outputs)) {
    obj <- decision_outputs[[nm]]
    if (inherits(obj, "data.table") || is.data.frame(obj)) {
      fwrite(as.data.table(obj), file.path(output_dir, paste0(pfx, nm, ".csv")))
    }
  }
  invisible(output_dir)
}

run_hier_mmm_decisioning <- function(fit_obj,
                                     spend_map = NULL,
                                     raw_data = NULL,
                                     calibration_input = NULL,
                                     budget_optimizer_config = NULL,
                                     kpi_value_per_outcome = NA_real_,
                                     output_dir = NULL,
                                     output_prefix = "") {
  out <- list()
  if (!is.null(spend_map)) {
    out$roi_mroi <- build_roi_mroi_hier_mmm(
      fit_obj,
      spend_map = spend_map,
      raw_data = raw_data,
      kpi_value_per_outcome = kpi_value_per_outcome
    )
  }
  if (!is.null(calibration_input)) {
    out$calibration <- calibrate_lift_tests_hier_mmm(fit_obj, calibration_input = calibration_input)
  }
  if (!is.null(budget_optimizer_config)) {
    cfg <- budget_optimizer_config
    if (is.null(cfg$spend_map)) cfg$spend_map <- spend_map
    if (is.null(cfg$raw_data)) cfg$raw_data <- raw_data
    out$budget_optimizer <- do.call(optimize_budget_hier_mmm, c(list(fit_obj = fit_obj), cfg))
  }
  out$decisioning_notes <- data.table(
    component = c("roi_mroi", "budget_optimizer"),
    basis = c("posterior_mean_point_estimate", "posterior_mean_point_estimate_prototype"),
    note = c(
      "KPI economics are computed from posterior means only; posterior draw intervals are not included in this table. roi/mroi are outcome-per-cost aliases unless revenue_roi is populated from kpi_value_per_outcome.",
      "Budget optimization uses posterior mean response only and should be treated as prototype decision support."
    )
  )
  write_decision_outputs_hier_mmm(out, output_dir = output_dir, prefix = output_prefix)
  out
}
