# 018-hier_mmm-public-wrappers.R
# Generated by behavior-preserving split of hier_mmm.R.

run_hier_mmm_sensitivity <- function(data,
                                     metadata_input,
                                     dep_var_col,
                                     group_col,
                                     time_col,
                                     entity_col,
                                     variants = NULL,
                                     output_dir = file.path("hier_mmm_outputs", "sensitivity"),
                                     chains = 2,
                                     parallel_chains = 2,
                                     iter_warmup = 500,
                                     iter_sampling = 500,
                                     continue_on_error = TRUE,
                                     ...) {
  if (is.null(variants)) {
    variants <- data.table(
      variant = c("base_fourier_student_t_fixed_curve", "fourier_centered_x", "flat_student_t_fixed_curve", "ucm_student_t_fixed_curve", "ucm_normal_fixed_curve", "ucm_student_t_est_curve"),
      intercept_type = c("fourier", "fourier", "flat", "ucm", "ucm", "ucm"),
      likelihood = c("student_t", "student_t", "student_t", "student_t", "normal", "student_t"),
      estimate_dvalue = c(FALSE, FALSE, FALSE, FALSE, FALSE, TRUE),
      center_predictors_for_sampling = c(FALSE, TRUE, FALSE, FALSE, FALSE, FALSE),
      sample_curve_parameters = c("never", "never", "never", "never", "never", "always")
    )
  } else {
    variants <- as.data.table(variants)
  }
  if (!"variant" %in% names(variants)) variants[, variant := paste0("variant_", .I)]
  variant_arg_list <- function(vrow) {
    keep <- setdiff(names(vrow), "variant")
    out <- as.list(vrow[, ..keep])
    out <- lapply(out, function(x) if (length(x) == 1L) x[[1]] else x)
    out[!vapply(out, function(x) length(x) == 0L || (length(x) == 1L && is.na(x)), logical(1))]
  }
  fits <- list()
  summary_rows <- list()
  dots <- list(...)
  for (i in seq_len(nrow(variants))) {
    vname <- variants$variant[i]
    base_args <- modifyList(list(
      data = data, metadata_input = metadata_input, dep_var_col = dep_var_col,
      group_col = group_col, time_col = time_col, entity_col = entity_col,
      intercept_type = "fourier", likelihood = "student_t",
      estimate_dvalue = FALSE, chains = chains,
      parallel_chains = parallel_chains, iter_warmup = iter_warmup,
      iter_sampling = iter_sampling, output_dir = file.path(output_dir, vname),
      output_prefix = vname
    ), dots)
    args <- modifyList(base_args, variant_arg_list(variants[i]))
    fit_result <- tryCatch(
      list(ok = TRUE, fit = do.call(fit_hier_mmm, args), error = NA_character_),
      error = function(e) list(ok = FALSE, fit = NULL, error = conditionMessage(e))
    )
    if (!isTRUE(fit_result$ok)) {
      if (!isTRUE(continue_on_error)) stop(fit_result$error, call. = FALSE)
      fits[[vname]] <- fit_result
      summary_rows[[i]] <- data.table(
        variant = vname,
        status = "error",
        error = fit_result$error,
        intercept_type = args$intercept_type %||% NA_character_,
        likelihood = args$likelihood %||% NA_character_,
        estimate_dvalue = isTRUE(args$estimate_dvalue),
        sample_curve_parameters = args$sample_curve_parameters %||% NA_character_,
        sample_coef_hierarchy = args$sample_coef_hierarchy %||% NA_character_,
        coef_parameterization = args$coef_parameterization %||% NA_character_,
        alpha_parameterization = args$alpha_parameterization %||% NA_character_,
        ucm_parameterization = args$ucm_parameterization %||% NA_character_,
        center_predictors_for_sampling = isTRUE(args$center_predictors_for_sampling),
        rmse = NA_real_,
        r2 = NA_real_,
        divergences_total = NA_real_,
        treedepth_hits_total = NA_real_,
        min_bfmi = NA_real_,
        max_rhat = NA_real_,
        model_readiness = "error"
      )
      next
    }
    fits[[vname]] <- fit_result$fit
    fit_i <- fits[[vname]]
    fq <- fit_i$diagnostics$fit_quality_overall
    so <- fit_i$diagnostics$sampler_overall
    flags <- fit_i$diagnostics$diagnostics_flags
    readiness <- fit_i$diagnostics$model_readiness %||% data.table()
    summary_rows[[i]] <- data.table(
      variant = vname,
      status = "ok",
      error = NA_character_,
      intercept_type = fit_i$intercept_type %||% NA_character_,
      likelihood = fit_i$likelihood %||% NA_character_,
      estimate_dvalue = isTRUE(fit_i$estimate_dvalue),
      sample_curve_parameters = fit_i$sample_curve_parameters %||% NA_character_,
      sample_coef_hierarchy = fit_i$sample_coef_hierarchy %||% NA_character_,
      coef_parameterization = fit_i$coef_parameterization %||% NA_character_,
      alpha_parameterization = fit_i$alpha_parameterization %||% NA_character_,
      ucm_parameterization = fit_i$ucm_parameterization %||% NA_character_,
      center_predictors_for_sampling = isTRUE(fit_i$center_predictors_for_sampling),
      rmse = if (nrow(fq)) fq[1, rmse] else NA_real_,
      r2 = if (nrow(fq)) fq[1, r2] else NA_real_,
      divergences_total = if (nrow(so)) so[1, divergences_total] else NA_real_,
      treedepth_hits_total = if (nrow(so)) so[1, treedepth_hits_total] else NA_real_,
      min_bfmi = if (nrow(so)) so[1, min_bfmi] else NA_real_,
      max_rhat = if (nrow(so)) so[1, max_rhat] else NA_real_,
      model_readiness = if (nrow(readiness)) readiness$model_readiness[1] else NA_character_
    )
  }
  summary <- rbindlist(summary_rows, fill = TRUE)
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  fwrite(summary, file.path(output_dir, "sensitivity_summary.csv"))
  list(summary = summary, fits = fits)
}

# Convenience wrapper for the final UCM run.
# This keeps the normal fit_hier_mmm() default lighter/Fourier-based, while making
# the intended final workflow explicit: use a UCM-informed initialization, optionally
# Pathfinder, then jointly estimate the UCM baseline with media and coefficients.
fit_hier_mmm_ucm_final <- function(data,
                                   metadata_input,
                                   dep_var_col,
                                   group_col,
                                   time_col,
                                   entity_col,
                                   baseline_config = NULL,
                                   output_dir = "hier_mmm_outputs_ucm_final",
                                   output_prefix = "ucm_final",
                                   ...) {
  dots <- list(...)
  ucm_base <- list(
    type = "ucm",
    level = TRUE,
    season = TRUE,
    cycle = FALSE,
    season_period = 52L,
    season_harmonics = 2L,
    cycle_period = 104L,
    cycle_harmonics = 1L
  )
  if (!is.null(baseline_config)) ucm_base <- modifyList(ucm_base, baseline_config)

  engine_args <- modifyList(dots, list(
    data = data,
    metadata_input = metadata_input,
    dep_var_col = dep_var_col,
    group_col = group_col,
    time_col = time_col,
    entity_col = entity_col,
    baseline_config = ucm_base,
    init_strategy = dots$init_strategy %||% "ucm_pathfinder",
    use_ucm_warm_start_init = dots$use_ucm_warm_start_init %||% TRUE,
    use_pathfinder_init = dots$use_pathfinder_init %||% TRUE,
    output_dir = output_dir,
    output_prefix = output_prefix
  ))

  do.call(fit_hier_mmm, engine_args)
}

fit_hier_mmm_fourier_then_ucm <- function(data,
                                      metadata_input,
                                      dep_var_col,
                                      group_col,
                                      time_col,
                                      entity_col,
                                      output_dir = "hier_mmm_outputs_staged",
                                      fourier_args = list(),
                                      ucm_args = list(),
                                      ...) {
  dots <- list(...)

  fourier_call <- modifyList(dots, modifyList(list(
    data = data,
    metadata_input = metadata_input,
    dep_var_col = dep_var_col,
    group_col = group_col,
    time_col = time_col,
    entity_col = entity_col,
    baseline_config = list(type = "fourier", season = TRUE, cycle = FALSE),
    output_dir = file.path(output_dir, "01_fourier_default"),
    output_prefix = "fourier_default"
  ), fourier_args))

  ucm_call <- modifyList(dots, modifyList(list(
    data = data,
    metadata_input = metadata_input,
    dep_var_col = dep_var_col,
    group_col = group_col,
    time_col = time_col,
    entity_col = entity_col,
    output_dir = file.path(output_dir, "02_ucm_final"),
    output_prefix = "ucm_final"
  ), ucm_args))

  fourier_fit <- do.call(fit_hier_mmm, fourier_call)
  ucm_fit <- do.call(fit_hier_mmm_ucm_final, ucm_call)

  list(
    fourier_default = fourier_fit,
    ucm_final = ucm_fit
  )
}

# Public wrapper. Keeps the normal call simple while preserving every advanced
# engine option through ... .
fit_hier_mmm <- function(data,
                         metadata_input,
                         dep_var_col,
                         group_col,
                         time_col,
                         entity_col,
                         baseline_config = NULL,
                         holiday_config = NULL,
                         spend_map = NULL,
                         business_priors = NULL,
                         kpi_value_per_outcome = 1,
                         business_prior_default_relative_sd = 0.50,
                         business_prior_min_coef_sd = 1e-6,
                         business_prior_max_precision = Inf,
                         business_prior_uncertainty_basis = "sd",
                         business_prior_marginal_step_pct = 0.01,
                         calibration_input = NULL,
                         budget_optimizer_config = NULL,
                         context_effects = NULL,
                         allow_time_context = FALSE,
                         coef_hierarchy_part_indices = NULL,
                         coef_hierarchy_index_base = c("one", "zero"),
                         raw_output_data = NULL,
                         create_response_curves = TRUE,
                         create_response_curve_draws = FALSE,
                         response_curve_multipliers = seq(0, 3, by = 0.05),
                         response_curve_step_pct = 0.01,
                         response_curve_scope = c("auto", "total", "group", "both"),
                         response_curve_draw_count = 200L,
                         response_curve_draw_seed = 123L,
                         output_dir = "hier_mmm_outputs",
                         output_prefix = "",
                         ...) {
  dots <- list(...)
  response_curve_scope <- match.arg(response_curve_scope)
  coef_hierarchy_index_base <- match.arg(coef_hierarchy_index_base)
  business_prior_update <- NULL

  if (!is.null(business_priors)) {
    business_prior_update <- apply_business_priors_to_metadata_hier_mmm(
      data = data,
      metadata_input = metadata_input,
      business_priors = business_priors,
      dep_var_col = dep_var_col,
      group_col = group_col,
      time_col = time_col,
      entity_col = entity_col,
      spend_map = spend_map,
      kpi_value_per_outcome = kpi_value_per_outcome,
      default_relative_sd = business_prior_default_relative_sd,
      min_coef_sd = business_prior_min_coef_sd,
      max_precision = business_prior_max_precision,
      uncertainty_basis = business_prior_uncertainty_basis,
      marginal_step_pct = business_prior_marginal_step_pct,
      prep_args = dots
    )
    metadata_input <- business_prior_update$metadata
  }

  engine_args <- modifyList(dots, list(
    data = data,
    metadata_input = metadata_input,
    dep_var_col = dep_var_col,
    group_col = group_col,
    time_col = time_col,
    entity_col = entity_col,
    context_effects = context_effects,
    allow_time_context = allow_time_context,
    coef_hierarchy_part_indices = coef_hierarchy_part_indices,
    coef_hierarchy_index_base = coef_hierarchy_index_base,
    holiday_config = holiday_config,
    output_dir = output_dir,
    output_prefix = output_prefix
  ))

  if (!is.null(baseline_config)) {
    bc <- baseline_config
    if (is.null(holiday_config) && !is.null(bc$holiday_config)) {
      engine_args$holiday_config <- bc$holiday_config
    }
    if (!is.null(bc$type)) engine_args$intercept_type <- as.character(bc$type)
    ucm_names <- intersect(names(bc), c("level", "season", "cycle", "season_period", "season_harmonics", "cycle_period", "cycle_harmonics"))
    if (length(ucm_names)) {
      base_type <- tolower(trimws(as.character((bc$type %||% engine_args$intercept_type %||% "fourier")[1])))
      base_spec <- engine_args$ucm_spec %||% if (identical(base_type, "ucm")) {
        list(
          level = TRUE, season = TRUE, cycle = FALSE,
          season_period = 52L, season_harmonics = 2L,
          cycle_period = 104L, cycle_harmonics = 1L
        )
      } else {
        list(
          level = FALSE, season = TRUE, cycle = FALSE,
          season_period = 52L, season_harmonics = 2L,
          cycle_period = 104L, cycle_harmonics = 1L
        )
      }
      engine_args$ucm_spec <- modifyList(base_spec, bc[ucm_names])
    }
    if (!is.null(bc$level_innovation_sd)) engine_args$sigma_level_prior_sd <- bc$level_innovation_sd
    if (!is.null(bc$initial_level_mean))  engine_args$level0_mu_prior_mean <- bc$initial_level_mean
    if (!is.null(bc$initial_level_sd))    engine_args$level0_mu_prior_sd <- bc$initial_level_sd
    if (!is.null(bc$group_level_sd))      engine_args$level0_sd_prior_sd <- bc$group_level_sd
    if (!is.null(bc$season_sd))           engine_args$season_sd_prior_sd <- bc$season_sd
    if (!is.null(bc$cycle_sd))            engine_args$cycle_sd_prior_sd <- bc$cycle_sd
    if (!is.null(bc$noise_sd))            engine_args$sigma_y_prior_sd <- bc$noise_sd
  }

  fit_obj <- do.call(fit_hier_mmm_engine, engine_args)
  fit_obj$business_prior_audit <- if (!is.null(business_prior_update)) business_prior_update$business_prior_audit else data.table()

  if (!is.null(spend_map)) {
    fit_obj <- attach_spend_to_hier_mmm_outputs(
      fit_obj,
      spend_map = spend_map,
      raw_data = raw_output_data %||% data
    )
    if (!is.null(output_dir) && nzchar(output_dir)) {
      pfx <- if (nzchar(output_prefix %||% "")) paste0(output_prefix, "_") else ""
      dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
      fwrite(fit_obj$wide_decomp, file.path(output_dir, paste0(pfx, "wide_decomp.csv")))
      fwrite(fit_obj$long_decomp, file.path(output_dir, paste0(pfx, "long_decomp.csv")))
      if (nrow(fit_obj$spend_attachment_diagnostics)) {
        fwrite(fit_obj$spend_attachment_diagnostics, file.path(output_dir, paste0(pfx, "spend_attachment_diagnostics.csv")))
      }
    }
  }

  if (isTRUE(create_response_curves)) {
    fit_obj$posterior_means <- fit_obj$posterior_means %||% extract_pm_from_fit_obj_hier_mmm(fit_obj)
    fit_obj$response_curves <- build_response_curves_hier_mmm(
      fit_obj = fit_obj,
      spend_map = spend_map,
      raw_data = raw_output_data %||% data,
      multiplier_grid = response_curve_multipliers,
      step_pct = response_curve_step_pct,
      response_curve_scope = response_curve_scope
    )
    if (!is.null(output_dir) && nzchar(output_dir) && nrow(fit_obj$response_curves)) {
      pfx <- if (nzchar(output_prefix %||% "")) paste0(output_prefix, "_") else ""
      dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
      fwrite(fit_obj$response_curves, file.path(output_dir, paste0(pfx, "response_curves.csv")))
    }
  } else {
    fit_obj$response_curves <- data.table()
  }

  if (isTRUE(create_response_curve_draws)) {
    fit_obj$response_curves_draws <- build_response_curves_draws_hier_mmm(
      fit_obj = fit_obj,
      spend_map = spend_map,
      raw_data = raw_output_data %||% data,
      multiplier_grid = response_curve_multipliers,
      step_pct = response_curve_step_pct,
      response_curve_scope = response_curve_scope,
      max_draws = response_curve_draw_count,
      seed = response_curve_draw_seed
    )
    if (!is.null(output_dir) && nzchar(output_dir) && nrow(fit_obj$response_curves_draws)) {
      pfx <- if (nzchar(output_prefix %||% "")) paste0(output_prefix, "_") else ""
      dir.create(output_dir, showWarnings = FALSE, recursive = TRUE)
      fwrite(fit_obj$response_curves_draws, file.path(output_dir, paste0(pfx, "response_curves_draws.csv")))
    }
  } else {
    fit_obj$response_curves_draws <- fit_obj$response_curves_draws %||% data.table()
  }

  if (!is.null(spend_map) || !is.null(calibration_input) || !is.null(budget_optimizer_config)) {
    fit_obj$posterior_means <- extract_pm_from_fit_obj_hier_mmm(fit_obj)
    fit_obj$decision_outputs <- run_hier_mmm_decisioning(
      fit_obj = fit_obj,
      spend_map = spend_map,
      raw_data = raw_output_data %||% data,
      calibration_input = calibration_input,
      budget_optimizer_config = budget_optimizer_config,
      output_dir = output_dir,
      output_prefix = output_prefix
    )
  } else {
    fit_obj$decision_outputs <- list()
  }

  fit_obj
}
