# 020-quasi_geo-utils.R
# Generated by behavior-preserving split of quasi_geo_test.R.

# quasi_geo_test.R
# Detect and estimate natural or unannounced geo tests from geo x time data.

`%||%` <- function(x, y) if (is.null(x)) y else x

qgt_clip <- function(x, lo, hi) pmin(pmax(x, lo), hi)
qgt_num <- function(x) suppressWarnings(as.numeric(x))
qgt_date <- function(x) {
  if (inherits(x, "Date")) return(x)
  out <- suppressWarnings(as.Date(x))
  if (all(is.na(out))) out <- suppressWarnings(as.Date(as.numeric(x), origin = "1899-12-30"))
  out
}
qgt_apply_holdout_flag <- function(dt,
                                   date_col,
                                   holdout_col = NULL,
                                   holdout_value = TRUE,
                                   holdout_last_n = 0L) {
  out <- copy(dt)
  is_holdout <- rep(FALSE, nrow(out))
  if (!is.null(holdout_col) && nzchar(as.character(holdout_col)[1])) {
    holdout_col <- as.character(holdout_col)[1]
    if (!holdout_col %in% names(out)) stop("holdout_col not found: ", holdout_col)
    hv <- out[[holdout_col]]
    if (is.logical(hv) && identical(holdout_value, TRUE)) {
      is_holdout <- is_holdout | (hv %in% TRUE)
    } else {
      is_holdout <- is_holdout | (as.character(hv) %in% as.character(holdout_value))
    }
  }
  holdout_last_n <- as.integer(holdout_last_n %||% 0L)[1]
  if (is.finite(holdout_last_n) && holdout_last_n > 0L) {
    dates <- qgt_date(out[[date_col]])
    holdout_dates <- utils::tail(sort(unique(dates[!is.na(dates)])), holdout_last_n)
    is_holdout <- is_holdout | (dates %in% holdout_dates)
  }
  out[, is_qgt_training__ := !is_holdout]
  if (!any(out$is_qgt_training__)) stop("All rows are holdout. At least one training row is required for quasi-geo estimation.")
  audit <- data.table(
    input_row_n = nrow(out),
    training_row_n = sum(out$is_qgt_training__),
    holdout_row_n = sum(!out$is_qgt_training__),
    holdout_col = as.character(holdout_col %||% NA_character_),
    holdout_value = paste(as.character(holdout_value), collapse = "|"),
    holdout_last_n = as.integer(holdout_last_n %||% 0L)
  )
  list(data = out[], audit = audit)
}
qgt_safe_mean <- function(x, default = NA_real_) {
  x <- qgt_num(x)
  m <- mean(x[is.finite(x)], na.rm = TRUE)
  if (is.finite(m)) m else default
}
qgt_safe_sd <- function(x, floor = 0) {
  x <- qgt_num(x)
  s <- stats::sd(x[is.finite(x)], na.rm = TRUE)
  if (is.finite(s) && s > floor) s else floor
}
qgt_event_value <- function(event, col, default = NA) {
  if (col %in% names(event)) event[[col]][1] else default
}
qgt_evidence_rank <- function(x) {
  tier_rank <- c(not_estimable = 0, weak_noisy_estimate = 1, moderate_quasi_geo = 2, strong_quasi_geo = 3)
  out <- unname(tier_rank[as.character(x)])
  out[is.na(out)] <- 0
  out
}
qgt_evidence_tier_from_score <- function(score) {
  data.table::fcase(
    is.finite(score) & score >= 80, "strong_quasi_geo",
    is.finite(score) & score >= 60, "moderate_quasi_geo",
    is.finite(score) & score > 0, "weak_noisy_estimate",
    default = "not_estimable"
  )
}
qgt_direction_from_signed_change <- function(signed_change,
                                             mixed = FALSE,
                                             eps = 1e-10) {
  data.table::fcase(
    isTRUE(mixed), "mixed",
    is.finite(signed_change) & signed_change > eps, "up_ramp",
    is.finite(signed_change) & signed_change < -eps, "down_ramp",
    default = "none"
  )
}
qgt_change_class <- function(pre,
                             post,
                             pct_threshold,
                             near_zero = 1e-8,
                             material = near_zero) {
  pre <- qgt_num(pre)
  post <- qgt_num(post)
  data.table::fcase(
    is.finite(pre) & is.finite(post) & pre <= near_zero & post >= material, "turn_on",
    is.finite(pre) & is.finite(post) & pre >= material & post <= near_zero, "turn_off",
    is.finite(pre) & pre > near_zero & is.finite(post) & ((post - pre) / pre) >= pct_threshold, "up_ramp",
    is.finite(pre) & pre > near_zero & is.finite(post) & ((post - pre) / pre) <= -pct_threshold, "down_ramp",
    default = "none"
  )
}
qgt_positive_scale <- function(x, floor = 1e-8) {
  x <- qgt_num(x)
  x <- x[is.finite(x) & x > floor]
  if (!length(x)) return(floor)
  out <- stats::median(x, na.rm = TRUE)
  if (is.finite(out) && out > floor) out else floor
}
qgt_mean_index_by_geo <- function(dt, cols, geo_col, train_col = NULL) {
  out <- copy(dt)
  for (cc in cols) {
    out[, (cc) := {
      z <- qgt_num(get(cc))
      ref <- if (!is.null(train_col) && train_col %in% names(.SD)) z[get(train_col) == TRUE] else z
      den <- qgt_safe_mean(ref, default = 1)
      if (!is.finite(den) || abs(den) < 1e-8) den <- 1
      z / den
    }, by = geo_col]
  }
  out[]
}
qgt_project_simplex <- function(v) {
  v <- qgt_num(v)
  if (!length(v)) return(v)
  if (all(!is.finite(v))) return(rep(1 / length(v), length(v)))
  v[!is.finite(v)] <- 0
  u <- sort(v, decreasing = TRUE)
  cssv <- cumsum(u)
  rho <- max(which(u * seq_along(u) > (cssv - 1)), 1L)
  theta <- (cssv[rho] - 1) / rho
  w <- pmax(v - theta, 0)
  s <- sum(w)
  if (!is.finite(s) || s <= 1e-12) rep(1 / length(v), length(v)) else w / s
}
qgt_ridge_synth_weights <- function(y_treat_pre,
                                    donor_pre_mat,
                                    lambda_grid = 10 ^ seq(-4, 2, length.out = 20),
                                    simplex = TRUE) {
  y <- qgt_num(y_treat_pre)
  X <- as.matrix(donor_pre_mat)
  storage.mode(X) <- "double"
  full_p <- ncol(X)
  if (!full_p) return(numeric())
  ok <- stats::complete.cases(y, X)
  min_pre_rows <- 4L
  if (sum(ok) < min_pre_rows) return(rep(NA_real_, full_p))
  y <- y[ok]
  X <- X[ok, , drop = FALSE]
  keep_cols <- apply(X, 2L, function(z) {
    z <- qgt_num(z)
    stats::sd(z, na.rm = TRUE) > 1e-8
  })
  if (!any(keep_cols)) return(rep(NA_real_, full_p))
  X <- X[, keep_cols, drop = FALSE]
  y <- y - mean(y, na.rm = TRUE)
  X <- scale(X, center = TRUE, scale = FALSE)
  XtX <- crossprod(X)
  Xty <- crossprod(X, y)
  lambda_grid <- sort(unique(qgt_num(lambda_grid)))
  lambda_grid <- lambda_grid[is.finite(lambda_grid) & lambda_grid >= 0]
  if (!length(lambda_grid)) lambda_grid <- 1
  best <- NULL
  for (lam in lambda_grid) {
    b <- tryCatch(as.numeric(solve(XtX + diag(lam, ncol(X)), Xty)), error = function(e) rep(NA_real_, ncol(X)))
    if (simplex) b <- qgt_project_simplex(b) else b[!is.finite(b)] <- 0
    pred <- as.numeric(X %*% b)
    mse <- mean((y - pred) ^ 2, na.rm = TRUE)
    if (is.finite(mse) && (is.null(best) || !is.finite(best$mse) || mse < best$mse)) best <- list(weights = b, lambda = lam, mse = mse)
  }
  if (is.null(best)) return(rep(NA_real_, full_p))
  out <- rep(0, full_p)
  out[keep_cols] <- best$weights
  attr(out, "lambda") <- best$lambda
  out
}
qgt_tbr_counterfactual <- function(wide,
                                   treat_col,
                                   donor_cols,
                                   pre_start,
                                   pre_end,
                                   post_start,
                                   post_end,
                                   min_pre_rows = 4L) {
  out_empty <- list(
    success = FALSE,
    method = "not_estimable",
    pred = rep(NA_real_, nrow(wide)),
    lift = NA_real_,
    lift_se = NA_real_,
    lift_z = NA_real_,
    pre_fit_score = NA_real_,
    scaled_l2_imbalance = NA_real_,
    complete_pre_n = 0L,
    complete_post_n = 0L
  )
  if (is.null(wide) || !nrow(wide) || !"date__" %in% names(wide)) return(out_empty)
  treat_col <- as.character(treat_col)[1]
  donor_cols <- setdiff(as.character(donor_cols), treat_col)
  donor_cols <- donor_cols[donor_cols %in% names(wide)]
  if (!treat_col %in% names(wide) || !length(donor_cols)) return(out_empty)

  w <- copy(wide)
  w[, control__ := rowMeans(.SD, na.rm = TRUE), .SDcols = donor_cols]
  w[!is.finite(control__), control__ := NA_real_]
  pre <- w[date__ >= pre_start & date__ <= pre_end]
  post <- w[date__ >= post_start & date__ <= post_end]
  pre_ok <- is.finite(qgt_num(pre[[treat_col]])) & is.finite(qgt_num(pre$control__))
  post_ok <- is.finite(qgt_num(post[[treat_col]])) & is.finite(qgt_num(post$control__))
  if (sum(pre_ok) < 2L || !sum(post_ok)) return(out_empty)

  pred_all <- rep(NA_real_, nrow(w))
  method <- "difference_in_differences"
  if (sum(pre_ok) >= as.integer(min_pre_rows) && qgt_safe_sd(pre$control__[pre_ok], floor = 0) > 1e-8) {
    fit <- tryCatch(stats::lm(qgt_num(pre[[treat_col]])[pre_ok] ~ pre$control__[pre_ok]), error = function(e) NULL)
    if (!is.null(fit) && length(stats::coef(fit)) == 2L && all(is.finite(stats::coef(fit)))) {
      pred_all <- as.numeric(stats::coef(fit)[1] + stats::coef(fit)[2] * w$control__)
      method <- "time_based_regression"
    }
  }
  if (all(!is.finite(pred_all))) {
    pre_treat_mean <- mean(qgt_num(pre[[treat_col]])[pre_ok], na.rm = TRUE)
    pre_control_mean <- mean(qgt_num(pre$control__)[pre_ok], na.rm = TRUE)
    if (!is.finite(pre_treat_mean) || !is.finite(pre_control_mean)) return(out_empty)
    pred_all <- pre_treat_mean + (w$control__ - pre_control_mean)
    method <- "difference_in_differences"
  }

  pre_pred <- pred_all[w$date__ >= pre_start & w$date__ <= pre_end]
  post_pred <- pred_all[w$date__ >= post_start & w$date__ <= post_end]
  pre_resid <- qgt_num(pre[[treat_col]]) - pre_pred
  post_resid <- qgt_num(post[[treat_col]]) - post_pred
  pre_complete <- is.finite(pre_resid)
  post_complete <- is.finite(post_resid)
  if (sum(pre_complete) < 2L || !sum(post_complete)) return(out_empty)
  pre_rmse <- sqrt(mean(pre_resid[pre_complete]^2, na.rm = TRUE))
  pre_sd <- qgt_safe_sd(pre[[treat_col]][pre_complete], floor = 1e-8)
  pre_fit_score <- 1 - qgt_clip(pre_rmse / pre_sd, 0, 1)
  scaled_l2_imbalance <- sqrt(sum(pre_resid[pre_complete]^2, na.rm = TRUE)) /
    pmax(sqrt(sum(qgt_num(pre[[treat_col]])[pre_complete]^2, na.rm = TRUE)), 1e-8)
  lift <- sum(post_resid[post_complete], na.rm = TRUE)
  lift_se <- qgt_safe_sd(pre_resid[pre_complete], floor = 1e-8) * sqrt(sum(post_complete))
  lift_z <- if (is.finite(lift_se) && lift_se > 1e-8) lift / lift_se else NA_real_
  list(
    success = TRUE,
    method = method,
    pred = pred_all,
    lift = lift,
    lift_se = lift_se,
    lift_z = lift_z,
    pre_fit_score = pre_fit_score,
    scaled_l2_imbalance = scaled_l2_imbalance,
    complete_pre_n = sum(pre_complete),
    complete_post_n = sum(post_complete)
  )
}
qgt_parse_variable_map <- function(variable_map = NULL, media_cols = character()) {
  if (!is.null(variable_map)) {
    vm <- as.data.table(copy(variable_map))
    if (!"variable" %in% names(vm)) stop("variable_map must contain variable.")
    if (!"modeled_x_col" %in% names(vm)) vm[, modeled_x_col := variable]
    if (!"spend_col" %in% names(vm)) vm[, spend_col := modeled_x_col]
    vm[, variable := as.character(variable)]
    vm[, modeled_x_col := as.character(modeled_x_col)]
    vm[, spend_col := as.character(spend_col)]
    vm[is.na(variable) | !nzchar(trimws(variable)), variable := NA_character_]
    if (any(is.na(vm$variable))) stop("variable_map contains blank/NA variable names.")
    dup_vars <- unique(vm$variable[duplicated(vm$variable)])
    if (length(dup_vars)) stop("variable_map contains duplicate variable keys: ", paste(dup_vars, collapse = ", "))
    vm[is.na(modeled_x_col) | !nzchar(trimws(modeled_x_col)), modeled_x_col := variable]
    vm[is.na(spend_col) | !nzchar(trimws(spend_col)), spend_col := modeled_x_col]
    return(vm[])
  }
  if (!length(media_cols)) stop("Provide variable_map or media_cols.")
  data.table(variable = media_cols, modeled_x_col = media_cols, spend_col = media_cols)
}
qgt_split_rollup_path <- function(path) {
  if (length(path) < 1L || is.na(path[1]) || !nzchar(as.character(path[1]))) return(character())
  nodes <- trimws(strsplit(as.character(path[1]), "\\s*(>|/)\\s*", perl = TRUE)[[1]])
  nodes[nzchar(nodes)]
}
qgt_rollup_lookup <- function(vm) {
  if (is.null(vm) || !nrow(vm)) {
    return(data.table(
      variable = character(),
      channel = character(),
      rollup_path = character(),
      rollup_root = character(),
      rollup_parent = character(),
      rollup_leaf = character()
    ))
  }
  out <- data.table(variable = as.character(vm$variable))
  out[, channel := if ("channel" %in% names(vm)) as.character(vm$channel) else variable]
  out[is.na(channel) | !nzchar(trimws(channel)), channel := variable]
  out[, rollup_path := if ("rollup_path" %in% names(vm)) as.character(vm$rollup_path) else channel]
  out[is.na(rollup_path) | !nzchar(trimws(rollup_path)), rollup_path := channel]
  parts <- lapply(out$rollup_path, qgt_split_rollup_path)
  out[, rollup_root := vapply(parts, function(x) if (length(x)) x[1] else NA_character_, character(1))]
  out[, rollup_parent := vapply(parts, function(x) if (length(x) >= 2L) x[length(x) - 1L] else NA_character_, character(1))]
  out[, rollup_leaf := vapply(parts, function(x) if (length(x)) x[length(x)] else NA_character_, character(1))]
  unique(out, by = "variable")[]
}
qgt_attach_rollup_metadata <- function(x, lookup, var_col = "variable") {
  out <- as.data.table(copy(x))
  roll_cols <- c("channel", "rollup_path", "rollup_root", "rollup_parent", "rollup_leaf")
  if (!var_col %in% names(out)) return(out[])
  if (is.null(lookup) || !nrow(lookup)) {
    for (cc in roll_cols) if (!cc %in% names(out)) out[, (cc) := NA_character_]
    return(out[])
  }
  lk <- unique(copy(lookup), by = "variable")
  out[, qgt_order__ := .I]
  out <- merge(out, lk, by.x = var_col, by.y = "variable", all.x = TRUE, sort = FALSE)
  data.table::setorder(out, qgt_order__)
  out[, qgt_order__ := NULL]
  out[]
}
qgt_build_rollup_evidence_summary <- function(event_results) {
  if (is.null(event_results) || !nrow(event_results) || !"rollup_path" %in% names(event_results)) {
    return(data.table())
  }
  dt <- copy(event_results)
  dt <- dt[!is.na(rollup_path) & nzchar(as.character(rollup_path))]
  if (!nrow(dt)) return(data.table())
  if (!"rollup_root" %in% names(dt)) dt[, rollup_root := NA_character_]
  tmp <- copy(dt)
  tmp[, variable := as.character(rollup_path)]
  out <- qgt_build_evidence_summary(tmp, "variable")
  if (!nrow(out)) return(data.table())
  data.table::setnames(out, "variable", "rollup_path")
  root_map <- unique(dt[, .(rollup_path, rollup_root)])
  out[root_map, rollup_root := i.rollup_root, on = "rollup_path"]
  data.table::setcolorder(out, c("summary_scope", "rollup_root", "rollup_path", setdiff(names(out), c("summary_scope", "rollup_root", "rollup_path"))))
  out[]
}
qgt_assign_raw_spend_cols <- function(dt, vm) {
  out_vm <- copy(vm)
  out_vm[, raw_spend_col__ := sprintf("..qgt_raw_spend_%03d", .I)]
  for (i in seq_len(nrow(out_vm))) {
    raw_col <- out_vm$raw_spend_col__[i]
    while (raw_col %in% names(dt)) raw_col <- paste0(raw_col, "_")
    out_vm$raw_spend_col__[i] <- raw_col
    dt[, (raw_col) := qgt_num(get(out_vm$spend_col[i]))]
  }
  out_vm[]
}
qgt_assign_raw_media_cols <- function(dt, vm) {
  out_vm <- copy(vm)
  out_vm[, raw_media_col__ := sprintf("..qgt_raw_media_%03d", .I)]
  for (i in seq_len(nrow(out_vm))) {
    raw_col <- out_vm$raw_media_col__[i]
    while (raw_col %in% names(dt)) raw_col <- paste0(raw_col, "_")
    out_vm$raw_media_col__[i] <- raw_col
    dt[, (raw_col) := qgt_num(get(out_vm$modeled_x_col[i]))]
  }
  out_vm[]
}
