# 021-quasi_geo-events.R
# Generated by behavior-preserving split of quasi_geo_test.R.

qgt_event_scan_one <- function(dt,
                               date_col,
                               geo_col,
                               variable,
                               media_col,
                               pre_weeks,
                               post_weeks,
                               min_abs_change,
                               min_pct_change,
                               min_robust_z,
                               min_volume,
                               media_cutoff_pct,
                               rolling_window,
                               period_days = 7L) {
  d <- copy(dt)
  period_days <- as.integer(period_days)[1]
  if (!is.finite(period_days) || period_days <= 0L) stop("period_days must be a positive integer.")
  setorderv(d, c(geo_col, date_col))
  d[, x__ := pmax(qgt_num(get(media_col)), 0)]
  primary_materiality <- max(min_volume, 0.05 * qgt_positive_scale(d$x__, floor = min_volume))
  primary_near_zero <- max(1e-8, min_volume * media_cutoff_pct)
  effective_min_abs_change <- max(min_abs_change, primary_materiality)
  d[, pre_mean__ := frollmean(shift(x__, 1L), n = rolling_window, align = "right", na.rm = TRUE), by = geo_col]
  d[, pre_med__ := frollapply(shift(x__, 1L), N = rolling_window, FUN = stats::median, align = "right", na.rm = TRUE), by = geo_col]
  d[, pre_mad__ := frollapply(shift(x__, 1L), N = rolling_window, FUN = stats::mad, align = "right", na.rm = TRUE), by = geo_col]
  d[, post_mean__ := frollmean(x__, n = post_weeks, align = "left", na.rm = TRUE), by = geo_col]
  d[, post_min__ := frollapply(x__, N = post_weeks, FUN = function(z) if (all(is.na(z))) NA_real_ else min(z, na.rm = TRUE), align = "left"), by = geo_col]
  d[, post_max__ := frollapply(x__, N = post_weeks, FUN = function(z) if (all(is.na(z))) NA_real_ else max(z, na.rm = TRUE), align = "left"), by = geo_col]
  d[, signed_change__ := post_mean__ - pre_mean__]
  d[, change_abs__ := abs(signed_change__)]
  d[, pct_change__ := fifelse(is.finite(pre_mean__) & pre_mean__ > 1e-8, signed_change__ / pre_mean__, NA_real_)]
  d[, pct_change_abs__ := abs(pct_change__)]
  d[, robust_z__ := fifelse(is.finite(pre_mad__) & pre_mad__ > 1e-8, (post_mean__ - pre_med__) / pre_mad__, NA_real_)]
  d[, robust_z_abs__ := abs(robust_z__)]
  d[, turn_on_flag__ := is.finite(pre_mean__) & pre_mean__ <= primary_near_zero &
      is.finite(post_mean__) & post_mean__ >= primary_materiality &
      change_abs__ >= effective_min_abs_change]
  d[, turn_off_flag__ := is.finite(pre_mean__) & pre_mean__ >= primary_materiality &
      is.finite(post_mean__) & post_mean__ <= primary_near_zero &
      change_abs__ >= effective_min_abs_change]
  d[, post_pos_hit__ := is.finite(pre_mean__) & pre_mean__ > 1e-8 &
      is.finite(post_max__) & ((post_max__ - pre_mean__) / pre_mean__) >= min_pct_change]
  d[, post_neg_hit__ := is.finite(pre_mean__) & pre_mean__ > 1e-8 &
      is.finite(post_min__) & ((post_min__ - pre_mean__) / pre_mean__) <= -min_pct_change]
  d[, media_cutoff_flag__ := is.finite(pre_mean__) & pre_mean__ >= primary_materiality &
      is.finite(post_mean__) & post_mean__ <= pmax(min_volume, pre_mean__ * media_cutoff_pct)]
  d[, ramp_direction__ := data.table::fcase(
    turn_on_flag__, "up_ramp",
    turn_off_flag__, "down_ramp",
    post_pos_hit__ & post_neg_hit__, "mixed",
    signed_change__ > 0, "up_ramp",
    signed_change__ < 0, "down_ramp",
    default = "none"
  )]
  d[, event_type__ := data.table::fcase(
    turn_on_flag__, "turn_on",
    turn_off_flag__ | media_cutoff_flag__, "turn_off",
    default = ramp_direction__
  )]
  d[, event_flag__ := is.finite(signed_change__) &
      pmax(pre_mean__, post_mean__, na.rm = TRUE) >= primary_materiality &
      (
        turn_on_flag__ |
          turn_off_flag__ |
          media_cutoff_flag__ |
          (
            change_abs__ >= effective_min_abs_change &
              ((is.finite(pct_change_abs__) & pct_change_abs__ >= min_pct_change) | turn_on_flag__ | turn_off_flag__) &
              (is.na(robust_z_abs__) | robust_z_abs__ >= min_robust_z)
          )
      )]
  ev <- d[event_flag__ == TRUE, .(
    variable = variable,
    geo = get(geo_col),
    event_start = get(date_col),
    event_end = get(date_col) + period_days * (post_weeks - 1L),
    pre_start = get(date_col) - period_days * pre_weeks,
    pre_end = get(date_col) - period_days,
    post_start = get(date_col),
    post_end = get(date_col) + period_days * (post_weeks - 1L),
    starting_support = pre_mean__,
    event_media = post_mean__,
    signed_treatment_intensity = signed_change__,
    abs_change = change_abs__,
    change_abs = change_abs__,
    pct_change = pct_change__,
    pct_change_abs = pct_change_abs__,
    robust_z = robust_z__,
    ramp_direction = ramp_direction__,
    event_type = event_type__,
    media_cutoff_flag = media_cutoff_flag__
  )]
  ev[, event_id := paste(variable, geo, event_start, ramp_direction, sep = "__")]
  ev[]
}
qgt_empty_candidate_events <- function() {
  data.table(
    variable = character(),
    geo = character(),
    event_start = as.Date(character()),
    event_end = as.Date(character()),
    pre_start = as.Date(character()),
    pre_end = as.Date(character()),
    post_start = as.Date(character()),
    post_end = as.Date(character()),
    starting_support = numeric(),
    event_media = numeric(),
    signed_treatment_intensity = numeric(),
    abs_change = numeric(),
    change_abs = numeric(),
    pct_change = numeric(),
    pct_change_abs = numeric(),
    robust_z = numeric(),
    ramp_direction = character(),
    event_type = character(),
    media_cutoff_flag = logical(),
    event_id = character()
  )
}
qgt_event_not_estimable <- function(event,
                                    reason,
                                    method = "not_estimable") {
  e <- event[1]
  data.table(
    event_id = e$event_id,
    variable = e$variable,
    geo = as.character(e$geo),
    event_start = e$event_start,
    event_end = e$event_end,
    starting_support = e$starting_support,
    event_media = qgt_event_value(e, "event_media", NA_real_),
    signed_treatment_intensity = qgt_event_value(e, "signed_treatment_intensity", qgt_event_value(e, "abs_change", NA_real_)),
    abs_change = qgt_event_value(e, "abs_change", abs(qgt_event_value(e, "signed_treatment_intensity", NA_real_))),
    change_abs = qgt_event_value(e, "change_abs", qgt_event_value(e, "abs_change", NA_real_)),
    pct_change = e$pct_change,
    pct_change_abs = qgt_event_value(e, "pct_change_abs", abs(e$pct_change)),
    robust_z = e$robust_z,
    ramp_direction = qgt_event_value(e, "ramp_direction", qgt_direction_from_signed_change(qgt_event_value(e, "signed_treatment_intensity", NA_real_))),
    event_type = qgt_event_value(e, "event_type", qgt_direction_from_signed_change(qgt_event_value(e, "signed_treatment_intensity", NA_real_))),
    media_cutoff_flag = qgt_event_value(e, "media_cutoff_flag", FALSE),
    donor_n = 0L,
    donor_weight_max = NA_real_,
    donor_weight_hhi = NA_real_,
    donor_effective_n = NA_real_,
    donor_dominant_flag = NA,
    scaled_l2_imbalance = NA_real_,
    pre_fit_score = NA_real_,
    recent_pre_fit_score = NA_real_,
    lookback_sensitivity_score = NA_real_,
    contamination_score = NA_real_,
    signal_score = NA_real_,
    direction_consistency_score = NA_real_,
    power_score = NA_real_,
    evidence_score = 0,
    quality_score = 0,
    evidence_tier = "not_estimable",
    diagnostic_reason = reason,
    placebo_lift = NA_real_,
    placebo_lift_abs_ratio = NA_real_,
    donor_placebo_p_value = NA_real_,
    donor_placebo_strength = NA_real_,
    donor_placebo_lift_median = NA_real_,
    donor_placebo_lift_max_abs = NA_real_,
    time_placebo_n = NA_integer_,
    time_placebo_p_value = NA_real_,
    time_placebo_strength = NA_real_,
    time_placebo_lift_median = NA_real_,
    time_placebo_lift_max_abs = NA_real_,
    time_placebo_false_positive_rate = NA_real_,
    placebo_bh_q_value = NA_real_,
    multiple_testing_warning = NA_character_,
    leave_one_donor_out_lift_sd = NA_real_,
    leave_one_donor_out_lift_max_abs_delta = NA_real_,
    leave_one_donor_out_stability_score = NA_real_,
    selected_counterfactual_method = method,
    ridge_lambda = NA_real_,
    ridge_lambda_cv_rmse = NA_real_,
    ridge_lambda_selection_method = NA_character_,
    ridge_lambda_cv_fold_n = NA_integer_,
    ridge_retained_donor_n = NA_integer_,
    ridge_dropped_zero_variance_donor_n = NA_integer_,
    counterfactual_fallback_reason = reason,
    synthetic_control_pre_fit_score = NA_real_,
    tbr_pre_fit_score = NA_real_,
    tbr_incremental_outcome = NA_real_,
    tbr_incremental_outcome_raw = NA_real_,
    tbr_lift_z = NA_real_,
    did_incremental_outcome = NA_real_,
    did_incremental_outcome_raw = NA_real_,
    lift_se = NA_real_,
    lift_z = NA_real_,
    incremental_outcome_ci_low = NA_real_,
    incremental_outcome_ci_high = NA_real_,
    incremental_outcome = NA_real_,
    incremental_outcome_raw = NA_real_,
    incremental_media = NA_real_,
    incremental_spend = NA_real_,
    contribution = NA_real_,
    contribution_raw = NA_real_,
    contribution_pct = NA_real_,
    marginal_response = NA_real_,
    cost_per_incremental_outcome = NA_real_,
    roi_like = NA_real_,
    marginal_response_ci_low = NA_real_,
    marginal_response_ci_high = NA_real_,
    mde_lift_abs = NA_real_,
    mde_lift_pct = NA_real_,
    observed_to_mde_ratio = NA_real_,
    lift_pct = NA_real_,
    effect_direction = "inconclusive",
    co_moving_channel_n = NA_integer_,
    co_moving_media_summary = "",
    overlap_event_n = NA_integer_,
    same_geo_overlap_event_n = NA_integer_,
    overlap_contamination_score = NA_real_,
    synth_intercept = NA_real_,
    raw_synth_intercept = NA_real_,
    bundle_incremental_support = NA_real_,
    bundle_incremental_outcome_raw = NA_real_,
    bundle_incremental_spend_raw = NA_real_,
    bundle_return_prior_raw = NA_real_,
    bundle_cost_per_outcome_raw = NA_real_,
    counterfactual_method = method,
    donor_geos = "",
    donor_weights = ""
  )
}
qgt_empty_event_estimates <- function() {
  template <- data.table(
    event_id = "",
    variable = "",
    geo = "",
    event_start = as.Date("1970-01-01"),
    event_end = as.Date("1970-01-01"),
    starting_support = NA_real_,
    event_media = NA_real_,
    signed_treatment_intensity = NA_real_,
    abs_change = NA_real_,
    change_abs = NA_real_,
    pct_change = NA_real_,
    pct_change_abs = NA_real_,
    robust_z = NA_real_,
    ramp_direction = "none",
    event_type = "none",
    media_cutoff_flag = FALSE
  )
  qgt_event_not_estimable(template, reason = "no_candidate_events")[0]
}
qgt_empty_dose_response_summary <- function() {
  data.table(
    variable = character(),
    event_n = integer(),
    strong_event_n = integer(),
    moderate_or_better_event_n = integer(),
    mean_evidence_score = numeric(),
    mean_quality_score = numeric(),
    mean_contamination_score = numeric(),
    median_abs_lift_z = numeric(),
    median_placebo_lift_abs_ratio = numeric(),
    positive_effect_event_n = integer(),
    median_incremental_outcome = numeric(),
    median_incremental_media = numeric(),
    median_marginal_response = numeric(),
    low = numeric(),
    medium = numeric(),
    high = numeric(),
    high_to_low_response_ratio = numeric(),
    medium_to_low_response_ratio = numeric(),
    curve_prior_direction = character()
  )
}
qgt_empty_prior_recommendations <- function() {
  data.table(
    variable = character(),
    event_n = integer(),
    usable_positive_event_n = integer(),
    mean_evidence_score = numeric(),
    max_evidence_score = numeric(),
    contribution_prior_mean = numeric(),
    contribution_pct_prior_mean = numeric(),
    coef_prior_mean = numeric(),
    coef_prior_sd = numeric(),
    coef_prior_precision = numeric(),
    cost_per_outcome_prior_mean = numeric(),
    roi_like_prior_mean = numeric(),
    evidence_direction = character(),
    negative_or_confounded_event_n = integer(),
    co_moving_event_n = integer()
  )
}
qgt_empty_bundle_prior_recommendations <- function() {
  data.table(
    bundle_name = character(),
    moved_channels = character(),
    event_n = integer(),
    usable_bundle_event_n = integer(),
    usable_bundle_prior = logical(),
    mean_evidence_score = numeric(),
    max_evidence_score = numeric(),
    bundle_contribution_prior_mean = numeric(),
    bundle_spend_prior_mean = numeric(),
    bundle_return_prior_mean = numeric(),
    bundle_cost_per_outcome_prior_mean = numeric(),
    diagnostic_bundle_return_read = numeric(),
    diagnostic_bundle_cost_per_outcome_read = numeric(),
    evidence_direction = character()
  )
}
qgt_empty_evidence_summary <- function() {
  data.table(
    summary_scope = character(),
    variable = character(),
    estimand_level = character(),
    bundle_name = character(),
    event_n = integer(),
    estimable_event_n = integer(),
    calibration_event_n = integer(),
    directional_prior_event_n = integer(),
    diagnostic_event_n = integer(),
    ignored_event_n = integer(),
    channel_specific_usable_n = integer(),
    bundle_usable_n = integer(),
    max_evidence_score = numeric(),
    mean_evidence_score = numeric(),
    best_recommended_use = character(),
    best_confidence_band = character(),
    median_marginal_response = numeric(),
    median_roi_like = numeric(),
    median_cost_per_outcome = numeric(),
    top_downgrade_reasons = character(),
    top_blocker_reasons = character(),
    recommended_analyst_action = character()
  )
}
