# 024-quasi_geo-priors.R
# Generated by behavior-preserving split of quasi_geo_test.R.

qgt_summarize_dose_response <- function(event_results) {
  if (is.null(event_results) || !nrow(event_results)) return(qgt_empty_dose_response_summary())
  out <- copy(event_results)
  if (!"channel_specific_usable" %in% names(out)) out[, channel_specific_usable := TRUE]
  event_rollup <- out[, .(
    event_n = .N,
    strong_event_n = sum(evidence_tier == "strong_quasi_geo", na.rm = TRUE),
    moderate_or_better_event_n = sum(evidence_tier %in% c("strong_quasi_geo", "moderate_quasi_geo"), na.rm = TRUE),
    mean_evidence_score = mean(evidence_score, na.rm = TRUE),
    mean_quality_score = mean(quality_score, na.rm = TRUE),
    mean_contamination_score = mean(contamination_score, na.rm = TRUE),
    median_abs_lift_z = stats::median(abs(lift_z), na.rm = TRUE),
    median_placebo_lift_abs_ratio = stats::median(placebo_lift_abs_ratio, na.rm = TRUE),
    positive_effect_event_n = sum(effect_direction == "positive_media_effect", na.rm = TRUE),
    median_incremental_outcome = stats::median(incremental_outcome, na.rm = TRUE),
    median_incremental_media = stats::median(incremental_media, na.rm = TRUE),
    median_marginal_response = stats::median(marginal_response, na.rm = TRUE)
  ), by = variable]
  if (!any(is.finite(out$marginal_response))) {
    event_rollup[, `:=`(
      low = NA_real_,
      medium = NA_real_,
      high = NA_real_,
      high_to_low_response_ratio = NA_real_,
      medium_to_low_response_ratio = NA_real_,
      curve_prior_direction = "inconclusive"
    )]
    return(event_rollup[])
  }
  out_fit <- out[is.finite(marginal_response) & effect_direction == "positive_media_effect" & channel_specific_usable %in% TRUE]
  if (!nrow(out_fit)) {
    event_rollup[, `:=`(
      low = NA_real_,
      medium = NA_real_,
      high = NA_real_,
      high_to_low_response_ratio = NA_real_,
      medium_to_low_response_ratio = NA_real_,
      curve_prior_direction = "inconclusive_negative_or_confounded"
    )]
    return(event_rollup[])
  }
  out_fit[, support_bin := data.table::fcase(
    starting_support <= stats::quantile(starting_support, 1 / 3, na.rm = TRUE), "low",
    starting_support >= stats::quantile(starting_support, 2 / 3, na.rm = TRUE), "high",
    default = "medium"
  ), by = variable]
  bin <- out_fit[, .(
    event_n = .N,
    weighted_marginal_response = stats::weighted.mean(marginal_response, w = pmax(evidence_score, 5), na.rm = TRUE),
    median_marginal_response = stats::median(marginal_response, na.rm = TRUE),
    mean_quality_score = mean(quality_score, na.rm = TRUE),
    mean_evidence_score = mean(evidence_score, na.rm = TRUE),
    strong_event_n = sum(evidence_tier == "strong_quasi_geo", na.rm = TRUE)
  ), by = .(variable, support_bin)]
  wide <- dcast(bin, variable ~ support_bin, value.var = "weighted_marginal_response")
  for (cc in c("low", "medium", "high")) if (!cc %in% names(wide)) wide[, (cc) := NA_real_]
  wide[, high_to_low_response_ratio := fifelse(is.finite(low) & abs(low) > 1e-8, high / low, NA_real_)]
  wide[, medium_to_low_response_ratio := fifelse(is.finite(low) & abs(low) > 1e-8, medium / low, NA_real_)]
  wide[, curve_prior_direction := data.table::fcase(
    is.finite(high_to_low_response_ratio) & high_to_low_response_ratio < 0.45, "faster_saturation",
    is.finite(high_to_low_response_ratio) & high_to_low_response_ratio < 0.75, "moderate_saturation",
    is.finite(high_to_low_response_ratio) & high_to_low_response_ratio >= 0.75, "slow_or_flat_saturation",
    default = "inconclusive"
  )]
  wide[event_rollup, on = "variable"][]
}
qgt_build_prior_recommendations <- function(event_results) {
  if (is.null(event_results) || !nrow(event_results)) return(qgt_empty_prior_recommendations())
  dt <- copy(event_results)
  dt <- dt[is.finite(marginal_response) | is.finite(incremental_outcome)]
  if (!nrow(dt)) return(qgt_empty_prior_recommendations())
  if (!"channel_specific_usable" %in% names(dt)) dt[, channel_specific_usable := FALSE]
  dt[, prior_weight := pmax(evidence_score, 1) / 100]
  dt[, positive_weight := fifelse(channel_specific_usable %in% TRUE & effect_direction == "positive_media_effect" & is.finite(marginal_response), prior_weight, 0)]
  out <- dt[, {
    pos <- .SD[positive_weight > 0 & is.finite(marginal_response)]
    mean_score <- mean(evidence_score, na.rm = TRUE)
    coef_mean <- if (nrow(pos)) stats::weighted.mean(pos$marginal_response, w = pos$positive_weight, na.rm = TRUE) else NA_real_
    coef_sd <- if (nrow(pos) >= 2L) {
      sqrt(stats::weighted.mean((pos$marginal_response - coef_mean) ^ 2, w = pos$positive_weight, na.rm = TRUE))
    } else {
      NA_real_
    }
    list(
      event_n = .N,
      usable_positive_event_n = nrow(pos),
      mean_evidence_score = mean_score,
      max_evidence_score = max(evidence_score, na.rm = TRUE),
      contribution_prior_mean = if (nrow(pos) && any(is.finite(pos$incremental_outcome))) stats::weighted.mean(pos$incremental_outcome, w = pos$positive_weight, na.rm = TRUE) else NA_real_,
      contribution_pct_prior_mean = if (nrow(pos) && any(is.finite(pos$contribution_pct))) stats::weighted.mean(pos$contribution_pct, w = pos$positive_weight, na.rm = TRUE) else NA_real_,
      coef_prior_mean = coef_mean,
      coef_prior_sd = coef_sd,
      coef_prior_precision = if (is.finite(coef_sd) && coef_sd > 1e-8) 1 / (coef_sd ^ 2) else NA_real_,
      cost_per_outcome_prior_mean = if (nrow(pos) && any(is.finite(pos$cost_per_incremental_outcome))) stats::weighted.mean(pos$cost_per_incremental_outcome, w = pos$positive_weight, na.rm = TRUE) else NA_real_,
      roi_like_prior_mean = if (nrow(pos) && any(is.finite(pos$roi_like))) stats::weighted.mean(pos$roi_like, w = pos$positive_weight, na.rm = TRUE) else NA_real_,
      evidence_direction = data.table::fcase(
        nrow(pos) >= 2L && mean_score >= 60, "usable_as_coef_prior",
        nrow(pos) >= 1L && mean_score >= 35, "directional_prior_only",
        default = "diagnostic_only"
      ),
      negative_or_confounded_event_n = sum(effect_direction == "negative_or_confounded_media_effect", na.rm = TRUE),
      co_moving_event_n = sum(co_moving_channel_n > 0, na.rm = TRUE)
    )
  }, by = variable]
  out[]
}
qgt_build_bundle_prior_recommendations <- function(event_results) {
  if (is.null(event_results) || !nrow(event_results)) return(qgt_empty_bundle_prior_recommendations())
  dt <- copy(event_results)
  if (!"bundle_usable" %in% names(dt)) dt[, bundle_usable := FALSE]
  dt <- dt[estimand_level == "bundle" & (is.finite(bundle_return_prior) | is.finite(bundle_cost_per_outcome) | is.finite(bundle_incremental_outcome))]
  if (!nrow(dt)) return(qgt_empty_bundle_prior_recommendations())
  data.table::setorder(dt, bundle_name, geo, event_start, event_end, -evidence_score)
  dt <- dt[, .SD[1], by = .(bundle_name, geo, event_start, event_end)]
  dt[, prior_weight := pmax(evidence_score, 1) / 100]
  out <- dt[, {
    usable <- .SD[bundle_usable %in% TRUE]
    diagnostic <- .SD[!(bundle_usable %in% TRUE)]
    usable_w <- pmax(usable$prior_weight, 0.01)
    diag_w <- pmax(diagnostic$prior_weight, 0.01)
    list(
      moved_channels = paste(unique(moved_channels), collapse = "||"),
      event_n = .N,
      usable_bundle_event_n = nrow(usable),
      usable_bundle_prior = nrow(usable) > 0L,
      mean_evidence_score = mean(evidence_score, na.rm = TRUE),
      max_evidence_score = max(evidence_score, na.rm = TRUE),
      bundle_contribution_prior_mean = if (nrow(usable) && any(is.finite(usable$bundle_incremental_outcome))) stats::weighted.mean(usable$bundle_incremental_outcome, w = usable_w, na.rm = TRUE) else NA_real_,
      bundle_spend_prior_mean = if (nrow(usable) && any(is.finite(usable$bundle_incremental_spend))) stats::weighted.mean(usable$bundle_incremental_spend, w = usable_w, na.rm = TRUE) else NA_real_,
      bundle_return_prior_mean = if (nrow(usable) && any(is.finite(usable$bundle_return_prior))) stats::weighted.mean(usable$bundle_return_prior, w = usable_w, na.rm = TRUE) else NA_real_,
      bundle_cost_per_outcome_prior_mean = if (nrow(usable) && any(is.finite(usable$bundle_cost_per_outcome))) stats::weighted.mean(usable$bundle_cost_per_outcome, w = usable_w, na.rm = TRUE) else NA_real_,
      diagnostic_bundle_return_read = if (nrow(diagnostic) && any(is.finite(diagnostic$bundle_return_prior))) stats::weighted.mean(diagnostic$bundle_return_prior, w = diag_w, na.rm = TRUE) else NA_real_,
      diagnostic_bundle_cost_per_outcome_read = if (nrow(diagnostic) && any(is.finite(diagnostic$bundle_cost_per_outcome))) stats::weighted.mean(diagnostic$bundle_cost_per_outcome, w = diag_w, na.rm = TRUE) else NA_real_,
      evidence_direction = data.table::fcase(
        nrow(usable) >= 2L && mean(evidence_score, na.rm = TRUE) >= 60, "usable_as_bundle_prior",
        nrow(usable) >= 1L, "directional_bundle_prior",
        default = "diagnostic_only"
      )
    )
  }, by = bundle_name]
  out[]
}
qgt_empty_stan_prior_handoff <- function() {
  data.table(
    variable = character(),
    coef = numeric(),
    coef_precision = numeric(),
    coef_bound = character(),
    quasi_geo_prior_source = character(),
    quasi_geo_evidence_direction = character(),
    quasi_geo_recommended_use = character(),
    quasi_geo_max_evidence_score = numeric(),
    quasi_geo_event_n = integer(),
    quasi_geo_usable_event_n = integer(),
    quasi_geo_cost_per_outcome_prior = numeric(),
    quasi_geo_roi_like_prior = numeric()
  )
}
qgt_build_stan_prior_handoff <- function(quasi_geo_result,
                                         min_evidence_score = 35,
                                         max_coef_precision = 25,
                                         min_coef_precision = 2,
                                         single_event_precision = 4) {
  rec <- if (is.list(quasi_geo_result) && !is.null(quasi_geo_result$prior_recommendations)) {
    as.data.table(copy(quasi_geo_result$prior_recommendations))
  } else {
    as.data.table(copy(quasi_geo_result))
  }
  if (!nrow(rec)) return(qgt_empty_stan_prior_handoff())
  required <- c("variable", "coef_prior_mean", "coef_prior_precision", "evidence_direction",
                "max_evidence_score", "event_n", "usable_positive_event_n")
  missing <- setdiff(required, names(rec))
  if (length(missing)) stop("quasi_geo_result prior recommendations are missing required columns: ", paste(missing, collapse = ", "))
  for (cc in c("cost_per_outcome_prior_mean", "roi_like_prior_mean")) if (!cc %in% names(rec)) rec[, (cc) := NA_real_]
  rec <- rec[
    usable_positive_event_n > 0L &
      is.finite(coef_prior_mean) &
      coef_prior_mean > 0 &
      is.finite(max_evidence_score) &
      max_evidence_score >= min_evidence_score &
      evidence_direction %in% c("usable_as_coef_prior", "directional_prior_only")
  ]
  if (!nrow(rec)) return(qgt_empty_stan_prior_handoff())
  rec[, reliability := pmin(1, pmax(0, max_evidence_score / 100))]
  rec[, coef_precision_out := fifelse(
    is.finite(coef_prior_precision) & coef_prior_precision > 0,
    coef_prior_precision,
    fifelse(evidence_direction == "usable_as_coef_prior", single_event_precision * 2, single_event_precision)
  )]
  rec[, coef_precision_out := pmin(max_coef_precision, pmax(min_coef_precision, coef_precision_out * pmax(reliability, 0.25)))]
  rec[, recommended_use_out := fifelse(evidence_direction == "usable_as_coef_prior" & max_evidence_score >= 80,
                                       "calibration_or_tight_directional_prior",
                                       "directional_prior")]
  rec[, .(
    variable = as.character(variable),
    coef = as.numeric(coef_prior_mean),
    coef_precision = as.numeric(coef_precision_out),
    coef_bound = "pos",
    quasi_geo_prior_source = "quasi_geo_channel_specific_marginal_response",
    quasi_geo_evidence_direction = as.character(evidence_direction),
    quasi_geo_recommended_use = as.character(recommended_use_out),
    quasi_geo_max_evidence_score = as.numeric(max_evidence_score),
    quasi_geo_event_n = as.integer(event_n),
    quasi_geo_usable_event_n = as.integer(usable_positive_event_n),
    quasi_geo_cost_per_outcome_prior = as.numeric(cost_per_outcome_prior_mean),
    quasi_geo_roi_like_prior = as.numeric(roi_like_prior_mean)
  )]
}
qgt_apply_stan_prior_handoff <- function(metadata_input,
                                         quasi_geo_handoff,
                                         overwrite_existing = FALSE) {
  md <- as.data.table(copy(metadata_input))
  handoff <- as.data.table(copy(quasi_geo_handoff))
  if (!nrow(handoff)) return(md[])
  if (!"variable" %in% names(md)) stop("metadata_input must include variable.")
  if (anyDuplicated(as.character(md$variable))) stop("metadata_input has duplicate variable keys.")
  if (anyDuplicated(as.character(handoff$variable))) stop("quasi_geo_handoff has duplicate variable keys.")
  for (cc in setdiff(names(handoff), names(md))) {
    md[, (cc) := handoff[[cc]][NA_integer_]]
  }
  md[handoff, on = "variable", `:=`(
    coef = fifelse(isTRUE(overwrite_existing) | !is.finite(suppressWarnings(as.numeric(coef))), i.coef, suppressWarnings(as.numeric(coef))),
    coef_precision = fifelse(isTRUE(overwrite_existing) | !is.finite(suppressWarnings(as.numeric(coef_precision))), i.coef_precision, suppressWarnings(as.numeric(coef_precision))),
    coef_bound = fifelse(isTRUE(overwrite_existing) | is.na(coef_bound) | !nzchar(as.character(coef_bound)), i.coef_bound, as.character(coef_bound)),
    quasi_geo_prior_source = i.quasi_geo_prior_source,
    quasi_geo_evidence_direction = i.quasi_geo_evidence_direction,
    quasi_geo_recommended_use = i.quasi_geo_recommended_use,
    quasi_geo_max_evidence_score = i.quasi_geo_max_evidence_score,
    quasi_geo_event_n = i.quasi_geo_event_n,
    quasi_geo_usable_event_n = i.quasi_geo_usable_event_n,
    quasi_geo_cost_per_outcome_prior = i.quasi_geo_cost_per_outcome_prior,
    quasi_geo_roi_like_prior = i.quasi_geo_roi_like_prior
  )]
  md[]
}
