# 024-quasi_geo-priors.R
# Generated by behavior-preserving split of quasi_geo_test.R.

qgt_empty_curve_evidence_points <- function() {
  data.table(
    variable = character(), event_id = character(), geo = character(),
    event_start = as.Date(character()), event_end = as.Date(character()),
    starting_support = numeric(), event_media = numeric(), support_midpoint = numeric(),
    marginal_response = numeric(), marginal_response_se = numeric(),
    marginal_response_ci_low = numeric(), marginal_response_ci_high = numeric(),
    evidence_score = numeric(), quality_score = numeric(), evidence_tier = character(),
    selected_counterfactual_method = character(), channel_specific_usable = logical(),
    curve_point_usable = logical(), curve_point_weight_raw = numeric(), curve_point_weight = numeric(),
    curve_point_exclusion_reason = character()
  )
}

qgt_build_curve_evidence_points <- function(event_results, min_evidence_score = 25) {
  if (is.null(event_results) || !nrow(event_results)) return(qgt_empty_curve_evidence_points())
  dt <- copy(as.data.table(event_results))
  required_defaults <- list(
    event_id = NA_character_, geo = NA_character_, event_start = as.Date(NA), event_end = as.Date(NA),
    event_media = NA_real_, marginal_response_ci_low = NA_real_, marginal_response_ci_high = NA_real_,
    evidence_score = 0, quality_score = 0, evidence_tier = "not_estimable",
    selected_counterfactual_method = NA_character_, channel_specific_usable = FALSE,
    effect_direction = "inconclusive"
  )
  for (nm in names(required_defaults)) if (!(nm %in% names(dt))) dt[, (nm) := required_defaults[[nm]]]
  dt[, support_midpoint := rowMeans(cbind(qgt_num(starting_support), qgt_num(event_media)), na.rm = TRUE)]
  dt[!is.finite(support_midpoint), support_midpoint := qgt_num(starting_support)]
  dt[, marginal_response_se := abs(qgt_num(marginal_response_ci_high) - qgt_num(marginal_response_ci_low)) / (2 * 1.96)]
  dt[!is.finite(marginal_response_se) | marginal_response_se <= 1e-12, marginal_response_se := NA_real_]
  dt[, curve_point_usable := channel_specific_usable %in% TRUE &
       effect_direction == "positive_media_effect" &
       is.finite(support_midpoint) & support_midpoint > 0 &
       is.finite(marginal_response) & marginal_response > 0 &
       is.finite(evidence_score) & evidence_score >= min_evidence_score]
  dt[, curve_point_exclusion_reason := data.table::fcase(
    channel_specific_usable %in% FALSE, "channel_not_separately_identified",
    effect_direction != "positive_media_effect", "nonpositive_or_confounded_effect",
    !is.finite(support_midpoint) | support_midpoint <= 0, "invalid_support_point",
    !is.finite(marginal_response) | marginal_response <= 0, "invalid_marginal_response",
    evidence_score < min_evidence_score, "evidence_score_below_curve_threshold",
    default = NA_character_
  )]
  dt[, curve_point_weight_raw := fifelse(
    curve_point_usable,
    (pmax(qgt_num(evidence_score), 1) / 100) * (pmax(qgt_num(quality_score), 1) / 100) /
      fifelse(is.finite(marginal_response_se), marginal_response_se^2, pmax(abs(marginal_response) * 0.50, 1e-8)^2),
    0
  )]
  dt[, curve_point_weight_raw := {
    positive <- curve_point_weight_raw[curve_point_weight_raw > 0 & is.finite(curve_point_weight_raw)]
    cap <- if (length(positive)) as.numeric(stats::quantile(positive, 0.90, na.rm = TRUE)) else 0
    if (is.finite(cap) && cap > 0) pmin(curve_point_weight_raw, cap) else curve_point_weight_raw
  }, by = variable]
  dt[, curve_point_weight := {
    den <- sum(curve_point_weight_raw, na.rm = TRUE)
    if (is.finite(den) && den > 0) curve_point_weight_raw / den else rep(0, .N)
  }, by = variable]
  keep <- names(qgt_empty_curve_evidence_points())
  dt[, ..keep][]
}

qgt_fit_conservative_curve_priors <- function(curve_evidence_points,
                                              default_anchor_saturation = 0.50,
                                              min_events = 3L,
                                              max_data_weight = 0.75) {
  pts <- copy(as.data.table(curve_evidence_points))
  if (!nrow(pts)) return(data.table())
  vars <- unique(as.character(pts$variable))
  fit_one <- function(z, allow_loo = TRUE) {
    z <- z[curve_point_usable %in% TRUE & is.finite(support_midpoint) & support_midpoint > 0 &
             is.finite(marginal_response) & marginal_response > 0]
    if (nrow(z) < 2L || uniqueN(round(z$support_midpoint, 8)) < 2L) return(NULL)
    w <- pmax(qgt_num(z$curve_point_weight), 1e-8)
    w <- w / sum(w)
    support_scale <- as.numeric(stats::weighted.mean(z$support_midpoint, w = w, na.rm = TRUE))
    if (!is.finite(support_scale) || support_scale <= 0) support_scale <- stats::median(z$support_midpoint)
    s <- z$support_midpoint / support_scale
    y <- z$marginal_response
    objective <- function(par) {
      amplitude <- exp(par[1])
      rate <- exp(par[2])
      pred <- amplitude * rate / (1 + rate * s)^2
      sum(w * (log(pmax(y, 1e-12)) - log(pmax(pred, 1e-12)))^2)
    }
    init_rate <- 1
    init_amp <- stats::weighted.mean(y, w = w) * (1 + init_rate)^2 / init_rate
    opt <- tryCatch(
      stats::optim(c(log(pmax(init_amp, 1e-8)), log(init_rate)), objective,
                   method = "L-BFGS-B", lower = c(-20, log(0.01)), upper = c(20, log(100))),
      error = function(e) NULL
    )
    if (is.null(opt) || opt$convergence != 0L) return(NULL)
    rate <- exp(opt$par[2])
    anchor <- rate / (1 + rate)
    list(anchor = anchor, rate = rate, support_scale = support_scale, loss = opt$value)
  }
  rbindlist(lapply(vars, function(v) {
    z <- pts[variable == v & curve_point_usable %in% TRUE]
    event_n <- nrow(z)
    support_level_n <- uniqueN(round(z$support_midpoint, 8))
    base <- fit_one(z)
    if (is.null(base) || event_n < as.integer(min_events) || support_level_n < 2L) {
      return(data.table(
        variable = v, usable_curve_event_n = event_n, distinct_support_level_n = support_level_n,
        curve_fit_status = "insufficient_independent_dose_evidence", curve_type = "hill",
        anchor_saturation_raw = NA_real_, anchor_saturation = default_anchor_saturation,
        anchor_saturation_sd = 0.25, anchor_saturation_precision = 16,
        dvalue = 1, dvalue_sd = 0.50, data_weight = 0,
        recommended_use = "diagnostic_only"
      ))
    }
    loo_anchor <- if (event_n >= 4L) vapply(seq_len(event_n), function(i) {
      f <- fit_one(z[-i])
      if (is.null(f)) NA_real_ else f$anchor
    }, numeric(1)) else numeric()
    loo_sd <- if (sum(is.finite(loo_anchor)) >= 2L) stats::sd(loo_anchor[is.finite(loo_anchor)]) else NA_real_
    support_span <- max(z$support_midpoint) / min(z$support_midpoint)
    score_component <- pmin(1, mean(z$evidence_score, na.rm = TRUE) / 80)
    event_component <- pmin(1, event_n / 6)
    span_component <- pmin(1, pmax(0, log(pmax(support_span, 1))) / log(3))
    stability_component <- if (is.finite(loo_sd)) pmax(0, 1 - loo_sd / 0.20) else 0.50
    data_weight <- pmin(max_data_weight, score_component * event_component * pmax(span_component, 0.15) * stability_component)
    anchor_final <- default_anchor_saturation + data_weight * (base$anchor - default_anchor_saturation)
    anchor_final <- pmin(0.90, pmax(0.10, anchor_final))
    anchor_sd <- pmax(0.08, if (is.finite(loo_sd)) loo_sd else 0, 0.25 * (1 - data_weight))
    data.table(
      variable = v,
      usable_curve_event_n = event_n,
      distinct_support_level_n = support_level_n,
      support_min = min(z$support_midpoint),
      support_max = max(z$support_midpoint),
      support_span_ratio = support_span,
      mean_evidence_score = mean(z$evidence_score, na.rm = TRUE),
      curve_fit_status = "conservative_hill_marginal_response_fit",
      curve_type = "hill",
      fitted_support_scale = base$support_scale,
      fitted_curve_rate_normalized = base$rate,
      fit_log_marginal_loss = base$loss,
      anchor_saturation_raw = base$anchor,
      anchor_saturation = anchor_final,
      anchor_saturation_sd = anchor_sd,
      anchor_saturation_precision = 1 / anchor_sd^2,
      leave_one_event_out_anchor_sd = loo_sd,
      dvalue = 1,
      dvalue_sd = 0.50,
      data_weight = data_weight,
      recommended_use = fifelse(data_weight >= 0.45, "directional_curve_prior", "weak_directional_curve_prior"),
      methodology_note = "Hill dvalue fixed at 1 for conservative identification; data update is shrunk toward 50% saturation at median active support."
    )
  }), use.names = TRUE, fill = TRUE)
}

qgt_summarize_dose_response <- function(event_results) {
  if (is.null(event_results) || !nrow(event_results)) return(qgt_empty_dose_response_summary())
  out <- copy(event_results)
  if (!"channel_specific_usable" %in% names(out)) out[, channel_specific_usable := TRUE]
  event_rollup <- out[, .(
    event_n = .N,
    strong_event_n = sum(evidence_tier == "strong_quasi_geo", na.rm = TRUE),
    moderate_or_better_event_n = sum(evidence_tier %in% c("strong_quasi_geo", "moderate_quasi_geo"), na.rm = TRUE),
    mean_evidence_score = mean(evidence_score, na.rm = TRUE),
    mean_quality_score = mean(quality_score, na.rm = TRUE),
    mean_contamination_score = mean(contamination_score, na.rm = TRUE),
    median_abs_lift_z = stats::median(abs(lift_z), na.rm = TRUE),
    median_placebo_lift_abs_ratio = stats::median(placebo_lift_abs_ratio, na.rm = TRUE),
    positive_effect_event_n = sum(effect_direction == "positive_media_effect", na.rm = TRUE),
    median_incremental_outcome = stats::median(incremental_outcome, na.rm = TRUE),
    median_incremental_media = stats::median(incremental_media, na.rm = TRUE),
    median_marginal_response = stats::median(marginal_response, na.rm = TRUE)
  ), by = variable]
  if (!any(is.finite(out$marginal_response))) {
    event_rollup[, `:=`(
      low = NA_real_,
      medium = NA_real_,
      high = NA_real_,
      high_to_low_response_ratio = NA_real_,
      medium_to_low_response_ratio = NA_real_,
      curve_prior_direction = "inconclusive"
    )]
    return(event_rollup[])
  }
  out_fit <- out[is.finite(marginal_response) & effect_direction == "positive_media_effect" & channel_specific_usable %in% TRUE]
  if (!nrow(out_fit)) {
    event_rollup[, `:=`(
      low = NA_real_,
      medium = NA_real_,
      high = NA_real_,
      high_to_low_response_ratio = NA_real_,
      medium_to_low_response_ratio = NA_real_,
      curve_prior_direction = "inconclusive_negative_or_confounded"
    )]
    return(event_rollup[])
  }
  out_fit[, support_bin := data.table::fcase(
    starting_support <= stats::quantile(starting_support, 1 / 3, na.rm = TRUE), "low",
    starting_support >= stats::quantile(starting_support, 2 / 3, na.rm = TRUE), "high",
    default = "medium"
  ), by = variable]
  bin <- out_fit[, .(
    event_n = .N,
    weighted_marginal_response = stats::weighted.mean(marginal_response, w = pmax(evidence_score, 5), na.rm = TRUE),
    median_marginal_response = stats::median(marginal_response, na.rm = TRUE),
    mean_quality_score = mean(quality_score, na.rm = TRUE),
    mean_evidence_score = mean(evidence_score, na.rm = TRUE),
    strong_event_n = sum(evidence_tier == "strong_quasi_geo", na.rm = TRUE)
  ), by = .(variable, support_bin)]
  wide <- dcast(bin, variable ~ support_bin, value.var = "weighted_marginal_response")
  for (cc in c("low", "medium", "high")) if (!cc %in% names(wide)) wide[, (cc) := NA_real_]
  wide[, high_to_low_response_ratio := fifelse(is.finite(low) & abs(low) > 1e-8, high / low, NA_real_)]
  wide[, medium_to_low_response_ratio := fifelse(is.finite(low) & abs(low) > 1e-8, medium / low, NA_real_)]
  wide[, curve_prior_direction := data.table::fcase(
    is.finite(high_to_low_response_ratio) & high_to_low_response_ratio < 0.45, "faster_saturation",
    is.finite(high_to_low_response_ratio) & high_to_low_response_ratio < 0.75, "moderate_saturation",
    is.finite(high_to_low_response_ratio) & high_to_low_response_ratio >= 0.75, "slow_or_flat_saturation",
    default = "inconclusive"
  )]
  wide[event_rollup, on = "variable"][]
}
qgt_build_prior_recommendations <- function(event_results) {
  if (is.null(event_results) || !nrow(event_results)) return(qgt_empty_prior_recommendations())
  dt <- copy(event_results)
  dt <- dt[is.finite(marginal_response) | is.finite(incremental_outcome)]
  if (!nrow(dt)) return(qgt_empty_prior_recommendations())
  if (!"channel_specific_usable" %in% names(dt)) dt[, channel_specific_usable := FALSE]
  dt[, prior_weight := pmax(evidence_score, 1) / 100]
  dt[, positive_weight := fifelse(channel_specific_usable %in% TRUE & effect_direction == "positive_media_effect" & is.finite(marginal_response), prior_weight, 0)]
  out <- dt[, {
    pos <- .SD[positive_weight > 0 & is.finite(marginal_response)]
    mean_score <- mean(evidence_score, na.rm = TRUE)
    coef_mean <- if (nrow(pos)) stats::weighted.mean(pos$marginal_response, w = pos$positive_weight, na.rm = TRUE) else NA_real_
    coef_sd <- if (nrow(pos) >= 2L) {
      sqrt(stats::weighted.mean((pos$marginal_response - coef_mean) ^ 2, w = pos$positive_weight, na.rm = TRUE))
    } else {
      NA_real_
    }
    list(
      event_n = .N,
      usable_positive_event_n = nrow(pos),
      mean_evidence_score = mean_score,
      max_evidence_score = max(evidence_score, na.rm = TRUE),
      contribution_prior_mean = if (nrow(pos) && any(is.finite(pos$incremental_outcome))) stats::weighted.mean(pos$incremental_outcome, w = pos$positive_weight, na.rm = TRUE) else NA_real_,
      contribution_pct_prior_mean = if (nrow(pos) && any(is.finite(pos$contribution_pct))) stats::weighted.mean(pos$contribution_pct, w = pos$positive_weight, na.rm = TRUE) else NA_real_,
      coef_prior_mean = coef_mean,
      coef_prior_sd = coef_sd,
      coef_prior_precision = if (is.finite(coef_sd) && coef_sd > 1e-8) 1 / (coef_sd ^ 2) else NA_real_,
      cost_per_outcome_prior_mean = if (nrow(pos) && any(is.finite(pos$cost_per_incremental_outcome))) stats::weighted.mean(pos$cost_per_incremental_outcome, w = pos$positive_weight, na.rm = TRUE) else NA_real_,
      roi_like_prior_mean = if (nrow(pos) && any(is.finite(pos$roi_like))) stats::weighted.mean(pos$roi_like, w = pos$positive_weight, na.rm = TRUE) else NA_real_,
      evidence_direction = data.table::fcase(
        nrow(pos) >= 2L && mean_score >= 60, "usable_as_coef_prior",
        nrow(pos) >= 1L && mean_score >= 35, "directional_prior_only",
        default = "diagnostic_only"
      ),
      negative_or_confounded_event_n = sum(effect_direction == "negative_or_confounded_media_effect", na.rm = TRUE),
      co_moving_event_n = sum(co_moving_channel_n > 0, na.rm = TRUE)
    )
  }, by = variable]
  out[]
}
qgt_build_bundle_prior_recommendations <- function(event_results) {
  if (is.null(event_results) || !nrow(event_results)) return(qgt_empty_bundle_prior_recommendations())
  dt <- copy(event_results)
  if (!"bundle_usable" %in% names(dt)) dt[, bundle_usable := FALSE]
  dt <- dt[estimand_level == "bundle" & (is.finite(bundle_return_prior) | is.finite(bundle_cost_per_outcome) | is.finite(bundle_incremental_outcome))]
  if (!nrow(dt)) return(qgt_empty_bundle_prior_recommendations())
  data.table::setorder(dt, bundle_name, geo, event_start, event_end, -evidence_score)
  dt <- dt[, .SD[1], by = .(bundle_name, geo, event_start, event_end)]
  dt[, prior_weight := pmax(evidence_score, 1) / 100]
  out <- dt[, {
    usable <- .SD[bundle_usable %in% TRUE]
    diagnostic <- .SD[!(bundle_usable %in% TRUE)]
    usable_w <- pmax(usable$prior_weight, 0.01)
    diag_w <- pmax(diagnostic$prior_weight, 0.01)
    list(
      moved_channels = paste(unique(moved_channels), collapse = "||"),
      event_n = .N,
      usable_bundle_event_n = nrow(usable),
      usable_bundle_prior = nrow(usable) > 0L,
      mean_evidence_score = mean(evidence_score, na.rm = TRUE),
      max_evidence_score = max(evidence_score, na.rm = TRUE),
      bundle_contribution_prior_mean = if (nrow(usable) && any(is.finite(usable$bundle_incremental_outcome))) stats::weighted.mean(usable$bundle_incremental_outcome, w = usable_w, na.rm = TRUE) else NA_real_,
      bundle_spend_prior_mean = if (nrow(usable) && any(is.finite(usable$bundle_incremental_spend))) stats::weighted.mean(usable$bundle_incremental_spend, w = usable_w, na.rm = TRUE) else NA_real_,
      bundle_return_prior_mean = if (nrow(usable) && any(is.finite(usable$bundle_return_prior))) stats::weighted.mean(usable$bundle_return_prior, w = usable_w, na.rm = TRUE) else NA_real_,
      bundle_cost_per_outcome_prior_mean = if (nrow(usable) && any(is.finite(usable$bundle_cost_per_outcome))) stats::weighted.mean(usable$bundle_cost_per_outcome, w = usable_w, na.rm = TRUE) else NA_real_,
      diagnostic_bundle_return_read = if (nrow(diagnostic) && any(is.finite(diagnostic$bundle_return_prior))) stats::weighted.mean(diagnostic$bundle_return_prior, w = diag_w, na.rm = TRUE) else NA_real_,
      diagnostic_bundle_cost_per_outcome_read = if (nrow(diagnostic) && any(is.finite(diagnostic$bundle_cost_per_outcome))) stats::weighted.mean(diagnostic$bundle_cost_per_outcome, w = diag_w, na.rm = TRUE) else NA_real_,
      evidence_direction = data.table::fcase(
        nrow(usable) >= 2L && mean(evidence_score, na.rm = TRUE) >= 60, "usable_as_bundle_prior",
        nrow(usable) >= 1L, "directional_bundle_prior",
        default = "diagnostic_only"
      )
    )
  }, by = bundle_name]
  out[]
}
qgt_empty_stan_prior_handoff <- function() {
  data.table(
    variable = character(),
    coef = numeric(),
    coef_precision = numeric(),
    coef_bound = character(),
    quasi_geo_prior_source = character(),
    quasi_geo_evidence_direction = character(),
    quasi_geo_recommended_use = character(),
    quasi_geo_max_evidence_score = numeric(),
    quasi_geo_event_n = integer(),
    quasi_geo_usable_event_n = integer(),
    quasi_geo_cost_per_outcome_prior = numeric(),
    quasi_geo_roi_like_prior = numeric(),
    anchor_saturation = numeric(),
    anchor_saturation_sd = numeric(),
    anchor_saturation_precision = numeric(),
    curve_type = character(),
    dvalue = numeric(),
    quasi_geo_curve_prior_source = character(),
    quasi_geo_curve_recommended_use = character()
  )
}
qgt_build_stan_prior_handoff <- function(quasi_geo_result,
                                         min_evidence_score = 35,
                                         max_coef_precision = 25,
                                         min_coef_precision = 2,
                                         single_event_precision = 4) {
  rec <- if (is.list(quasi_geo_result) && !is.null(quasi_geo_result$prior_recommendations)) {
    as.data.table(copy(quasi_geo_result$prior_recommendations))
  } else {
    as.data.table(copy(quasi_geo_result))
  }
  curve_fits <- if (is.list(quasi_geo_result) && !is.null(quasi_geo_result$curve_prior_fits)) {
    as.data.table(copy(quasi_geo_result$curve_prior_fits))
  } else {
    data.table()
  }
  if (!nrow(rec)) return(qgt_empty_stan_prior_handoff())
  required <- c("variable", "coef_prior_mean", "coef_prior_precision", "evidence_direction",
                "max_evidence_score", "event_n", "usable_positive_event_n")
  missing <- setdiff(required, names(rec))
  if (length(missing)) stop("quasi_geo_result prior recommendations are missing required columns: ", paste(missing, collapse = ", "))
  for (cc in c("cost_per_outcome_prior_mean", "roi_like_prior_mean")) if (!cc %in% names(rec)) rec[, (cc) := NA_real_]
  rec <- rec[
    usable_positive_event_n > 0L &
      is.finite(coef_prior_mean) &
      coef_prior_mean > 0 &
      is.finite(max_evidence_score) &
      max_evidence_score >= min_evidence_score &
      evidence_direction %in% c("usable_as_coef_prior", "directional_prior_only")
  ]
  if (!nrow(rec)) return(qgt_empty_stan_prior_handoff())
  rec[, reliability := pmin(1, pmax(0, max_evidence_score / 100))]
  rec[, coef_precision_out := fifelse(
    is.finite(coef_prior_precision) & coef_prior_precision > 0,
    coef_prior_precision,
    fifelse(evidence_direction == "usable_as_coef_prior", single_event_precision * 2, single_event_precision)
  )]
  rec[, coef_precision_out := pmin(max_coef_precision, pmax(min_coef_precision, coef_precision_out * pmax(reliability, 0.25)))]
  rec[, recommended_use_out := fifelse(evidence_direction == "usable_as_coef_prior" & max_evidence_score >= 80,
                                       "calibration_or_tight_directional_prior",
                                       "directional_prior")]
  out <- rec[, .(
    variable = as.character(variable),
    coef = as.numeric(coef_prior_mean),
    coef_precision = as.numeric(coef_precision_out),
    coef_bound = "pos",
    quasi_geo_prior_source = "quasi_geo_channel_specific_marginal_response",
    quasi_geo_evidence_direction = as.character(evidence_direction),
    quasi_geo_recommended_use = as.character(recommended_use_out),
    quasi_geo_max_evidence_score = as.numeric(max_evidence_score),
    quasi_geo_event_n = as.integer(event_n),
    quasi_geo_usable_event_n = as.integer(usable_positive_event_n),
    quasi_geo_cost_per_outcome_prior = as.numeric(cost_per_outcome_prior_mean),
    quasi_geo_roi_like_prior = as.numeric(roi_like_prior_mean)
  )]
  if (nrow(curve_fits) && "variable" %in% names(curve_fits)) {
    curve_keep <- intersect(
      c("variable", "anchor_saturation", "anchor_saturation_sd", "anchor_saturation_precision",
        "curve_type", "dvalue", "recommended_use", "curve_fit_status"),
      names(curve_fits)
    )
    cf <- unique(curve_fits[, ..curve_keep], by = "variable")
    if ("curve_fit_status" %in% names(cf)) {
      weak <- cf$curve_fit_status != "conservative_hill_marginal_response_fit"
      for (cc in intersect(c("anchor_saturation", "anchor_saturation_sd", "anchor_saturation_precision", "dvalue"), names(cf))) {
        data.table::set(cf, which(weak), cc, NA_real_)
      }
      if ("curve_type" %in% names(cf)) data.table::set(cf, which(weak), "curve_type", NA_character_)
    }
    out <- cf[out, on = "variable"]
    if ("recommended_use" %in% names(out)) data.table::setnames(out, "recommended_use", "quasi_geo_curve_recommended_use")
    if ("curve_fit_status" %in% names(out)) {
      out[, quasi_geo_curve_prior_source := fifelse(
        curve_fit_status == "conservative_hill_marginal_response_fit",
        "quasi_geo_uncertainty_weighted_dose_response",
        "quasi_geo_default_anchor_due_to_insufficient_dose_evidence"
      )]
      out[, curve_fit_status := NULL]
    }
  }
  for (cc in setdiff(names(qgt_empty_stan_prior_handoff()), names(out))) out[, (cc) := qgt_empty_stan_prior_handoff()[[cc]]]
  out[, names(qgt_empty_stan_prior_handoff()), with = FALSE]
}
qgt_apply_stan_prior_handoff <- function(metadata_input,
                                         quasi_geo_handoff,
                                         overwrite_existing = FALSE) {
  md <- as.data.table(copy(metadata_input))
  handoff <- as.data.table(copy(quasi_geo_handoff))
  if (!nrow(handoff)) return(md[])
  if (!"variable" %in% names(md)) stop("metadata_input must include variable.")
  if (anyDuplicated(as.character(md$variable))) stop("metadata_input has duplicate variable keys.")
  if (anyDuplicated(as.character(handoff$variable))) stop("quasi_geo_handoff has duplicate variable keys.")
  for (cc in setdiff(names(handoff), names(md))) {
    md[, (cc) := handoff[[cc]][NA_integer_]]
  }
  md[handoff, on = "variable", `:=`(
    coef = fifelse(isTRUE(overwrite_existing) | !is.finite(suppressWarnings(as.numeric(coef))), i.coef, suppressWarnings(as.numeric(coef))),
    coef_precision = fifelse(isTRUE(overwrite_existing) | !is.finite(suppressWarnings(as.numeric(coef_precision))), i.coef_precision, suppressWarnings(as.numeric(coef_precision))),
    coef_bound = fifelse(isTRUE(overwrite_existing) | is.na(coef_bound) | !nzchar(as.character(coef_bound)), i.coef_bound, as.character(coef_bound)),
    quasi_geo_prior_source = i.quasi_geo_prior_source,
    quasi_geo_evidence_direction = i.quasi_geo_evidence_direction,
    quasi_geo_recommended_use = i.quasi_geo_recommended_use,
    quasi_geo_max_evidence_score = i.quasi_geo_max_evidence_score,
    quasi_geo_event_n = i.quasi_geo_event_n,
    quasi_geo_usable_event_n = i.quasi_geo_usable_event_n,
    quasi_geo_cost_per_outcome_prior = i.quasi_geo_cost_per_outcome_prior,
    quasi_geo_roi_like_prior = i.quasi_geo_roi_like_prior,
    anchor_saturation = fifelse(isTRUE(overwrite_existing) | !is.finite(suppressWarnings(as.numeric(anchor_saturation))), i.anchor_saturation, suppressWarnings(as.numeric(anchor_saturation))),
    anchor_saturation_sd = fifelse(isTRUE(overwrite_existing) | !is.finite(suppressWarnings(as.numeric(anchor_saturation_sd))), i.anchor_saturation_sd, suppressWarnings(as.numeric(anchor_saturation_sd))),
    anchor_saturation_precision = fifelse(isTRUE(overwrite_existing) | !is.finite(suppressWarnings(as.numeric(anchor_saturation_precision))), i.anchor_saturation_precision, suppressWarnings(as.numeric(anchor_saturation_precision))),
    curve_type = fifelse(isTRUE(overwrite_existing) | is.na(curve_type) | !nzchar(as.character(curve_type)), i.curve_type, as.character(curve_type)),
    dvalue = fifelse(isTRUE(overwrite_existing) | !is.finite(suppressWarnings(as.numeric(dvalue))), i.dvalue, suppressWarnings(as.numeric(dvalue))),
    quasi_geo_curve_prior_source = i.quasi_geo_curve_prior_source,
    quasi_geo_curve_recommended_use = i.quasi_geo_curve_recommended_use
  )]
  md[]
}

qgt_empty_multi_treated_market_estimates <- function() {
  data.table(
    variable = character(), event_start = as.Date(character()), event_end = as.Date(character()),
    ramp_direction = character(), treated_geos = character(), treated_geo_n = integer(),
    estimable_geo_n = integer(), usable_geo_n = integer(), pooled_incremental_outcome = numeric(),
    pooled_incremental_outcome_se = numeric(), pooled_incremental_outcome_ci_low = numeric(),
    pooled_incremental_outcome_ci_high = numeric(), total_incremental_outcome_raw = numeric(),
    total_incremental_spend = numeric(), total_incremental_media = numeric(),
    pooled_marginal_response = numeric(), total_return_prior = numeric(),
    total_cost_per_outcome = numeric(), heterogeneity_q = numeric(), heterogeneity_i2 = numeric(),
    mean_evidence_score = numeric(), evidence_score = numeric(), multi_market_usable = logical(),
    recommended_use = character(), methodology_note = character()
  )
}

qgt_build_multi_treated_market_estimates <- function(event_results) {
  dt <- copy(as.data.table(event_results))
  if (!nrow(dt)) return(qgt_empty_multi_treated_market_estimates())
  for (cc in c("channel_specific_usable", "lift_se", "incremental_outcome_raw", "incremental_spend",
               "incremental_media", "marginal_response", "evidence_score")) {
    if (!cc %in% names(dt)) dt[, (cc) := if (cc == "channel_specific_usable") FALSE else NA_real_]
  }
  dt <- dt[!is.na(geo) & nzchar(as.character(geo)) & is.finite(incremental_outcome)]
  if (!nrow(dt)) return(qgt_empty_multi_treated_market_estimates())
  out <- dt[, {
    z <- .SD[!duplicated(as.character(geo))]
    valid <- z[is.finite(incremental_outcome) & is.finite(lift_se) & lift_se > 1e-8]
    w <- if (nrow(valid)) 1 / valid$lift_se^2 else numeric()
    pooled <- if (length(w)) sum(w * valid$incremental_outcome) / sum(w) else NA_real_
    pooled_se <- if (length(w)) sqrt(1 / sum(w)) else NA_real_
    q <- if (length(w) >= 2L) sum(w * (valid$incremental_outcome - pooled)^2) else NA_real_
    i2 <- if (is.finite(q) && q > 0 && length(w) >= 2L) pmax(0, (q - (length(w) - 1L)) / q) else 0
    usable_n <- sum(z$channel_specific_usable %in% TRUE, na.rm = TRUE)
    mean_score <- mean(z$evidence_score, na.rm = TRUE)
    adjusted_score <- qgt_clip(mean_score * (1 - 0.35 * i2), 0, 100)
    raw_total <- if (any(is.finite(z$incremental_outcome_raw))) sum(z$incremental_outcome_raw, na.rm = TRUE) else NA_real_
    spend_total <- if (any(is.finite(z$incremental_spend))) sum(z$incremental_spend, na.rm = TRUE) else NA_real_
    media_total <- if (any(is.finite(z$incremental_media))) sum(z$incremental_media, na.rm = TRUE) else NA_real_
    multi_usable <- uniqueN(as.character(z$geo)) >= 2L && usable_n >= 2L && is.finite(pooled) && i2 <= 0.75
    list(
      treated_geos = paste(sort(unique(as.character(z$geo))), collapse = "|"),
      treated_geo_n = uniqueN(as.character(z$geo)), estimable_geo_n = nrow(valid), usable_geo_n = usable_n,
      pooled_incremental_outcome = pooled, pooled_incremental_outcome_se = pooled_se,
      pooled_incremental_outcome_ci_low = pooled - 1.96 * pooled_se,
      pooled_incremental_outcome_ci_high = pooled + 1.96 * pooled_se,
      total_incremental_outcome_raw = raw_total, total_incremental_spend = spend_total,
      total_incremental_media = media_total,
      pooled_marginal_response = if (any(is.finite(z$marginal_response))) stats::weighted.mean(z$marginal_response, pmax(z$evidence_score, 1), na.rm = TRUE) else NA_real_,
      total_return_prior = if (is.finite(raw_total) && is.finite(spend_total) && abs(spend_total) > 1e-8) raw_total / spend_total else NA_real_,
      total_cost_per_outcome = if (is.finite(raw_total) && abs(raw_total) > 1e-8 && is.finite(spend_total)) spend_total / raw_total else NA_real_,
      heterogeneity_q = q, heterogeneity_i2 = i2, mean_evidence_score = mean_score,
      evidence_score = adjusted_score, multi_market_usable = multi_usable,
      recommended_use = data.table::fcase(
        multi_usable && adjusted_score >= 70, "calibration",
        multi_usable && adjusted_score >= 35, "directional_prior",
        default = "diagnostic_only"
      ),
      methodology_note = "Inverse-variance pooled treated-market effects; raw business lift and spend are summed across distinct markets. High cross-market heterogeneity downgrades use."
    )
  }, by = .(variable, event_start, event_end, ramp_direction)]
  out <- out[treated_geo_n >= 2L]
  if (!nrow(out)) return(qgt_empty_multi_treated_market_estimates())
  out[]
}
