# 030-optimizer-utils-constraints.R
# Generated by behavior-preserving split of optimizer_scenario_planner.R.

# optimizer_scenario_planner.R
#
# Standalone optimizer and scenario planner for MMM response curves.
# The optimizer always allocates against response curves. It can get those
# curves from either:
#   1. A Stan MMM fit object from hier_mmm.R, preferably using fit$response_curves.
#      If that sheet is missing, the same curve points are generated from the
#      fitted transforms and coefficients.
#   2. A precomputed response-curve table, useful for hand-built curves,
#      external models, or baseline planning before a full MMM fit exists.
#
# Industry alignment:
#   - Response curves scale historical media/support flighting by channel.
#   - ROI is historical/average contribution per cost.
#   - mROI is next-dollar incremental outcome around the current or scenario spend.
#   - Optimization is point-estimate decision support. When draw-level response
#     curves are supplied, scenario and optimized-plan uncertainty summaries are
#     reported separately from the point recommendation.

opsp_require_data_table <- function() {
  if (!requireNamespace("data.table", quietly = TRUE)) {
    stop("optimizer_scenario_planner.R requires the data.table package.", call. = FALSE)
  }
  invisible(TRUE)
}

opsp_as_dt <- function(x, label = "input") {
  opsp_require_data_table()
  if (is.null(x)) return(data.table::data.table())
  data.table::as.data.table(data.table::copy(x))
}

`%||%` <- function(a, b) if (is.null(a)) b else a

opsp_script_dir <- function() {
  tryCatch({
    frames <- sys.frames()
    ofiles <- vapply(frames, function(f) {
      if (!is.null(f$ofile)) as.character(f$ofile)[1] else NA_character_
    }, character(1))
    ofiles <- ofiles[!is.na(ofiles) & nzchar(ofiles)]
    if (length(ofiles)) {
      dirname(normalizePath(ofiles[length(ofiles)], mustWork = FALSE))
    } else {
      file_arg <- grep("^--file=", commandArgs(FALSE), value = TRUE)
      if (length(file_arg)) dirname(normalizePath(sub("^--file=", "", file_arg[1]), mustWork = FALSE)) else getwd()
    }
  }, error = function(e) getwd())
}

opsp_source_hier_if_needed <- function() {
  if (exists("variable_contribution_sum_hier_mmm", mode = "function") &&
      exists("normalize_spend_map_hier_mmm", mode = "function") &&
      exists("get_aligned_raw_data_hier_mmm", mode = "function")) {
    return(invisible(TRUE))
  }
  path <- file.path(opsp_script_dir(), "hier_mmm.R")
  if (!file.exists(path)) {
    stop("MMM fit mode requires hier_mmm.R helpers. Source hier_mmm.R first or place it beside optimizer_scenario_planner.R.", call. = FALSE)
  }
  source(path, chdir = TRUE)
  invisible(TRUE)
}

opsp_num <- function(x) suppressWarnings(as.numeric(x))

opsp_pick_col <- function(dt, candidates) {
  hit <- intersect(candidates, names(dt))
  if (length(hit)) hit[1] else NA_character_
}

opsp_safe_div <- function(num, den) {
  den <- opsp_num(den)
  num <- opsp_num(num)
  out <- rep(NA_real_, length(num))
  ok <- is.finite(num) & is.finite(den) & abs(den) > 1e-8
  out[ok] <- num[ok] / den[ok]
  out
}

opsp_first_nonblank <- function(x, default = NA_character_) {
  x <- as.character(x)
  x <- x[!is.na(x) & nzchar(trimws(x))]
  if (length(x)) x[1] else default
}

opsp_mean_or_na <- function(x) {
  x <- opsp_num(x)
  x <- x[is.finite(x)]
  if (length(x)) mean(x) else NA_real_
}

opsp_evidence_level_from_score <- function(score) {
  score <- opsp_num(score)
  out <- rep("unknown", length(score))
  out[is.finite(score) & score >= 85] <- "very_strong"
  out[is.finite(score) & score >= 70 & score < 85] <- "strong"
  out[is.finite(score) & score >= 50 & score < 70] <- "directional"
  out[is.finite(score) & score >= 25 & score < 50] <- "diagnostic"
  out[is.finite(score) & score < 25] <- "weak"
  out
}

opsp_curve_metadata_columns <- function() {
  c(
    "curve_evidence_level", "curve_evidence_score", "curve_confidence_band",
    "curve_recommended_use", "curve_source", "curve_type", "response_curve_basis",
    "uncertainty_note", "flighting_assumption", "cost_assumption"
  )
}

opsp_combine_notes <- function(base, extra) {
  base <- as.character(base)
  extra <- as.character(extra)
  n <- max(length(base), length(extra), 1L)
  base <- rep(base, length.out = n)
  extra <- rep(extra, length.out = n)
  out <- base
  has_base <- !is.na(base) & nzchar(trimws(base))
  has_extra <- !is.na(extra) & nzchar(trimws(extra))
  out[!has_base & has_extra] <- extra[!has_base & has_extra]
  out[has_base & has_extra] <- paste(base[has_base & has_extra], extra[has_base & has_extra], sep = " | ")
  out[!has_base & !has_extra] <- NA_character_
  out
}

opsp_resolve_input_alias <- function(primary,
                                     alias,
                                     primary_name,
                                     alias_name) {
  if (is.null(alias)) return(primary)
  if (!is.null(primary)) {
    stop(
      "Pass either `", primary_name, "` or `", alias_name, "`, not both. ",
      "`", alias_name, "` is the clearer analyst-facing alias for `", primary_name, "`.",
      call. = FALSE
    )
  }
  alias
}

opsp_optimizer_input_alias_audit <- function(alias_used) {
  data.table::data.table(
    canonical_input = c(
      "fit_obj",
      "response_curves",
      "response_curve_draws",
      "raw_data",
      "variables",
      "constraints",
      "variable_group_map",
      "group_constraints",
      "support_cost_map",
      "output_dir"
    ),
    preferred_input = c(
      "model_fit",
      "response_curve_table",
      "response_curve_draw_table",
      "model_data",
      "drivers",
      "driver_constraints",
      "planning_group_map",
      "planning_group_constraints",
      "media_cost_map",
      "output_path"
    ),
    alias_used = as.logical(alias_used),
    note = c(
      "Fitted econimap/Stan MMM object.",
      "Response-curve table. This is the core optimizer input.",
      "Draw-level response-curve table for uncertainty-aware scenario reads.",
      "Raw/model-cut data used for spend/support lookup.",
      "Modeled media drivers/channels to include.",
      "Driver-level min/max/fixed spend or multiplier constraints.",
      "Mapping from driver to planning group for rollups and group constraints.",
      "Budget constraints by planning group.",
      "Cost per support unit assumptions when spend is not already in the curve.",
      "Folder where optimizer output tables are written."
    )
  )
}

opsp_add_driver_alias <- function(x) {
  if (is.null(x) || !(is.data.frame(x) || data.table::is.data.table(x))) return(x)
  out <- data.table::as.data.table(data.table::copy(x))
  if ("variable" %in% names(out) && !"driver" %in% names(out)) {
    out[, driver := as.character(variable)]
    data.table::setcolorder(out, c("variable", "driver", setdiff(names(out), c("variable", "driver"))))
  }
  out[]
}

opsp_add_optimizer_output_aliases <- function(out) {
  table_names <- c(
    "current_plan",
    "response_curves",
    "response_curve_uncertainty",
    "saturation_headroom",
    "scenario_detail",
    "scenario_uncertainty_by_variable",
    "scenario_uncertainty_draws_by_variable",
    "optimization_plan",
    "optimization_uncertainty_by_variable",
    "optimization_uncertainty_draws_by_variable",
    "allocation_history",
    "target_plan_detail"
  )
  for (nm in intersect(table_names, names(out))) {
    out[[nm]] <- opsp_add_driver_alias(out[[nm]])
  }
  out
}

opsp_interp_curve_value <- function(table, variable_name, multiplier, value_col, fallback = NA_real_) {
  if (is.null(table) || !nrow(table) || !(value_col %in% names(table))) return(fallback)
  vv <- as.character(variable_name)[1]
  tmp <- table[variable == vv]
  if (!nrow(tmp)) return(fallback)
  x <- opsp_num(tmp$spend_multiplier)
  y <- opsp_num(tmp[[value_col]])
  ok <- is.finite(x) & is.finite(y)
  if (sum(ok) < 1L) return(fallback)
  if (sum(ok) == 1L) return(y[ok][1])
  ord <- order(x[ok])
  stats::approx(x[ok][ord], y[ok][ord], xout = as.numeric(multiplier)[1], rule = 2, ties = mean)$y
}

opsp_curve_meta_for_variable <- function(table, variable_name, multiplier = NA_real_) {
  out <- data.table::data.table(
    curve_evidence_level = "unknown",
    curve_evidence_score = NA_real_,
    curve_confidence_band = NA_character_,
    curve_recommended_use = NA_character_,
    curve_source = NA_character_,
    curve_type = NA_character_,
    response_curve_basis = NA_character_,
    uncertainty_note = NA_character_,
    flighting_assumption = NA_character_,
    cost_assumption = NA_character_
  )
  if (is.null(table) || !nrow(table) || !"variable" %in% names(table)) return(out)
  tmp <- table[variable == as.character(variable_name)[1]]
  if (!nrow(tmp)) return(out)
  multiplier <- suppressWarnings(as.numeric(multiplier)[1])
  if (is.finite(multiplier) && "spend_multiplier" %in% names(tmp)) {
    mm <- suppressWarnings(as.numeric(tmp$spend_multiplier))
    tmp_m <- tmp[is.finite(mm) & abs(mm - multiplier) <= 1e-8]
    if (nrow(tmp_m)) tmp <- tmp_m
  }
  for (cc in intersect(names(out), names(tmp))) {
    if (is.numeric(out[[cc]])) {
      out[, (cc) := opsp_mean_or_na(tmp[[cc]])]
    } else {
      out[, (cc) := opsp_first_nonblank(tmp[[cc]])]
    }
  }
  if ((!is.finite(out$curve_evidence_score[1]) || is.na(out$curve_evidence_score[1])) &&
      "evidence_score_0_100" %in% names(tmp)) out[, curve_evidence_score := opsp_mean_or_na(tmp$evidence_score_0_100)]
  if ((!is.finite(out$curve_evidence_score[1]) || is.na(out$curve_evidence_score[1])) &&
      "evidence_score" %in% names(tmp)) out[, curve_evidence_score := opsp_mean_or_na(tmp$evidence_score)]
  if ((!is.finite(out$curve_evidence_score[1]) || is.na(out$curve_evidence_score[1])) &&
      "max_evidence_score" %in% names(tmp)) out[, curve_evidence_score := opsp_mean_or_na(tmp$max_evidence_score)]
  if ((!is.finite(out$curve_evidence_score[1]) || is.na(out$curve_evidence_score[1])) &&
      "mean_evidence_score" %in% names(tmp)) out[, curve_evidence_score := opsp_mean_or_na(tmp$mean_evidence_score)]
  if (!nzchar(out$curve_confidence_band[1] %||% "") && "confidence_band" %in% names(tmp)) {
    out[, curve_confidence_band := opsp_first_nonblank(tmp$confidence_band)]
  }
  if (!nzchar(out$curve_recommended_use[1] %||% "") && "recommended_use" %in% names(tmp)) {
    out[, curve_recommended_use := opsp_first_nonblank(tmp$recommended_use)]
  }
  if (!nzchar(out$curve_evidence_level[1] %||% "") || out$curve_evidence_level[1] == "unknown") {
    if (nzchar(out$curve_confidence_band[1] %||% "")) {
      out[, curve_evidence_level := curve_confidence_band]
    } else if (is.finite(out$curve_evidence_score[1])) {
      out[, curve_evidence_level := opsp_evidence_level_from_score(curve_evidence_score)]
    }
  }
  out[]
}

opsp_clip <- function(x, lo, hi) pmin(pmax(x, lo), hi)

opsp_check_unique_variables <- function(x, label) {
  if (!"variable" %in% names(x)) return(invisible(TRUE))
  dup <- unique(x$variable[duplicated(x$variable)])
  if (length(dup)) stop(label, " contains duplicate variable rows: ", paste(dup, collapse = ", "), call. = FALSE)
  invisible(TRUE)
}

opsp_split_rollup_path <- function(path) {
  if (length(path) < 1L || is.na(path[1]) || !nzchar(as.character(path[1]))) return(character())
  nodes <- trimws(strsplit(as.character(path[1]), ">", fixed = TRUE)[[1]])
  nodes[nzchar(nodes)]
}

opsp_rollup_reporting_node <- function(path, variable = NA_character_) {
  nodes <- opsp_split_rollup_path(path)
  variable <- as.character(variable)[1]
  if (!length(nodes)) return(variable)
  root_aliases <- c("total", "total_media", "media", "paid_media", "all_media", "all")
  first <- tolower(gsub("[^a-z0-9]+", "_", nodes[1]))
  if (length(nodes) >= 2L && first %in% root_aliases) return(nodes[2])
  nodes[1]
}

opsp_infer_variables <- function(fit_obj = NULL, response_curves = NULL, variables = NULL) {
  if (!is.null(variables)) return(unique(as.character(variables)))
  if (!is.null(fit_obj) && !is.null(fit_obj$variable_lookup)) {
    vl <- opsp_as_dt(fit_obj$variable_lookup, "fit_obj$variable_lookup")
    if ("variable" %in% names(vl)) return(unique(as.character(vl$variable)))
  }
  rc <- opsp_as_dt(response_curves, "response_curves")
  if (nrow(rc)) {
    vc <- opsp_pick_col(rc, c("variable", "channel", "media", "driver"))
    if (!is.na(vc)) return(unique(as.character(rc[[vc]])))
  }
  character()
}

opsp_normalize_constraints <- function(variables, current_spend, constraints = NULL,
                                       min_multiplier = 0,
                                       max_multiplier = 3) {
  opsp_require_data_table()
  out <- data.table::data.table(
    variable = as.character(variables),
    current_spend = as.numeric(current_spend),
    min_multiplier = as.numeric(min_multiplier)[1],
    max_multiplier = as.numeric(max_multiplier)[1],
    locked = FALSE,
    fixed_spend = NA_real_,
    min_spend = NA_real_,
    max_spend = NA_real_
  )
  if (!is.null(constraints) && nrow(opsp_as_dt(constraints))) {
    cs <- opsp_as_dt(constraints, "constraints")
    vcol <- opsp_pick_col(cs, c("variable", "driver", "channel", "media"))
    if (is.na(vcol)) stop("constraints must include variable, driver, channel, or media.", call. = FALSE)
    if (!identical(vcol, "variable")) data.table::setnames(cs, vcol, "variable")
    cs[, variable := as.character(variable)]
    opsp_check_unique_variables(cs, "constraints")
    for (cc in intersect(c("min_multiplier", "max_multiplier", "locked", "fixed_spend", "min_spend", "max_spend"), names(cs))) {
      out[cs, (cc) := get(paste0("i.", cc)), on = "variable"]
    }
  }
  out[, `:=`(
    current_spend = pmax(opsp_num(current_spend), 0),
    min_multiplier = pmax(opsp_num(min_multiplier), 0),
    max_multiplier = pmax(opsp_num(max_multiplier), 0),
    min_spend = opsp_num(min_spend),
    max_spend = opsp_num(max_spend),
    fixed_spend = opsp_num(fixed_spend),
    locked = as.logical(locked)
  )]
  out[is.na(locked), locked := FALSE]
  out[is.finite(opsp_num(min_spend)) & current_spend > 0, min_multiplier := pmax(min_multiplier, opsp_num(min_spend) / current_spend)]
  out[is.finite(opsp_num(max_spend)) & current_spend > 0, max_multiplier := pmin(max_multiplier, opsp_num(max_spend) / current_spend)]
  out[is.finite(opsp_num(fixed_spend)) & current_spend > 0, `:=`(
    min_multiplier = pmax(opsp_num(fixed_spend) / current_spend, 0),
    max_multiplier = pmax(opsp_num(fixed_spend) / current_spend, 0)
  )]
  out[locked == TRUE, `:=`(min_multiplier = 1, max_multiplier = 1)]
  out[!is.finite(min_multiplier), min_multiplier := 0]
  out[!is.finite(max_multiplier), max_multiplier := pmax(min_multiplier, 1)]
  out[max_multiplier < min_multiplier, max_multiplier := min_multiplier]
  out[]
}

opsp_normalize_variable_group_map <- function(variables, variable_group_map = NULL) {
  vars <- unique(as.character(variables))
  out <- data.table::data.table(variable = vars, planning_group = vars)
  if (is.null(variable_group_map) || !nrow(opsp_as_dt(variable_group_map))) return(out[])
  gm <- opsp_as_dt(variable_group_map, "variable_group_map")
  vcol <- opsp_pick_col(gm, c("variable", "driver", "channel", "media"))
  if (is.na(vcol)) stop("variable_group_map must include variable, driver, channel, or media.", call. = FALSE)
  if (!identical(vcol, "variable")) data.table::setnames(gm, vcol, "variable")
  gcol <- opsp_pick_col(gm, c("planning_group", "constraint_group", "group", "reporting_channel", "channel", "parent_channel", "channel_group", "product", "portfolio", "line_of_business", "lob"))
  if (is.na(gcol) && !"rollup_path" %in% names(gm)) {
    stop("variable_group_map must include a group column such as planning_group, channel, parent_channel, product, line_of_business, or rollup_path.", call. = FALSE)
  }
  if (!is.na(gcol)) {
    gm <- gm[, .(variable = as.character(variable), planning_group = as.character(get(gcol)))]
  } else {
    gm <- gm[, .(variable = as.character(variable),
                 planning_group = mapply(opsp_rollup_reporting_node, rollup_path, variable, USE.NAMES = FALSE))]
  }
  gm <- gm[nzchar(variable)]
  dup <- gm[duplicated(variable), unique(variable)]
  if (length(dup)) stop("variable_group_map has duplicate variable rows: ", paste(dup, collapse = ", "), call. = FALSE)
  gm[!nzchar(planning_group) | is.na(planning_group), planning_group := variable]
  out[gm, planning_group := i.planning_group, on = "variable"]
  out[]
}

opsp_normalize_group_constraints <- function(group_constraints = NULL, total_budget = NA_real_) {
  gc <- opsp_as_dt(group_constraints, "group_constraints")
  if (!nrow(gc)) return(data.table::data.table())
  gcol <- opsp_pick_col(gc, c("planning_group", "constraint_group", "group", "parent_channel", "channel_group", "product", "portfolio", "line_of_business", "lob"))
  if (is.na(gcol)) stop("group_constraints must include a group column such as planning_group, parent_channel, product, or line_of_business.", call. = FALSE)
  if (!identical(gcol, "planning_group")) data.table::setnames(gc, gcol, "planning_group")
  gc[, planning_group := as.character(planning_group)]
  gc <- gc[nzchar(planning_group)]
  dup <- gc[duplicated(planning_group), unique(planning_group)]
  if (length(dup)) stop("group_constraints has duplicate planning_group rows: ", paste(dup, collapse = ", "), call. = FALSE)
  for (cc in c("min_spend", "max_spend", "fixed_spend", "min_share", "max_share")) {
    if (!cc %in% names(gc)) gc[, (cc) := NA_real_]
    gc[, (cc) := opsp_num(get(cc))]
  }
  total_budget <- opsp_num(total_budget)[1]
  if (is.finite(total_budget) && total_budget >= 0) {
    gc[is.finite(min_share), min_spend := pmax(opsp_num(min_spend), min_share * total_budget, na.rm = TRUE)]
    gc[is.finite(max_share), max_spend := pmin(opsp_num(max_spend), max_share * total_budget, na.rm = TRUE)]
  }
  gc[is.finite(fixed_spend), `:=`(min_spend = pmax(fixed_spend, 0), max_spend = pmax(fixed_spend, 0))]
  gc[!is.finite(min_spend), min_spend := NA_real_]
  gc[!is.finite(max_spend), max_spend := NA_real_]
  gc[is.finite(min_spend) & is.finite(max_spend) & max_spend < min_spend, max_spend := min_spend]
  gc[, .(planning_group, min_spend, max_spend, fixed_spend, min_share, max_share)]
}

opsp_group_constraint_status <- function(engine,
                                         vars,
                                         multipliers,
                                         variable_group_map = NULL,
                                         group_constraints = NULL,
                                         total_budget = NA_real_) {
  gc <- opsp_normalize_group_constraints(group_constraints, total_budget = total_budget)
  gm <- opsp_normalize_variable_group_map(vars, variable_group_map)
  mult <- stats::setNames(as.numeric(multipliers[vars]), vars)
  spend <- data.table::data.table(
    variable = vars,
    spend = vapply(vars, function(v) opsp_spend_at(engine, v, mult[v]), numeric(1))
  )
  spend[gm, planning_group := i.planning_group, on = "variable"]
  spend[!nzchar(planning_group) | is.na(planning_group), planning_group := variable]
  rollup <- spend[, .(spend = sum(spend, na.rm = TRUE)), by = planning_group]
  if (!nrow(gc)) return(list(ok = TRUE, max_violation = 0, rollup = rollup))
  rollup[gc, `:=`(
    min_spend = i.min_spend,
    max_spend = i.max_spend,
    fixed_spend = i.fixed_spend,
    min_share = i.min_share,
    max_share = i.max_share
  ), on = "planning_group"]
  missing_groups <- setdiff(gc$planning_group, rollup$planning_group)
  if (length(missing_groups)) {
    rollup <- data.table::rbindlist(list(
      rollup,
      gc[planning_group %in% missing_groups, .(planning_group, spend = 0, min_spend, max_spend, fixed_spend, min_share, max_share)]
    ), fill = TRUE)
  }
  rollup[, `:=`(
    min_violation = data.table::fifelse(is.finite(min_spend), pmax(min_spend - spend, 0), 0),
    max_violation = data.table::fifelse(is.finite(max_spend), pmax(spend - max_spend, 0), 0)
  )]
  max_violation <- rollup[, max(c(min_violation, max_violation), na.rm = TRUE)]
  list(ok = is.finite(max_violation) && max_violation <= 1e-6, max_violation = max_violation, rollup = rollup[])
}

opsp_channel_constraint_status <- function(engine,
                                           vars,
                                           multipliers,
                                           constraints_table) {
  vars <- as.character(vars)
  cs <- opsp_as_dt(constraints_table, "constraints_table")
  if (!nrow(cs)) return(list(ok = TRUE, max_violation = 0, detail = data.table::data.table()))
  for (cc in c("min_spend", "max_spend", "fixed_spend")) {
    if (!cc %in% names(cs)) cs[, (cc) := NA_real_]
    cs[, (cc) := opsp_num(get(cc))]
  }
  mult <- stats::setNames(as.numeric(multipliers[vars]), vars)
  detail <- data.table::data.table(
    variable = vars,
    spend = vapply(vars, function(v) opsp_spend_at(engine, v, mult[v]), numeric(1))
  )
  detail[cs[, .(variable = as.character(variable), min_spend, max_spend, fixed_spend)],
         on = "variable", `:=`(
           min_spend = i.min_spend,
           max_spend = i.max_spend,
           fixed_spend = i.fixed_spend
         )]
  detail[is.finite(fixed_spend), `:=`(
    min_spend = pmax(fixed_spend, 0),
    max_spend = pmax(fixed_spend, 0)
  )]
  for (cc in c("min_spend", "max_spend")) if (!cc %in% names(detail)) detail[, (cc) := NA_real_]
  detail[, `:=`(
    min_violation = data.table::fifelse(is.finite(min_spend), pmax(min_spend - spend, 0), 0),
    max_violation = data.table::fifelse(is.finite(max_spend), pmax(spend - max_spend, 0), 0)
  )]
  max_violation <- detail[, max(c(min_violation, max_violation), na.rm = TRUE)]
  list(ok = is.finite(max_violation) && max_violation <= 1e-6, max_violation = max_violation, detail = detail[])
}

opsp_normalize_support_cost_map <- function(support_cost_map = NULL) {
  scm <- opsp_as_dt(support_cost_map, "support_cost_map")
  if (!nrow(scm)) return(data.table::data.table())
  if (!"variable" %in% names(scm)) stop("support_cost_map must include variable.", call. = FALSE)
  scm[, variable := as.character(variable)]
  opsp_check_unique_variables(scm, "support_cost_map")
  unit_col <- opsp_pick_col(scm, c("support_unit", "unit", "media_unit"))
  cps_col <- opsp_pick_col(scm, c("cost_per_support", "spend_per_support", "cost_per_unit", "unit_cost",
                                  "cpp", "cost_per_point", "cost_per_grp", "cost_per_rating_point"))
  cpm_col <- opsp_pick_col(scm, c("cpm", "cost_per_thousand", "cost_per_mille"))
  cur_sup_col <- opsp_pick_col(scm, c("current_support", "base_support", "historical_support",
                                      "current_impressions", "base_impressions", "current_grps"))
  cur_spend_col <- opsp_pick_col(scm, c("current_spend", "base_spend", "historical_spend"))
  out <- scm[, .(variable)]
  out[, support_cost_per_unit := NA_real_]
  out[, support_cost_source := NA_character_]
  if (!is.na(cps_col)) {
    out[, `:=`(
      support_cost_per_unit = opsp_num(scm[[cps_col]]),
      support_cost_source = cps_col
    )]
  }
  if (!is.na(cpm_col)) {
    cpm_val <- opsp_num(scm[[cpm_col]]) / 1000
    out[!is.finite(support_cost_per_unit), `:=`(
      support_cost_per_unit = cpm_val[!is.finite(support_cost_per_unit)],
      support_cost_source = cpm_col
    )]
  }
  out[, current_support_map := if (!is.na(cur_sup_col)) opsp_num(scm[[cur_sup_col]]) else NA_real_]
  out[, current_spend_map := if (!is.na(cur_spend_col)) opsp_num(scm[[cur_spend_col]]) else NA_real_]
  out[, support_unit := if (!is.na(unit_col)) as.character(scm[[unit_col]]) else NA_character_]
  out[!is.finite(support_cost_per_unit) | support_cost_per_unit < 0, support_cost_per_unit := NA_real_]
  out[]
}

opsp_apply_support_costs_to_curves <- function(rc, support_cost_map = NULL) {
  out <- data.table::copy(rc)
  scm <- opsp_normalize_support_cost_map(support_cost_map)
  cost_cols <- c("cost_per_support", "spend_per_support", "cost_per_unit", "unit_cost",
                 "cpp", "cost_per_point", "cost_per_grp", "cost_per_rating_point")
  cpm_cols <- c("cpm", "cost_per_thousand", "cost_per_mille")
  curve_cost_col <- opsp_pick_col(out, cost_cols)
  curve_cpm_col <- opsp_pick_col(out, cpm_cols)
  if (!"support_cost_per_unit" %in% names(out)) out[, support_cost_per_unit := NA_real_]
  if (!"support_cost_source" %in% names(out)) out[, support_cost_source := NA_character_]
  if (!is.na(curve_cost_col)) out[, `:=`(support_cost_per_unit = opsp_num(get(curve_cost_col)), support_cost_source = curve_cost_col)]
  if (!is.na(curve_cpm_col)) {
    out[!is.finite(support_cost_per_unit), `:=`(
      support_cost_per_unit = opsp_num(get(curve_cpm_col)) / 1000,
      support_cost_source = curve_cpm_col
    )]
  }
  if (!"support_unit" %in% names(out)) out[, support_unit := NA_character_]
  if (nrow(scm)) {
    out[scm, `:=`(
      support_cost_per_unit = data.table::fifelse(is.finite(support_cost_per_unit), support_cost_per_unit, i.support_cost_per_unit),
      support_cost_source = data.table::fifelse(!is.na(support_cost_source) & nzchar(as.character(support_cost_source)), as.character(support_cost_source), i.support_cost_source),
      support_unit = data.table::fifelse(!is.na(support_unit) & nzchar(as.character(support_unit)), as.character(support_unit), i.support_unit)
    ), on = "variable"]
    if ("current_support_map" %in% names(scm)) {
      if (!"current_support" %in% names(out)) out[, current_support := NA_real_]
      out[scm, current_support := data.table::fifelse(is.finite(current_support), current_support, i.current_support_map), on = "variable"]
    }
    if ("current_spend_map" %in% names(scm)) {
      if (!"current_spend" %in% names(out)) out[, current_spend := NA_real_]
      out[scm, current_spend := data.table::fifelse(is.finite(current_spend), current_spend, i.current_spend_map), on = "variable"]
    }
  }
  if ("support" %in% names(out) && "support_cost_per_unit" %in% names(out)) {
    if (!"spend" %in% names(out)) out[, spend := NA_real_]
    out[!is.finite(spend) & is.finite(support) & is.finite(support_cost_per_unit),
        spend := support * support_cost_per_unit]
  }
  if ("current_support" %in% names(out) && "support_cost_per_unit" %in% names(out)) {
    if (!"current_spend" %in% names(out)) out[, current_spend := NA_real_]
    out[!is.finite(current_spend) & is.finite(current_support) & is.finite(support_cost_per_unit),
        current_spend := current_support * support_cost_per_unit]
  }
  out[]
}
