# 031-optimizer-curve-engine.R
# Generated by behavior-preserving split of optimizer_scenario_planner.R.

opsp_normalize_response_curves <- function(response_curves, support_cost_map = NULL) {
  rc <- opsp_as_dt(response_curves, "response_curves")
  if (!nrow(rc)) return(rc)
  vcol <- opsp_pick_col(rc, c("variable", "channel", "media", "driver"))
  if (is.na(vcol)) stop("response_curves must include variable/channel/media/driver.", call. = FALSE)
  if (!identical(vcol, "variable")) data.table::setnames(rc, vcol, "variable")
  mcol <- opsp_pick_col(rc, c("spend_multiplier", "support_multiplier", "multiplier", "scale", "omega"))
  scol <- opsp_pick_col(rc, c("spend", "planned_spend", "total_spend", "cost"))
  csc <- opsp_pick_col(rc, c("current_spend", "base_spend", "historical_spend"))
  sup_col <- opsp_pick_col(rc, c("support", "planned_support", "total_support", "media_support", "modeled_support"))
  cur_sup_col <- opsp_pick_col(rc, c("current_support", "base_support", "historical_support"))
  ccol <- opsp_pick_col(rc, c("contribution", "incremental_outcome", "expected_contribution", "expected_kpi", "outcome", "kpi"))
  if (is.na(ccol)) stop("response_curves must include contribution/incremental_outcome/expected_kpi.", call. = FALSE)
  if (!identical(ccol, "contribution")) data.table::setnames(rc, ccol, "contribution")
  aggregate_mode <- "mean"
  if ("scope" %in% names(rc) && any(tolower(as.character(rc$scope)) == "total", na.rm = TRUE)) {
    rc <- rc[tolower(as.character(scope)) == "total"]
  } else if ("group" %in% names(rc) && any(toupper(as.character(rc$group)) == "ALL", na.rm = TRUE)) {
    rc <- rc[toupper(as.character(group)) == "ALL"]
  } else if ("scope" %in% names(rc) || "group" %in% names(rc)) {
    aggregate_mode <- "sum_groups"
  }
  if (!is.na(scol) && !identical(scol, "spend")) data.table::setnames(rc, scol, "spend")
  if (!is.na(csc) && !identical(csc, "current_spend")) data.table::setnames(rc, csc, "current_spend")
  if (!is.na(sup_col) && !identical(sup_col, "support")) data.table::setnames(rc, sup_col, "support")
  if (!is.na(cur_sup_col) && !identical(cur_sup_col, "current_support")) data.table::setnames(rc, cur_sup_col, "current_support")
  rc <- opsp_apply_support_costs_to_curves(rc, support_cost_map = support_cost_map)
  if (!is.na(mcol)) {
    if (!identical(mcol, "spend_multiplier")) data.table::setnames(rc, mcol, "spend_multiplier")
    rc[, spend_multiplier := opsp_num(spend_multiplier)]
  } else if ("spend" %in% names(rc) && "current_spend" %in% names(rc)) {
    rc[, spend_multiplier := opsp_safe_div(spend, current_spend)]
  } else if ("support" %in% names(rc) && "current_support" %in% names(rc)) {
    rc[, spend_multiplier := opsp_safe_div(support, current_support)]
  } else {
    stop("response_curves must include a multiplier, spend plus current_spend, or support plus current_support.", call. = FALSE)
  }
  rc[, `:=`(
    variable = as.character(variable),
    spend_multiplier = opsp_num(spend_multiplier),
    contribution = opsp_num(contribution)
  )]
  score_col <- opsp_pick_col(rc, c("curve_evidence_score", "evidence_score_0_100", "evidence_score", "max_evidence_score", "mean_evidence_score"))
  band_col <- opsp_pick_col(rc, c("curve_confidence_band", "confidence_band", "best_confidence_band"))
  use_col <- opsp_pick_col(rc, c("curve_recommended_use", "recommended_use", "use_as", "prior_use"))
  source_col <- opsp_pick_col(rc, c("curve_source", "evidence_source", "source", "response_curve_basis"))
  level_col <- opsp_pick_col(rc, c("curve_evidence_level", "evidence_level", "evidence_tier"))
  if (!"curve_evidence_score" %in% names(rc)) rc[, curve_evidence_score := if (!is.na(score_col)) opsp_num(get(score_col)) else NA_real_]
  if (!"curve_confidence_band" %in% names(rc)) rc[, curve_confidence_band := if (!is.na(band_col)) as.character(get(band_col)) else NA_character_]
  if (!"curve_recommended_use" %in% names(rc)) rc[, curve_recommended_use := if (!is.na(use_col)) as.character(get(use_col)) else NA_character_]
  if (!"curve_source" %in% names(rc)) rc[, curve_source := if (!is.na(source_col)) as.character(get(source_col)) else NA_character_]
  if (!"curve_evidence_level" %in% names(rc)) {
    rc[, curve_evidence_level := if (!is.na(level_col)) as.character(get(level_col)) else NA_character_]
  }
  rc[, curve_evidence_score := opsp_num(curve_evidence_score)]
  rc[is.na(curve_evidence_level) | !nzchar(trimws(as.character(curve_evidence_level))), curve_evidence_level := data.table::fifelse(
    !is.na(curve_confidence_band) & nzchar(trimws(as.character(curve_confidence_band))),
    as.character(curve_confidence_band),
    opsp_evidence_level_from_score(curve_evidence_score)
  )]
  rc[is.na(curve_evidence_level) | !nzchar(trimws(as.character(curve_evidence_level))), curve_evidence_level := "unknown"]
  for (cc in c("response_curve_basis", "uncertainty_note", "flighting_assumption", "cost_assumption", "curve_type")) {
    if (!cc %in% names(rc)) rc[, (cc) := NA_character_]
  }
  rc[is.na(curve_source) | !nzchar(trimws(as.character(curve_source))), curve_source := response_curve_basis]
  if ("spend" %in% names(rc)) rc[, spend := opsp_num(spend)]
  if ("current_spend" %in% names(rc)) rc[, current_spend := opsp_num(current_spend)]
  if ("support" %in% names(rc)) rc[, support := opsp_num(support)]
  if ("current_support" %in% names(rc)) rc[, current_support := opsp_num(current_support)]
  if ("support_cost_per_unit" %in% names(rc)) rc[, support_cost_per_unit := opsp_num(support_cost_per_unit)]
  if (!"spend" %in% names(rc)) rc[, spend := NA_real_]
  if ("current_spend" %in% names(rc)) {
    rc[!is.finite(spend) & is.finite(current_spend) & is.finite(spend_multiplier),
       spend := current_spend * spend_multiplier]
  }
  rc <- rc[is.finite(spend_multiplier) & is.finite(contribution) & nzchar(variable)]
  if (!nrow(rc)) stop("response_curves has no finite variable/multiplier/contribution rows.", call. = FALSE)
  rc[, .(
    contribution = if (identical(aggregate_mode, "sum_groups")) sum(contribution, na.rm = TRUE) else mean(contribution, na.rm = TRUE),
    spend = if ("spend" %in% names(rc)) {
      if (identical(aggregate_mode, "sum_groups")) sum(spend, na.rm = TRUE) else mean(spend, na.rm = TRUE)
    } else NA_real_,
    current_spend = if ("current_spend" %in% names(rc)) {
      if (identical(aggregate_mode, "sum_groups")) sum(current_spend, na.rm = TRUE) else mean(current_spend, na.rm = TRUE)
    } else NA_real_,
    support = if ("support" %in% names(rc)) {
      if (identical(aggregate_mode, "sum_groups")) sum(support, na.rm = TRUE) else mean(support, na.rm = TRUE)
    } else NA_real_,
    current_support = if ("current_support" %in% names(rc)) {
      if (identical(aggregate_mode, "sum_groups")) sum(current_support, na.rm = TRUE) else mean(current_support, na.rm = TRUE)
    } else NA_real_,
    support_cost_per_unit = if ("support_cost_per_unit" %in% names(rc)) {
      mean(support_cost_per_unit, na.rm = TRUE)
    } else NA_real_,
    support_unit = if ("support_unit" %in% names(rc)) {
      paste(sort(unique(as.character(support_unit[!is.na(support_unit) & nzchar(as.character(support_unit))]))), collapse = "|")
    } else NA_character_,
    support_cost_source = if ("support_cost_source" %in% names(rc)) {
      paste(sort(unique(as.character(support_cost_source[!is.na(support_cost_source) & nzchar(as.character(support_cost_source))]))), collapse = "|")
    } else NA_character_,
    curve_evidence_level = opsp_first_nonblank(curve_evidence_level, "unknown"),
    curve_evidence_score = opsp_mean_or_na(curve_evidence_score),
    curve_confidence_band = opsp_first_nonblank(curve_confidence_band),
    curve_recommended_use = opsp_first_nonblank(curve_recommended_use),
    curve_source = opsp_first_nonblank(curve_source),
    curve_type = opsp_first_nonblank(curve_type),
    response_curve_basis = opsp_first_nonblank(response_curve_basis),
    uncertainty_note = opsp_first_nonblank(uncertainty_note),
    flighting_assumption = opsp_first_nonblank(flighting_assumption),
    cost_assumption = opsp_first_nonblank(cost_assumption)
  ), by = .(variable, spend_multiplier)][order(variable, spend_multiplier)]
}

opsp_normalize_response_curve_draws <- function(response_curve_draws, support_cost_map = NULL) {
  dc <- opsp_as_dt(response_curve_draws, "response_curve_draws")
  if (!nrow(dc)) return(data.table::data.table())
  dcol <- opsp_pick_col(dc, c(".draw", "draw", "posterior_draw", "sample", "iteration"))
  if (is.na(dcol)) return(data.table::data.table())
  if (!identical(dcol, ".draw")) data.table::setnames(dc, dcol, ".draw")
  dc[, .draw := as.character(.draw)]
  dc <- dc[nzchar(.draw)]
  if (!nrow(dc)) return(data.table::data.table())
  out <- data.table::rbindlist(lapply(unique(dc$.draw), function(dd) {
    tmp <- data.table::copy(dc[.draw == dd])
    tmp[, .draw := NULL]
    norm <- tryCatch(opsp_normalize_response_curves(tmp, support_cost_map = support_cost_map), error = function(e) data.table::data.table())
    if (nrow(norm)) norm[, .draw := dd]
    norm
  }), fill = TRUE)
  if (!nrow(out)) return(out)
  data.table::setcolorder(out, c(".draw", setdiff(names(out), ".draw")))
  out[order(variable, .draw, spend_multiplier)]
}

opsp_response_curve_engine <- function(response_curves, variables = NULL, constraints = NULL, support_cost_map = NULL) {
  rc <- opsp_normalize_response_curves(response_curves, support_cost_map = support_cost_map)
  if (!is.null(variables)) rc <- rc[variable %in% as.character(variables)]
  if (!nrow(rc)) stop("No response-curve rows remain for requested variables.", call. = FALSE)

  cur <- rc[, {
    cs <- current_spend[is.finite(current_spend) & current_spend >= 0]
    if (length(cs)) {
      current <- median(cs, na.rm = TRUE)
    } else if (any(abs(spend_multiplier - 1) <= 1e-8) && "spend" %in% names(.SD)) {
      current <- spend[which.min(abs(spend_multiplier - 1))]
    } else {
      current <- NA_real_
    }
    csp <- if ("current_support" %in% names(.SD)) current_support[is.finite(current_support) & current_support >= 0] else numeric()
    if (length(csp)) {
      current_support <- median(csp, na.rm = TRUE)
    } else if ("support" %in% names(.SD) && any(abs(spend_multiplier - 1) <= 1e-8)) {
      current_support <- support[which.min(abs(spend_multiplier - 1))]
    } else {
      current_support <- NA_real_
    }
    current_multiplier <- if (is.finite(current) && "spend" %in% names(.SD) && any(is.finite(spend))) {
      spend_ok <- is.finite(spend)
      spend_multiplier[spend_ok][which.min(abs(spend[spend_ok] - current))]
    } else {
      1
    }
    if (!is.finite(current_multiplier)) current_multiplier <- 1
    data.table::data.table(current_spend = current, current_support = current_support, current_multiplier = current_multiplier)
  }, by = variable]
  if (!is.null(constraints) && nrow(opsp_as_dt(constraints))) {
    cs <- opsp_as_dt(constraints)
    if ("variable" %in% names(cs) && "current_spend" %in% names(cs)) {
      cur[cs[, .(variable = as.character(variable), current_spend_override = opsp_num(current_spend))],
          current_spend := data.table::fifelse(is.finite(i.current_spend_override), i.current_spend_override, current_spend),
          on = "variable"]
    }
  }
  bad <- cur[!is.finite(current_spend) | current_spend < 0, variable]
  if (length(bad)) {
    stop("Could not infer current_spend for response-curve variables: ", paste(bad, collapse = ", "),
         ". Add current_spend to response_curves or constraints.", call. = FALSE)
  }

  eval_one <- function(variable, multiplier) {
    opsp_interp_curve_value(rc, variable, multiplier, "contribution", fallback = NA_real_)
  }
  spend_one <- function(variable, multiplier) {
    vv <- as.character(variable)[1]
    fallback <- cur[variable == vv, current_spend][1] * as.numeric(multiplier)[1]
    opsp_interp_curve_value(rc, variable, multiplier, "spend", fallback = fallback)
  }
  support_one <- function(variable, multiplier) {
    vv <- as.character(variable)[1]
    current_support <- cur[variable == vv, current_support][1]
    fallback <- if (is.finite(current_support)) current_support * as.numeric(multiplier)[1] else NA_real_
    opsp_interp_curve_value(rc, variable, multiplier, "support", fallback = fallback)
  }
  list(
    mode = "response_curve_table",
    variables = cur$variable,
    current_spend = stats::setNames(cur$current_spend, cur$variable),
    current_support = stats::setNames(cur$current_support, cur$variable),
    current_multiplier = stats::setNames(cur$current_multiplier, cur$variable),
    spend = spend_one,
    support = support_one,
    contribution = eval_one,
    source_table = rc
  )
}

opsp_response_curve_draws_from_inputs <- function(fit_obj = NULL,
                                                  response_curve_draws = NULL,
                                                  response_curves = NULL,
                                                  spend_map = NULL,
                                                  raw_data = NULL,
                                                  variables = NULL,
                                                  multiplier_grid = seq(0, 3, by = 0.05),
                                                  step_pct = 0.01,
                                                  spend_suffix = "_spend",
                                                  support_cost_map = NULL,
                                                  uncertainty = c("auto", "none", "draws"),
                                                  posterior_draw_count = 200L,
                                                  posterior_draw_seed = 123L) {
  uncertainty <- match.arg(uncertainty)
  if (identical(uncertainty, "none")) return(data.table::data.table())
  if (!is.null(response_curve_draws) && nrow(opsp_as_dt(response_curve_draws))) {
    return(opsp_normalize_response_curve_draws(response_curve_draws, support_cost_map = support_cost_map))
  }
  if (!is.null(response_curves) && nrow(opsp_as_dt(response_curves))) {
    from_rc <- opsp_normalize_response_curve_draws(response_curves, support_cost_map = support_cost_map)
    if (nrow(from_rc)) return(from_rc)
  }
  if (!is.null(fit_obj) && !is.null(fit_obj$response_curves_draws) && nrow(opsp_as_dt(fit_obj$response_curves_draws))) {
    return(opsp_normalize_response_curve_draws(fit_obj$response_curves_draws, support_cost_map = support_cost_map))
  }
  if (!is.null(fit_obj) && identical(uncertainty, "draws")) {
    opsp_source_hier_if_needed()
    if (exists("build_response_curves_draws_hier_mmm", mode = "function")) {
      draw_curves <- tryCatch(
        build_response_curves_draws_hier_mmm(
          fit_obj = fit_obj,
          spend_map = spend_map,
          raw_data = raw_data,
          variables = variables,
          multiplier_grid = multiplier_grid,
          step_pct = step_pct,
          spend_suffix = spend_suffix,
          max_draws = posterior_draw_count,
          seed = posterior_draw_seed
        ),
        error = function(e) {
          warning("Could not build posterior-draw response curves: ", conditionMessage(e), call. = FALSE)
          data.table::data.table()
        }
      )
      return(opsp_normalize_response_curve_draws(draw_curves, support_cost_map = support_cost_map))
    }
  }
  data.table::data.table()
}

opsp_fit_engine <- function(fit_obj, spend_map = NULL, raw_data = NULL,
                            variables = NULL, spend_suffix = "_spend",
                            support_cost_map = NULL) {
  opsp_source_hier_if_needed()
  vars <- opsp_infer_variables(fit_obj = fit_obj, variables = variables)
  existing_curves <- opsp_as_dt(fit_obj$response_curves, "fit_obj$response_curves")
  if (nrow(existing_curves)) {
    curve_vars <- if (is.null(variables)) NULL else vars
    curve_check <- opsp_normalize_response_curves(existing_curves, support_cost_map = support_cost_map)
    if (!is.null(curve_vars)) curve_check <- curve_check[variable %in% curve_vars]
    has_spend <- nrow(curve_check) &&
      "current_spend" %in% names(curve_check) &&
      all(curve_check[, any(is.finite(current_spend) & current_spend >= 0), by = variable]$V1)
    if (isTRUE(has_spend)) {
      eng <- opsp_response_curve_engine(existing_curves, variables = curve_vars, constraints = NULL, support_cost_map = support_cost_map)
      eng$mode <- "stan_response_curve_sheet"
      return(eng)
    }
  }
  sm <- normalize_spend_map_hier_mmm(fit_obj, spend_map = spend_map, raw_data = raw_data,
                                     spend_suffix = spend_suffix, variables = vars)
  if (!nrow(sm)) stop("MMM fit mode needs spend_map, metadata spend_col/cost_col, or inferable *_spend columns.", call. = FALSE)
  raw_aligned <- get_aligned_raw_data_hier_mmm(fit_obj, raw_data = raw_data)
  missing_cols <- sm[!(spend_col %in% names(raw_aligned)), spend_col]
  if (length(missing_cols)) stop("Spend columns missing from aligned raw data: ", paste(missing_cols, collapse = ", "), call. = FALSE)
  sm[, current_spend := vapply(spend_col, function(cc) sum(opsp_num(raw_aligned[[cc]]), na.rm = TRUE), numeric(1))]
  sm[, current_support := vapply(variable, function(vv) {
    if (vv %in% names(raw_aligned)) sum(opsp_num(raw_aligned[[vv]]), na.rm = TRUE) else NA_real_
  }, numeric(1))]
  sm <- sm[current_spend >= 0]
  if (!nrow(sm)) stop("No non-negative spend rows available for optimizer.", call. = FALSE)
  eval_one <- function(variable, multiplier) {
    variable_contribution_sum_hier_mmm(fit_obj, as.character(variable)[1], multiplier = as.numeric(multiplier)[1])
  }
  spend_one <- function(variable, multiplier) {
    sm[variable == as.character(variable)[1], current_spend][1] * as.numeric(multiplier)[1]
  }
  support_one <- function(variable, multiplier) {
    cur_support <- sm[variable == as.character(variable)[1], current_support][1]
    if (is.finite(cur_support)) cur_support * as.numeric(multiplier)[1] else NA_real_
  }
  list(
    mode = "stan_mmm_fit",
    variables = sm$variable,
    current_spend = stats::setNames(sm$current_spend, sm$variable),
    current_support = stats::setNames(sm$current_support, sm$variable),
    current_multiplier = stats::setNames(rep(1, nrow(sm)), sm$variable),
    spend_map = sm,
    spend = spend_one,
    support = support_one,
    contribution = eval_one,
    source_table = data.table::data.table()
  )
}

opsp_engine_from_inputs <- function(fit_obj = NULL,
                                    response_curves = NULL,
                                    spend_map = NULL,
                                    raw_data = NULL,
                                    variables = NULL,
                                    constraints = NULL,
                                    support_cost_map = NULL,
                                    spend_suffix = "_spend") {
  if (!is.null(fit_obj)) {
    return(opsp_fit_engine(fit_obj, spend_map = spend_map, raw_data = raw_data,
                           variables = variables, spend_suffix = spend_suffix,
                           support_cost_map = support_cost_map))
  }
  if (!is.null(response_curves) && nrow(opsp_as_dt(response_curves))) {
    return(opsp_response_curve_engine(response_curves, variables = variables, constraints = constraints, support_cost_map = support_cost_map))
  }
  stop("Pass either fit_obj or response_curves.", call. = FALSE)
}

opsp_spend_at <- function(engine, variable, multiplier) {
  if (!is.null(engine$spend) && is.function(engine$spend)) {
    return(engine$spend(as.character(variable)[1], as.numeric(multiplier)[1]))
  }
  engine$current_spend[[as.character(variable)[1]]] * as.numeric(multiplier)[1]
}

opsp_support_at <- function(engine, variable, multiplier) {
  if (!is.null(engine$support) && is.function(engine$support)) {
    return(engine$support(as.character(variable)[1], as.numeric(multiplier)[1]))
  }
  cs <- if (!is.null(engine$current_support)) engine$current_support[[as.character(variable)[1]]] else NA_real_
  if (is.finite(cs)) cs * as.numeric(multiplier)[1] else NA_real_
}

opsp_multiplier_for_support <- function(engine, variable, target_support) {
  v <- as.character(variable)[1]
  target_support <- opsp_num(target_support)[1]
  if (!is.finite(target_support) || target_support < 0) return(NA_real_)
  tbl <- if (!is.null(engine$source_table)) engine$source_table else data.table::data.table()
  if (nrow(tbl) && all(c("variable", "support", "spend_multiplier") %in% names(tbl))) {
    tmp <- tbl[variable == v & is.finite(support) & is.finite(spend_multiplier)]
    if (nrow(tmp) >= 2L) {
      data.table::setorder(tmp, support, spend_multiplier)
      tmp <- tmp[, .(spend_multiplier = mean(spend_multiplier, na.rm = TRUE)), by = support]
      if (nrow(tmp) >= 2L) {
        return(stats::approx(tmp$support, tmp$spend_multiplier, xout = target_support, rule = 2, ties = mean)$y)
      }
    } else if (nrow(tmp) == 1L && abs(tmp$support[1] - target_support) <= 1e-8) {
      return(tmp$spend_multiplier[1])
    }
  }
  current_support <- if (!is.null(engine$current_support) && v %in% names(engine$current_support)) engine$current_support[[v]] else NA_real_
  if (is.finite(current_support) && current_support > 1e-8) target_support / current_support else NA_real_
}

