# 034-optimizer-methods.R
# Generated by behavior-preserving split of optimizer_scenario_planner.R.

opsp_finalize_optimizer_plan <- function(engine,
                                         multipliers,
                                         cs,
                                         total_budget,
                                         min_required,
                                         max_possible,
                                         optimizer_basis,
                                         optimizer_iterations,
                                         allow_unallocated,
                                         allocation_history = NULL,
                                         step_pct = 0.01,
                                         value_per_kpi = NA_real_) {
  optimizer_basis_value <- as.character(optimizer_basis)[1]
  plan <- opsp_evaluate_scenario(engine, multipliers, "optimized",
                                 step_pct = step_pct, value_per_kpi = value_per_kpi)
  cur <- opsp_current_plan(engine, step_pct = step_pct, value_per_kpi = value_per_kpi)
  plan[cur[, .(variable, current_spend, current_support, current_contribution, current_roi, current_mroi)],
       on = "variable", `:=`(
         current_spend = i.current_spend,
         current_support = i.current_support,
         current_contribution = i.current_contribution,
         current_roi = i.current_roi,
         current_mroi = i.current_mroi
       )]
  plan[cs[, .(variable, min_multiplier, max_multiplier, locked)], on = "variable", `:=`(
    min_multiplier = i.min_multiplier,
    max_multiplier = i.max_multiplier,
    locked = i.locked
  )]
  data.table::setnames(plan, c("spend_multiplier", "spend", "support", "contribution", "roi", "mroi"),
                       c("recommended_multiplier", "recommended_spend", "recommended_support", "expected_contribution", "expected_roi", "expected_mroi"))
  plan[, `:=`(
    spend_change = recommended_spend - current_spend,
    spend_change_pct = opsp_safe_div(recommended_spend - current_spend, current_spend),
    contribution_change = expected_contribution - current_contribution,
    total_budget = total_budget,
    optimizer_basis = optimizer_basis_value
  )]
  summary <- plan[, .(
    total_budget = total_budget[1],
    current_spend = sum(current_spend, na.rm = TRUE),
    recommended_spend = sum(recommended_spend, na.rm = TRUE),
    current_support = if (any(is.finite(current_support))) sum(current_support, na.rm = TRUE) else NA_real_,
    recommended_support = if (any(is.finite(recommended_support))) sum(recommended_support, na.rm = TRUE) else NA_real_,
    unallocated_budget = pmax(total_budget[1] - sum(recommended_spend, na.rm = TRUE), 0),
    current_contribution = sum(current_contribution, na.rm = TRUE),
    expected_contribution = sum(expected_contribution, na.rm = TRUE),
    incremental_contribution = sum(contribution_change, na.rm = TRUE),
    current_roi = opsp_safe_div(sum(current_contribution, na.rm = TRUE), sum(current_spend, na.rm = TRUE)),
    expected_roi = opsp_safe_div(sum(expected_contribution, na.rm = TRUE), sum(recommended_spend, na.rm = TRUE)),
    current_cost_per_kpi = ifelse(sum(current_contribution, na.rm = TRUE) > 1e-8,
                                  sum(current_spend, na.rm = TRUE) / sum(current_contribution, na.rm = TRUE),
                                  NA_real_),
    expected_cost_per_kpi = ifelse(sum(expected_contribution, na.rm = TRUE) > 1e-8,
                                   sum(recommended_spend, na.rm = TRUE) / sum(expected_contribution, na.rm = TRUE),
                                   NA_real_),
    optimizer_iterations = optimizer_iterations,
    min_required_budget = min_required,
    max_possible_budget = max_possible,
    allow_unallocated = isTRUE(allow_unallocated),
    optimizer_basis = optimizer_basis_value,
    min_curve_evidence_score = if ("curve_evidence_score" %in% names(plan) && any(is.finite(curve_evidence_score))) min(curve_evidence_score, na.rm = TRUE) else NA_real_,
    weak_curve_count = if ("curve_evidence_level" %in% names(plan)) {
      sum(curve_evidence_level %in% c("weak", "diagnostic", "unknown") |
            !is.finite(if ("curve_evidence_score" %in% names(plan)) curve_evidence_score else NA_real_), na.rm = TRUE)
    } else NA_integer_,
    curve_evidence_summary = if ("curve_evidence_level" %in% names(plan)) paste(sort(unique(curve_evidence_level[!is.na(curve_evidence_level) & nzchar(as.character(curve_evidence_level))])), collapse = "|") else NA_character_
  )]
  hist <- if (is.null(allocation_history)) data.table::data.table() else data.table::as.data.table(allocation_history)
  list(
    plan = plan[order(-recommended_spend)][],
    summary = summary[],
    allocation_history = hist[]
  )
}

opsp_build_group_rollup <- function(engine,
                                    optimization_plan,
                                    variable_group_map = NULL,
                                    group_constraints = NULL,
                                    total_budget = NA_real_) {
  plan <- opsp_as_dt(optimization_plan, "optimization_plan")
  if (!nrow(plan) || !"variable" %in% names(plan)) return(data.table::data.table())
  vars <- unique(as.character(plan$variable))
  gm <- opsp_normalize_variable_group_map(vars, variable_group_map)
  plan[gm, planning_group := i.planning_group, on = "variable"]
  plan[!nzchar(planning_group) | is.na(planning_group), planning_group := variable]
  needed <- c("current_spend", "recommended_spend", "current_support", "recommended_support",
              "current_contribution", "expected_contribution", "contribution_change")
  for (cc in setdiff(needed, names(plan))) plan[, (cc) := NA_real_]
  rollup <- plan[, .(
    variable_count = data.table::uniqueN(variable),
    variables = paste(sort(unique(variable)), collapse = "|"),
    current_spend = sum(current_spend, na.rm = TRUE),
    recommended_spend = sum(recommended_spend, na.rm = TRUE),
    current_support = if (any(is.finite(current_support))) sum(current_support, na.rm = TRUE) else NA_real_,
    recommended_support = if (any(is.finite(recommended_support))) sum(recommended_support, na.rm = TRUE) else NA_real_,
    current_contribution = sum(current_contribution, na.rm = TRUE),
    expected_contribution = sum(expected_contribution, na.rm = TRUE),
    contribution_change = sum(contribution_change, na.rm = TRUE)
  ), by = planning_group]
  total_budget <- opsp_num(total_budget)[1]
  recommended_total <- rollup[, sum(recommended_spend, na.rm = TRUE)]
  current_total <- rollup[, sum(current_spend, na.rm = TRUE)]
  rollup[, `:=`(
    spend_change = recommended_spend - current_spend,
    spend_change_pct = opsp_safe_div(recommended_spend - current_spend, current_spend),
    current_share = opsp_safe_div(current_spend, current_total),
    recommended_share = opsp_safe_div(recommended_spend, recommended_total),
    target_budget_share = if (is.finite(total_budget) && total_budget > 0) recommended_spend / total_budget else NA_real_,
    current_roi = opsp_safe_div(current_contribution, current_spend),
    expected_roi = opsp_safe_div(expected_contribution, recommended_spend),
    current_cost_per_kpi = ifelse(current_contribution > 1e-8, current_spend / current_contribution, NA_real_),
    expected_cost_per_kpi = ifelse(expected_contribution > 1e-8, recommended_spend / expected_contribution, NA_real_)
  )]
  gc <- opsp_normalize_group_constraints(group_constraints, total_budget = total_budget)
  if (nrow(gc)) {
    rollup[gc, `:=`(
      min_spend = i.min_spend,
      max_spend = i.max_spend,
      fixed_spend = i.fixed_spend,
      min_share = i.min_share,
      max_share = i.max_share
    ), on = "planning_group"]
    missing_groups <- setdiff(gc$planning_group, rollup$planning_group)
    if (length(missing_groups)) {
      rollup <- data.table::rbindlist(list(
        rollup,
        gc[planning_group %in% missing_groups, .(
          planning_group,
          variable_count = 0L,
          variables = "",
          current_spend = 0,
          recommended_spend = 0,
          current_support = NA_real_,
          recommended_support = NA_real_,
          current_contribution = 0,
          expected_contribution = 0,
          contribution_change = 0,
          spend_change = 0,
          spend_change_pct = NA_real_,
          current_share = 0,
          recommended_share = 0,
          target_budget_share = 0,
          current_roi = NA_real_,
          expected_roi = NA_real_,
          current_cost_per_kpi = NA_real_,
          expected_cost_per_kpi = NA_real_,
          min_spend,
          max_spend,
          fixed_spend,
          min_share,
          max_share
        )]
      ), fill = TRUE)
    }
  }
  for (cc in c("min_spend", "max_spend", "fixed_spend", "min_share", "max_share")) {
    if (!cc %in% names(rollup)) rollup[, (cc) := NA_real_]
  }
  rollup[, `:=`(
    min_violation = data.table::fifelse(is.finite(min_spend), pmax(min_spend - recommended_spend, 0), 0),
    max_violation = data.table::fifelse(is.finite(max_spend), pmax(recommended_spend - max_spend, 0), 0)
  )]
  rollup[, `:=`(
    group_constraint_ok = min_violation <= 1e-6 & max_violation <= 1e-6,
    group_constraint_status = data.table::fifelse(min_violation > 1e-6, "below_minimum",
                                                  data.table::fifelse(max_violation > 1e-6, "above_maximum", "ok"))
  )]
  rollup[order(planning_group)][]
}

opsp_optimize_greedy <- function(engine,
                                 constraints = NULL,
                                 total_budget = NULL,
                                 budget_change_pct = 0,
                                 budget_step_frac = 0.005,
                                 min_multiplier = 0,
                                 max_multiplier = 3,
                                 max_iter = 5000,
                                 allow_unallocated = FALSE,
                                 step_pct = 0.01,
                                 value_per_kpi = NA_real_) {
  vars <- engine$variables
  cur_spend <- as.numeric(engine$current_spend[vars])
  cs <- opsp_normalize_constraints(vars, cur_spend, constraints = constraints,
                                   min_multiplier = min_multiplier, max_multiplier = max_multiplier)
  if (is.null(total_budget)) total_budget <- sum(cur_spend, na.rm = TRUE) * (1 + opsp_num(budget_change_pct)[1])
  total_budget <- opsp_num(total_budget)[1]
  if (!is.finite(total_budget) || total_budget < 0) stop("total_budget must be finite and non-negative.", call. = FALSE)
  min_required <- cs[, sum(current_spend * min_multiplier, na.rm = TRUE)]
  max_possible <- cs[, sum(current_spend * max_multiplier, na.rm = TRUE)]
  if (total_budget + 1e-8 < min_required) {
    stop("total_budget is below required minimum spend from constraints. Minimum required: ", round(min_required, 4), call. = FALSE)
  }

  multipliers <- stats::setNames(cs$min_multiplier, cs$variable)
  remaining <- min(total_budget, max_possible) - min_required
  chunk <- max(total_budget * budget_step_frac, total_budget / max_iter, 1e-8)
  history <- list()
  iter <- 0L
  while (remaining > 1e-8 && iter < max_iter) {
    iter <- iter + 1L
    cand <- lapply(seq_len(nrow(cs)), function(i) {
      v <- cs$variable[i]
      if (cs$current_spend[i] <= 1e-8) return(NULL)
      cur_m <- multipliers[v]
      if (cur_m >= cs$max_multiplier[i] - 1e-8) return(NULL)
      add_spend <- min(chunk, remaining, cs$current_spend[i] * (cs$max_multiplier[i] - cur_m))
      if (add_spend <= 1e-8) return(NULL)
      delta_m <- add_spend / cs$current_spend[i]
      base <- engine$contribution(v, cur_m)
      up <- engine$contribution(v, cur_m + delta_m)
      data.table::data.table(
        variable = v,
        add_spend = add_spend,
        delta_multiplier = delta_m,
        incremental_contribution = up - base,
        marginal_response = opsp_safe_div(up - base, add_spend)
      )
    })
    cand <- data.table::rbindlist(cand, fill = TRUE)
    if (!nrow(cand)) break
    cand <- cand[order(-marginal_response)]
    best <- cand[1]
    if (isTRUE(allow_unallocated) && (!is.finite(best$marginal_response) || best$marginal_response <= 0)) break
    multipliers[best$variable] <- multipliers[best$variable] + best$delta_multiplier
    remaining <- remaining - best$add_spend
    history[[iter]] <- best[, optimizer_iteration := iter]
  }
  opsp_finalize_optimizer_plan(
    engine = engine,
    multipliers = multipliers,
    cs = cs,
    total_budget = total_budget,
    min_required = min_required,
    max_possible = max_possible,
    optimizer_basis = paste0(engine$mode, "_greedy_marginal_point_estimate"),
    optimizer_iterations = iter,
    allow_unallocated = allow_unallocated,
    allocation_history = if (length(history)) data.table::rbindlist(history, fill = TRUE) else data.table::data.table(),
    step_pct = step_pct,
    value_per_kpi = value_per_kpi
  )
}

opsp_multiplier_grid_values <- function(lo, hi, step) {
  lo <- as.numeric(lo)[1]
  hi <- as.numeric(hi)[1]
  step <- as.numeric(step)[1]
  if (!is.finite(lo) || !is.finite(hi) || hi < lo) return(lo)
  if (!is.finite(step) || step <= 0) stop("optimization_grid_step must be positive.", call. = FALSE)
  vals <- seq(lo, hi, by = step)
  if (!length(vals) || abs(vals[length(vals)] - hi) > 1e-8) vals <- c(vals, hi)
  unique(round(vals, 10))
}

opsp_optimize_grid <- function(engine,
                               constraints = NULL,
                               variable_group_map = NULL,
                               group_constraints = NULL,
                               total_budget = NULL,
                               budget_change_pct = 0,
                               optimization_grid_step = 0.05,
                               max_grid_combinations = 250000L,
                               min_multiplier = 0,
                               max_multiplier = 3,
                               allow_unallocated = FALSE,
                               step_pct = 0.01,
                               value_per_kpi = NA_real_) {
  vars <- engine$variables
  cur_spend <- as.numeric(engine$current_spend[vars])
  cs <- opsp_normalize_constraints(vars, cur_spend, constraints = constraints,
                                   min_multiplier = min_multiplier, max_multiplier = max_multiplier)
  if (is.null(total_budget)) total_budget <- sum(cur_spend, na.rm = TRUE) * (1 + opsp_num(budget_change_pct)[1])
  total_budget <- opsp_num(total_budget)[1]
  if (!is.finite(total_budget) || total_budget < 0) stop("total_budget must be finite and non-negative.", call. = FALSE)
  min_required <- cs[, sum(vapply(seq_len(.N), function(i) opsp_spend_at(engine, variable[i], min_multiplier[i]), numeric(1)), na.rm = TRUE)]
  max_possible <- cs[, sum(vapply(seq_len(.N), function(i) opsp_spend_at(engine, variable[i], max_multiplier[i]), numeric(1)), na.rm = TRUE)]
  if (total_budget + 1e-8 < min_required) {
    stop("total_budget is below required minimum spend from constraints. Minimum required: ", round(min_required, 4), call. = FALSE)
  }

  grid_values <- stats::setNames(
    lapply(seq_len(nrow(cs)), function(i) opsp_multiplier_grid_values(cs$min_multiplier[i], cs$max_multiplier[i], optimization_grid_step)),
    cs$variable
  )
  combination_count <- prod(vapply(grid_values, length, integer(1)))
  if (!is.finite(combination_count) || combination_count > as.numeric(max_grid_combinations)[1]) {
    stop(
      "Grid optimizer would evaluate ", format(combination_count, scientific = FALSE),
      " combinations. Increase optimization_grid_step, reduce variables, tighten constraints, ",
      "or increase max_grid_combinations deliberately.",
      call. = FALSE
    )
  }
  grid <- data.table::as.data.table(do.call(expand.grid, c(grid_values, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)))
  if (!nrow(grid)) stop("Grid optimizer has no candidate allocations.", call. = FALSE)
  spend_mat <- vapply(vars, function(v) vapply(grid[[v]], function(m) opsp_spend_at(engine, v, m), numeric(1)), numeric(nrow(grid)))
  contrib_mat <- vapply(vars, function(v) vapply(grid[[v]], function(m) engine$contribution(v, m), numeric(1)), numeric(nrow(grid)))
  grid[, candidate_spend := rowSums(spend_mat, na.rm = TRUE)]
  grid[, candidate_contribution := rowSums(contrib_mat, na.rm = TRUE)]
  feasible_budget <- min(total_budget, max_possible)
  feasible <- grid[candidate_spend <= feasible_budget + 1e-8 & candidate_spend + 1e-8 >= min_required]
  channel_filtered_count <- 0L
  if (nrow(feasible)) {
    channel_status <- data.table::rbindlist(lapply(seq_len(nrow(feasible)), function(i) {
      mult <- stats::setNames(as.numeric(feasible[i, ..vars]), vars)
      st <- opsp_channel_constraint_status(engine, vars, mult, cs)
      data.table::data.table(candidate_id = i, channel_constraint_ok = st$ok, channel_constraint_max_violation = st$max_violation)
    }), fill = TRUE)
    feasible[, candidate_id := seq_len(.N)]
    feasible[channel_status, `:=`(
      channel_constraint_ok = i.channel_constraint_ok,
      channel_constraint_max_violation = i.channel_constraint_max_violation
    ), on = "candidate_id"]
    channel_filtered_count <- feasible[is.na(channel_constraint_ok) | channel_constraint_ok != TRUE, .N]
    feasible <- feasible[channel_constraint_ok == TRUE]
  }
  gc <- opsp_normalize_group_constraints(group_constraints, total_budget = total_budget)
  group_filtered_count <- 0L
  if (nrow(gc) && nrow(feasible)) {
    group_status <- data.table::rbindlist(lapply(seq_len(nrow(feasible)), function(i) {
      mult <- stats::setNames(as.numeric(feasible[i, ..vars]), vars)
      st <- opsp_group_constraint_status(
        engine = engine,
        vars = vars,
        multipliers = mult,
        variable_group_map = variable_group_map,
        group_constraints = gc,
        total_budget = total_budget
      )
      data.table::data.table(candidate_id = i, group_constraint_ok = st$ok, group_constraint_max_violation = st$max_violation)
    }), fill = TRUE)
    feasible[, candidate_id := seq_len(.N)]
    feasible[group_status, `:=`(
      group_constraint_ok = i.group_constraint_ok,
      group_constraint_max_violation = i.group_constraint_max_violation
    ), on = "candidate_id"]
    group_filtered_count <- feasible[is.na(group_constraint_ok) | group_constraint_ok != TRUE, .N]
    feasible <- feasible[group_constraint_ok == TRUE]
  }
  if (!nrow(feasible)) {
    stop("No feasible grid allocation satisfies budget, channel constraints, and group constraints. Try a smaller optimization_grid_step or relax constraints.", call. = FALSE)
  }
  feasible[, budget_gap_abs := abs(candidate_spend - feasible_budget)]
  if (!isTRUE(allow_unallocated)) {
    best_spend <- feasible[, max(candidate_spend, na.rm = TRUE)]
    feasible <- feasible[candidate_spend >= best_spend - max(optimization_grid_step * max(cur_spend, na.rm = TRUE), 1e-8)]
  }
  data.table::setorder(feasible, -candidate_contribution, budget_gap_abs)
  best <- feasible[1]
  multipliers <- stats::setNames(as.numeric(best[, ..vars]), vars)
  hist <- data.table::data.table(
    optimizer_method = "grid",
    searched_combinations = as.numeric(combination_count),
    feasible_combinations = nrow(feasible),
    channel_constraint_filtered_combinations = channel_filtered_count,
    group_constraint_filtered_combinations = group_filtered_count,
    optimization_grid_step = as.numeric(optimization_grid_step)[1],
    selected_spend = best$candidate_spend[1],
    selected_contribution = best$candidate_contribution[1]
  )
  opsp_finalize_optimizer_plan(
    engine = engine,
    multipliers = multipliers,
    cs = cs,
    total_budget = total_budget,
    min_required = min_required,
    max_possible = max_possible,
    optimizer_basis = paste0(engine$mode, "_grid_search_point_estimate"),
    optimizer_iterations = as.integer(combination_count),
    allow_unallocated = allow_unallocated,
    allocation_history = hist,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi
  )
}

opsp_draw_metrics_for_multipliers <- function(draw_curves,
                                              vars,
                                              multipliers,
                                              step_pct = 0.01,
                                              value_per_kpi = NA_real_,
                                              normalize = TRUE) {
  dc <- if (isTRUE(normalize)) opsp_normalize_response_curve_draws(draw_curves) else data.table::as.data.table(draw_curves)
  if (!nrow(dc)) return(data.table::data.table())
  vars <- intersect(as.character(vars), unique(dc$variable))
  if (!length(vars)) return(data.table::data.table())
  mult <- stats::setNames(rep(1, length(vars)), vars)
  if (!is.null(names(multipliers))) {
    hit <- intersect(names(multipliers), vars)
    mult[hit] <- opsp_num(multipliers[hit])
  } else if (length(multipliers) == length(vars)) {
    mult[] <- opsp_num(multipliers)
  }
  mult[!is.finite(mult) | mult < 0] <- 0
  raw <- data.table::rbindlist(lapply(unique(dc$.draw), function(dd) {
    data.table::rbindlist(lapply(vars, function(v) {
      opsp_eval_draw_curve_variable(
        dc,
        draw_id = dd,
        variable = v,
        multiplier = mult[v],
        step_pct = step_pct,
        value_per_kpi = value_per_kpi
      )
    }), fill = TRUE)
  }), fill = TRUE)
  if (!nrow(raw)) return(data.table::data.table())
  raw[, .(
    spend = sum(spend, na.rm = TRUE),
    spend_vs_current = sum(spend_vs_current, na.rm = TRUE),
    contribution = sum(contribution, na.rm = TRUE),
    contribution_vs_current = sum(contribution_vs_current, na.rm = TRUE),
    profit = sum(profit, na.rm = TRUE),
    incremental_profit = sum(incremental_profit, na.rm = TRUE)
  ), by = .draw][, `:=`(
    roi = opsp_safe_div(contribution, spend),
    incremental_roi = opsp_safe_div(contribution_vs_current, spend_vs_current),
    cost_per_kpi = ifelse(is.finite(contribution) & contribution > 1e-8, spend / contribution, NA_real_),
    value_per_cost = ifelse(is.finite(value_per_kpi) & is.finite(spend) & abs(spend) > 1e-8,
                            contribution * value_per_kpi / spend, NA_real_)
  )][]
}

opsp_robust_objective_score <- function(draw_metrics,
                                        robust_objective = "q05_contribution",
                                        robust_quantile = 0.05,
                                        robust_target_contribution = NULL,
                                        robust_target_cost_per_kpi = NULL,
                                        robust_target_roi = NULL,
                                        robust_risk_aversion = 0) {
  dm <- opsp_as_dt(draw_metrics, "draw_metrics")
  if (!nrow(dm)) return(list(score = NA_real_, summary = data.table::data.table()))
  robust_quantile <- opsp_validate_quantile(robust_quantile, fallback = 0.05)
  obj <- match.arg(
    as.character(robust_objective)[1],
    opsp_robust_objective_choices()
  )
  for (cc in c("spend_vs_current", "incremental_roi", "profit", "incremental_profit")) {
    if (!cc %in% names(dm)) dm[, (cc) := NA_real_]
  }
  contribution_mean <- mean(dm$contribution, na.rm = TRUE)
  incremental_contribution_mean <- opsp_mean_finite(dm$contribution_vs_current)
  contribution_sd <- stats::sd(dm$contribution[is.finite(dm$contribution)], na.rm = TRUE)
  if (!is.finite(contribution_sd)) contribution_sd <- 0
  cost_q95 <- opsp_quantile(dm$cost_per_kpi, 0.95)
  roi_q05 <- opsp_quantile(dm$roi, 0.05)
  incremental_roi_q <- opsp_quantile(dm$incremental_roi, robust_quantile)
  profit_mean <- opsp_mean_finite(dm$profit)
  profit_q <- opsp_quantile(dm$profit, robust_quantile)
  profit_probability <- opsp_probability_positive(dm$profit)
  incremental_contribution_probability <- opsp_probability_positive(dm$contribution_vs_current)
  target_contribution <- suppressWarnings(as.numeric(robust_target_contribution)[1])
  target_cost <- suppressWarnings(as.numeric(robust_target_cost_per_kpi)[1])
  target_roi <- suppressWarnings(as.numeric(robust_target_roi)[1])
  target_ok <- rep(TRUE, nrow(dm))
  if (is.finite(target_contribution)) target_ok <- target_ok & is.finite(dm$contribution) & dm$contribution >= target_contribution
  if (is.finite(target_cost)) target_ok <- target_ok & is.finite(dm$cost_per_kpi) & dm$cost_per_kpi <= target_cost
  if (is.finite(target_roi)) target_ok <- target_ok & is.finite(dm$roi) & dm$roi >= target_roi
  target_probability <- mean(target_ok, na.rm = TRUE)
  score <- switch(
    obj,
    q05_contribution = opsp_quantile(dm$contribution, robust_quantile),
    q50_contribution = opsp_quantile(dm$contribution, 0.50),
    mean_contribution = contribution_mean,
    q05_incremental_contribution = opsp_quantile(dm$contribution_vs_current, robust_quantile),
    quantile_incremental_contribution = opsp_quantile(dm$contribution_vs_current, robust_quantile),
    mean_incremental_contribution = incremental_contribution_mean,
    expected_utility = contribution_mean - pmax(suppressWarnings(as.numeric(robust_risk_aversion)[1]), 0) * contribution_sd,
    probability_target = {
      if (!is.finite(target_contribution) && !is.finite(target_cost) && !is.finite(target_roi)) {
        stop("robust_objective = 'probability_target' requires robust_target_contribution, robust_target_cost_per_kpi, or robust_target_roi.", call. = FALSE)
      }
      target_probability
    },
    q05_roi = roi_q05,
    q05_incremental_roi = incremental_roi_q,
    quantile_incremental_roi = incremental_roi_q,
    q95_cost_per_kpi = -cost_q95,
    expected_profit = profit_mean,
    q05_profit = profit_q,
    quantile_profit = profit_q,
    probability_profit_positive = profit_probability,
    probability_incremental_contribution_positive = incremental_contribution_probability
  )
  summary <- data.table::data.table(
    robust_objective = obj,
    robust_score = score,
    draw_n = uniqueN(dm$.draw),
    robust_quantile = robust_quantile,
    contribution_q05 = opsp_quantile(dm$contribution, 0.05),
    contribution_q50 = opsp_quantile(dm$contribution, 0.50),
    contribution_q95 = opsp_quantile(dm$contribution, 0.95),
    contribution_q_custom = opsp_quantile(dm$contribution, robust_quantile),
    contribution_mean = contribution_mean,
    incremental_contribution_q05 = opsp_quantile(dm$contribution_vs_current, 0.05),
    q05_incremental_contribution = opsp_quantile(dm$contribution_vs_current, 0.05),
    incremental_contribution_q_custom = opsp_quantile(dm$contribution_vs_current, robust_quantile),
    mean_incremental_contribution = incremental_contribution_mean,
    probability_incremental_contribution_positive = incremental_contribution_probability,
    contribution_sd = contribution_sd,
    roi_q05 = roi_q05,
    roi_q50 = opsp_quantile(dm$roi, 0.50),
    roi_q95 = opsp_quantile(dm$roi, 0.95),
    roi_q_custom = opsp_quantile(dm$roi, robust_quantile),
    incremental_roi_q05 = opsp_quantile(dm$incremental_roi, 0.05),
    q05_incremental_roi = opsp_quantile(dm$incremental_roi, 0.05),
    incremental_roi_q_custom = incremental_roi_q,
    cost_per_kpi_q05 = opsp_quantile(dm$cost_per_kpi, 0.05),
    cost_per_kpi_q50 = opsp_quantile(dm$cost_per_kpi, 0.50),
    cost_per_kpi_q95 = cost_q95,
    expected_profit = profit_mean,
    profit_q05 = opsp_quantile(dm$profit, 0.05),
    q05_profit = opsp_quantile(dm$profit, 0.05),
    profit_q_custom = profit_q,
    expected_incremental_profit = opsp_mean_finite(dm$incremental_profit),
    incremental_profit_q05 = opsp_quantile(dm$incremental_profit, 0.05),
    incremental_profit_q_custom = opsp_quantile(dm$incremental_profit, robust_quantile),
    probability_profit_positive = profit_probability,
    target_probability = target_probability
  )
  list(score = score, summary = summary)
}

opsp_optimize_robust_grid <- function(engine,
                                      draw_curves,
                                      constraints = NULL,
                                      variable_group_map = NULL,
                                      group_constraints = NULL,
                                      total_budget = NULL,
                                      budget_change_pct = 0,
                                      optimization_grid_step = 0.10,
                                      max_grid_combinations = 50000L,
                                      min_multiplier = 0,
                                      max_multiplier = 3,
                                      allow_unallocated = FALSE,
                                      robust_objective = opsp_robust_objective_choices(),
                                      robust_quantile = 0.05,
                                      robust_target_contribution = NULL,
                                      robust_target_cost_per_kpi = NULL,
                                      robust_target_roi = NULL,
                                      robust_risk_aversion = 0,
                                      step_pct = 0.01,
                                      value_per_kpi = NA_real_) {
  robust_objective <- match.arg(robust_objective)
  dc <- opsp_normalize_response_curve_draws(draw_curves)
  if (!nrow(dc)) {
    stop("optimizer_method = 'robust_grid' requires draw-level response curves. Pass response_curve_draws, fit$response_curves_draws, or use uncertainty = 'draws' with a Stan fit.", call. = FALSE)
  }
  vars <- intersect(engine$variables, unique(dc$variable))
  if (!length(vars)) stop("Draw-level response curves do not contain any optimizer variables.", call. = FALSE)
  cur_spend <- as.numeric(engine$current_spend[vars])
  cs <- opsp_normalize_constraints(vars, cur_spend, constraints = constraints,
                                   min_multiplier = min_multiplier, max_multiplier = max_multiplier)
  if (is.null(total_budget)) total_budget <- sum(cur_spend, na.rm = TRUE) * (1 + opsp_num(budget_change_pct)[1])
  total_budget <- opsp_num(total_budget)[1]
  if (!is.finite(total_budget) || total_budget < 0) stop("total_budget must be finite and non-negative.", call. = FALSE)
  min_required <- cs[, sum(vapply(seq_len(.N), function(i) opsp_spend_at(engine, variable[i], min_multiplier[i]), numeric(1)), na.rm = TRUE)]
  max_possible <- cs[, sum(vapply(seq_len(.N), function(i) opsp_spend_at(engine, variable[i], max_multiplier[i]), numeric(1)), na.rm = TRUE)]
  if (total_budget + 1e-8 < min_required) {
    stop("total_budget is below required minimum spend from constraints. Minimum required: ", round(min_required, 4), call. = FALSE)
  }
  grid_values <- stats::setNames(
    lapply(seq_len(nrow(cs)), function(i) opsp_multiplier_grid_values(cs$min_multiplier[i], cs$max_multiplier[i], optimization_grid_step)),
    cs$variable
  )
  combination_count <- prod(vapply(grid_values, length, integer(1)))
  if (!is.finite(combination_count) || combination_count > as.numeric(max_grid_combinations)[1]) {
    stop(
      "Robust grid optimizer would evaluate ", format(combination_count, scientific = FALSE),
      " combinations across posterior draws. Increase optimization_grid_step, tighten constraints, ",
      "or increase max_grid_combinations deliberately.",
      call. = FALSE
    )
  }
  grid <- data.table::as.data.table(do.call(expand.grid, c(grid_values, KEEP.OUT.ATTRS = FALSE, stringsAsFactors = FALSE)))
  if (!nrow(grid)) stop("Robust grid optimizer has no candidate allocations.", call. = FALSE)
  spend_mat <- vapply(vars, function(v) vapply(grid[[v]], function(m) opsp_spend_at(engine, v, m), numeric(1)), numeric(nrow(grid)))
  grid[, candidate_spend := rowSums(spend_mat, na.rm = TRUE)]
  feasible_budget <- min(total_budget, max_possible)
  feasible <- grid[candidate_spend <= feasible_budget + 1e-8 & candidate_spend + 1e-8 >= min_required]
  channel_filtered_count <- 0L
  if (nrow(feasible)) {
    channel_status <- data.table::rbindlist(lapply(seq_len(nrow(feasible)), function(i) {
      mult <- stats::setNames(as.numeric(feasible[i, ..vars]), vars)
      st <- opsp_channel_constraint_status(engine, vars, mult, cs)
      data.table::data.table(candidate_id = i, channel_constraint_ok = st$ok, channel_constraint_max_violation = st$max_violation)
    }), fill = TRUE)
    feasible[, candidate_id := seq_len(.N)]
    feasible[channel_status, `:=`(
      channel_constraint_ok = i.channel_constraint_ok,
      channel_constraint_max_violation = i.channel_constraint_max_violation
    ), on = "candidate_id"]
    channel_filtered_count <- feasible[is.na(channel_constraint_ok) | channel_constraint_ok != TRUE, .N]
    feasible <- feasible[channel_constraint_ok == TRUE]
  }
  gc <- opsp_normalize_group_constraints(group_constraints, total_budget = total_budget)
  group_filtered_count <- 0L
  if (nrow(gc) && nrow(feasible)) {
    group_status <- data.table::rbindlist(lapply(seq_len(nrow(feasible)), function(i) {
      mult <- stats::setNames(as.numeric(feasible[i, ..vars]), vars)
      st <- opsp_group_constraint_status(
        engine = engine,
        vars = vars,
        multipliers = mult,
        variable_group_map = variable_group_map,
        group_constraints = gc,
        total_budget = total_budget
      )
      data.table::data.table(candidate_id = i, group_constraint_ok = st$ok, group_constraint_max_violation = st$max_violation)
    }), fill = TRUE)
    feasible[, candidate_id := seq_len(.N)]
    feasible[group_status, `:=`(
      group_constraint_ok = i.group_constraint_ok,
      group_constraint_max_violation = i.group_constraint_max_violation
    ), on = "candidate_id"]
    group_filtered_count <- feasible[is.na(group_constraint_ok) | group_constraint_ok != TRUE, .N]
    feasible <- feasible[group_constraint_ok == TRUE]
  }
  if (!nrow(feasible)) {
    stop("No feasible robust-grid allocation satisfies budget, channel constraints, and group constraints. Try a smaller optimization_grid_step or relax constraints.", call. = FALSE)
  }
  if (!isTRUE(allow_unallocated)) {
    best_spend <- feasible[, max(candidate_spend, na.rm = TRUE)]
    feasible <- feasible[candidate_spend >= best_spend - max(optimization_grid_step * max(cur_spend, na.rm = TRUE), 1e-8)]
  }
  scores <- data.table::rbindlist(lapply(seq_len(nrow(feasible)), function(i) {
    mult <- stats::setNames(as.numeric(feasible[i, ..vars]), vars)
    dm <- opsp_draw_metrics_for_multipliers(
      dc,
      vars = vars,
      multipliers = mult,
      step_pct = step_pct,
      value_per_kpi = value_per_kpi,
      normalize = FALSE
    )
    sc <- opsp_robust_objective_score(
      dm,
      robust_objective = robust_objective,
      robust_quantile = robust_quantile,
      robust_target_contribution = robust_target_contribution,
      robust_target_cost_per_kpi = robust_target_cost_per_kpi,
      robust_target_roi = robust_target_roi,
      robust_risk_aversion = robust_risk_aversion
    )$summary
    cbind(data.table::data.table(candidate_id = i, candidate_spend = feasible$candidate_spend[i]), sc)
  }), fill = TRUE)
  if (!nrow(scores) || all(!is.finite(scores$robust_score))) stop("No finite robust-grid objective score was produced.", call. = FALSE)
  scores[, budget_gap_abs := abs(candidate_spend - feasible_budget)]
  data.table::setorder(scores, -robust_score, budget_gap_abs)
  best_id <- scores$candidate_id[1]
  best <- feasible[best_id]
  multipliers <- stats::setNames(as.numeric(best[, ..vars]), vars)
  hist <- scores[1:min(.N, 100L)]
  hist[, `:=`(
    optimizer_method = "robust_grid",
    searched_combinations = as.numeric(combination_count),
    feasible_combinations = nrow(feasible),
    channel_constraint_filtered_combinations = channel_filtered_count,
    group_constraint_filtered_combinations = group_filtered_count,
    optimization_grid_step = as.numeric(optimization_grid_step)[1]
  )]
  opsp_finalize_optimizer_plan(
    engine = engine,
    multipliers = multipliers,
    cs = cs,
    total_budget = total_budget,
    min_required = min_required,
    max_possible = max_possible,
    optimizer_basis = paste0(engine$mode, "_robust_grid_", robust_objective),
    optimizer_iterations = as.integer(combination_count),
    allow_unallocated = allow_unallocated,
    allocation_history = hist,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi
  )
}

opsp_total_spend_for_multipliers <- function(engine, vars, multipliers) {
  mult <- stats::setNames(as.numeric(multipliers[vars]), vars)
  sum(vapply(vars, function(v) opsp_spend_at(engine, v, mult[v]), numeric(1)), na.rm = TRUE)
}

opsp_point_score_for_multipliers <- function(engine, vars, multipliers) {
  mult <- stats::setNames(as.numeric(multipliers[vars]), vars)
  sum(vapply(vars, function(v) engine$contribution(v, mult[v]), numeric(1)), na.rm = TRUE)
}

opsp_refine_multipliers_continuous <- function(engine,
                                               start_multipliers,
                                               cs,
                                               total_budget,
                                               max_possible,
                                               variable_group_map = NULL,
                                               group_constraints = NULL,
                                               allow_unallocated = FALSE,
                                               draw_curves = NULL,
                                               robust_objective = NULL,
                                               robust_quantile = 0.05,
                                               robust_target_contribution = NULL,
                                               robust_target_cost_per_kpi = NULL,
                                               robust_target_roi = NULL,
                                               robust_risk_aversion = 0,
                                               step_pct = 0.01,
                                               value_per_kpi = NA_real_,
                                               max_iter = 120L,
                                               penalty_weight = 1000) {
  vars <- as.character(cs$variable)
  lower <- stats::setNames(as.numeric(cs$min_multiplier), vars)
  upper <- stats::setNames(as.numeric(cs$max_multiplier), vars)
  start <- stats::setNames(as.numeric(start_multipliers[vars]), vars)
  start[!is.finite(start)] <- lower[!is.finite(start)]
  start <- pmin(pmax(start, lower), upper)
  feasible_budget <- min(as.numeric(total_budget)[1], as.numeric(max_possible)[1])
  if (!is.finite(feasible_budget)) feasible_budget <- as.numeric(total_budget)[1]
  budget_scale <- max(abs(feasible_budget), 1)
  max_iter <- suppressWarnings(as.integer(max_iter)[1])
  if (!is.finite(max_iter) || max_iter <= 0L || all(abs(upper - lower) <= 1e-12)) {
    return(list(multipliers = start, history = data.table::data.table()))
  }
  penalty_weight <- suppressWarnings(as.numeric(penalty_weight)[1])
  if (!is.finite(penalty_weight) || penalty_weight <= 0) penalty_weight <- 1000
  dc <- if (!is.null(draw_curves)) opsp_normalize_response_curve_draws(draw_curves) else data.table::data.table()
  robust_mode <- !is.null(robust_objective) && nrow(dc)

  raw_score <- function(mult) {
    mult <- stats::setNames(as.numeric(mult[vars]), vars)
    if (isTRUE(robust_mode)) {
      dm <- opsp_draw_metrics_for_multipliers(
        dc,
        vars = vars,
        multipliers = mult,
        step_pct = step_pct,
        value_per_kpi = value_per_kpi,
        normalize = FALSE
      )
      opsp_robust_objective_score(
        dm,
        robust_objective = robust_objective,
        robust_quantile = robust_quantile,
        robust_target_contribution = robust_target_contribution,
        robust_target_cost_per_kpi = robust_target_cost_per_kpi,
        robust_target_roi = robust_target_roi,
        robust_risk_aversion = robust_risk_aversion
      )$score
    } else {
      opsp_point_score_for_multipliers(engine, vars, mult)
    }
  }

  score0 <- raw_score(start)
  score_scale <- max(abs(score0), 1)
  objective <- function(par) {
    mult <- stats::setNames(as.numeric(par), vars)
    score <- raw_score(mult)
    spend <- opsp_total_spend_for_multipliers(engine, vars, mult)
    overspend <- max(0, spend - feasible_budget)
    underspend <- if (isTRUE(allow_unallocated)) 0 else max(0, feasible_budget - spend)
    channel_status <- opsp_channel_constraint_status(engine, vars, mult, cs)
    group_status <- opsp_group_constraint_status(
      engine = engine,
      vars = vars,
      multipliers = mult,
      variable_group_map = variable_group_map,
      group_constraints = group_constraints,
      total_budget = total_budget
    )
    channel_violation <- if (is.finite(channel_status$max_violation)) pmax(channel_status$max_violation, 0) else 0
    group_violation <- if (is.finite(group_status$max_violation)) pmax(group_status$max_violation, 0) else 0
    penalty <- penalty_weight * score_scale * (
      (overspend / budget_scale) ^ 2 +
        (underspend / budget_scale) ^ 2 +
        (channel_violation / budget_scale) ^ 2 +
        (group_violation / budget_scale) ^ 2
    )
    if (!is.finite(score)) return(.Machine$double.xmax / 100)
    -(score - penalty)
  }

  fit <- tryCatch(
    stats::optim(
      par = as.numeric(start),
      fn = objective,
      method = "L-BFGS-B",
      lower = as.numeric(lower),
      upper = as.numeric(upper),
      control = list(maxit = max_iter)
    ),
    error = function(e) NULL
  )
  if (is.null(fit) || is.null(fit$par) || any(!is.finite(fit$par))) {
    return(list(multipliers = start, history = data.table::data.table(
      optimizer_phase = "continuous_refine",
      refine_status = "failed",
      objective_before = score0,
      objective_after = score0
    )))
  }
  candidate <- stats::setNames(pmin(pmax(as.numeric(fit$par), lower), upper), vars)
  score1 <- raw_score(candidate)
  spend0 <- opsp_total_spend_for_multipliers(engine, vars, start)
  spend1 <- opsp_total_spend_for_multipliers(engine, vars, candidate)
  channel_status0 <- opsp_channel_constraint_status(engine, vars, start, cs)
  channel_status1 <- opsp_channel_constraint_status(engine, vars, candidate, cs)
  group_status0 <- opsp_group_constraint_status(engine, vars, start, variable_group_map, group_constraints, total_budget)
  group_status1 <- opsp_group_constraint_status(engine, vars, candidate, variable_group_map, group_constraints, total_budget)
  accepted <- is.finite(score1) && score1 >= score0 - 1e-8 &&
    spend1 <= feasible_budget + max(1e-6, budget_scale * 1e-6) &&
    isTRUE(channel_status1$ok) &&
    isTRUE(group_status1$ok)
  if (!isTRUE(allow_unallocated)) {
    accepted <- accepted && spend1 >= feasible_budget - max(1e-4, budget_scale * 1e-4)
  }
  final <- if (isTRUE(accepted)) candidate else start
  hist <- data.table::data.table(
    optimizer_phase = "continuous_refine",
    refine_status = if (isTRUE(accepted)) "accepted" else "rejected",
    convergence = if (is.null(fit$convergence)) NA_integer_ else fit$convergence,
    objective_before = score0,
    objective_after = score1,
    spend_before = spend0,
    spend_after = spend1,
    channel_constraint_violation_before = channel_status0$max_violation,
    channel_constraint_violation_after = channel_status1$max_violation,
    group_constraint_violation_before = group_status0$max_violation,
    group_constraint_violation_after = group_status1$max_violation,
    feasible_budget = feasible_budget,
    optimizer_method = if (isTRUE(robust_mode)) "robust_hybrid" else "hybrid"
  )
  list(multipliers = final, history = hist)
}

opsp_optimize_hybrid <- function(engine,
                                 constraints = NULL,
                                 variable_group_map = NULL,
                                 group_constraints = NULL,
                                 total_budget = NULL,
                                 budget_change_pct = 0,
                                 optimization_grid_step = 0.10,
                                 max_grid_combinations = 250000L,
                                 min_multiplier = 0,
                                 max_multiplier = 3,
                                 allow_unallocated = FALSE,
                                 hybrid_refine_max_iter = 120L,
                                 hybrid_penalty_weight = 1000,
                                 step_pct = 0.01,
                                 value_per_kpi = NA_real_) {
  coarse <- opsp_optimize_grid(
    engine,
    constraints = constraints,
    variable_group_map = variable_group_map,
    group_constraints = group_constraints,
    total_budget = total_budget,
    budget_change_pct = budget_change_pct,
    optimization_grid_step = optimization_grid_step,
    max_grid_combinations = max_grid_combinations,
    min_multiplier = min_multiplier,
    max_multiplier = max_multiplier,
    allow_unallocated = allow_unallocated,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi
  )
  vars <- engine$variables
  cur_spend <- as.numeric(engine$current_spend[vars])
  cs <- opsp_normalize_constraints(vars, cur_spend, constraints = constraints,
                                   min_multiplier = min_multiplier, max_multiplier = max_multiplier)
  if (is.null(total_budget)) total_budget <- sum(cur_spend, na.rm = TRUE) * (1 + opsp_num(budget_change_pct)[1])
  total_budget <- opsp_num(total_budget)[1]
  min_required <- cs[, sum(vapply(seq_len(.N), function(i) opsp_spend_at(engine, variable[i], min_multiplier[i]), numeric(1)), na.rm = TRUE)]
  max_possible <- cs[, sum(vapply(seq_len(.N), function(i) opsp_spend_at(engine, variable[i], max_multiplier[i]), numeric(1)), na.rm = TRUE)]
  start <- stats::setNames(coarse$plan$recommended_multiplier, coarse$plan$variable)
  refine <- opsp_refine_multipliers_continuous(
    engine = engine,
    start_multipliers = start,
    cs = cs,
    total_budget = total_budget,
    max_possible = max_possible,
    variable_group_map = variable_group_map,
    group_constraints = group_constraints,
    allow_unallocated = allow_unallocated,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi,
    max_iter = hybrid_refine_max_iter,
    penalty_weight = hybrid_penalty_weight
  )
  hist <- data.table::rbindlist(list(
    data.table::copy(coarse$allocation_history)[, optimizer_phase := "coarse_grid"],
    refine$history
  ), fill = TRUE)
  opsp_finalize_optimizer_plan(
    engine = engine,
    multipliers = refine$multipliers,
    cs = cs,
    total_budget = total_budget,
    min_required = min_required,
    max_possible = max_possible,
    optimizer_basis = paste0(engine$mode, "_hybrid_grid_refine_point_estimate"),
    optimizer_iterations = coarse$summary$optimizer_iterations[1] + as.integer(hybrid_refine_max_iter),
    allow_unallocated = allow_unallocated,
    allocation_history = hist,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi
  )
}

opsp_optimize_robust_hybrid <- function(engine,
                                        draw_curves,
                                        constraints = NULL,
                                        variable_group_map = NULL,
                                        group_constraints = NULL,
                                        total_budget = NULL,
                                        budget_change_pct = 0,
                                        optimization_grid_step = 0.10,
                                        max_grid_combinations = 50000L,
                                        min_multiplier = 0,
                                        max_multiplier = 3,
                                        allow_unallocated = FALSE,
                                        robust_objective = opsp_robust_objective_choices(),
                                        robust_quantile = 0.05,
                                        robust_target_contribution = NULL,
                                        robust_target_cost_per_kpi = NULL,
                                        robust_target_roi = NULL,
                                        robust_risk_aversion = 0,
                                        hybrid_refine_max_iter = 120L,
                                        hybrid_penalty_weight = 1000,
                                        step_pct = 0.01,
                                        value_per_kpi = NA_real_) {
  robust_objective <- match.arg(robust_objective)
  coarse <- opsp_optimize_robust_grid(
    engine,
    draw_curves = draw_curves,
    constraints = constraints,
    variable_group_map = variable_group_map,
    group_constraints = group_constraints,
    total_budget = total_budget,
    budget_change_pct = budget_change_pct,
    optimization_grid_step = optimization_grid_step,
    max_grid_combinations = max_grid_combinations,
    min_multiplier = min_multiplier,
    max_multiplier = max_multiplier,
    allow_unallocated = allow_unallocated,
    robust_objective = robust_objective,
    robust_quantile = robust_quantile,
    robust_target_contribution = robust_target_contribution,
    robust_target_cost_per_kpi = robust_target_cost_per_kpi,
    robust_target_roi = robust_target_roi,
    robust_risk_aversion = robust_risk_aversion,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi
  )
  vars <- engine$variables
  cur_spend <- as.numeric(engine$current_spend[vars])
  cs <- opsp_normalize_constraints(vars, cur_spend, constraints = constraints,
                                   min_multiplier = min_multiplier, max_multiplier = max_multiplier)
  if (is.null(total_budget)) total_budget <- sum(cur_spend, na.rm = TRUE) * (1 + opsp_num(budget_change_pct)[1])
  total_budget <- opsp_num(total_budget)[1]
  min_required <- cs[, sum(vapply(seq_len(.N), function(i) opsp_spend_at(engine, variable[i], min_multiplier[i]), numeric(1)), na.rm = TRUE)]
  max_possible <- cs[, sum(vapply(seq_len(.N), function(i) opsp_spend_at(engine, variable[i], max_multiplier[i]), numeric(1)), na.rm = TRUE)]
  start <- stats::setNames(coarse$plan$recommended_multiplier, coarse$plan$variable)
  refine <- opsp_refine_multipliers_continuous(
    engine = engine,
    start_multipliers = start,
    cs = cs,
    total_budget = total_budget,
    max_possible = max_possible,
    variable_group_map = variable_group_map,
    group_constraints = group_constraints,
    allow_unallocated = allow_unallocated,
    draw_curves = draw_curves,
    robust_objective = robust_objective,
    robust_quantile = robust_quantile,
    robust_target_contribution = robust_target_contribution,
    robust_target_cost_per_kpi = robust_target_cost_per_kpi,
    robust_target_roi = robust_target_roi,
    robust_risk_aversion = robust_risk_aversion,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi,
    max_iter = hybrid_refine_max_iter,
    penalty_weight = hybrid_penalty_weight
  )
  hist <- data.table::rbindlist(list(
    data.table::copy(coarse$allocation_history)[, optimizer_phase := "coarse_grid"],
    refine$history
  ), fill = TRUE)
  opsp_finalize_optimizer_plan(
    engine = engine,
    multipliers = refine$multipliers,
    cs = cs,
    total_budget = total_budget,
    min_required = min_required,
    max_possible = max_possible,
    optimizer_basis = paste0(engine$mode, "_robust_hybrid_", robust_objective),
    optimizer_iterations = coarse$summary$optimizer_iterations[1] + as.integer(hybrid_refine_max_iter),
    allow_unallocated = allow_unallocated,
    allocation_history = hist,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi
  )
}

