# 035-optimizer-runner-output.R
# Generated by behavior-preserving split of optimizer_scenario_planner.R.

opsp_budget_bounds <- function(engine,
                               constraints = NULL,
                               min_multiplier = 0,
                               max_multiplier = 3) {
  vars <- engine$variables
  cur_spend <- as.numeric(engine$current_spend[vars])
  cs <- opsp_normalize_constraints(vars, cur_spend, constraints = constraints,
                                   min_multiplier = min_multiplier, max_multiplier = max_multiplier)
  data.table::data.table(
    current_budget = sum(cur_spend, na.rm = TRUE),
    min_required_budget = cs[, sum(current_spend * min_multiplier, na.rm = TRUE)],
    max_possible_budget = cs[, sum(current_spend * max_multiplier, na.rm = TRUE)]
  )
}

opsp_target_plan <- function(engine,
                             constraints = NULL,
                             target_contribution = NULL,
                             target_incremental_contribution = NULL,
                             target_cost_per_kpi = NULL,
                             target_roi = NULL,
                             budget_step_frac = 0.005,
                             min_multiplier = 0,
                             max_multiplier = 3,
                             max_iter = 5000,
                             search_iter = 28,
                             allow_unallocated = FALSE,
                             step_pct = 0.01,
                             value_per_kpi = NA_real_) {
  targets <- list()
  current_plan <- opsp_current_plan(engine, step_pct = step_pct, value_per_kpi = value_per_kpi)
  current_contribution <- current_plan[, sum(current_contribution, na.rm = TRUE)]
  bounds <- opsp_budget_bounds(engine, constraints = constraints,
                               min_multiplier = min_multiplier, max_multiplier = max_multiplier)
  low_bound <- bounds$min_required_budget[1]
  high_bound <- bounds$max_possible_budget[1]
  if (!is.finite(low_bound)) low_bound <- 0
  if (!is.finite(high_bound)) high_bound <- bounds$current_budget[1]
  if (!is.finite(high_bound) || high_bound < low_bound) high_bound <- low_bound

  optimize_at <- function(budget) {
    opsp_optimize_greedy(
      engine = engine,
      constraints = constraints,
      total_budget = budget,
      budget_step_frac = budget_step_frac,
      min_multiplier = min_multiplier,
      max_multiplier = max_multiplier,
      max_iter = max_iter,
      allow_unallocated = allow_unallocated,
      step_pct = step_pct,
      value_per_kpi = value_per_kpi
    )
  }

  add_summary <- function(opt, target_type, target_value, target_met, target_direction) {
    sm <- data.table::copy(opt$summary)
    sm[, `:=`(
      target_type = target_type,
      target_value = target_value,
      target_met = isTRUE(target_met),
      target_direction = target_direction
    )]
    pl <- data.table::copy(opt$plan)
    pl[, `:=`(
      target_type = target_type,
      target_value = target_value,
      target_met = isTRUE(target_met)
    )]
    list(summary = sm, plan = pl)
  }

  find_min_budget <- function(target_total, target_type, target_value) {
    high <- optimize_at(high_bound)
    high_hit <- high$summary$expected_contribution[1] >= target_total - 1e-8
    if (!isTRUE(high_hit)) {
      return(add_summary(high, target_type, target_value, FALSE, "minimum_budget_for_target_kpi"))
    }
    low <- low_bound
    hi <- high_bound
    for (ii in seq_len(search_iter)) {
      mid <- (low + hi) / 2
      opt <- optimize_at(mid)
      if (opt$summary$expected_contribution[1] >= target_total - 1e-8) hi <- mid else low <- mid
    }
    final <- optimize_at(hi)
    add_summary(final, target_type, target_value, TRUE, "minimum_budget_for_target_kpi")
  }

  find_max_efficient_budget <- function(metric, threshold, target_type) {
    feasible <- function(opt) {
      sm <- opt$summary
      if (identical(metric, "cost_per_kpi")) {
        is.finite(sm$expected_cost_per_kpi[1]) && sm$expected_cost_per_kpi[1] <= threshold + 1e-8
      } else {
        is.finite(sm$expected_roi[1]) && sm$expected_roi[1] >= threshold - 1e-8
      }
    }
    start_budget <- pmin(pmax(bounds$current_budget[1], low_bound), high_bound)
    low <- optimize_at(start_budget)
    if (!feasible(low)) {
      return(add_summary(low, target_type, threshold, FALSE, "maximum_budget_with_target_efficiency"))
    }
    high <- optimize_at(high_bound)
    if (feasible(high)) {
      return(add_summary(high, target_type, threshold, TRUE, "maximum_budget_with_target_efficiency"))
    }
    lo <- start_budget
    hi <- high_bound
    for (ii in seq_len(search_iter)) {
      mid <- (lo + hi) / 2
      opt <- optimize_at(mid)
      if (feasible(opt)) lo <- mid else hi <- mid
    }
    final <- optimize_at(lo)
    add_summary(final, target_type, threshold, TRUE, "maximum_budget_with_target_efficiency")
  }

  tc <- suppressWarnings(as.numeric(target_contribution)[1])
  if (is.finite(tc) && tc >= 0) {
    targets[[length(targets) + 1L]] <- find_min_budget(tc, "target_contribution", tc)
  }
  tic <- suppressWarnings(as.numeric(target_incremental_contribution)[1])
  if (is.finite(tic) && tic >= 0) {
    target_total <- current_contribution + tic
    targets[[length(targets) + 1L]] <- find_min_budget(target_total, "target_incremental_contribution", tic)
  }
  tcpk <- suppressWarnings(as.numeric(target_cost_per_kpi)[1])
  if (is.finite(tcpk) && tcpk > 0) {
    targets[[length(targets) + 1L]] <- find_max_efficient_budget("cost_per_kpi", tcpk, "target_cost_per_kpi")
  }
  troi <- suppressWarnings(as.numeric(target_roi)[1])
  if (is.finite(troi) && troi > 0) {
    targets[[length(targets) + 1L]] <- find_max_efficient_budget("roi", troi, "target_roi")
  }

  if (!length(targets)) {
    return(list(summary = data.table::data.table(), plan = data.table::data.table()))
  }
  list(
    summary = data.table::rbindlist(lapply(targets, `[[`, "summary"), fill = TRUE),
    plan = data.table::rbindlist(lapply(targets, `[[`, "plan"), fill = TRUE)
  )
}

opsp_build_diagnostics <- function(engine, current_plan, optimization, constraints = NULL) {
  flags <- data.table::data.table(flag = character(), severity = character(), detail = character())
  add_flag <- function(flag, severity, detail) {
    flags <<- data.table::rbindlist(list(flags, data.table::data.table(flag = flag, severity = severity, detail = as.character(detail))), fill = TRUE)
  }
  if (any(!is.finite(current_plan$current_spend) | current_plan$current_spend <= 0)) {
    add_flag("zero_or_missing_current_spend", "warning", paste(current_plan[!is.finite(current_spend) | current_spend <= 0, variable], collapse = ", "))
  }
  if (any(is.finite(current_plan$current_contribution) & current_plan$current_contribution <= 0)) {
    add_flag("non_positive_current_contribution", "warning", paste(current_plan[is.finite(current_contribution) & current_contribution <= 0, variable], collapse = ", "))
  }
  if (any(!is.finite(current_plan$current_mroi))) {
    add_flag("missing_current_mroi", "warning", paste(current_plan[!is.finite(current_mroi), variable], collapse = ", "))
  }
  if (!is.null(optimization$plan) && nrow(opsp_as_dt(optimization$plan)) &&
      any(is.finite(optimization$plan$expected_contribution) & optimization$plan$expected_contribution <= 0)) {
    add_flag("non_positive_expected_contribution", "warning", paste(optimization$plan[is.finite(expected_contribution) & expected_contribution <= 0, variable], collapse = ", "))
  }
  if (nrow(optimization$summary) && optimization$summary$unallocated_budget[1] > 1e-6) {
    add_flag("unallocated_budget", "info", optimization$summary$unallocated_budget[1])
  }
  if (identical(engine$mode, "response_curve_table")) {
    add_flag("response_curve_table_mode", "info", "Planner used supplied response curves; posterior/model uncertainty is not available.")
  }
  if ("curve_evidence_level" %in% names(current_plan) &&
      any(current_plan$curve_evidence_level %in% c("weak", "diagnostic", "unknown") |
            !is.finite(current_plan$curve_evidence_score), na.rm = TRUE)) {
    weak_vars <- current_plan[curve_evidence_level %in% c("weak", "diagnostic", "unknown") |
                                !is.finite(curve_evidence_score), variable]
    add_flag(
      "weak_or_unknown_curve_evidence",
      "warning",
      paste(unique(weak_vars), collapse = ", ")
    )
  }
  data.table::data.table(
    decisioning_basis = paste0(engine$mode, "_point_estimate"),
    uncertainty_note = "Scenario planning and optimization are point-estimate decision support. They do not yet optimize over posterior uncertainty.",
    flighting_assumption = "Channel spend/support changes scale the historical response curve for that channel while other channels are held at their current path.",
    cost_assumption = "Cost per media/support unit is treated as constant within each channel unless the supplied response curve already encodes a different cost assumption."
  )[, flags := list(flags)][]
}

opsp_write_outputs <- function(out, output_dir = NULL, output_prefix = "") {
  if (is.null(output_dir) || !nzchar(output_dir)) return(invisible(NULL))
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  pfx <- if (nzchar(output_prefix)) paste0(output_prefix, "_") else ""
  write_one <- function(x, nm) {
    if (inherits(x, "data.table") || is.data.frame(x)) {
      data.table::fwrite(data.table::as.data.table(x), file.path(output_dir, paste0(pfx, nm, ".csv")))
    }
  }
  write_one(out$current_plan, "current_plan")
  write_one(out$response_curves, "response_curves")
  write_one(out$response_curve_uncertainty, "response_curve_uncertainty")
  write_one(out$saturation_headroom, "saturation_headroom")
  write_one(out$scenario_summary, "scenario_summary")
  write_one(out$scenario_detail, "scenario_detail")
  write_one(out$scenario_uncertainty_summary, "scenario_uncertainty_summary")
  write_one(out$scenario_uncertainty_by_variable, "scenario_uncertainty_by_variable")
  write_one(out$scenario_uncertainty_draws, "scenario_uncertainty_draws")
  write_one(out$scenario_uncertainty_draws_by_variable, "scenario_uncertainty_draws_by_variable")
  write_one(out$optimization_summary, "optimization_summary")
  write_one(out$optimization_plan, "optimization_plan")
  write_one(out$optimization_group_rollup, "optimization_group_rollup")
  write_one(out$optimization_uncertainty_summary, "optimization_uncertainty_summary")
  write_one(out$optimization_uncertainty_by_variable, "optimization_uncertainty_by_variable")
  write_one(out$optimization_uncertainty_draws, "optimization_uncertainty_draws")
  write_one(out$optimization_uncertainty_draws_by_variable, "optimization_uncertainty_draws_by_variable")
  write_one(out$allocation_history, "allocation_history")
  write_one(out$target_plan_summary, "target_plan_summary")
  write_one(out$target_plan_detail, "target_plan_detail")
  write_one(out$uncertainty_diagnostics, "uncertainty_diagnostics")
  if (!is.null(out$diagnostics$flags)) write_one(out$diagnostics$flags, "diagnostic_flags")
  invisible(output_dir)
}

run_optimizer_scenario_planner <- function(fit_obj = NULL,
                                           response_curves = NULL,
                                           response_curve_draws = NULL,
                                           spend_map = NULL,
                                           raw_data = NULL,
                                           variables = NULL,
                                           constraints = NULL,
                                           variable_group_map = NULL,
                                           group_constraints = NULL,
                                           total_budget = NULL,
                                           budget_change_pct = 0,
                                           scenario_multipliers = c(0.8, 1, 1.2),
                                           scenario_plan = NULL,
                                           multiplier_grid = seq(0, 3, by = 0.05),
                                           step_pct = 0.01,
                                           budget_step_frac = 0.005,
                                           optimizer_method = c("greedy", "grid", "hybrid", "robust_grid", "robust_hybrid"),
                                           optimization_grid_step = 0.05,
                                           max_grid_combinations = 250000L,
                                           hybrid_refine_max_iter = 120L,
                                           hybrid_penalty_weight = 1000,
                                           uncertainty = c("auto", "none", "draws"),
                                           posterior_draw_count = 200L,
                                           posterior_draw_seed = 123L,
                                           robust_objective = opsp_robust_objective_choices(),
                                           robust_quantile = 0.05,
                                           uncertainty_quantile = NULL,
                                           robust_target_contribution = NULL,
                                           robust_target_cost_per_kpi = NULL,
                                           robust_target_roi = NULL,
                                           robust_risk_aversion = 0,
                                           min_multiplier = 0,
                                           max_multiplier = 3,
                                           max_iter = 5000,
                                           allow_unallocated = FALSE,
                                           target_contribution = NULL,
                                           target_incremental_contribution = NULL,
                                           target_cost_per_kpi = NULL,
                                           target_roi = NULL,
                                           target_search_iter = 28,
                                           value_per_kpi = NA_real_,
                                           kpi_label = "KPI",
                                           spend_suffix = "_spend",
                                           support_cost_map = NULL,
                                           output_dir = NULL,
                                           output_prefix = "",
                                           model_fit = NULL,
                                           response_curve_table = NULL,
                                           response_curve_draw_table = NULL,
                                           model_data = NULL,
                                           drivers = NULL,
                                           driver_constraints = NULL,
                                           planning_group_map = NULL,
                                           planning_group_constraints = NULL,
                                           media_cost_map = NULL,
                                           output_path = NULL) {
  alias_used <- c(
    !is.null(model_fit),
    !is.null(response_curve_table),
    !is.null(response_curve_draw_table),
    !is.null(model_data),
    !is.null(drivers),
    !is.null(driver_constraints),
    !is.null(planning_group_map),
    !is.null(planning_group_constraints),
    !is.null(media_cost_map),
    !is.null(output_path)
  )
  fit_obj <- opsp_resolve_input_alias(fit_obj, model_fit, "fit_obj", "model_fit")
  response_curves <- opsp_resolve_input_alias(response_curves, response_curve_table, "response_curves", "response_curve_table")
  response_curve_draws <- opsp_resolve_input_alias(response_curve_draws, response_curve_draw_table, "response_curve_draws", "response_curve_draw_table")
  raw_data <- opsp_resolve_input_alias(raw_data, model_data, "raw_data", "model_data")
  variables <- opsp_resolve_input_alias(variables, drivers, "variables", "drivers")
  constraints <- opsp_resolve_input_alias(constraints, driver_constraints, "constraints", "driver_constraints")
  variable_group_map <- opsp_resolve_input_alias(variable_group_map, planning_group_map, "variable_group_map", "planning_group_map")
  group_constraints <- opsp_resolve_input_alias(group_constraints, planning_group_constraints, "group_constraints", "planning_group_constraints")
  support_cost_map <- opsp_resolve_input_alias(support_cost_map, media_cost_map, "support_cost_map", "media_cost_map")
  output_dir <- opsp_resolve_input_alias(output_dir, output_path, "output_dir", "output_path")
  input_alias_audit <- opsp_optimizer_input_alias_audit(alias_used)
  opsp_require_data_table()
  optimizer_method <- match.arg(optimizer_method)
  uncertainty <- match.arg(uncertainty)
  robust_objective <- match.arg(robust_objective)
  robust_quantile <- opsp_validate_quantile(robust_quantile, fallback = 0.05)
  uncertainty_quantile <- if (is.null(uncertainty_quantile)) {
    robust_quantile
  } else {
    opsp_validate_quantile(uncertainty_quantile, fallback = robust_quantile)
  }
  group_constraints_norm <- opsp_normalize_group_constraints(group_constraints, total_budget = total_budget)
  has_group_constraints <- nrow(group_constraints_norm) > 0L
  if (isTRUE(has_group_constraints) && identical(optimizer_method, "greedy")) {
    stop("group_constraints require optimizer_method = 'grid', 'hybrid', 'robust_grid', or 'robust_hybrid'; greedy is a marginal-step heuristic and does not enforce portfolio/group caps.", call. = FALSE)
  }
  has_target_request <- !is.null(target_contribution) ||
    !is.null(target_incremental_contribution) ||
    !is.null(target_cost_per_kpi) ||
    !is.null(target_roi)
  if (isTRUE(has_group_constraints) && isTRUE(has_target_request)) {
    stop("Target-search planning with group_constraints is not yet supported. Run budget optimization with grid/hybrid group constraints, or omit group_constraints for target-search mode.", call. = FALSE)
  }
  engine <- opsp_engine_from_inputs(
    fit_obj = fit_obj,
    response_curves = response_curves,
    spend_map = spend_map,
    raw_data = raw_data,
    variables = variables,
    constraints = constraints,
    support_cost_map = support_cost_map,
    spend_suffix = spend_suffix
  )
  current <- opsp_current_plan(engine, step_pct = step_pct, value_per_kpi = value_per_kpi)
  curves <- opsp_build_response_curves(engine, multiplier_grid = multiplier_grid,
                                       step_pct = step_pct, value_per_kpi = value_per_kpi)
  saturation_headroom <- opsp_build_saturation_headroom(curves)
  scenarios <- opsp_scenario_tables(engine, scenario_multipliers = scenario_multipliers,
                                    scenario_plan = scenario_plan, step_pct = step_pct,
                                    value_per_kpi = value_per_kpi)
  uncertainty_for_draws <- if (optimizer_method %in% c("robust_grid", "robust_hybrid") && identical(uncertainty, "auto")) "draws" else uncertainty
  draw_curves <- opsp_response_curve_draws_from_inputs(
    fit_obj = fit_obj,
    response_curve_draws = response_curve_draws,
    response_curves = response_curves,
    spend_map = spend_map,
    raw_data = raw_data,
    variables = engine$variables,
    multiplier_grid = multiplier_grid,
    step_pct = step_pct,
    spend_suffix = spend_suffix,
    support_cost_map = support_cost_map,
    uncertainty = uncertainty_for_draws,
    posterior_draw_count = posterior_draw_count,
    posterior_draw_seed = posterior_draw_seed
  )
  opt <- if (identical(optimizer_method, "grid")) {
    opsp_optimize_grid(
      engine,
      constraints = constraints,
      variable_group_map = variable_group_map,
      group_constraints = group_constraints_norm,
      total_budget = total_budget,
      budget_change_pct = budget_change_pct,
      optimization_grid_step = optimization_grid_step,
      max_grid_combinations = max_grid_combinations,
      min_multiplier = min_multiplier,
      max_multiplier = max_multiplier,
      allow_unallocated = allow_unallocated,
      step_pct = step_pct,
      value_per_kpi = value_per_kpi
    )
  } else if (identical(optimizer_method, "hybrid")) {
    opsp_optimize_hybrid(
      engine,
      constraints = constraints,
      variable_group_map = variable_group_map,
      group_constraints = group_constraints_norm,
      total_budget = total_budget,
      budget_change_pct = budget_change_pct,
      optimization_grid_step = optimization_grid_step,
      max_grid_combinations = max_grid_combinations,
      min_multiplier = min_multiplier,
      max_multiplier = max_multiplier,
      allow_unallocated = allow_unallocated,
      hybrid_refine_max_iter = hybrid_refine_max_iter,
      hybrid_penalty_weight = hybrid_penalty_weight,
      step_pct = step_pct,
      value_per_kpi = value_per_kpi
    )
  } else if (identical(optimizer_method, "robust_grid")) {
    opsp_optimize_robust_grid(
      engine,
      draw_curves = draw_curves,
      constraints = constraints,
      variable_group_map = variable_group_map,
      group_constraints = group_constraints_norm,
      total_budget = total_budget,
      budget_change_pct = budget_change_pct,
      optimization_grid_step = optimization_grid_step,
      max_grid_combinations = max_grid_combinations,
      min_multiplier = min_multiplier,
      max_multiplier = max_multiplier,
      allow_unallocated = allow_unallocated,
      robust_objective = robust_objective,
      robust_quantile = robust_quantile,
      robust_target_contribution = robust_target_contribution,
      robust_target_cost_per_kpi = robust_target_cost_per_kpi,
      robust_target_roi = robust_target_roi,
      robust_risk_aversion = robust_risk_aversion,
      step_pct = step_pct,
      value_per_kpi = value_per_kpi
    )
  } else if (identical(optimizer_method, "robust_hybrid")) {
    opsp_optimize_robust_hybrid(
      engine,
      draw_curves = draw_curves,
      constraints = constraints,
      variable_group_map = variable_group_map,
      group_constraints = group_constraints_norm,
      total_budget = total_budget,
      budget_change_pct = budget_change_pct,
      optimization_grid_step = optimization_grid_step,
      max_grid_combinations = max_grid_combinations,
      min_multiplier = min_multiplier,
      max_multiplier = max_multiplier,
      allow_unallocated = allow_unallocated,
      robust_objective = robust_objective,
      robust_quantile = robust_quantile,
      robust_target_contribution = robust_target_contribution,
      robust_target_cost_per_kpi = robust_target_cost_per_kpi,
      robust_target_roi = robust_target_roi,
      robust_risk_aversion = robust_risk_aversion,
      hybrid_refine_max_iter = hybrid_refine_max_iter,
      hybrid_penalty_weight = hybrid_penalty_weight,
      step_pct = step_pct,
      value_per_kpi = value_per_kpi
    )
  } else {
    opsp_optimize_greedy(
      engine,
      constraints = constraints,
      total_budget = total_budget,
      budget_change_pct = budget_change_pct,
      budget_step_frac = budget_step_frac,
      min_multiplier = min_multiplier,
      max_multiplier = max_multiplier,
      max_iter = max_iter,
      allow_unallocated = allow_unallocated,
      step_pct = step_pct,
      value_per_kpi = value_per_kpi
    )
  }
  target_plan <- opsp_target_plan(
    engine,
    constraints = constraints,
    target_contribution = target_contribution,
    target_incremental_contribution = target_incremental_contribution,
    target_cost_per_kpi = target_cost_per_kpi,
    target_roi = target_roi,
    budget_step_frac = budget_step_frac,
    min_multiplier = min_multiplier,
    max_multiplier = max_multiplier,
    max_iter = max_iter,
    search_iter = target_search_iter,
    allow_unallocated = allow_unallocated,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi
  )
  optimization_group_rollup <- opsp_build_group_rollup(
    engine = engine,
    optimization_plan = opt$plan,
    variable_group_map = variable_group_map,
    group_constraints = group_constraints_norm,
    total_budget = opt$summary$total_budget[1]
  )
  uncertainty_tables <- opsp_build_uncertainty_tables(
    draw_curves = draw_curves,
    vars = engine$variables,
    scenario_multipliers = scenario_multipliers,
    scenario_plan = scenario_plan,
    optimization_plan = opt$plan,
    engine = engine,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi,
    uncertainty_quantile = uncertainty_quantile
  )
  response_curve_uncertainty <- opsp_build_response_curve_uncertainty(
    draw_curves = draw_curves,
    step_pct = step_pct,
    value_per_kpi = value_per_kpi
  )
  diagnostics <- opsp_build_diagnostics(engine, current, opt, constraints = constraints)
  uncertainty_diagnostics <- data.table::data.table(
    uncertainty_mode = uncertainty_for_draws,
    response_curve_draw_rows = nrow(draw_curves),
    posterior_draw_count_used = if (is.null(uncertainty_tables$draw_count)) 0L else uncertainty_tables$draw_count,
    uncertainty_note = if (nrow(draw_curves)) {
      if (optimizer_method %in% c("robust_grid", "robust_hybrid")) {
        paste0("Scenario uncertainty summaries are computed from draw-level response curves. The optimized plan was selected by ", optimizer_method, " using a posterior/draw objective.")
      } else {
        "Scenario uncertainty summaries are computed from draw-level response curves. Optimization selected the point-estimate plan."
      }
    } else {
      "No draw-level response curves were available, so uncertainty-aware scenario summaries were not created."
    }
  )
  out <- list(
    package_info = econimap_output_metadata("run_optimizer_scenario_planner", surface = "scenario_planner"),
    inputs_used = data.table::data.table(
      engine_mode = engine$mode,
      variable_count = length(engine$variables),
      driver_count = length(engine$variables),
      kpi_label = kpi_label,
      value_per_kpi = suppressWarnings(as.numeric(value_per_kpi)[1])
    ),
    input_alias_audit = input_alias_audit[],
    settings = data.table::data.table(
      total_budget = if (is.null(total_budget)) NA_real_ else suppressWarnings(as.numeric(total_budget)[1]),
      budget_change_pct = suppressWarnings(as.numeric(budget_change_pct)[1]),
      step_pct = step_pct,
      budget_step_frac = budget_step_frac,
      optimizer_method = optimizer_method,
      optimization_grid_step = optimization_grid_step,
      max_grid_combinations = max_grid_combinations,
      hybrid_refine_max_iter = hybrid_refine_max_iter,
      hybrid_penalty_weight = hybrid_penalty_weight,
      uncertainty = uncertainty,
      posterior_draw_count = posterior_draw_count,
      robust_objective = robust_objective,
      robust_quantile = robust_quantile,
      uncertainty_quantile = uncertainty_quantile,
      robust_risk_aversion = robust_risk_aversion,
      min_multiplier = min_multiplier,
      max_multiplier = max_multiplier,
      allow_unallocated = isTRUE(allow_unallocated),
      group_constraint_count = nrow(group_constraints_norm)
    ),
    current_plan = current[],
    response_curves = curves[],
    response_curve_uncertainty = response_curve_uncertainty[],
    saturation_headroom = saturation_headroom[],
    scenario_summary = scenarios$summary[],
    scenario_detail = scenarios$detail[],
    scenario_uncertainty_summary = uncertainty_tables$scenario_summary[],
    scenario_uncertainty_by_variable = uncertainty_tables$scenario_by_variable[],
    scenario_uncertainty_draws = uncertainty_tables$scenario_draws[],
    scenario_uncertainty_draws_by_variable = uncertainty_tables$scenario_draws_by_variable[],
    optimization_summary = opt$summary[],
    optimization_plan = opt$plan[],
    optimization_group_rollup = optimization_group_rollup[],
    optimization_uncertainty_summary = uncertainty_tables$optimization_summary[],
    optimization_uncertainty_by_variable = uncertainty_tables$optimization_by_variable[],
    optimization_uncertainty_draws = uncertainty_tables$optimization_draws[],
    optimization_uncertainty_draws_by_variable = uncertainty_tables$optimization_draws_by_variable[],
    allocation_history = opt$allocation_history[],
    target_plan_summary = target_plan$summary[],
    target_plan_detail = target_plan$plan[],
    uncertainty_diagnostics = uncertainty_diagnostics[],
    diagnostics = diagnostics
  )
  out <- opsp_add_optimizer_output_aliases(out)
  opsp_write_outputs(out, output_dir = output_dir, output_prefix = output_prefix)
  out
}

optimizer_scenario_planner <- run_optimizer_scenario_planner
run_mmm_optimizer <- run_optimizer_scenario_planner
run_mmm_scenario_planner <- run_optimizer_scenario_planner
