# 040-deck-utils-standardize.R
# Generated by behavior-preserving split of mmm_deck_output_builder.R.

# mmm_deck_output_builder.R
# Reporting helpers for turning MMM decomposition outputs into analyst-ready
# tables, charts, and a static HTML dashboard.

if (!requireNamespace("data.table", quietly = TRUE)) stop("Package 'data.table' is required.")

mdo_null_coalesce <- function(x, y) if (is.null(x)) y else x

mdo_as_dt <- function(x, label = "input") {
  if (is.null(x)) return(NULL)
  if (data.table::is.data.table(x)) return(data.table::copy(x))
  if (is.data.frame(x)) return(data.table::as.data.table(data.table::copy(x)))
  if (is.character(x) && length(x) == 1L) {
    if (!file.exists(x)) stop(label, " path does not exist: ", x)
    ext <- tolower(tools::file_ext(x))
    if (ext %in% c("csv", "txt")) return(data.table::fread(x))
    if (ext == "rds") return(readRDS(x))
    if (ext %in% c("xlsx", "xls")) {
      if (!requireNamespace("readxl", quietly = TRUE)) {
        stop("Package 'readxl' is required to read Excel inputs.")
      }
      return(data.table::as.data.table(readxl::read_excel(x)))
    }
    stop("Unsupported ", label, " file extension: ", ext)
  }
  stop(label, " must be a data.frame, data.table, or file path.")
}

mdo_pick_col <- function(dt, candidates) {
  if (is.null(dt)) return(NA_character_)
  candidates <- candidates[!is.na(candidates) & nzchar(candidates)]
  hit <- candidates[candidates %in% names(dt)]
  if (length(hit)) hit[1] else NA_character_
}

mdo_require_cols <- function(dt, cols, label) {
  miss <- cols[!(cols %in% names(dt))]
  if (length(miss)) stop(label, " is missing required columns: ", paste(miss, collapse = ", "))
  invisible(TRUE)
}

mdo_safe_num <- function(x) {
  out <- suppressWarnings(as.numeric(x))
  out[!is.finite(out)] <- NA_real_
  out
}

mdo_sum_or_na <- function(x) {
  x <- mdo_safe_num(x)
  if (!any(is.finite(x))) return(NA_real_)
  sum(x, na.rm = TRUE)
}

mdo_quantile_or_na <- function(x, prob) {
  x <- mdo_safe_num(x)
  x <- x[is.finite(x)]
  if (!length(x)) return(NA_real_)
  as.numeric(stats::quantile(x, prob, na.rm = TRUE, names = FALSE))
}

mdo_as_dateish <- function(x) {
  if (inherits(x, "Date")) return(x)
  if (inherits(x, "IDate")) return(as.Date(x))
  if (inherits(x, "POSIXt")) return(as.Date(x))
  if (is.numeric(x)) {
    if (all(is.na(x))) return(as.Date(rep(NA, length(x))))
    med <- median(x, na.rm = TRUE)
    if (is.finite(med) && med > 30000) return(as.Date(x, origin = "1899-12-30"))
    if (is.finite(med) && med > 10000) return(as.Date(x, origin = "1970-01-01"))
  }
  suppressWarnings(as.Date(x))
}

mdo_add_period_fields <- function(dt, time_col, period_granularity = "month") {
  out <- data.table::copy(dt)
  period_granularity <- match.arg(period_granularity, c("week", "month", "quarter", "year", "all"))
  if (period_granularity == "all" || is.na(time_col) || !(time_col %in% names(out))) {
    out[, `:=`(
      period_granularity = "all",
      period_start = as.Date(NA),
      period_label = "All periods",
      period_sort = 1L
    )]
    return(out[])
  }

  d <- mdo_as_dateish(out[[time_col]])
  if (all(is.na(d))) {
    out[, `:=`(
      period_granularity = period_granularity,
      period_start = as.Date(NA),
      period_label = as.character(get(time_col)),
      period_sort = data.table::frank(as.character(get(time_col)), ties.method = "dense")
    )]
    return(out[])
  }

  if (period_granularity == "week") {
    ps <- d
    lab <- format(ps, "%Y-%m-%d")
  } else if (period_granularity == "month") {
    ps <- as.Date(sprintf("%s-01", format(d, "%Y-%m")))
    lab <- format(ps, "%Y-%m")
  } else if (period_granularity == "quarter") {
    yr <- as.integer(format(d, "%Y"))
    q <- floor((as.integer(format(d, "%m")) - 1L) / 3L) + 1L
    ps <- as.Date(sprintf("%04d-%02d-01", yr, (q - 1L) * 3L + 1L))
    lab <- paste0(yr, "-Q", q)
  } else {
    yr <- as.integer(format(d, "%Y"))
    ps <- as.Date(sprintf("%04d-01-01", yr))
    lab <- as.character(yr)
  }
  out[, `:=`(
    period_granularity = period_granularity,
    period_start = ps,
    period_label = lab,
    period_sort = data.table::frank(ps, ties.method = "dense")
  )]
  out[]
}

mdo_standardize_long <- function(long_decomp,
                                 time_col = NULL,
                                 group_col = NULL,
                                 entity_col = NULL,
                                 variable_col = "variable",
                                 contribution_col = "contribution",
                                 actual_col = "y_actual",
                                 fitted_col = "pred",
                                 residual_col = "residual",
                                 sample_col = "sample",
                                 sample_values = NULL,
                                 period_granularity = "month") {
  long <- mdo_as_dt(long_decomp, "long_decomp")
  if (is.null(long) || !nrow(long)) stop("long_decomp must contain at least one row.")

  if (!(variable_col %in% names(long))) stop("variable_col not found in long_decomp: ", variable_col)
  if (!(contribution_col %in% names(long))) stop("contribution_col not found in long_decomp: ", contribution_col)
  if (variable_col != "variable") data.table::setnames(long, variable_col, "variable")
  if (contribution_col != "contribution") data.table::setnames(long, contribution_col, "contribution")

  time_col <- mdo_pick_col(long, c(time_col, "week", "date", "period", "month", "time", "ds"))
  group_col <- mdo_pick_col(long, c(group_col, "geo", "market", "dma", "region", "country", "group"))
  entity_col <- mdo_pick_col(long, c(entity_col, "target_entity", "entity", "brand", "business_unit"))
  sample_col <- mdo_pick_col(long, c(sample_col, "sample", "split"))

  actual_col <- mdo_pick_col(long, c(actual_col, "actual", "y", "dep_var", "kpi"))
  fitted_col <- mdo_pick_col(long, c(fitted_col, "fitted", "y_pred", "prediction", "pred_q50"))
  residual_col <- mdo_pick_col(long, c(residual_col, "error", "resid"))

  long[, variable := as.character(variable)]
  long[, contribution := mdo_safe_num(contribution)]
  if (!is.na(actual_col) && actual_col != "y_actual") data.table::setnames(long, actual_col, "y_actual")
  if (!is.na(fitted_col) && fitted_col != "pred") data.table::setnames(long, fitted_col, "pred")
  if (!is.na(residual_col) && residual_col != "residual") data.table::setnames(long, residual_col, "residual")

  if (!is.null(sample_values) && !is.na(sample_col) && sample_col %in% names(long)) {
    long <- long[get(sample_col) %in% sample_values]
  }
  long <- mdo_add_period_fields(long, time_col, period_granularity)
  data.table::setattr(long, "mdo_cols", list(time_col = time_col, group_col = group_col, entity_col = entity_col, sample_col = sample_col))
  long[]
}

mdo_standardize_wide <- function(wide_decomp,
                                 long_decomp,
                                 time_col = NULL,
                                 group_col = NULL,
                                 entity_col = NULL,
                                 actual_col = "y_actual",
                                 fitted_col = "pred",
                                 residual_col = "residual",
                                 sample_col = "sample",
                                 sample_values = NULL,
                                 period_granularity = "month") {
  if (!is.null(wide_decomp)) {
    wide <- mdo_as_dt(wide_decomp, "wide_decomp")
  } else {
    long_cols <- names(long_decomp)
    id_cols <- setdiff(long_cols, c("variable", "contribution"))
    wide <- unique(long_decomp[, ..id_cols])
  }
  if (!nrow(wide)) return(wide)

  time_col <- mdo_pick_col(wide, c(time_col, "week", "date", "period", "month", "time", "ds"))
  group_col <- mdo_pick_col(wide, c(group_col, "geo", "market", "dma", "region", "country", "group"))
  entity_col <- mdo_pick_col(wide, c(entity_col, "target_entity", "entity", "brand", "business_unit"))
  sample_col <- mdo_pick_col(wide, c(sample_col, "sample", "split"))
  actual_col <- mdo_pick_col(wide, c(actual_col, "actual", "y", "dep_var", "kpi"))
  fitted_col <- mdo_pick_col(wide, c(fitted_col, "fitted", "y_pred", "prediction", "pred_q50"))
  residual_col <- mdo_pick_col(wide, c(residual_col, "error", "resid"))

  if (!is.na(actual_col) && actual_col != "y_actual") data.table::setnames(wide, actual_col, "y_actual")
  if (!is.na(fitted_col) && fitted_col != "pred") data.table::setnames(wide, fitted_col, "pred")
  if (!is.na(residual_col) && residual_col != "residual") data.table::setnames(wide, residual_col, "residual")
  if (!is.null(sample_values) && !is.na(sample_col) && sample_col %in% names(wide)) {
    wide <- wide[get(sample_col) %in% sample_values]
  }
  wide <- mdo_add_period_fields(wide, time_col, period_granularity)
  data.table::setattr(wide, "mdo_cols", list(time_col = time_col, group_col = group_col, entity_col = entity_col, sample_col = sample_col))
  wide[]
}

mdo_infer_spend_map <- function(raw_data, variables, spend_map = NULL, spend_suffix = "_spend") {
  if (!is.null(spend_map)) {
    sm <- mdo_as_dt(spend_map, "spend_map")
    if (!"variable" %in% names(sm)) stop("spend_map must include variable.")
    if (!"spend_col" %in% names(sm)) {
      spend_col <- mdo_pick_col(sm, c("cost_col", "cost", "spend"))
      if (is.na(spend_col)) stop("spend_map must include spend_col or cost_col.")
      data.table::setnames(sm, spend_col, "spend_col")
    }
    sm[, `:=`(variable = as.character(variable), spend_col = as.character(spend_col))]
    return(unique(sm[nzchar(variable) & nzchar(spend_col), .(variable, spend_col)]))
  }
  raw <- mdo_as_dt(raw_data, "raw_data")
  if (is.null(raw) || !nrow(raw)) return(data.table::data.table(variable = character(), spend_col = character()))
  rows <- lapply(as.character(variables), function(v) {
    candidates <- c(paste0(v, spend_suffix), paste0(v, "_cost"), paste0(v, "_investment"), paste0(v, "_media_spend"))
    hit <- candidates[candidates %in% names(raw)]
    if (length(hit)) data.table::data.table(variable = v, spend_col = hit[1]) else NULL
  })
  data.table::rbindlist(rows, fill = TRUE)
}

mdo_assign_roles <- function(variables, media_variables = NULL, baseline_variables = NULL) {
  vars <- as.character(variables)
  lower <- tolower(vars)
  if (is.null(baseline_variables)) {
    baseline_variables <- c("intercept", "intercept_total", "baseline", "base", "trend", "seasonality", "holiday")
  }
  base_lower <- tolower(baseline_variables)
  data.table::fifelse(
    lower == "residual",
    "residual",
    data.table::fifelse(
      vars %in% media_variables,
      "media",
      data.table::fifelse(
        lower %in% base_lower | grepl("intercept|baseline|season|trend|holiday", lower),
        "baseline_control",
        "other_model_term"
      )
    )
  )
}

mdo_split_rollup_path <- function(path) {
  if (length(path) < 1L || is.na(path[1]) || !nzchar(as.character(path[1]))) return(character())
  nodes <- trimws(strsplit(as.character(path[1]), "\\s*(>|/)\\s*", perl = TRUE)[[1]])
  nodes[nzchar(nodes)]
}

mdo_rollup_reporting_node <- function(path, variable = NA_character_) {
  nodes <- mdo_split_rollup_path(path)
  variable <- as.character(variable)[1]
  if (!length(nodes)) return(variable)
  root_aliases <- c("total", "total_media", "media", "paid_media", "all_media", "all")
  first <- gsub("[^a-z0-9]+", "_", tolower(nodes[1]))
  if (length(nodes) >= 2L && first %in% root_aliases) return(nodes[2])
  nodes[1]
}

mdo_normalize_channel_map <- function(channel_map = NULL, variables) {
  vars <- unique(as.character(variables))
  out <- data.table::data.table(variable = vars, channel = vars, rollup_path = vars)
  if (is.null(channel_map)) return(out[])
  cmap <- data.table::as.data.table(data.table::copy(channel_map))
  if (!"variable" %in% names(cmap)) stop("channel_map must contain variable.", call. = FALSE)
  if (!"channel" %in% names(cmap) && !"rollup_path" %in% names(cmap)) {
    stop("channel_map must contain channel or rollup_path.", call. = FALSE)
  }
  if (!"channel" %in% names(cmap)) cmap[, channel := NA_character_]
  if (!"rollup_path" %in% names(cmap)) cmap[, rollup_path := NA_character_]
  cmap[, `:=`(
    variable = as.character(variable),
    channel = as.character(channel),
    rollup_path = as.character(rollup_path)
  )]
  cmap <- cmap[!is.na(variable) & nzchar(variable)]
  dup <- cmap[duplicated(variable), unique(variable)]
  if (length(dup)) stop("channel_map has duplicate variable rows: ", paste(dup, collapse = ", "), call. = FALSE)
  cmap[is.na(rollup_path) | !nzchar(rollup_path), rollup_path := variable]
  cmap[is.na(channel) | !nzchar(channel),
       channel := mapply(mdo_rollup_reporting_node, rollup_path, variable, USE.NAMES = FALSE)]
  out[cmap[, .(variable, channel, rollup_path)],
      `:=`(channel = i.channel, rollup_path = i.rollup_path),
      on = "variable"]
  out[is.na(channel) | !nzchar(channel), channel := variable]
  out[is.na(rollup_path) | !nzchar(rollup_path), rollup_path := variable]
  out[]
}

mdo_expand_variable_rollup_map <- function(channel_map_normalized) {
  cm <- mdo_as_dt(channel_map_normalized, "channel_map_normalized")
  if (is.null(cm) || !nrow(cm)) {
    return(data.table::data.table(
      variable = character(),
      channel = character(),
      rollup_path = character(),
      rollup_level = integer(),
      rollup_node = character(),
      rollup_node_path = character(),
      is_reporting_channel = logical(),
      is_root_node = logical(),
      is_leaf_node = logical()
    ))
  }
  root_aliases <- c("total", "total_media", "media", "paid_media", "all_media", "all")
  rows <- lapply(seq_len(nrow(cm)), function(i) {
    variable <- as.character(cm$variable[i])
    channel <- as.character(cm$channel[i])
    path <- as.character(cm$rollup_path[i])
    nodes <- mdo_split_rollup_path(path)
    if (!length(nodes)) nodes <- variable
    last_key <- gsub("[^a-z0-9]+", "_", tolower(nodes[length(nodes)]))
    variable_key <- gsub("[^a-z0-9]+", "_", tolower(variable))
    if (!identical(last_key, variable_key)) nodes <- c(nodes, variable)
    node_key <- gsub("[^a-z0-9]+", "_", tolower(nodes))
    data.table::data.table(
      variable = variable,
      channel = channel,
      rollup_path = paste(nodes, collapse = " > "),
      rollup_level = seq_along(nodes),
      rollup_node = nodes,
      rollup_node_path = vapply(seq_along(nodes), function(j) paste(nodes[seq_len(j)], collapse = " > "), character(1)),
      is_reporting_channel = nodes == channel,
      is_root_node = seq_along(nodes) == 1L & node_key %in% root_aliases,
      is_leaf_node = seq_along(nodes) == length(nodes)
    )
  })
  data.table::rbindlist(rows, use.names = TRUE, fill = TRUE)
}

mdo_fit_metrics <- function(dt, by_cols = character()) {
  req <- c("y_actual", "pred")
  if (!all(req %in% names(dt))) return(data.table::data.table())
  x <- data.table::copy(dt)
  x[, y_actual := mdo_safe_num(y_actual)]
  x[, pred := mdo_safe_num(pred)]
  if (!"residual" %in% names(x)) x[, residual := y_actual - pred]
  x[, residual := mdo_safe_num(residual)]
  calc <- function(.dt) {
    y <- .dt$y_actual
    p <- .dt$pred
    r <- .dt$residual
    ok <- is.finite(y) & is.finite(p)
    y <- y[ok]
    p <- p[ok]
    r <- r[ok]
    if (!length(y)) {
      return(data.table::data.table(n = 0L, actual = NA_real_, pred = NA_real_, residual = NA_real_,
                                    rmse = NA_real_, mae = NA_real_, mape = NA_real_, smape = NA_real_,
                                    r_squared = NA_real_, bias = NA_real_, residual_share_of_actual = NA_real_))
    }
    denom <- sum((y - mean(y, na.rm = TRUE)) ^ 2, na.rm = TRUE)
    data.table::data.table(
      n = length(y),
      actual = sum(y, na.rm = TRUE),
      pred = sum(p, na.rm = TRUE),
      residual = sum(r, na.rm = TRUE),
      rmse = sqrt(mean((y - p) ^ 2, na.rm = TRUE)),
      mae = mean(abs(y - p), na.rm = TRUE),
      mape = mean(abs((y - p) / data.table::fifelse(abs(y) > 1e-8, y, NA_real_)), na.rm = TRUE),
      smape = mean(2 * abs(y - p) / data.table::fifelse(abs(y) + abs(p) > 1e-8, abs(y) + abs(p), NA_real_), na.rm = TRUE),
      r_squared = if (is.finite(denom) && denom > 1e-8) 1 - sum((y - p) ^ 2, na.rm = TRUE) / denom else NA_real_,
      bias = mean(p - y, na.rm = TRUE),
      residual_share_of_actual = sum(r, na.rm = TRUE) / data.table::fifelse(abs(sum(y, na.rm = TRUE)) > 1e-8, sum(y, na.rm = TRUE), NA_real_)
    )
  }
  if (!length(by_cols)) return(calc(x))
  x[, calc(.SD), by = by_cols]
}

mdo_build_spend_totals <- function(raw_data,
                                   spend_map,
                                   time_col,
                                   group_col,
                                   entity_col,
                                   period_granularity = "month",
                                   decomp_domain = NULL,
                                   sample_col = NULL) {
  raw <- mdo_as_dt(raw_data, "raw_data")
  if (is.null(raw) || !nrow(raw) || is.null(spend_map) || !nrow(spend_map)) {
    return(list(total = data.table::data.table(), by_period = data.table::data.table()))
  }
  raw_time_col <- mdo_pick_col(raw, c(time_col, "week", "date", "period", "month", "time", "ds"))
  raw_group_col <- mdo_pick_col(raw, c(group_col, "geo", "market", "dma", "region", "country", "group"))
  raw_entity_col <- mdo_pick_col(raw, c(entity_col, "target_entity", "entity", "brand", "business_unit"))
  raw_sample_col <- mdo_pick_col(raw, c(sample_col, "sample", "split"))
  if (!is.null(decomp_domain) && nrow(decomp_domain)) {
    dom <- data.table::as.data.table(data.table::copy(decomp_domain))
    join_cols <- character()
    if (!is.na(raw_time_col) && !is.na(time_col) && time_col %in% names(dom)) {
      raw[, `__mdo_time_key` := mdo_as_dateish(get(raw_time_col))]
      dom[, `__mdo_time_key` := mdo_as_dateish(get(time_col))]
      join_cols <- c(join_cols, "__mdo_time_key")
    }
    if (!is.na(raw_group_col) && !is.na(group_col) && group_col %in% names(dom)) {
      raw[, `__mdo_group_key` := as.character(get(raw_group_col))]
      dom[, `__mdo_group_key` := as.character(get(group_col))]
      join_cols <- c(join_cols, "__mdo_group_key")
    }
    if (!is.na(raw_entity_col) && !is.na(entity_col) && entity_col %in% names(dom)) {
      raw[, `__mdo_entity_key` := as.character(get(raw_entity_col))]
      dom[, `__mdo_entity_key` := as.character(get(entity_col))]
      join_cols <- c(join_cols, "__mdo_entity_key")
    }
    if (!is.na(raw_sample_col) && !is.na(sample_col) && sample_col %in% names(dom)) {
      raw[, `__mdo_sample_key` := as.character(get(raw_sample_col))]
      dom[, `__mdo_sample_key` := as.character(get(sample_col))]
      join_cols <- c(join_cols, "__mdo_sample_key")
    }
    if (length(join_cols)) {
      dom_keys <- unique(dom[, ..join_cols])
      raw <- raw[dom_keys, on = join_cols, nomatch = 0]
    }
  }
  raw <- mdo_add_period_fields(raw, raw_time_col, period_granularity)

  rows_total <- lapply(seq_len(nrow(spend_map)), function(i) {
    v <- spend_map$variable[i]
    sc <- spend_map$spend_col[i]
    if (!(sc %in% names(raw))) {
      return(data.table::data.table(variable = v, spend_col = sc, spend = NA_real_, spend_rows = 0L, spend_status = "spend_col_missing"))
    }
    spend <- sum(mdo_safe_num(raw[[sc]]), na.rm = TRUE)
    data.table::data.table(variable = v, spend_col = sc, spend = spend, spend_rows = sum(is.finite(mdo_safe_num(raw[[sc]]))), spend_status = "ok")
  })
  total <- data.table::rbindlist(rows_total, fill = TRUE)

  rows_period <- lapply(seq_len(nrow(spend_map)), function(i) {
    v <- spend_map$variable[i]
    sc <- spend_map$spend_col[i]
    if (!(sc %in% names(raw))) return(NULL)
    raw[, .(spend = sum(mdo_safe_num(get(sc)), na.rm = TRUE)), by = .(period_granularity, period_start, period_label, period_sort)
    ][, `:=`(variable = v, spend_col = sc)]
  })
  by_period <- data.table::rbindlist(rows_period, fill = TRUE)

  by_group <- data.table::data.table()
  if (!is.na(raw_group_col) && raw_group_col %in% names(raw)) {
    rows_group <- lapply(seq_len(nrow(spend_map)), function(i) {
      v <- spend_map$variable[i]
      sc <- spend_map$spend_col[i]
      if (!(sc %in% names(raw))) return(NULL)
      raw[, .(spend = sum(mdo_safe_num(get(sc)), na.rm = TRUE)), by = raw_group_col][, `:=`(variable = v, spend_col = sc)]
    })
    by_group <- data.table::rbindlist(rows_group, fill = TRUE)
  }

  by_entity <- data.table::data.table()
  if (!is.na(raw_entity_col) && raw_entity_col %in% names(raw)) {
    rows_entity <- lapply(seq_len(nrow(spend_map)), function(i) {
      v <- spend_map$variable[i]
      sc <- spend_map$spend_col[i]
      if (!(sc %in% names(raw))) return(NULL)
      raw[, .(spend = sum(mdo_safe_num(get(sc)), na.rm = TRUE)), by = raw_entity_col][, `:=`(variable = v, spend_col = sc)]
    })
    by_entity <- data.table::rbindlist(rows_entity, fill = TRUE)
  }

  list(total = total[], by_period = by_period[], by_group = by_group[], by_entity = by_entity[])
}

mdo_empty_kpi_economics <- function(by_period = FALSE) {
  out <- data.table::data.table(
    variable = character(),
    spend_col = character(),
    spend = numeric(),
    spend_rows = integer(),
    spend_status = character(),
    contribution = numeric(),
    role = character(),
    outcome_per_cost = numeric(),
    cost_per_outcome = numeric(),
    signed_economics_flag = character(),
    spend_share = numeric(),
    contribution_share = numeric(),
    efficiency_index = numeric(),
    fair_share_index = numeric()
  )
  if (isTRUE(by_period)) {
    out[, `:=`(
      period_granularity = character(),
      period_start = as.Date(character()),
      period_label = character(),
      period_sort = integer()
    )]
    data.table::setcolorder(out, c("period_granularity", "period_start", "period_label", "period_sort", setdiff(names(out), c("period_granularity", "period_start", "period_label", "period_sort"))))
  }
  out[]
}

