# 045-deck-runner.R
# Generated by behavior-preserving split of mmm_deck_output_builder.R.

write_mmm_deck_outputs <- function(report_tables,
                                   output_dir,
                                   prefix = "",
                                   write_charts = TRUE,
                                   write_html = TRUE,
                                   write_excel = FALSE,
                                   write_shiny = FALSE,
                                   top_n_charts = 12) {
  if (is.null(output_dir) || !nzchar(output_dir)) stop("output_dir is required.")
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  table_dir <- file.path(output_dir, "tables")
  chart_dir <- file.path(output_dir, "charts")
  dir.create(table_dir, recursive = TRUE, showWarnings = FALSE)
  pfx <- if (nzchar(prefix)) paste0(prefix, "_") else ""

  table_files <- character()
  table_names <- names(report_tables)[vapply(report_tables, function(x) data.table::is.data.table(x) || is.data.frame(x), logical(1))]
  table_names <- setdiff(table_names, c("standardized_long", "standardized_wide"))
  for (nm in table_names) {
    tab <- data.table::as.data.table(report_tables[[nm]])
    if (!ncol(tab)) next
    path <- file.path(table_dir, paste0(pfx, nm, ".csv"))
    data.table::fwrite(tab, path)
    table_files <- c(table_files, path)
  }

  chart_files <- character()
  if (isTRUE(write_charts)) chart_files <- write_mmm_deck_charts(report_tables, chart_dir, top_n = top_n_charts)

  html_path <- NA_character_
  if (isTRUE(write_html)) {
    html_path <- write_mmm_deck_html(report_tables, chart_files = chart_files, output_path = file.path(output_dir, paste0(pfx, "mmm_deck_dashboard.html")))
  }

  excel_path <- NA_character_
  if (isTRUE(write_excel)) {
    excel_path <- write_mmm_deck_excel(report_tables, file.path(output_dir, paste0(pfx, "mmm_deck_summary.xlsx")))
  }

  shiny_path <- NA_character_
  if (isTRUE(write_shiny)) {
    shiny_path <- write_mmm_deck_shiny_app(report_tables, output_dir = output_dir, prefix = prefix)
  }

  index <- data.table::data.table(
    artifact_type = c(rep("table", length(table_files)), rep("chart", length(chart_files)), "html", "excel", "shiny_app"),
    path = c(table_files, chart_files, html_path, excel_path, shiny_path)
  )
  index <- index[!is.na(path)]
  data.table::fwrite(index, file.path(output_dir, paste0(pfx, "report_index.csv")))

  invisible(list(
    output_dir = output_dir,
    table_files = table_files,
    chart_files = chart_files,
    html_path = html_path,
    excel_path = excel_path,
    shiny_path = shiny_path,
    index = index
  ))
}

run_mmm_deck_output_builder <- function(long_decomp,
                                        wide_decomp = NULL,
                                        raw_data = NULL,
                                        modcut = NULL,
                                        spend_map = NULL,
                                        optimizer_output = NULL,
                                        posterior_decomp_draws = NULL,
                                        posterior_coef_draws = NULL,
                                        channel_map = NULL,
                                        output_dir,
                                        prefix = "",
                                        media_variables = NULL,
                                        baseline_variables = NULL,
                                        time_col = NULL,
                                        group_col = NULL,
                                        entity_col = NULL,
                                        variable_col = "variable",
                                        contribution_col = "contribution",
                                        actual_col = "y_actual",
                                        fitted_col = "pred",
                                        residual_col = "residual",
                                        sample_col = "sample",
                                        sample_values = NULL,
                                        period_granularity = "month",
                                        spend_suffix = "_spend",
                                        kpi_value_per_outcome = NULL,
                                        write_charts = TRUE,
                                        write_html = TRUE,
                                        write_excel = FALSE,
                                        write_shiny = FALSE,
                                        top_n_charts = 12) {
  tables <- build_mmm_deck_tables(
    long_decomp = long_decomp,
    wide_decomp = wide_decomp,
    raw_data = raw_data,
    modcut = modcut,
    spend_map = spend_map,
    optimizer_output = optimizer_output,
    posterior_decomp_draws = posterior_decomp_draws,
    posterior_coef_draws = posterior_coef_draws,
    channel_map = channel_map,
    media_variables = media_variables,
    baseline_variables = baseline_variables,
    time_col = time_col,
    group_col = group_col,
    entity_col = entity_col,
    variable_col = variable_col,
    contribution_col = contribution_col,
    actual_col = actual_col,
    fitted_col = fitted_col,
    residual_col = residual_col,
    sample_col = sample_col,
    sample_values = sample_values,
    period_granularity = period_granularity,
    spend_suffix = spend_suffix,
    kpi_value_per_outcome = kpi_value_per_outcome
  )
  files <- write_mmm_deck_outputs(
    report_tables = tables,
    output_dir = output_dir,
    prefix = prefix,
    write_charts = write_charts,
    write_html = write_html,
    write_excel = write_excel,
    write_shiny = write_shiny,
    top_n_charts = top_n_charts
  )
  list(tables = tables, files = files)
}
